 <body ng-controller="AdminCtrl">
 
     {{va.usuarios_acl}}




<div class="panel">
  
  <section class="panel">
    <header class="panel-heading">
        Lista de Proyectos
    <span class="pull-right">
        

      <button type="button" class="btn btn-success btn-xs" ng-click="va.cargarProyectos('A')">Activos</button>
      <button type="button" class="btn btn-warning btn-xs" ng-click="va.cargarProyectos('C')">Cerrados</button>
    </span>
    </header>
</section>

  <div class="panel-body">
    
 
         <table datatable="ng" class="table table-condensed table-hover p-table">
      <thead>
        
         <th style="width: 10%;">Usuario</th>
                <th style="width: 20%;">Area</th>
                
                
                <th style="width: 5%;">Estado</th>
                <th style="width: 10%;">Acciones</th>
      </thead>
      <tbody>
        <tr ng-repeat="usuario in va.usuarios_acl track by $index">
          <td>
            {{usuario.uid}}
          </td>
          <td>
            {{usuario.areaid}}
          </td>
          

          <td>
           <select ng-model="proyecto.estado"
            ng-options="pro.value as pro.text for pro in vp.estadoproyecto" ng-change="vp.cambiarEstadoProyecto($index,proyecto.estado)">
            {{ vp.showEstadoproyecto(proyecto) }}
            </select>
          </td>


          <!--<td >      
            <span editable-select="proyecto.estado" e-form="rowform" e-ng-options="pro.value as pro.text for pro in vp.estadoproyecto">
              {{ vp.showEstadoproyecto(proyecto) }} 
            </span>
          </td> -->



          <td>
            <ul>
              <li>
                <button type="button" class="btn btn-info btn-xs"
                ng-click="proyecto.verInformacion()">
                  Información
                </button>
              </li>
              
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="panel">
    <button type="button" class="btn btn-default">Editar</button>
    <button type="button" class="btn btn-default">Exportar</button>
    <button type="button" class="btn btn-default">Imprimir</button>
  </div>
</div>

  </body>