<body class="cs-bg">
    <!-- START HEADER -->
    <section id="header">
        <div class="container">
            <header>
                <!-- HEADLINE -->
                <h1 > Muy Pronto...</h1>
                <br/>
                <p> Estamos trabajando para brindarte el mejor servicio, Gracias... </p>
            </header>
            <!-- START TIMER -->
            <div id="timer" data-animated="FadeIn">
                <p id="message"></p>
                <div id="days" class="timer_box"></div>
                <div id="hours" class="timer_box"></div>
                <div id="minutes" class="timer_box"></div>
                <div id="seconds" class="timer_box"></div>
            </div>
            <!-- END TIMER -->
        </div>

    </section>
    <!-- END HEADER -->
</body>
<!-- END BODY -->