<?php 
/*<body class="cs-bg">
    <!-- START HEADER -->
    <section id="header">
        <div class="container">
            <header>
                <!-- HEADLINE -->
                <h1 > Muy Pronto...</h1>
                <br/>
                <p> Estamos trabajando para brindarte el mejor servicio, Gracias... </p>
            </header>
            <!-- START TIMER -->
            <!--
            <div id="timer" data-animated="FadeIn">
                <p id="message"></p>
                <div id="days" class="timer_box"></div>
                <div id="hours" class="timer_box"></div>
                <div id="minutes" class="timer_box"></div>
                <div id="seconds" class="timer_box"></div>
            </div>-->
            <!-- END TIMER -->
        </div>

    </section>
    <!-- END HEADER -->
</body>
<!-- END BODY -->*/
?>

    <div ng-app="moduloAdmin">
        <div ng-view>

        </div>
    </div>

    <script type="text/javascript" src="/js/angular-route.js"></script>
    <script type="text/javascript" src="/js/Chart.js"></script>
    <script type="text/javascript" src="/js/angular-chart.js"></script>
    <script type="text/javascript" src="/js/checklist-model.js"></script>
    <script type="text/javascript" src="/js/xeditable.js"></script>
    <script type="text/javascript" src="/js/angular-mock.js"></script>
    <script type="text/javascript" src="/js/angular-file-upload.min.js"></script>
    
    
    <link rel="stylesheet" type="text/css" href="/css/style-controlproyecto.css">
    <link rel="stylesheet" type="text/css" href="/css/xeditable.css"> 
           
    <script src="http://m-e-conroy.github.io/angular-dialog-service/javascripts/dialogs.min.js" type="text/javascript"></script>

    <script type="text/javascript" src="/js/Admin/admin.js"></script>
    <script type="text/javascript" src="/js/Admin/controllers/AdminCtrl.js"></script>
   
    
    <script type="text/javascript" src="/js/Admin/services/httpFactory.js"></script>
    <script type="text/javascript" src="/js/Admin/services/adminFactory.js"></script>




