<div ng-app="reporteApp" ng-controller="mainController as reporte" class="div-reportes">

	<div class="col-lg-12 m-bot15">
		<h1>Reporte Tareopersona</h1>
		<div>
			<div class="col-lg-6">
				<h4>Clientes</h4>
				<select class="form-control m-bot15" ng-model="reporte.cliente_seleccionado" ng-change="reporte.getProyectos(reporte.cliente_seleccionado, 'byCliente')">
					<option value="todos">Seleccione Cliente</option>
					<option value="{{cliente.id}}" ng-repeat="cliente in reporte.clientes track by $index">{{cliente.nombre}}</option>
				</select>
			</div>
			<div class="col-lg-6">
				<h4>Gerentes</h4>
				<select class="form-control m-bot15" ng-model="reporte.gerente_seleccionado" ng-change="reporte.getProyectos(reporte.gerente_seleccionado, 'byGerente')">
					<option value="todos">Seleccione Gerente</option>
					<option value="{{gerente.gerente_proyecto}}" ng-repeat="gerente in reporte.gerentes track by $index">{{gerente.gerente_proyecto}}</option>
				</select>
			</div>
			
			<div class="col-lg-12">
				<h4>Proyectos</h4>
				{{reporte.text_proyectos}}
				<table>
					<tr ng-repeat="proyecto in reporte.proyectos">
						<th>{{proyecto.nombre_proyecto}}</th>
						<th><input ng-model="reporte.proyectos[$index].selected" ng-change="reporte.getData(proyecto.codigo_prop_proy, $index)" ng-true-value="true" ng-false-value="false" type="checkbox"></th>
					</tr>
			</table>
			</div>			
		
		</div>
		<div class="col-lg-4">
			<h4>Usuarios</h4>
			<select ng-disabled="reporte.disabled_children" class="form-control m-bot15" ng-model="reporte.usuario_seleccionado">
				<option value="." selected="selected">Todos</option>
				<option value="{{usuario.uid}}" ng-repeat="usuario in reporte.usuarios track by $index | orderBy: 'uid'">{{usuario.uid}}</option>
			</select>
		</div>
		<div class="col-lg-4">
			<h4>Tipo de Actividad</h4>
			<input ng-disabled="reporte.tareopersona_void" type="checkbox" ng-model="reporte.tipo_activo.Todo" ng-true-value="true" ng-false-value="false" ng-click="reporte.tipoActivoTodo()">Todos
			<div ng-repeat="item in reporte.tipo_actividad">
				<input ng-disabled="reporte.tareopersona_void" type="checkbox" ng-model="reporte.tipo_activo[item.text]" ng-true-value="true" ng-false-value="false" ng-click="reporte.tipoActivoHijo()">{{item.text}}
			</div>
		</div>
		<div class="col-lg-4">
			<h4>Rango de Rendición</h4>
			<div>
	            <div class="input-group input-large" data-date="13/07/2013" data-date-format="mm/dd/yyyy">
	                <input ng-disabled="reporte.disabled_children" type="text" ng-model="reporte.fecha_from.cadena" ng-change="reporte.cambiarFecha()" class="form-control dpd1" name="from">
	                <span class="input-group-addon">a</span>
	                <input ng-disabled="reporte.disabled_children" type="text" ng-model="reporte.fecha_to.cadena" ng-change="reporte.cambiarFecha()" class="form-control dpd2" name="to">
	            </div>
	            <span class="help-block">Seleccione fechas para rango de rendición</span>
	        </div>
	        <h4>Granularidad</h4>
	        <div>
	        	<select ng-model="reporte.agrupado_seleccionado" ng-change="reporte.cambiarAgrupamiento()" class="form-control m-bot15" ng-disabled="reporte.disabled_children">
	        		<option value="{{item.value}}" ng-repeat="item in reporte.agrupado">{{item.text}}</option>
	        	</select>
	        </div>
		</div>
	</div>

	<div id="container-tareopersona-table">
		<table datatable="ng" class="table table-bordered table-striped table-condensed">
		<thead>
			<th>
				<div>
					Usuario Id
				</div>
			</th>
			<th>
				<div>
					Usuario
				</div>
			</th>
			<th>
				<div>
					Rate del proyecto
				</div>
			</th>
			<th>
				<div>
					Código de Proyecto
				</div>
			</th>
			<th>
				<div>
					Cobrable/No Cobrable
				</div>
			</th>
			<th>
				<div>
					Proyecto (Unidad minera - proyecto)
				</div>
			</th>
			<th>
				<div>
					Status Proyecto
				</div>
			</th>
			<th ng-repeat="dia in reporte.dias track by $index" ng-show="reporte.dias_visible">
				<div>
					{{dia.cadena}}
				</div>
			</th>
			<th ng-repeat="semana in reporte.semanas track by $index" ng-show="reporte.semanas_visible">
				<div>
					{{semana.cadena}}
				</div>
			</th>
			<th ng-repeat="mes in reporte.meses track by $index" ng-show="reporte.meses_visible">
				<div>
					{{mes}}
				</div>
			</th>
			<th>
				<div>
					Full Sumary
				</div>
			</th>
		</thead>
		<tbody class="">
			<tr ng-repeat="fila in reporte.tareopersona | filter: reporte.usuario_seleccionado" ng-show="reporte.tipo_activo[fila.tipo_actividad]">
				<td>
					<div>
						{{fila.dni}}
					</div>
				</td>
				<td>
					<div>
						{{fila.uid}}
					</div>
				</td>
				<td>
					<div>
						{{fila.rate_proyecto}}
					</div>
				</td>
				<td>
					<div>
						{{fila.proyectoid}}
					</div>
				</td>
				<td>
					<div>
						{{fila.tipo_actividad}}
					</div>
				</td>
				<td>
					<div>
						{{fila.nombre + ' / ' +fila.nombre_proyecto}}
					</div>
				</td>
				<td>
					<div>
						{{fila.estado}}
					</div>
				</td>
				<td ng-repeat="hora in fila.horas track by $index" ng-show="reporte.dias_visible">
					<div>
						{{hora}}
					</div>
				</td>
				<td ng-repeat="hora in fila.horasxsemanas track by $index" ng-show="reporte.semanas_visible">
					<div>
						{{hora}}
					</div>
				</td>
				<td ng-repeat="hora in fila.horasxmeses track by $index" ng-show="reporte.meses_visible">
					<div>
						{{hora}}
					</div>
				</td>
				<td>
					<div>
						{{fila.summary}}
					</div>
				</td>
			</tr>
		</tbody>
		<tfoot class="">
			<td>
				<div>
					Full Summary
				</div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td ng-repeat="dia in reporte.dias" ng-show="reporte.dias_visible">
				<div>
					
				</div>
			</td>
			<td ng-repeat="semana in reporte.semanas" ng-show="reporte.semanas_visible">
				<div>
					
				</div>
			</td>
			<td ng-repeat="mes in reporte.meses" ng-show="reporte.meses_visible">
				<div>
					
				</div>
			</td>
			<td>
				<div></div>
			</td>
		</tfoot>	
		</table>
	</div>
</div>

<!--div de modal para barra cargando-->
<div class="modal fade" id="wait" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-body">
			<img src="/img/ico-loading.gif" alt="">
          </div>
      </div>
  </div>
</div>


	<script src="js/adt/vendor/highlightjs/highlight.pack.js"></script>
    <script src="js/adt/vendor/jquery/dist/jquery.js"></script>
    <script src="js/adt/vendor/backtotop/backtotop.min.js"></script>
	<script src="js/adt/vendor/angular/angular.js"></script>
    <script src="js/adt/vendor/angular-highlightjs/angular-highlightjs.min.js"></script>
    <script src="js/adt/vendor/angular-resource/angular-resource.min.js"></script>
    <script src="js/adt/vendor/angular-ui-router/release/angular-ui-router.min.js"></script>
	<script src="js/adt/vendor/datatables/media/js/jquery.dataTables.js"></script>
    <script src="js/adt/vendor/datatables-colreorder/js/dataTables.colReorder.js"></script>
	<script src="js/adt/vendor/datatables-colvis/js/dataTables.colVis.js"></script>
	<script src="js/adt/vendor/datatables-tabletools/js/dataTables.tableTools.js"></script>
    <script src="js/adt/vendor/datatables-responsive/js/dataTables.responsive.js"></script>
    <script src="js/adt/vendor/datatables-scroller/js/dataTables.scroller.js"></script>
    <script src="js/adt/vendor/datatables-columnfilter/js/dataTables.columnFilter.js"></script>
    <script src="js/adt/vendor/datatables-fixedcolumns/js/dataTables.fixedColumns.js"></script>
    <script src="js/adt/vendor/datatables-fixedheader/js/dataTables.fixedHeader.js"></script>
	<script src="js/adt/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="js/adt/vendor/angular-bootstrap/ui-bootstrap.min.js"></script>
	<script src="js/adt/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script src="js/adt/vendor/angular-translate/angular-translate.min.js"></script>

	 <!--<script src="dist/angular-datatables.min.js"></script>-->
	 <!--<script src="dist/plugins/bootstrap/angular-datatables.bootstrap.min.js"></script>-->
	 <!--<script src="dist/plugins/colreorder/angular-datatables.colreorder.min.js"></script>-->
	 <!--<script src="dist/plugins/columnfilter/angular-datatables.columnfilter.min.js"></script>-->
	 <!--<script src="dist/plugins/colvis/angular-datatables.colvis.min.js"></script>-->
	 <!--<script src="dist/plugins/scroller/angular-datatables.scroller.min.js"></script>-->
	 <!--<script src="dist/plugins/tabletools/angular-datatables.tabletools.min.js"></script>-->
	 <!--<script src="dist/plugins/fixedcolumns/angular-datatables.fixedcolumns.min.js"></script>-->
	 <!--<script src="dist/plugins/fixedheader/angular-datatables.fixedheader.min.js"></script>-->
    <script src="js/adt/src/angular-datatables.js"></script>
    <script src="js/adt/src/angular-datatables.util.js"></script>
    <script src="js/adt/src/angular-datatables.options.js"></script>
    <script src="js/adt/src/angular-datatables.instances.js"></script>
    <script src="js/adt/src/angular-datatables.factory.js"></script>
    <script src="js/adt/src/angular-datatables.renderer.js"></script>
    <script src="js/adt/src/plugins/bootstrap/angular-datatables.bootstrap.options.js"></script>
    <script src="js/adt/src/plugins/bootstrap/angular-datatables.bootstrap.colvis.js"></script>
    <script src="js/adt/src/plugins/bootstrap/angular-datatables.bootstrap.tabletools.js"></script>
    <script src="js/adt/src/plugins/bootstrap/angular-datatables.bootstrap.js"></script>
    <script src="js/adt/src/angular-datatables.directive.js"></script>
    <script src="js/adt/src/plugins/colvis/angular-datatables.colvis.js"></script>
    <script src="js/adt/src/plugins/colreorder/angular-datatables.colreorder.js"></script>
    <script src="js/adt/src/plugins/tabletools/angular-datatables.tabletools.js"></script>
    <script src="js/adt/src/plugins/scroller/angular-datatables.scroller.js"></script>
    <script src="js/adt/src/plugins/columnfilter/angular-datatables.columnfilter.js"></script>
    <script src="js/adt/src/plugins/fixedcolumns/angular-datatables.fixedcolumns.js"></script>
    <script src="js/adt/src/plugins/fixedheader/angular-datatables.fixedheader.js"></script>
    <script src="js/modulos-angular.js"></script>
