<div ng-app="reporteApp" ng-controller="mainController as reporte" class="div-reportes">
	<h1>Reporte Tareopersona</h1>
	<div>
		<div class="table-inline">
			<h4>Cobrabilidad</h4>
			<input type="checkbox" ng-model="reporte.tipo_todo" ng-true-value="true" ng-false-value="false" ng-click="reporte.mostrarTodo()">
			<div ng-repeat="item in reporte.cobrabilidad">
				<input type="checkbox" ng-model="reporte.activo[item.text]" ng-true-value="true" ng-false-value="false">{{item.text}}
			</div>
		</div>
		<div class="table-inline">
			<h4>Rango Fecha de Rendición</h4>
			<div ng-repeat="fecha in reporte.rango_fecha">
				{{fecha}}
			</div>
		</div>
		<div class="table-inline">
			<h4>Clientes</h4>
			<select ng-model="reporte.cliente_seleccionado" ng-change="reporte.getUnidadMinera(reporte.cliente_seleccionado)">
				<option value="todos" selected="selected">Todos</option>
				<option value="{{cliente.id}}" ng-repeat="cliente in reporte.clientes track by $index">{{cliente.nombre}}</option>
			</select>
			<h4>Unidad Minera</h4>
			<select name="" id="">
				<option ng-repeat="uni_min in reporte.unidadminera track by $index">{{uni_min.nombre}}</option>
			</select>
		</div>
		<div class="table-inline">
			<table class="table-bordered">
				<thead class="title-table">
					<th>
						<div>
							Usuarios
						</div>
					</th>
				</thead>
				<tbody class="scroll-content-small" id="usuarioScroll" >
					<tr ng-repeat="usuario in reporte.usuarios track by $index">
						<td>
							<div>
								{{usuario.uid}}
							</div>
						</td>
					</tr>
				</tbody>	
			</table>
		</div>
	</div>
	<div>
		<table class="table-bordered">
		<thead class="title-table">
			<th>
				<div>
					Usuario Id
				</div>
			</th>
			<th>
				<div>
					Usuario
				</div>
			</th>
			<th>
				<div>
					Rate del proyecto
				</div>
			</th>
			<th>
				<div>
					Código de Proyecto
				</div>
			</th>
			<th>
				<div>
					Cobrable/No Cobrable
				</div>
			</th>
			<th>
				<div>
					Proyecto (Unidad minera - proyecto)
				</div>
			</th>
			<th>
				<div>
					Status Proyecto
				</div>
			</th>
			<th ng-repeat="dia in reporte.dias">
				<div>
					{{dia}}
				</div>
			</th>
			<th>
				<div>
					Full Sumary
				</div>
			</th>
		</thead>
		<tbody class="scroll-content-high">
			<tr ng-repeat="fila in reporte.tareopersona" ng-show="reporte.activo[fila.tipo_actividad]">
				<td>
					<div>
						{{fila.dni}}
					</div>
				</td>
				<td>
					<div>
						{{fila.uid}}
					</div>
				</td>
				<td>
					<div>
						{{fila.rate}}
					</div>
				</td>
				<td>
					<div>
						{{fila.proyectoid}}
					</div>
				</td>
				<td>
					<div>
						{{fila.tipo_actividad}}
					</div>
				</td>
				<td>
					<div>
						{{fila.nombre_proyecto}}
					</div>
				</td>
				<td>
					<div>
						{{fila.estado}}
					</div>
				</td>
				<td ng-repeat="dia in reporte.dias">
					<div>
						
					</div>
				</td>
				<td>
					<div>
						{{fila.summary}}
					</div>
				</td>
			</tr>
		</tbody>
		<tfoot class="title-table">
			<td>
				<div>
					Full Summary
				</div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td>
				<div></div>
			</td>
			<td ng-repeat="dia in reporte.dias">
				<div>
					
				</div>
			</td>
			<td>
				<div></div>
			</td>
		</tfoot>	
		</table>
	</div>

</div>

<!--script>
  //Funcion para poner el scroll personalizado a las tablas
  $('#usuarioScroll').ready(function ($) {
    //$('.bodyScroll').addClass('scrollContent');
    $('#usuarioScroll').perfectScrollbar();
  });
</script-->


<!--div de modal para barra cargando-->
<div class="modal fade" id="wait" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-body">
			<img src="/img/ico-loading.gif" alt="">
          </div>
      </div>
  </div>
</div>