<div class="panel">
  <nav class="panel-heading tab-bg-dark-navy-blue">
    <ul class="nav nav-tabs">
      <!-- <li ng-class="va.edt_activo"><a href="" ng-click="va.cambiarPanel('edt')">EDT</a></li> -->

      <li><a href="">Búsqueda</a></li>
      <li><a href="">Búsqueda</a></li>
      <li><a href="">Filtro</a></li>
    </ul>
  </nav>
  <div class="panel-body">
    <div class="tab-content">

<!--       <div class="tab-pane" ng-class="va.edt_activo">
        <div class="col-md-6">
          <table class="table table-bordered">
            <thead>
              <th>
                N°
              </th>
              <th>
                EDT
              </th>
            </thead>
            <tbody>
              <tr ng-repeat="edt in va.edt track by $index">
                <td>
                  {{edt.codigo}}
                </td>
                <td>
                  {{edt.nombre}}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <button type="button" class="btn btn-default">Imprimir</button>
        </div>
      </div> -->



    </div>
   </div>

</div>
