<div class="panel">
  <nav class="panel-heading tab-bg-dark-navy-blue">
    <ul class="nav nav-tabs">
      <li ng-class="CP.edt_activo"><a href="" ng-click="CP.cambiarPanel('edt')">EDT</a></li>  
      <li ng-class="CP.perfomance_activo"><a href="" ng-click="CP.cambiarPanel('perfomance')">Perfomance</a></li>
      <li ng-class="CP.curva_activo"><a href="" ng-click="CP.cambiarPanel('curva')" >Curva</a></li>
    </ul>
  </nav>
  <div class="panel-body">
    <div class="tab-content">

      <div ng-include="'/control/index/edt'" class="tab-pane" ng-class="CP.edt_activo">
      fssss
      </div>


      <div ng-include="'/control/index/perfomance'" class="tab-pane" ng-class="CP.perfomance_activo">
        perfomance
      </div>

      <div ng-include="'/control/index/curvas'"  class="tab-pane" ng-class="CP.curva_activo">
          HHHCURVAAAA
      </div>

      <!--<div ng-include="'/control/index/curvas'"
      ng-controller="CurvasCtrl as CP" class="tab-pane" ng-class="CP.curva_activo">
      </div> -->

    </div>
  </div>
</div>
