<div class="form-group col-md-6">
	<table class=" table table-striped table-hover table-bordered " >
	<thead>	
		<tr class="menu">    
	        <th>Codigo Cronograma</th>
	        <th>Revision</th>
	        <!-- <th>Estado</th> -->

	    </tr>
	</thead>
	<tbody>
		<tr ng-repeat="cronograma in CP.procronograma" >

			<td>			
				<span editable-text="cronograma.codigo_cronograma" e-name="codigo_cronograma" e-form="rowform" onbeforesave="checkName($data, cronograma.cronogramaid)">
				{{ cronograma.codigo_cronograma }}
				</span>
			</td>

			<td>			
				<span editable-text="cronograma.revision_cronograma" e-name="revision_cronograma" e-form="rowform" onbeforesave="checkName($data, cronograma.revision_cronograma)">
				{{ cronograma.revision_cronograma }}
				</span>
			</td>

			<!--<td>			
				<span editable-text="cronograma.state" e-name="state" e-form="rowform" onbeforesave="checkName($data, cronograma.state)">
				{{ cronograma.state }}
				</span>
			</td> -->
         	<td style="white-space: nowrap">
                  <!-- form -->
                  <form editable-form name="rowform" onbeforesave="CP.ModificarCronograma($data, cronograma.cronogramaid)" ng-show="rowform.$visible" class="form-buttons form-inline" shown="inserted ==   cronograma ">
                    <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary">
                      guardar
                    </button>
                    <button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-default">
                      cancelar
                    </button>
                  </form>
                  <div class="buttons" ng-show="!rowform.$visible">
                    <button class="btn btn-primary" ng-click="rowform.$show()">editar</button>
                    <button class="btn btn-danger" ng-click="CP.EliminarCronograma($index,cronograma.cronogramaid,cronograma.revision_cronograma)">eliminar</button>
                  </div>  
            </td>
			
		</tr>
	</tbody>
	</table>
</div>



<div class="form-group col-md-4">
           
	<div ng-show="CP.formVisibilityCronograma" class="col-md-12" >

		<div class="col-md-12">
			<div class="col-md-6" >
				<label> Codigo Cronograma</label>
	        </div>
			<div class="col-md-6" >
				<input class="form-control"  type="text" ng-model="CP.codigocronograma"></input>
			</div>
	    </div>
	                
		<div class="col-md-12">
			<div class="col-md-6" >
	            <label> Revision</label>
	        </div>        
	        <div class="col-md-6" >
	                    <input class="form-control" type="text" ng-model="CP.revision"></input>
	        </div>
		</div>  

	<!-- 	<div class="col-md-12">
			<div class="col-md-6" >
				<label> Estado</label>
			</div>      
			<div class="col-md-6" >   
				<input class="form-control" type="text" ng-model="CP.estado"></input>   
			</div>
		</div>
 -->
		<div class="col-md-12">         
			<div class="col-md-6" >      
				<button class="btn btn-warning" ng-click="CP.GuardarCronograma()">Guardar</button>
			</div>            
			<div class="col-md-6" >      
				<button class="btn btn-danger" ng-click="CP.CancelarCronograma()">Cancelar</button>
			</div>
		</div>
	             
	</div>
	<button class="btn btn-primary" ng-click="CP.ShowFormCronograma()" ng-hide="CP.formVisibilityCronograma">
	    Anadir Cronograma
	</button>
        
</div>










<!-- 

      <div ng-repeat-start="category in CP.performance" class="animate-repeat-category">
          <button class="btn btn-primary btn-block btn-sm" ng-click="CP.toggleCategory(category)">
            {{ category.actividadid}}
           
            <span class="expand-indicator" ng-show="category.expanded">&mdash;</span>
            <span class="expand-indicator" ng-show="!category.expanded">+</span>
          </button>
     
        <div class="list-items animate-show-item" ng-show="category.expanded">
          <ul>
          <li ng-repeat="item in category.items" class="animate-repeat-item">
            {{item.fecha_performance}}
            <span ng-class="{done:item.completed}" ltc-editable class-off="done" ng-model="item.fecha_performance"></span>
         
          </li>
          </ul>
          <div class="no-items"><small ng-show="category.expanded && category.items.length==0">NO ITEMS!</small></div>
        </div>

        <div ng-repeat-end>
          <button ng-show="category.expanded" class="btn btn-primary btn-block btn-sm animate-show-item" disabled="disabled">/ {{ category.actividadid}} </button>
          <hr>
        </div> -->



<style type="text/css">
body {
  font-size: 12px;
}
span.done {
  text-decoration: line-through;
}

span.expand-indicator {
  float: right;
  margin-right: 15px;
  font-size: 12px;
}

div.list-items ul {
  margin-top: 10px;
}
div.list-items li {
  margin-top: 5px;
  height: 22px;
  cursor: default;
}

div.list-items li:hover {
  background-color: #EEE;
}

div.list-items .btn {
  float: right;
  margin-right: 10px;
}

.no-items {
  color: #999;
  text-align: center;
  margin-bottom: 5px;
}


/* Animations */
.animate-show-item.ng-hide-add,
.animate-show-item.ng-hide-remove {
  -webkit-transition:0.33s ease all;
  transition:0.5s linear all;

  /* remember to add this */
  display:block!important;
  position: relative;
  top: 0;
  opacity:1;
}
.animate-show-item.ng-hide {
  top: -15px;
  opacity:0;
}

.animate-repeat-category.ng-enter,
.animate-repeat-category.ng-leave,
.animate-repeat-category.ng-move,
.animate-repeat-item.ng-enter,
.animate-repeat-item.ng-leave,
.animate-repeat-item.ng-move {
  -webkit-transition: 0.33s ease all;
  transition: 0.33s eases all;
  position:relative;
}

.animate-repeat-item.ng-enter {
  left:-10px;
  opacity:0;
}
.animate-repeat-item.ng-enter.ng-enter-active {
  left:0;
  opacity:1;
}

.animate-repeat-item.ng-leave {
  left:0;
  opacity:1;
}
.animate-repeat-item.ng-leave.ng-leave-active {
  left:-10px;
  opacity:0;
}

.animate-repeat-category.ng-enter {
  top:-10px;
  opacity:0;
}
.animate-repeat-category.ng-enter.ng-enter-active {
  top:0;
  opacity:1;
}

.animate-repeat-category.ng-leave {
  top:0;
  opacity:1;
}
.animate-repeat-category.ng-leave.ng-leave-active {
  top:-10px;
  opacity:0;
}

.animate-repeat-item.ng-move {
  opacity:0.5;
}
.animate-repeat-item.ng-move.ng-move-active {
  opacity:1;
}

/* bootstrap  overrides */
.page-header {
  margin: 10px 0 10px;
  padding-bottom: 0;
  text-align: center;
}
.form-control {
  font-size: 12px;
}

.form-group {
  margin-bottom: 8px;
}

hr {
  margin-top: 10px;
  margin-bottom: 10px;
}
</style>
