<div class="form-group col-md-6">
	<table class=" table table-striped table-hover table-bordered " >
	<thead>	
		<tr class="menu">    
	        <th>Codigo Cronograma</th>
	        <th>Revision</th>
	        <!-- <th>Estado</th> -->

	    </tr>
	</thead>
	<tbody>
		<tr ng-repeat="cronograma in CP.procronograma" >

			<td>			
				<span editable-text="cronograma.codigo_cronograma" e-name="codigo_cronograma" e-form="rowform" >
				{{ cronograma.codigo_cronograma }}
				</span>
			</td>

			<td>			
				<span editable-text="cronograma.revision_cronograma" e-name="revision_cronograma" e-form="rowform" >
				{{ cronograma.revision_cronograma }}
				</span>
			</td>

			<!--<td>			
				<span editable-text="cronograma.state" e-name="state" e-form="rowform" onbeforesave="checkName($data, cronograma.state)">
				{{ cronograma.state }}
				</span>
			</td> -->
         	<td style="white-space: nowrap">
                  <!-- form -->
                  <form editable-form name="rowform" onbeforesave="CP.ModificarCronograma($data, cronograma.cronogramaid)" ng-show="rowform.$visible" class="form-buttons form-inline" shown="inserted ==   cronograma ">
                    <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary">
                      guardar
                    </button>
                    <button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-default">
                      cancelar
                    </button>
                  </form>
                  <div class="buttons" ng-show="!rowform.$visible">
                    <button class="btn btn-primary" ng-click="rowform.$show()">editar</button>
                    <button class="btn btn-danger" ng-click="CP.EliminarCronograma($index,cronograma.cronogramaid,cronograma.revision_cronograma)">eliminar</button>
                  </div>  
            </td>
			
		</tr>
	</tbody>
	</table>
</div>



<div class="form-group col-md-4">
           
	<div ng-show="CP.formVisibilityCronograma" class="col-md-12" >

		<div class="col-md-12">
			<div class="col-md-6" >
				<label> Codigo Cronograma</label>
	        </div>
			<div class="col-md-6" >
				<input class="form-control"  type="text" ng-model="CP.codigocronograma"></input>
			</div>
	    </div>
	                
		<div class="col-md-12">
			<div class="col-md-6" >
	            <label> Revision</label>
	        </div>        
	        <div class="col-md-6" >
	                    <input class="form-control" type="text" ng-model="CP.revision"></input>
	        </div>
		</div>  


		<div class="col-md-12">         
			<div class="col-md-6" >      
				<button class="btn btn-warning" ng-click="CP.GuardarCronograma()">Guardar</button>
			</div>            
			<div class="col-md-6" >      
				<button class="btn btn-danger" ng-click="CP.CancelarCronograma()">Cancelar</button>
			</div>
		</div>
	             
	</div>
	<button class="btn btn-primary" ng-click="CP.ShowFormCronograma()" ng-hide="CP.formVisibilityCronograma">
	    Anadir Cronograma
	</button>
        
</div>




<!-- 
    <div ng-repeat-start="category in CP.procronograma" class="animate-repeat-category">
          <button class="btn btn-primary btn-block btn-sm" ng-click="CP.toggleCategory(category)">
            	{{ category.codigo_cronograma }}-{{ category.revision_cronograma }}           
            <span class="expand-indicator" ng-show="category.expanded">&mdash;</span>
            <span class="expand-indicator" ng-show="!category.expanded">+</span> 
          </button>
    </div>
     
        <div class="list-items animate-show-item" ng-show="">
        
		<form method="POST" action="#" editable-form name="tableform" onaftersave="CP.saveTable()" oncancel="cancel()" >
			<table class=" table table-striped table-hover table-bordered ">
				<thead>	
					<tr class="menu">    
				        <th>Item</th>
				        <th >Descripcion de Tareas</th>
				        <th >Duracion</th>
				
				        <th>Inicio Real</th>
				        <th>Fin Real</th>
				        <th>Predecesoras</th>
				        <th>Sucesoras</th>					    
				    </tr>
				</thead>
				<tbody>
			  		<tr ng-repeat-start="performance in CP.performance " >
			          	<td >
			            	{{ performance.actividadid }}  
			          	</td>
			          	<td>
							{{ performance.nombre}}
						</td>
						<td>			
							<span editable-text="performance.duracion" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
							{{ performance.duracion }}
						</td>
				
			
						<td>
							<span editable-text="performance.fecha_comienzo_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
							{{ performance.fecha_comienzo_real }}
							</span>
						</td> 
						
						<td>
				          <span editable-text="performance.fecha_fin_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				            {{ performance.fecha_fin_real }}
				          </span>
				        </td>
				        <td>
							<span editable-text="performance.predecesoras" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
							{{ performance.predecesoras }}
							</span>
						</td> 
						<td>
							<span editable-text="performance.sucesoras" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
							{{ performance.sucesoras }}
							</span>
						</td> 
		        
			        </tr>

			   <tr ng-repeat-end>
			 
			        <hr>
			    </tr>
				</tbody>
			</table> 

			<div class="btn-edit">
			    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
			        editar
			    </button>
			</div>
			<div class="btn-form" ng-show="tableform.$visible">

			    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-primary">guardar</button>
			    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-default">cancelar</button>
			</div>

		</form>
    
          <div class="no-items"><small ng-show="category.expanded && category.items.length==0">NO ITEMS!</small></div>
        </div>

    <div ng-repeat-end>
          <button ng-show="category.expanded" class="btn btn-primary btn-block btn-sm animate-show-item" disabled="disabled">/ {{ category.actividadid}} </button>
          <hr>
    </div>
 -->








<!--   <accordion close-others="oneAtATime">
    <accordion-group heading="Static Header, initially expanded" is-open="status.isFirstOpen" is-disabled="status.isFirstDisabled">
      This content is straight in the template.
    </accordion-group>
    <accordion-group heading="{{group.title}}" ng-repeat="group in groups">
      {{group.content}}
    </accordion-group>
    <accordion-group heading="Dynamic Body Content">
      <p>The body of the accordion group grows to fit the contents</p>
        <button type="button" class="btn btn-default btn-sm" ng-click="addItem()">Add Item</button>
        <div ng-repeat="item in items">{{item}}</div>
    </accordion-group>
    <accordion-group is-open="status.open">
        <accordion-heading>
            I can have markup, too! <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': status.open, 'glyphicon-chevron-right': !status.open}"></i>
        </accordion-heading>
        This is just some content to illustrate fancy headings.
    </accordion-group>
  </accordion> -->



