
<!-- <canvas id="bar" class="chart chart-bar" data="CP.data"
  labels="CP.labels"></canvas>  -->


<table class=" table table-striped table-hover table-bordered " >
  <!--<tr>
  	<td><b>Fecha Inicio</b></td><td><p type="text" ng-model="CP.cuanto" size="4" ></p></td>
  	<td><b>Fecha Final</b></td><td><p type="text" ng-model="CP.cuanto" size="4" ></p></td>
  </tr>-->
<div >
  <tr>
    <td style="width:10%">
        Revision de Proyecto
    </td>
	  <td style="width:30%">
        Fecha de Proyecto
        <form editable-form name="nameform_fecha" onaftersave="CP.saveColumn('fecha_proyecto')" ng-show="nameform_fecha.$visible">
          <button type="submit" ng-disabled="nameform_fecha.$waiting" class="btn btn-primary">
            guardar
          </button>
          <button type="button" ng-disabled="nameform_fecha.$waiting" ng-click="nameform_fecha.$cancel()" class="btn btn-default">
            cancelar
          </button>
        </form>  
        <button class="btn btn-default" ng-show="!nameform_fecha.$visible" ng-click="nameform_fecha.$show()">
          editar
        </button>
    </td>
   	<td style="width:30%">
        Porcentaje de avance planificado
        <form editable-form name="nameform_plani" onaftersave="CP.saveColumn('porc_avance_plani')" ng-show="nameform_plani.$visible">
          <button type="submit" ng-disabled="nameform_plani.$waiting" class="btn btn-primary">
            guardar
          </button>
          <button type="button" ng-disabled="nameform_plani.$waiting" ng-click="nameform_plani.$cancel()" class="btn btn-default">
            cancelar
          </button>
        </form>  
        <button class="btn btn-default" ng-show="!nameform_plani.$visible" ng-click="nameform_plani.$show()">
          editar
        </button>
    </td>
    <td style="width:30%">
        Porcentaje de avance Real
        <form editable-form name="nameform_real" onaftersave="CP.saveColumn('porc_avance_real')" ng-show="nameform_real.$visible">
          <button type="submit" ng-disabled="nameform_real.$waiting" class="btn btn-primary">
            guardar
          </button>
          <button type="button" ng-disabled="nameform_real.$waiting" ng-click="nameform_real.$cancel()" class="btn btn-default">
            cancelar
          </button>
        </form>  
        <button class="btn btn-default" ng-show="!nameform_real.$visible" ng-click="nameform_real.$show()">
          editar
        </button>
    </td>
  </tr>


  <div class="large-12 columns">
    <label>Establece un orden: </label> 
      <select class="form-control"  ng-model="revision">
        <option value="A" selected>A</option>
        <option value="B">B</option>
        <option value="Z">Z</option>
      </select>
  </div>

  <div class="form-group">
    <button ng-click="CP.busca(revision)" class="btn btn-primary btn-xs">Busca</button>
  </div>


  <tr ng-repeat="label in CP.dat | orderBy:'fecha_proyecto' | filter:revision ">
    <td >     
        <span editable-text="label.revision_perf_curva" e-name="revision_perf_curva" e-form="nameform_revision_perf_curva" onbeforesave="checkName($data)">
          {{label.revision_perf_curva}}
        </span>
    </td>
  	<td >     
        <span editable-text="label.fecha_proyecto" e-name="fecha_proyecto" e-form="nameform_fecha" onbeforesave="checkName($data)">
          {{label.fecha_proyecto}}
        </span>
    </td>
	<td >     
        <span editable-text="label.porc_avance_plani " e-name="porc_avance_plani" e-form="nameform_plani" onbeforesave="checkName($data)">
          {{label.porc_avance_plani}}
        </span>
    </td>
   	<td >     
        <span editable-text="label.porc_avance_real" e-name="porc_avance_real" e-form="nameform_real" onbeforesave="checkName($data)">
          {{label.porc_avance_real}}
        </span>
    </td>
  </tr>

</div>

</table>
<canvas id="line" class="chart chart-line" data="CP.data"
  labels="CP.labels" legend="true" series="CP.series"
  click="CP.onClick">
</canvas> 







	<head>
	
		<style>
			canvas{
			}
		</style>
	</head>
	<body>
		<canvas id="canvas" height="450" width="450"></canvas>


	<script>

	// 	var pieData = [
	// 			{
	// 				value: 30,
	// 				color:"#F38630"
	// 			},
	// 			{
	// 				value : 50,
	// 				color : "#E0E4CC"
	// 			},
	// 			{
	// 				value : 100,
	// 				color : "#69D2E7"
	// 			}
			
	// 		];

	// var myPie = new Chart(document.getElementById("canvas").getContext("2d")).Pie(pieData);
	
	</script>
	</body>

