      <div >
        <div class="col-md-8">
          <table class="table table-bordered">
            <thead>
              <th>
                N°
              </th>
              <th>
                EDT
              </th>
              <th>
                Descripcion
              </th>
              <th>
                Acciones
              </th>
            </thead>
            <tbody>
            <tr ng-repeat="edt in CP.edt" >
                <td>
                  <span editable-text="edt.codigo" e-name="codigo" e-form="rowform" onbeforesave="checkName($data, edt.id)" e-required>
                  {{edt.codigo}}
                  </span>
                </td>
                <td>
                  <span editable-text="edt.nombre" e-name="nombre" e-form="rowform" onbeforesave="checkName($data, edt.id)" e-required>
                  {{edt.nombre}}
                  </span>
                </td>
                <td>
                  <span editable-text="edt.descripcion" e-name="descripcion" e-form="rowform" onbeforesave="checkName($data, edt.id)" e-required>
                  {{edt.descripcion}}
                  </span>
                </td>
                <td style="white-space: nowrap">
                  <!-- form -->
                  <form editable-form name="rowform" onbeforesave="CP.ModificarEdt($data, edt.codigo)" ng-show="rowform.$visible" class="form-buttons form-inline" shown="inserted ==   edt ">
                    <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary">
                      guardar
                    </button>
                    <button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-default">
                      cancelar
                    </button>
                  </form>
                  <div class="buttons" ng-show="!rowform.$visible">
                    <button class="btn btn-primary" ng-click="rowform.$show()">editar</button>
                    <button class="btn btn-danger" ng-click="CP.EliminarEdt($index,edt.codigo)">eliminar</button>
                  </div>  
                </td>
       
            </tr>     

       

            </tbody>
          </table>
        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      <div class="form-group col-md-4">
           
          <div ng-show="CP.formVisibilityEdt" class="col-md-12" >

                <div class="col-md-12">
                  <div class="col-md-6" >
                      <label> Codigo EDT</label>
                  </div>
                  <div class="col-md-6" >
                      <input class="form-control"  type="text" ng-model="CP.codigo"></input>
                  </div>
                </div>
                
                <div class="col-md-12">
                  <div class="col-md-6" >
                    <label> Nombre EDT</label>
                  </div>        
                  <div class="col-md-6" >
                    <input class="form-control" type="text" ng-model="CP.nombre"></input>
                  </div>
                </div>  

                <div class="col-md-12">
                  <div class="col-md-6" >
                    <label> Descripcion EDT</label>
                  </div>      
                  <div class="col-md-6" >   
                    <input class="form-control" type="text" ng-model="CP.descripcion"></input>   
                  </div>
                </div>
                <div class="col-md-12">         
                  <div class="col-md-6" >      
                    <button class="btn btn-warning" ng-click="CP.GuardarEdt()">Guardar</button>
                  </div>            
                  <div class="col-md-6" >      
                    <button class="btn btn-danger" ng-click="CP.CancelarEdt()">Cancelar</button>
                  </div>
                </div>
             
          </div>
          <button class="btn btn-primary" ng-click="CP.ShowFormEdt()" ng-hide="CP.formVisibilityEdt">
                  Anadir EDT
          </button>
        
      </div>