      <div >
        <div class="col-md-6">
          <table class="table table-bordered">
            <thead>
              <th>
                N°
              </th>
              <th>
                EDT
              </th>
            </thead>
            <tbody>
            <!--<tr ng-repeat="edt in CP.edt track by $index">
                <td>
                  {{edt.codigo}}
                </td>
                <td>
                  {{edt.nombre}}
                </td>
            </tr>-->
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <button type="button" class="btn btn-default">Imprimir</button>
        </div>
      </div>