    <div ng-app="moduloCp">
        <div ng-view>

        </div>
    </div>

    <script type="text/javascript" src="/js/angular-route.js"></script>
    <script type="text/javascript" src="/js/Chart.js"></script>
    <script type="text/javascript" src="/js/angular-chart.js"></script>
    <script type="text/javascript" src="/js/checklist-model.js"></script>
    <script type="text/javascript" src="/js/xeditable.js"></script>
    <script type="text/javascript" src="/js/angular-mock.js"></script>
    
    <link rel="stylesheet" type="text/css" href="/css/style-controlproyecto.css">
    <link rel="stylesheet" type="text/css" href="/css/xeditable.css">        
    <script src="http://m-e-conroy.github.io/angular-dialog-service/javascripts/dialogs.min.js" type="text/javascript"></script>

    <script type="text/javascript" src="/js/ControlProyecto/controlproyecto.js"></script>
    <script type="text/javascript" src="/js/ControlProyecto/controllers/PanelCtrl.js"></script>
   
    <script type="text/javascript" src="/js/ControlProyecto/controllers/ControlCtrl.js"></script>
    <script type="text/javascript" src="/js/ControlProyecto/controllers/DetalleCtrl.js"></script>
    <script type="text/javascript" src="/js/ControlProyecto/controllers/ProyectoCtrl.js"></script>
    <script type="text/javascript" src="/js/ControlProyecto/services/httpFactory.js"></script>
    <script type="text/javascript" src="/js/ControlProyecto/services/proyectoFactory.js"></script>

    <script type="text/javascript" src="/js/ControlDocumentario/services/entregableFactory.js"></script>
    <script type="text/javascript" src="/js/ControlDocumentario/services/transmittalFactory.js"></script>


