
<div class="panel" style="overflow:scroll">

	<div class="panel-body col-md-12"  >
		<div class="col-md-2" >
	    <label>Escoja una revision: </label> 
	  	</div>
	  	<div class="col-md-2" >
	    <select class="form-control" ng-model="CP.revisionE"         
	      ng-options="c.revision_entregable for c in CP.entregable ">
	    </select> 
	  	</div>
	  	<div class="col-md-2" >
	    <button class="btn btn-shadow btn-success" ng-click="CP.buscaentregables(CP.revisionE)" class="btn btn-primary btn-xs">Busca</button>
	  	</div>

		<div class="col-md-6">	
			<section class="panel">				
				<div ng-show="CP.formVisibilityEntregable" class="col-md-12" >	                
					<div class="col-md-12">
						<div class="col-md-3" >
				            <label> Revision</label>
				        </div>        
				        <div class="col-md-3" >
				            <input class="form-control" type="text" ng-model="CP.revisionEntregable"></input>
				        </div>
				       
						<div class="col-md-3" >      
							<button class="btn btn-shadow btn-warning" ng-click="CP.GuardarEntregable()">Guardar</button>
						</div>            
						<div class="col-md-3" >      
							<button class="btn btn-shadow btn-danger" ng-click="CP.CancelarEntregable()">Cancelar</button>
						</div>
					</div>
				             
				</div>
				<button class="btn btn-shadow btn-primary"  ng-click="CP.ShowFormEntregable()" ng-hide="CP.formVisibilityEntregable">
				    Añadir Revision
			</button>
			</section>	           

		</div>
	</div>
	<div class="row">
		<div class="panel col-sm-2 col-md-2" style="border:1px solid #000000, margin:5px, padding: 5px;" >
			<li ng-if="CP.responsable=='S' && (CP.statelista.indice==1 || CP.statelista.indice==3) ">
		    	<button type="button" class="btn btn-primary" ng-click="CP.CambiarEstadoListaEntregable(2)">Completo</button>
			</li>

			<li ng-if="CP.jefearea=='S' && (CP.statelista.indice==2 || CP.statelista.indice==5) ">
			    <button type="button" class="btn btn-shadow btn-success " ng-click="CP.CambiarEstadoListaEntregable(4)"><i class='fa fa-check'></i>jefe</button>
			    <button type="button" class="btn btn-shadow btn-danger" ng-click="CP.CambiarEstadoListaEntregable(3)"><i class='fa fa-times'></i>jefe</button>
			</li > 

			<li ng-if="CP.gerente=='S'  && CP.statelista.indice==4 && CP.statelista.status=='gr'">	
			    <button type="button" class="btn btn-shadow btn-success" ng-click="CP.CambiarEstadoListaEntregable(6)"><i class='fa fa-check'></i>gerente</button>
			    <button type="button" class="btn btn-shadow btn-danger" ng-click="CP.CambiarEstadoListaEntregable(5)"><i class='fa fa-times'></i>gerente</button>
			</li >

			<li ng-if="CP.gerente=='S' && CP.statelista.indice==7">
			    <button type="button" class="btn btn-shadow btn-success" ng-click="CP.CambiarEstadoListaEntregable(9)"><i class='fa fa-check'></i>gr cod</button>
			    <button type="button" class="btn btn-shadow btn-danger" ng-click="CP.CambiarEstadoListaEntregable(8)"><i class='fa fa-times'></i>gr cod</button>
			</li>	  
		</div>
<!-- 		<fieldset> -->

		<!-- </fieldset> -->
	</div>

	<table class="table table-bordered table-hover table-condensed">

	    <tr style="font-weight: bold"> 
			<td style="width:10%">EDT</td>
			<td>tipo_documento</td>
			<td>disciplina</td>
			<td>Codigo Anddes</td>
			<td>Codigo Cliente</td>

			<td>descripcion</td>
			<td>fecha_a</td>
			<td>fecha_b</td>
			<td>fecha_0</td>
			<td><span ng-show="tableform.$visible">Action</span></td>	
	    </tr>

	    <tr ng-repeat="lista in CP.listaentregable track by $index" ng-class="{'cerrado':lista.disciplina===CP.areaid}">	    	
	    	<td >      
		        <span editable-select="lista.edt" e-name="edt" e-form="rowform" e-ng-options="s.codigo as s.nombre for s in CP.edt"  >		         
		       	   {{ CP.showStatus(lista) }}  
		        </span>
	     	</td> 
	 		<td>      
		        <span editable-select="lista.tipo_documento" e-name="tipo_documento" e-form="rowform" e-ng-options="s.value as s.text for s in CP.tipodocumentoE" >
		       	  {{ CP.showTipodoc(lista) }} 		       	
		        </span>
	     	</td>
	     	<td>	        	
		        <span editable-select="lista.disciplina" e-name="disciplina" e-form="rowform"   e-ng-options="s.areaid as s.nombre for s in CP.disciplina ">		         
		       	  {{ CP.showDisciplina(lista) }} 	          
		        </span>
	      	</td>
			<!-- <td >
				<span editable-text="lista.codigo_anddes" ng-disabled="CP.desabilitar==1" e-name="codigo_anddes" e-form="rowform" onbeforesave="checkEntregable($dataentregable, lista.cod_le)"  >
					{{ lista.codigo_anddes }}
				</span>
			</td>-->
			<td>
			  <input class="form-control" ng-model="lista.codigo_anddes" ng-disabled="CP.desabilitar==1" type="text"  >
			</td>
			<!-- <td  >
				<span editable-text="lista.codigo_cliente" e-name="codigo_cliente" e-form="rowform" onbeforesave="checkEntregable($dataentregable, lista.cod_le)" >
					{{ lista.codigo_cliente }}
				</span>
			</td> -->
			<td>
			  <input class="form-control" ng-model="lista.codigo_cliente" ng-disabled="CP.desabilitar==1" type="text"  >
			</td>
			<td >
				<span editable-textarea ="lista.descripcion_entregable" e-rows="7" e-cols="20" e-name="descripcion_entregable" e-form="rowform" >	
					{{ lista.descripcion_entregable }}
				</span>
			</td>

			<td>
				<input class="form-control" ng-show="rowform.$visible"  type="text" e-form="rowform" ui-date="{ dateFormat: 'yy-mm-dd' }" ename="fecha_a" ng-model='CP.fecha_a'/>		
				<span ng-show="!rowform.$visible" ename="fecha_a" >
				{{ lista.fecha_a | date:"yyyy-MM-dd" }}					
				</span>
			
			</td>

			<td>
				<input class="form-control" ng-show="rowform.$visible"  type="text" e-form="rowform" ui-date="{ dateFormat: 'yy-mm-dd' }" ename="fecha_b" ng-model='CP.fecha_b'/>		
				<span ng-show="!rowform.$visible" ename="fecha_b" >
				{{ lista.fecha_b | date:"yyyy-MM-dd" }}					
				</span>
			
			</td>

			<td>
				<input class="form-control" ng-show="rowform.$visible" type="text" e-form="rowform" ui-date="{ dateFormat: 'yy-mm-dd' }" ename="fecha_0" ng-model='CP.fecha_0'/>		
				<span ng-show="!rowform.$visible" ename="fecha_0" >
				{{ lista.fecha_0 | date:"yyyy-MM-dd" }}					
				</span>
			
			</td>


			<!-- <td>
				<span editable-text="lista.fecha_b" e-name="fecha_b" e-form="rowform" e-datepicker-popup="yyyy-MM-dd" >
					{{ lista.fecha_b }}
				</span>
			</td>
			<td  >
				<span editable-text="lista.fecha_0" e-name="fecha_0" e-form="rowform" e-datepicker-popup="yyyy-MM-dd" >
					{{ lista.fecha_0 }}
				</span>
			</td> -->


	        <td style="white-space: nowrap">	        
		        <form editable-form name="rowform" onbeforesave="CP.guardatListaentregable($data, lista.cod_le)" 
		        ng-show="rowform.$visible" class="form-buttons form-inline" 
		        shown="inserted == lista">

		          <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary">
		            guardar
		          </button>
		          <button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()"  class="btn btn-default">
		            cancelar
		          </button>
		        </form>
		        <div class="buttons" ng-show="!rowform.$visible">
		          <button class="btn btn-shadow btn-primary" ng-click="rowform.$show()" ng-disabled="CP.activareditar===false">editar</button>
		          <button class="btn btn-shadow btn-danger" ng-click="CP.deleteEntregable($index,lista.cod_le)" ng-disabled="CP.activareditar===false">eliminar</button>
		        </div>  
	        </td>

	    </tr>
	</table>

	<div class="panel" >
		<button ng-disabled="!(CP.gerente==='S' && CP.statelista.indice===1)" class="btn btn-shadow btn-success" ng-click="CP.addListaEntregable()" >Agregar </button>
		<!-- ng-disabled="CP.activareditar===false" -->

	  <!--   <button type="button" class="btn btn-default" ng-click="CP.exportarToXml()">Exportar</button> -->
	    <button type="button" class="btn btn-shadow btn-success" ng-click="CP.imprimir()">Imprimir</button>	  
	</div>
</div>

<div >
	<header class="panel-heading">
		<h5>Flujo de Entregables</h5>		
	</header>
	<!-- <section class="panel"> -->
		<div class="vvanel-body" >			
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===1}" class='btn btn-shadow btn-warning'>Creado</button>
		
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===2}" class='btn btn-shadow btn-warning'>Completo</button>

				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===3}" class='btn btn-shadow btn-warning'>Jefe Des.</button>
		
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===4}" class='btn btn-shadow btn-warning'>Jefe Aprob.</button>
			
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===5}" class='btn btn-shadow btn-warning'>Gerente Des.</button>
			
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===6}" class='btn btn-shadow btn-warning'>Gerente Aprob.</button>
		
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===7}" class='btn btn-shadow btn-warning'>Control Doc.</button>
		
				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===8}" class='btn btn-shadow btn-warning'>Codif Aprob.</button>

				<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===9}" class='btn btn-shadow btn-warning'>Codif Des.</button>
			
	<!-- 		<fieldset>
				<table class="table table-bordered table-hover table-condensed">
					<tr>
						<head>
							<th><h5><center>Creado</center></h5></th>
							<th><h5><center>Responsable Proyecto</center></h5></th>
							<th><h5><center>Jefe Area</center><h5></th>
							<th><h5><center>Gerente Proyecto</center><h5></th>
							<th><h5><center>Control Documentario</center><h5></th>
							<th><h5><center>Codificacion</center><h5></th>
						</head>				
					</tr>
					<tr>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===1}" class='btn btn-shadow btn-warning'>Creado</button>
							</center>
						</td>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===2}" class='btn btn-shadow btn-warning'>Llenado</button>
							</center>
						</td>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===3}" class='btn btn-shadow btn-warning'>No aprobado</button></br>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===4}" class='btn btn-shadow btn-warning'>Aprobado</button>
							</center>					
						</td>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===5}" class='btn btn-shadow btn-warning'>No Aprobado</button></br>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===6}" class='btn btn-shadow btn-warning'>Aprobado</button>
							</center>					
						</td>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===7}" class='btn btn-shadow btn-warning'>Control</button>
							</center>					
						</td>
						<td><center>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===8}" class='btn btn-shadow btn-warning'>No Aprobado </button></br>
							<button ng-class="{'btn btn-shadow btn-danger':CP.statelista.indice===9}" class='btn btn-shadow btn-warning'>Aprobado</button>
							</center>					
						</td>
					</tr>
				</table >

			</fieldset> -->
		</div>
	<!-- </section> -->
</div>


<style type="text/css">

.cerrado { Background: rgb(203,115,100);color:#2F2D2D;}



@import url(http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic);
* {
		font-family: "Roboto", Arial, sans-serif;
}

h1 {
		font-weight: 100;
		color: #777;
}

.main-wrapper {
		border-radius: 4px;
		background-color: white;
		padding: 20px;
		box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
		position: relative;
}
</style>

<style type="text/css">

/*@import url("http://fonts.googleapis.com/css?family=Lobster");
@import url(http://fonts.googleapis.com/css?family=Lobster);
@font-face {
  font-family: 'ModernPictogramsNormal';
  src: url("http://s202540075.onlinehome.us/codepen/fonts/modernpics-webfont.eot");
  src: url("http://s202540075.onlinehome.us/codepen/fonts/modernpics-webfont.eot?#iefix") format("embedded-opentype"), url("http://s202540075.onlinehome.us/codepen/fonts/modernpics-webfont.woff") format("woff"), url("http://s202540075.onlinehome.us/codepen/fonts/modernpics-webfont.ttf") format("truetype"), url("http://s202540075.onlinehome.us/codepen/fonts/modernpics-webfont.svg#ModernPictogramsNormal") format("svg");
  font-weight: normal;
  font-style: normal;
}
/*body {
  margin: 0;
  padding: 0;
  background: url("http://www.bradysammons.com/codepen/darkui/noise.png") repeat;
  padding: 20px;
}

a,button, input[type='radio'] + label {
  text-align: center;
  display: inline-block;
  text-decoration: none;
  cursor: pointer;
  font-family: 'Trebuchet MS', Helvetica, sans-serif;
}

fieldset {
  border: 1px solid #222;
  -moz-border-radius: 8px;
  -webkit-border-radius: 8px;
  float: left;
  border-radius: 8px;
  position: relative;
/*  margin: 20px 0 0 0;
  min-height: 90px;
  line-height: 90px;
  margin-right: 20px;
  padding: 20px;
}
fieldset h2 {
  font-family: 'Lobster';
  font-weight: normal;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.12);
  display: inline-block;
  margin: 0;
  line-height: 1.5;
  position: absolute;
  top: -20px;
  background: url("http://www.bradysammons.com/codepen/darkui/noise.png") repeat;
  padding: 0 5px 0 10px;
}

input[type='radio'] {
  display: none;
}

/* -------------------
	Default State
-------------------- 
a.glowBtn, button.glowBtn, input[type='radio'] + label {
  z-index: 10;
  margin: 0 10px 10px 0;
  width: 115.5px;
  height: 37.29px;
  line-height: 36.3px;
  position: relative;
  font-size: 13.2px;
  letter-spacing: .1em;
  color: #0e0e0e;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.1);
  font-weight: bold;
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzExMTExMSIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzAwMDAwMCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #E4BA00), color-stop(100%, #E4BA00));
  background-image: -moz-linear-gradient(#E4BA00, #E4BA00);
  background-image: -webkit-linear-gradient(#E4BA00, #E4BA00);
  background-image: linear-gradient(#E4BA00, #E4BA00);
  -moz-border-radius: 3px;
  -webkit-border-radius: 3px;
  border-radius: 3px;
  -moz-box-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 3px rgba(255, 255, 255, 0.2);
  -webkit-box-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 3px rgba(255, 255, 255, 0.2);
  box-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 3px rgba(255, 255, 255, 0.2);
}

a.glowBtn:after,button.glowBtn:after input[type='radio'] + label:after {
  z-index: -1;
  content: '';
  cursor: pointer;
  top: 1.98px;
  margin-left: 50%;
  left: -55px;
  width: 110px;
  height: 33px;
  display: block;
  position: absolute;
 /* background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzQ0NDQ0NCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzM3MzczOCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #444444), color-stop(100%, #373738));
  background-image: -moz-linear-gradient(#444444, #373738);
  background-image: -webkit-linear-gradient(#444444, #373738);
  background-image: linear-gradient(#444444, #373738);
  -moz-box-shadow: inset 0 2px 1px -1px rgba(255, 255, 255, 0.2), inset 0 -2px 1px -1px rgba(0, 0, 0, 0.2), 0 12px 12px rgba(0, 0, 0, 0.5), 0 4px 6px rgba(0, 0, 0, 0.3);
  -webkit-box-shadow: inset 0 2px 1px -1px rgba(255, 255, 255, 0.2), inset 0 -2px 1px -1px rgba(0, 0, 0, 0.2), 0 12px 12px rgba(0, 0, 0, 0.5), 0 4px 6px rgba(0, 0, 0, 0.3);
  box-shadow: inset 0 2px 1px -1px rgba(255, 255, 255, 0.2), inset 0 -2px 1px -1px rgba(0, 0, 0, 0.2), 0 12px 12px rgba(0, 0, 0, 0.5), 0 4px 6px rgba(0, 0, 0, 0.3);
  -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
  border-radius: 2px;
}

/* -------------------
	Hover States
-------------------- */
/*a.glowBtn:hover, a.hover,button.glowBtn:hover, button.hover, input[type='radio'] + label:hover {
  color: #FFFFFF;
  text-shadow: 0px -1px 0px rgba(35, 18, 18, 0);
}*/

/*a.glowBtn:hover:after, a.hover:after,button.glowBtn:hover:after, button.hover:after, input[type='radio'] + label:hover:after {
  /*background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzU0NTQ1NCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzM3MzczOCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #545454), color-stop(100%, #373738));
  background-image: -moz-linear-gradient(#545454, #373738);
  background-image: -webkit-linear-gradient(#545454, #373738);
  background-image: linear-gradient(#545454, #373738);
}

/* -------------------
	Active States
-------------------- */
/*a.glowBtn:active, a.active, a.active:hover,button.glowBtn:active, button.active, button.active:hover, input[type='radio']:checked + label {
 /* color: #06980D;*/
/*  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.3), 0 0px 30px rgba(0, 255, 255, 0.7);
  -moz-box-shadow: 0 -1px 0 rgba(0, 193, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.4), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 20px rgba(0, 193, 255, 0.1), 0 0 30px rgba(0, 193, 255, 0.1);
  -webkit-box-shadow: 0 -1px 0 rgba(0, 193, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.4), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 20px rgba(0, 193, 255, 0.1), 0 0 30px rgba(0, 193, 255, 0.1);
  box-shadow: 0 -1px 0 rgba(0, 193, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.4), 0 1px 0 rgba(255, 255, 255, 0.05), 0 0 20px rgba(0, 193, 255, 0.1), 0 0 30px rgba(0, 193, 255, 0.1);
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #EC6459), color-stop(100%, #EC6459));
  background-image: -moz-linear-gradient(#EC6459, #EC6459);
  background-image: -webkit-linear-gradient(#EC6459, #EC6459);
  background-image: linear-gradient(#EC6459, #EC6459);


}

a.glowBtn:active, a.active, a.active:hover,
button.glowBtn:active, button.active, button.active:hover
{
  /*text-shadow: 0 -1px 0 black, 0 0px 30px #06BF15, 0 0px 50px #06BF15;
}

a.glowBtn:active:after, a.active:after, a.active:hover:after,
button.glowBtn:active:after, button.active:after, button.active:hover:after,
 input[type='radio']:checked + label:after {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzI2MjYyNyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzJkMmQyZSIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #262627), color-stop(100%, #2d2d2e));
  background-image: -moz-linear-gradient(#262627, #2d2d2e);
  background-image: -webkit-linear-gradient(#262627, #2d2d2e);
  background-image: linear-gradient(#262627, #2d2d2e);
  -moz-box-shadow: inset 0 5px 6px rgba(0, 0, 0, 0.3), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
  -webkit-box-shadow: inset 0 5px 6px rgba(0, 0, 0, 0.3), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
  box-shadow: inset 0 5px 6px rgba(0, 0, 0, 0.3), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
}

/* -------------------
	Radio Specific Style
-------------------- 
input[type='radio'] + label {
  font-family: 'ModernPictogramsNormal', Arial, sans-serif;
  font-size: 36.66667px;
  line-height: 55px;
  letter-spacing: 0;
  width: 55px;
  height: 55px;
}

input[type='radio'] + label:after {
  top: 2.64px;
  left: -25.0px;
  width: 50.0px;
  height: 50.0px;
}

/* -------------------
	SuperBtn
-------------------- 
a.superBtn {
  color: #0e0e0e;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.1);
  font-weight: bold;
  letter-spacing: .08em;
  width: 242.0px;
  height: 39.6px;
  line-height: 39.6px;
  position: relative;
  -moz-border-radius: 30px;
  -webkit-border-radius: 30px;
  border-radius: 30px;
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzJlMzUzNyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzQyNDc0OCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #2e3537), color-stop(100%, #424748));
  background-image: -moz-linear-gradient(#2e3537, #424748);
  background-image: -webkit-linear-gradient(#2e3537, #424748);
  background-image: linear-gradient(#2e3537, #424748);
  -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.6), inset 0 -1px 0 rgba(0, 0, 0, 0.3), inset 0 0 0px 1px rgba(0, 0, 0, 0.1), 0 0 1px rgba(0, 0, 0, 0.5), 0 2px 2px rgba(0, 0, 0, 0.4);
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.6), inset 0 -1px 0 rgba(0, 0, 0, 0.3), inset 0 0 0px 1px rgba(0, 0, 0, 0.1), 0 0 1px rgba(0, 0, 0, 0.5), 0 2px 2px rgba(0, 0, 0, 0.4);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.6), inset 0 -1px 0 rgba(0, 0, 0, 0.3), inset 0 0 0px 1px rgba(0, 0, 0, 0.1), 0 0 1px rgba(0, 0, 0, 0.5), 0 2px 2px rgba(0, 0, 0, 0.4);
}

a.superBtn:after {
  width: 253.0px;
  height: 49.5px;
  top: -4.95px;
  margin-left: 50%;
  left: -126.5px;
  content: '';
  display: block;
  -moz-border-radius: 30px;
  -webkit-border-radius: 30px;
  border-radius: 30px;
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzJhZjFmYyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzE3YjJlNiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #2af1fc), color-stop(100%, #17b2e6));
  background-image: -moz-linear-gradient(#2af1fc, #17b2e6);
  background-image: -webkit-linear-gradient(#2af1fc, #17b2e6);
  background-image: linear-gradient(#2af1fc, #17b2e6);
  -moz-box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6);
  -webkit-box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6);
  box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6);
  position: absolute;
  z-index: -1;
}

/* -------------------
	SuperBtn Hover
-------------------- 
a.superBtn:hover {
  color: #AEAEAE;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.8);
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzU0NTQ1NCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzM3MzczOCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #545454), color-stop(100%, #373738));
  background-image: -moz-linear-gradient(#545454, #373738);
  background-image: -webkit-linear-gradient(#545454, #373738);
  background-image: linear-gradient(#545454, #373738);
}

a.superBtn:hover:after {
  -moz-box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6), 0 0 15px 5px rgba(0, 255, 255, 0.2);
  -webkit-box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6), 0 0 15px 5px rgba(0, 255, 255, 0.2);
  box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.7), 0 1px 1px rgba(255, 255, 255, 0.4), 0 0 1px 1px rgba(0, 0, 0, 0.3), inset 0 0px 3px rgba(0, 0, 0, 0.4), inset 0 1px 2px rgba(0, 0, 0, 0.6), 0 0 15px 5px rgba(0, 255, 255, 0.2);
}

a.superBtn:active {
  color: #00ccff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.3), 0 0px 30px rgba(0, 255, 255, 0.7);
  background: #333;
  -moz-box-shadow: 0 1px 0px rgba(255, 255, 255, 0.4), inset 0 3px 3px rgba(0, 0, 0, 0.7), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
  -webkit-box-shadow: 0 1px 0px rgba(255, 255, 255, 0.4), inset 0 3px 3px rgba(0, 0, 0, 0.7), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
  box-shadow: 0 1px 0px rgba(255, 255, 255, 0.4), inset 0 3px 3px rgba(0, 0, 0, 0.7), inset 0 0 4px rgba(0, 0, 0, 0.9), 0 0 0 black;
}
*/
</style>
