<!-- <table class=" table table-striped table-hover table-bordered " >
<thead>	
	<tr class="menu">    
        <th>Item</th>
        <th >Descripcion de Tareas</th>
        <th>US$/item</th>
        <th>hrs/item</th>  
        <th>Inicio Planificado</th>
        <th>Fin Planificado</th>
        <th>Inicio Real</th>
        <th>Fin Real</th>    
    </tr>
</thead>
<tbody>
	<td ng-repeat="per in CP.thi" >
			{{ per.fecha_ingreso_performance }}
	</td>
</tbody>
</table> -->

<div class="form-group" class="col-md-4"  >
  <div class="col-md-1" >
      <label>Escoja una revision: </label> 
  </div>
  <div class="col-md-2" >
    <select class="form-control" ng-model="CP.revi"         
      ng-options="c.revision_cronograma for c in CP.procronograma ">
    </select> 
  </div>
  <div class="col-md-2" >
    <button class="btn btn-success" ng-click="CP.buscaperformance(CP.revi)" class="btn btn-primary btn-xs">Busca</button>
  </div>
</div>



<form method="POST" action="#" editable-form name="tableform" onaftersave="CP.saveTable()" oncancel="cancel()" >
<table class=" table table-striped table-hover table-bordered ">
	<thead>	
		<tr class="menu">    
	        <th>Item</th>
	        <th>Actividad Id</th>
	        <th >Descripcion de Tareas</th>
	        <th >Predecesora</th>
	        <th>US$/item</th>
	        <th>hrs/item</th>	
	        <th>US$/item</th>
	        <th>hrs/item</th>	
	        <th>%</th>	
	        <th>hrs/item</th>	
	        <th>US$/item</th>
	        
	        <th>%</th>	
	        <th>Inicio Planificado</th>
	        <th>Fin Planificado</th>
	        <th >Duracion</th>
	        <th>Inicio Real</th>
	        <th>Fin Real</th>
	        <td ng-repeat="per in CP.thi" >
			{{ per.fecha }}
			</td>
					
	    
	    </tr>
	</thead>
	<tbody>
  		<tr ng-repeat-start="performance in CP.performance " >
          	<td >
            	{{ $index }}  
          	</td>
          	<td >
            	{{ performance.actividadid }}  
          	</td>
          	<td>
				{{ performance.nombre}}
			</td>
 			<td>
 				<span editable-text="performance.predecesoras" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.predecesoras }}
				</span>
			</td>
          	<td>			
				<span editable-text="performance.horas_propuesta" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.horas_propuesta }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.costo_propuesta" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.costo_propuesta }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.horas_planificado" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.horas_planificado }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.costo_planificado" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.costo_planificado }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.porcentaje_planificado" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.porcentaje_planificado }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.horas_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.horas_real }}
				</span>
			</td> 

			<td>
				<span editable-text="performance.costo_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.costo_real }}
				</span>
			</td>
	
			<td>
				<span editable-text="performance.porcentaje_real" e-form="tableform" onbeforesave="checkName($data, performance.porcentaje_real)">
				{{ performance.porcentaje_real }}
				</span>
			</td>

	
			<td>
				<span editable-text="performance.fecha_comienzo" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.fecha_comienzo | date:'medium' }}
				</span>				
			</td> 
			<td>
				<span editable-text="performance.fecha_fin" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.fecha_fin }}
				</span>
			</td>

			<td>			
				<span editable-text="performance.duracion" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)" ng-enter="CP.calculafechafin()">
				{{ performance.duracion }}
				</span>
			</td>

			<td>
				<span editable-text="performance.fecha_comienzo_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
				{{ performance.fecha_comienzo_real }}
				</span>
			</td> 
			
			<td>
	          <span editable-text="performance.fecha_fin_real" e-form="tableform" onbeforesave="checkName($data, performance.codigo_performance)">
	            {{ performance.fecha_fin_real }}
	          </span>
	        </td>


	      	<td ng-repeat="item in performance.items" >
	          <!--   <input class="form-control" type="text" ng-model=" item.porcentaje_performance "></input> -->
	          <span editable-text="item.porcentaje_performance" e-form="tableform" onbeforesave="checkName($data, item.porcentaje_performance)">
	            {{ item.porcentaje_performance }}
	          </span>
	             
	        </td>	        
        </tr>

   <tr ng-repeat-end>
 
        <hr>
    </tr>
	</tbody>
</table> 

<div class="btn-edit">
    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button>
</div>
<div class="btn-form" ng-show="tableform.$visible">

    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-primary">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-default">cancelar</button>
</div>

</form>
    <input id="taskName" class="form-control" type="text" placeholder="type task name"  ng-enter="CP.calculafechafin()" />