<div class="panel">
  <nav class="panel-heading tab-bg-dark-navy-blue">
    <ul class="nav nav-tabs">
      <li ng-class="va.edt_activo"><a href="" ng-click="va.cambiarPanel('edt')">EDT</a></li>
      <li ng-class="va.tecnicos_activo"><a href="" ng-click="va.cambiarPanel('tecnicos')">Técnicos</a></li>
      <li ng-class="va.gestion_activo"><a href="" ng-click="va.cambiarPanel('gestion')">Gestión</a></li>
      <li ng-class="va.comunicacion_activo"><a href="" ng-click="va.cambiarPanel('comunicacion')">Comunicación</a></li>
    </ul>
  </nav>
  <div class="panel-body">
    <div class="tab-content">

      <div class="tab-pane" ng-class="va.edt_activo">
        <div class="col-md-6">
          <table class="table table-bordered">
            <thead>
              <th>
                N°
              </th>
              <th>
                EDT
              </th>
            </thead>
            <tbody>
              <tr ng-repeat="edt in va.edt track by $index">
                <td>
                  {{edt.codigo}}
                </td>
                <td>
                  {{edt.nombre}}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <button type="button" class="btn btn-default" ng-click="va.imprimirEdt()">Imprimir</button>
        </div>
      </div>

      <div class="tab-pane" ng-class="va.tabla_visible">
        <header>
            <button type="button" class="btn btn-success btn-xs"
            ng-click="va.cargarRevisiones('Ultimo')">Últimas Revisiones</button>
            <button type="button" class="btn btn-info btn-xs"
            ng-click="va.cargarRevisiones('all')">Historial Revisiones</button>
            <button type="button" class="btn btn-warning btn-xs"
            ng-click="va.editarTransmittal()">Transmittals</button>
            <button type="button" class="btn btn-danger btn-xs">Planificación</button>
        </header>

        <div class="tab-content">

          <div ng-include="'/controldocumentario/index/tablaentregables'"
          class="tab-pane" ng-class="va.tabla_activa">

          </div>
          <div ng-include="'/controldocumentario/index/editartransmittal'"
          class="tab-pane" ng-class="va.trans_activo">

          </div>
        </div>

      </div>

    </div>
   </div>

</div>
