<div class="">
  <nav>
    <ul>
      <li><a href="#">EDT</a></li>
      <li><a href="#">Técnicos</a></li>
      <li><a href="#">Gestión</a></li>
      <li><a href="#">Comunicación</a></li>
      <li><a href="#">Búsqueda</a></li>
      <li><a href="#">Filtro</a></li>
    </ul>
  </nav>
  <div class="">
    <table class="table table-bordered">
      <thead>
        <th>
          N°
        </th>
        <th>
          EDT
        </th>
      </thead>
      <tbody>
        <tr ng-repeat="edt in CD.edt track by $index">
          <td>
            {{edt.codigo}}
          </td>
          <td>
            {{edt.nombre}}
          </td>
        </tr>
      </tbody>
    </table>
    <ul>
      <li><a href="#">Imprimir</a></li>
      <li><a href="#">Editar</a></li>
      <li><a href="#">Agregar</a></li>
      <li><a href="#">Guardar</a></li>
      <li><a href="#">Cancelar</a></li>
      <li><a href="#">Eliminar</a></li>
    </ul>
  </div>
  <div class="">
    
  </div>
</div>
