<div>
  <div class="col-md-6">
    <div class="panel">
      <h1 class="panel-heading">Ubicación de Carpetas de Proyectos</h1>
      <div class="panel-body">
        <table class="table table-bordered table-striped table-condensed">
          <thead>
            <th>
              Carpetas
            </th>
            <th>
              En Proceso
            </th>
            <th>
              Stand By
            </th>
            <th>
              Cancelado
            </th>
            <th>
              Cerrado
            </th>
          </thead>
          <tbody>
            <tr ng-repeat="carpeta in uc.carpetas track by $index">
              <td>
                {{carpeta.nombre}}
              </td>
              <td>
                {{carpeta.A}}
              </td>
              <td>
                {{carpeta.P}}
              </td>
              <td>
                {{carpeta.CA}}
              </td>
              <td>
                {{carpeta.C}}
              </td>
            </tr>
          </tbody>
          <tfoot>
            <td>
              Sub Total
            </td>
            <td>
              {{uc.cantidad_carpetas.en_proceso}}
            </td>
            <td>
              {{uc.cantidad_carpetas.stand_by}}
            </td>
            <td>
              {{uc.cantidad_carpetas.cancelado}}
            </td>
            <td>
              {{uc.cantidad_carpetas.cerrado}}
            </td>
          </tfoot>
        </table>
      </div>
    </div>

  </div>

  <div class="col-md-6">
    <div class="panel">
			<h1 class="panel-heading">Ubicación de los Proyectos</h1>
			<div class="panel-body">
				<canvas id="bar" class="chart chart-bar" data="uc.datos" labels="uc.labels"
					series="uc.series" options="uc.options"></canvas>
			</div>
		</div>
  </div>

  <footer class="col-md-12">
    <div class="panel">
      <h1 class="panel-heading">Acciones</h1>
      <div class="panel-body">
        <button type="button" class="btn btn-default" ng-click="uc.imprimir()">Imprimir</button>
      </div>
    </div>


  </footer>
</div>
