<div class="panel">
  <div class="form-inline">

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Codificación</label>
      <input type="text" class="form-control" ng-model="vc.transmittal.codificacion">
      <label for=""> - </label>
      <input type="text" class="form-control" disabled ng-model="vc.transmittal.correlativo">
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Formato:</label>
      <select class="form-control" ng-model="vc.transmittal.formato"
      ng-options="formato.tipo as formato.tipo for formato in vc.formatos">
      </select>
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Cliente:</label>
      <label for="" class="">{{vc.transmittal.cliente}}</label>
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Tipo de envío:</label>
      <select class="form-control" ng-model="vc.transmittal.tipo_envio"
      ng-options="tipo.tipo as tipo.tipo for tipo in vc.tipos_envio">
      </select>
      <button type="button" class="btn btn-default btn-xs" ng-click="vc.editarTipoEnvio()">Editar</button>
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Atención:</label>
      <select class="form-control" ng-model="vc.transmittal.atencion"
      ng-change="vc.cambiarContacto()"
      ng-options="contacto.contactoid as contacto.nombre for contacto in vc.contactos">
      </select>
      <button type="button" class="btn btn-default btn-xs" ng-click="vc.editarContacto()">Editar</button>
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">CD:</label>
      <input type="text" class="form-control" disabled ng-model="vc.control_documentario">
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Área:</label>
      <input type="text" class="form-control" disabled ng-model="vc.datos_contacto_seleccionado.area">
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Días de alerta:</label>
      <input type="number" min="0" class="form-control" ng-model="vc.transmittal.dias_alerta">
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Correo:</label>
      <input type="text" class="form-control" disabled ng-model="vc.datos_contacto_seleccionado.correo">
    </section>

    <section class="col-md-6 col-sm-12 form-group panel-body">
      <label for="" class="col-md-3">Tipo de proyecto:</label>
      <select class="form-control" ng-model="vc.transmittal.tipo_proyecto"
      ng-options="tipo.tipo_proyecto as tipo.tipo_proyecto for tipo in vc.tipos_proyecto">
      </select>
    </section>

    <section class="col-md-12 col-sm-12 form-group panel-body">
      <button type="button" class="btn btn-success" ng-click="vc.guardarConfiguracion()">Guardar</button>
    </section>

  </div>
</div>
