<div ng-app="moduloCd">
	<div ng-view>

	</div>
</div>

<script type="text/javascript" src="/js/angular-route.js"></script>
<script type="text/javascript" src="/js/Chart.js"></script>
<script type="text/javascript" src="/js/angular-chart.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controldocumentario.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/services/httpFactory.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/services/proyectoFactory.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/services/entregableFactory.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/services/transmittalFactory.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/PanelCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/CarpetasCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/ProyectoCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/TransmittalCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/ConfigurarTrCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/AnddesCtrl.js"></script>
<script type="text/javascript" src="/js/ControlDocumentario/controllers/ModalContactoCtrl.js"></script>
