<div class="panel" ng-app>
	<h2>Panel de Control</h2>
	<div class="col-md-6">
		<h3>Cantidad de Proyectos</h3>
		<table class="table table-bordered table-striped table-condensed">
			<thead>
				<th>
					Cantidad de Py
				</th>
				<th>
					En Proceso
				</th>
				<th>
					Stand By
				</th>
				<th>
					Cancelado
				</th>
				<th>
					Cerrado
				</th>
			</thead>
			<tbody>
				<tr>
					<td>
						{{CD.cantidad_proyectos.total}}
					</td>
					<td>
						{{CD.cantidad_proyectos.en_proceso}}
					</td>
					<td>
						{{CD.cantidad_proyectos.stand_by}}
					</td>
					<td>
						{{CD.cantidad_proyectos.cancelado}}
					</td>
					<td>
						{{CD.cantidad_proyectos.cerrado}}
					</td>
				</tr>
			</tbody>
		</table>
		<h3>Carga Laboral Control Documentario</h3>
		<table class="table table-bordered table-striped table-condensed">
			<thead>
				<th>
					Integrantes
				</th>
				<th>
					En Proceso
				</th>
				<th>
					Stand By
				</th>
				<th>
					Cancelado
				</th>
				<th>
					Cerrado
				</th>
			</thead>
			<tbody>
				<tr ng-repeat="integrante in CD.integrantes track by $index">
					<td>
						{{integrante.nombre}}
					</td>
					<td>
						{{integrante.en_proceso}}
					</td>
					<td>
						{{integrante.stand_by}}
					</td>
					<td>
						{{integrante.cancelado}}
					</td>
					<td>
						{{integrante.cerrado}}
					</td>
				</tr>
			</tbody>
			<tfoot>
				<td>
					Sub Total
				</td>
				<td>
					{{CD.cantidad_proyectos.en_proceso}}
				</td>
				<td>
					{{CD.cantidad_proyectos.stand_by}}
				</td>
				<td>
					{{CD.cantidad_proyectos.cancelado}}
				</td>
				<td>
					{{CD.cantidad_proyectos.cerrado}}
				</td>
			</tfoot>
		</table>
	</div>
	<div class="col-md-6">

	</div>
	<nav class="col-md-12">
		<ul>
			<li><a href="#">Listar los Proyectos</a></li>
			<li><a href="#">Asignar CD a Proyecto</a></li>
			<li><a href="#">Ubicación de Carpetas de Proyectos</a></li>
			<li><a href="#">Generar Reporte de Planificación</a></li>
		</ul>
	</nav>
</div>
