<!--div de modal edicion de contactos-->
<div class="modal fade" id="edit_contacto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <header class="modal-header">
          <button type="button" class="close" aria-hidden="true">x</button>
          <h4 class="modal-title">Editar Contacto:</h1>
        </header>
          <div class="modal-body">
            <section class="form-group">
              <label for="">Atención:</label>
              <input type="text" class="form-control">
            </section>
            <section class="form-group">
              <label for="">Área:</label>
              <input type="text" class="form-control">
            </section>
            <section class="form-group">
              <label for="">Correo:</label>
              <input type="text" class="form-control">
            </section>
          </div>
          <footer class="modal-footer">
            <button type="button" class="btn btn-info btn-xs">Agregar</button>
            <button type="button" class="btn btn-warning btn-xs">Modificar</button>
            <button type="button" class="btn btn-danger btn-xs">Eliminar</button>
            <button type="button" class="btn btn-success btn-xs">Guardar</button>
          </footer>
      </div>
  </div>
</div>
