<header class="modal-header">
  <button type="button" class="close" aria-hidden="true" ng-click="mt.cancel()">x</button>
  <h4 class="modal-title">Editar Tipo de Envío:</h1>
</header>
<div class="modal-body">
  <table>
    <thead>
      <th>
        Empresa
      </th>
      <th>
        Abrev.
      </th>
      <th>
        Emitido para:
      </th>
    </thead>
    <tbody>
      <tr ng-repeat="tipo_envio in mt.tipo_envio">
        <td>
          <input type="text" ng-model="tipo_envio.empresa">
        </td>
        <td>
          <input type="text" ng-model="tipo_envio.abrev">
        </td>
        <td>
          <input type="text" ng-model="tipo_envio.emitido_para">
        </td>
      </tr>
    </tbody>
  </table>
</div>
<footer class="modal-footer">
  <button type="button" class="btn btn-success btn-xs">Agregar</button>
  <button type="button" class="btn btn-warning btn-xs">Modificar</button>
  <button type="button" class="btn btn-info btn-xs">Eliminar</button>
  <button type="button" class="btn btn-default btn-xs">Guardar</button>
  <button type="button" class="btn btn-danger btn-xs" ng-click="mt.cancel()">Cancelar</button>
</footer>
