<div class="panel">
  <header>
    <h2>Proyectos</h2>
    <div class="pull-right">
      <button type="button" class="btn btn-success">Activo</button>
  		<button type="button" class="btn btn-warning">Cerrado</button>
      <button type="button" class="btn btn-info">Cancelado</button>
      <button type="button" class="btn btn-danger">Paralizado</button>
    </div>
    <div class="">
      <button type="button" class="btn btn-primary">Crear</button>
    </div>
  </header>
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>
        CÓDIGO
      </th>
      <th>
        CLIENTE
      </th>
      <th>
        NOMBRE
      </th>
      <th>
        GERENTE DEL PROYECTO
      </th>
      <th>
        CONTROL DEL PROYECTO
      </th>
      <th>
        CONTROL DOCUMENTARIO
      </th>
      <th>
        ESTADO
      </th>
      <th>
        ACCIONES
      </th>
    </thead>
    <tbody>
      <tr ng-repeat="proyecto in CD.proyectos track by $index">
        <td>
          {{proyecto.codigo}}
        </td>
        <td>
          {{proyecto.cliente}}
        </td>
        <td>
          {{proyecto.nombre}}
        </td>
        <td>
          {{proyecto.gerente}}
        </td>
        <td>
          {{proyecto.control_proyecto}}
        </td>
        <td>
          {{proyecto.control_documentario}}
        </td>
        <td>
          {{proyecto.estado}}
        </td>
        <td>
          <ul>
            <li>
              <button type="button" class="btn btn-default btn-sm">Información</button>
            </li>
            <li>
              <button type="button" class="btn btn-default btn-sm" ng-click="CD.generarTr(proyecto.codigo)">
                Generar TR
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-default btn-sm">Generar RPT</button>
            </li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="panel">
    <button type="button" class="btn btn-default">Editar</button>
    <button type="button" class="btn btn-default">Exportar</button>
    <button type="button" class="btn btn-default">Imprimir</button>
  </div>
</div>
