<div class="panel">
  <h1 class="panel-heading">Generar reporte de Planificación</h1>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-condensed">
        <thead>
          <tr>
            <th colspan="12">

            </th>
            <th colspan="7">
              SEMANA PASADA
            </th>
            <th colspan="7">
              SEMANA ACTUAL
            </th>
            <th colspan="7">
              SEMANA FUTURA
            </th>
          </tr>
          <tr>
            <th>
              N°
            </th>
            <th>
              EDT
            </th>
            <th>
              Tipo
            </th>
            <th>
              Disciplina
            </th>
            <th>
              Codigo Anddes
            </th>
            <th>
              Codigo Cliente
            </th>
            <th>
              descripción de Entregables
            </th>
            <th>
              Fecha
            </th>
            <th>
              Fecha
            </th>
            <th>
              Fecha
            </th>
            <th>
              Rev.
            </th>
            <th>
              Estado
            </th>
            <th ng-repeat="dia in reporte.dias track by $index">
              {{dia.texto}}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat-start="grupo in reporte.grupos track by $index">
            <td colspan="12" class="post-highlight terques">
              {{grupo.proyecto.nombre}}
            </td>
            <td ng-repeat="dia in grupo.dias track by $index"
            ng-class="dia">

            </td>
          </tr>
          <tr ng-repeat="entregable in grupo.entregables track by $index">
            <td>
              {{$index + 1}}
            </td>
            <td>
              {{entregable.edt}}
            </td>
            <td>
              {{entregable.tipo_documento}}
            </td>
            <td>
              {{entregable.disciplina}}
            </td>
            <td>
              {{entregable.codigo_anddes}}
            </td>
            <td>
              {{entregable.codigo_cliente}}
            </td>
            <td>
              {{entregable.descripcion_entregable}}
            </td>
            <td>
              {{entregable.fecha_a}}
            </td>
            <td>
              {{ebtregable.fecha_b}}
            </td>
            <td>
              {{entregable.fecha_0}}
            </td>
            <td>
              {{entregable.revision_entregable}}
            </td>
            <td>
              {{entregable.estado}}
            </td>
            <td ng-repeat="dia in entregable.dias track by $index"
            ng-class="dia">

            </td>
          </tr>
          <tr ng-repeat-end>

          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>

</div>
<footer class="panel">
  <h1 class="panel-heading">Acciones:</h1>
  <div class="panel-body">
    <div class="col-md-3">
      <p class="input-group">
        <input type="date" class="form-control" datepicker-popup ng-model="reporte.dia_sel"
        is-open="status.opened" datepicker-options="dateOptions"
        date-disabled="disabled(date, mode)" ng-change="reporte.actualizarDias()"
        ng-required="true" close-text="Close" />
      </p>
    </div>
    <button type="button" class="btn btn-default">Imprimir</button>
  </div>
</footer>
