<div class="panel">
  <h1 class="panel-heading">Generar reporte de Planificación</h1>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-condensed">
        <thead>
          <th>
            N°
          </th>
          <th>
            EDT
          </th>
          <th>
            Tipo
          </th>
          <th>
            Disciplina
          </th>
          <th>
            Codigo Anddes
          </th>
          <th>
            Codigo Cliente
          </th>
          <th>
            descripción de Entregables
          </th>
          <th>
            Fecha
          </th>
          <th>
            Fecha
          </th>
          <th>
            Fecha
          </th>
          <th>
            Rev.
          </th>
          <th>
            Estado
          </th>
          <th ng-repeat="dia in reporte.dias">
            {{dia}}
          </th>
        </thead>
        <tbody>
          <tr ng-repeat-start="grupo in reporte.grupos track by $index">
            <td colspan="12" class="post-highlight terques">
              Fecha de inicio y fin del proyecto
            </td>
            <td ng-repeat="dia in reporte.dias">

            </td>
          </tr>
          <tr ng-repeat="entregable in grupo.entregables track by $index">
            <td>
              {{$index + 1}}
            </td>
            <td>
              {{entregable.edt}}
            </td>
            <td>
              {{entregable.tipo_documento}}
            </td>
            <td>
              {{entregable.disciplina}}
            </td>
            <td>
              {{entregable.codigo_anddes}}
            </td>
            <td>
              {{entregable.codigo_cliente}}
            </td>
            <td>
              {{entregable.descripcion_entregable}}
            </td>
            <td>
              {{entregable.fecha_a}}
            </td>
            <td>
              {{ebtregable.fecha_b}}
            </td>
            <td>
              {{entregable.fecha_0}}
            </td>
            <td>
              {{entregable.revision_entregable}}
            </td>
            <td>
              {{entregable.estado}}
            </td>
            <td ng-repeat="dia in reporte.dias">

            </td>
          </tr>
          <tr ng-repeat-end>

          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div gantt data="reporte.grupos">

  </div>
  <div class="panel-body">
    <button type="button" class="btn btn-default">Almanaque</button>
    <button type="button" class="btn btn-default">Filtrar x CD</button>
    <button type="button" class="btn btn-default"> Filtrar x GP</button>
  </div>
</div>

</div>
<footer class="panel">
  <h1 class="panel-heading">Acciones:</h1>
  <div class="panel-body">
    <button type="button" class="btn btn-default">Agregar</button>
    <button type="button" class="btn btn-default">Editar</button>
    <button type="button" class="btn btn-default">Guardar</button>
    <button type="button" class="btn btn-default">Eliminar</button>
    <button type="button" class="btn btn-default">Imprimir</button>
  </div>
</footer>
