<section class="panel">
    <header class="panel-heading">
      Lista de Clientes
      <span class="pull-right">
            <a id="mostrar_enelaboracion" class=" btn btn-success btn-xs"> Proyecto</a>
            <a id="mostrar_enviada" class=" btn btn-warning  btn-xs"> Proveedores</a>
            <a id="mostrar_ganada" class=" btn btn-primary  btn-xs" style="background-color: #59ace2;color: #fff;"> Propuesta</a>
      </span>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div class="input-group"><input id="buscar_propuesta" type="text" placeholder="Buscar Cliente" class="input-sm form-control"> <span class="input-group-btn">
                <button id="btn_buscar_propuesta" type="button" class="btn btn-sm btn-success"> Buscar!</button> 
                <a href="/propuesta/index/nuevo" class=" btn btn-primary btn-sm" > Crear</a>
                <!--/propuesta/index/reporteexcel-->
                <a href="#" class=" btn btn-danger btn-sm " > Exportar</a>
              </span></div>
          </div>
      </div>
  </div>
  
  <div id="propuesta_enelaboracion" >
  <table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 10%;">RUC</th>
          <th style="width: 40%;"> Razon Social</th>
          <th style="width: 30%;">Logo</th>
          <th style="width: 20%;">Tag</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_cliente as $lista) {
          //print_r($lista);
        ?>  

        <tr>
            <td class="p-name">
            <a class="control-label">
                <?php echo $lista['clienteid'];?>
                </a>
            </td>

            <td class="p-name">
                <?php echo $lista['nombre_comercial'];?>  
            </td>

            <td class="p-name">
               <a href="#" class="logo"><img width="150" src="/img/logo.jpg"></a>
            </td>
                  <td class="p-name">
              
            </td>
          
            
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
              <a href="/propuesta/index/ver" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
              <a href="/propuesta/index/ver" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>


<script>
$(document).ready(function(){
    $("#mostrar_ganada").click(function(){
             
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").show();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();

    });
    $("#mostrar_enelaboracion").click(function(){
        $("#propuesta_enelaboracion").show();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });
    $("#mostrar_perdida").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").show();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_enviada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").show();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_declinada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").show();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_anulada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").show();
        $("#resultado_busqueda").hide();
    });    


    $("#btn_buscar_propuesta").click(function(){
        var buscar_propuesta = $("#buscar_propuesta").val();
        
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").show();
        if (buscar_propuesta=='')  
        {
            alert("ingrese propuesta a buscar");
        }
        else
        { 
            var url="/propuesta/index/buscar/propuesta/"+buscar_propuesta;    
        }
        $("#resultado_busqueda").load(url);
    });    

});
</script>