<section class="panel">
    <header class="panel-heading">
        Nuevo Cliente
    </header>
</section>

<div class="row">
<div class="col-md-12">
<section class="panel">
    <div class="panel-body bio-graph-info">
        <div class="row p-details">
            
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >RUC ID(*)</label>
                    <input id="clienteid" type="text" class="input-sm form-control" maxlength="11" required/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Nombre Comercial (*)</label>
                    <input id="nombre_comercial" type="text" class="input-sm form-control" required/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Nombre (*)</label>
                    <input id="nombre" type="text" class="input-sm form-control" required/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Codigo Anddes</label>
                    <input id="codigoid" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Fecha de Registro</label>
                    <input id="fecha_registro" type="text" class="form-control input-sm form-control-inline input-medium default-date-picker"  />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Web</label>
                    <input id="web" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Dirección</label>
                    <input id="direccion" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >País</label>
                    <input id="paisid" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Departamento</label>
                    <input id="departamentoid" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Provincia</label>
                    <input id="provinciaid" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Distrito</label>
                    <input id="distritoid" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Estado</label>
                    <input id="estado" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Tag</label>
                    <input id="tag" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Proveedor</label>
                    <input id="isproveedor" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Cliente</label>
                    <input id="iscliente" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Abreviatura</label>
                    <input id="abreviatura" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Tipo de Cliente</label>
                    <input id="tipo_cliente" type="text" class="input-sm form-control" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Ruc</label>
                    <input id="ruc" type="text" class="input-sm form-control" maxlength="11" />
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Socio</label>
                    <input id="issocio" type="text" class="input-sm form-control"/>
                </div>
            </div>

            <div class="bio-row form-group has-success">
                <div class="panel-body">
                    <a class="btn btn-success btn-sm" id="guardar_cliente">Guardar</a>                                      
                    <a class="btn btn-info btn-sm" href="/admin/tbmaestracliente/listarcliente">Cancelar</a> 
                </div>
            </div>
        </div>
    </div>
</section>
</div>
</div>

<div id="cargar_datos"></div>

<script type='text/javascript'>
 $("#guardar_cliente").click(function(){
   var clienteid = $("#clienteid").val();//no null
   var nombre_comercial = $("#nombre_comercial").val();//no null
   var nombre = $("#nombre").val();//no null
   var codigoid = $("#codigoid").val();
   var fecha_registro = $("#fecha_registro").val();
   var web = $("#web").val();
   var direccion = $("#direccion").val();
   var paisid = $("#paisid").val();
   var departamentoid = $("#departamentoid").val();
   var provinciaid = $("#provinciaid").val();
   var distritoid = $("#distritoid").val();
   var estado = $("#estado").val();
   var tag = $("#tag").val();
   var isproveedor = $("#isproveedor").val();
   var iscliente = $("#iscliente").val();
   var abreviatura = $("#abreviatura").val();
   var tipo_cliente = $("#tipo_cliente").val();
   var ruc = $("#ruc").val();
   var issocio = $("#issocio").val();
   
   if (clienteid=='' || nombre_comercial=='' || nombre=='')
   {
    alert("ingrese los datos requeridos (*)");
   }
   else
   {
    url="/admin/tbmaestracliente/guardarcliente/clienteid/"+clienteid+"/nombre_comercial/"+nombre_comercial+"/nombre/"+nombre+"/codigoid/"+codigoid+"/fecha_registro/"+fecha_registro+"/web/"+web+"/direccion/"+direccion+"/paisid/"+paisid+"/departamentoid/"+departamentoid+"/provinciaid/"+provinciaid+"/distritoid/"+distritoid+"/estado/"+estado+"/tag/"+tag+"/isproveedor/"+isproveedor+"/iscliente/"+iscliente+"/abreviatura/"+abreviatura+"/tipo_cliente/"+tipo_cliente+"/ruc/"+ruc+"/issocio/"+issocio;
    // alert(url);
    $("#cargar_datos").load(url);
    document.location.href="/admin/tbmaestracliente/listarcliente";

   }
   });

</script>