<table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 80%;">Codigo</th>
          <th style="width: 20%;">Revisión</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_buscar as $lista) {
         // print_r($lista_buscar);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

         
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>