 <table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 45%;">Nombre</th>
          <th style="width: 10%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_buscar as $lista) {
         // print_r($lista_buscar);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
          
            <td>
                <?php
                if ($lista['estado_propuesta']=='D') 
                    {
                        ?>
                        <span class="label label-default label-mini">Declinada</span><?php
                    }
                ?>
                <?php
                if ($lista['estado_propuesta']=='EE') 
                    {
                        ?>
                        <span class="label label-success label-mini">En Elaboración</span><?php
                    }
                ?>
                 <?php
                if ($lista['estado_propuesta']=='G') 
                    {
                        ?>
                        <span class="label label-primary label-mini">Ganada</span><?php
                    }
                ?>
  <?php
                if ($lista['estado_propuesta']=='P') 
                    {
                        ?>
                        <span class="label label-danger label-mini">Perdida</span><?php
                    }
                ?>
                  <?php
                if ($lista['estado_propuesta']=='E') 
                    {
                        ?>
                        <span class="label label-warning label-mini">Enviada</span><?php
                    }
                ?>
                  <?php
                if ($lista['estado_propuesta']=='A') 
                    {
                        ?>
                        <span class="label label-info label-mini">Anulada</span><?php
                    }
                ?>
            <!-- Habilitar cambio estado d elas propuesta sganadas -->
            <!--
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                </ul>
            </div>-->
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
              <a href="/propuesta/index/ver" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
              <a href="/propuesta/index/ver" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>