<?php
    $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
    include_once($dir);
    ob_start();
    $sesion1  = Zend_Auth::getInstance();
    $sesion = $sesion1->getStorage()->read();
?>

<!-- <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  --> 
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<!-- <link href="/css/print.css" rel="stylesheet">  -->


<table  style="width:100%," class="table table-bordered" font-size="9px" style="font-family: 'Abel', serif;">
    <tr>
        <th ><img style="width: 30%;" src="/img/logo.jpg"></th>
        <th rowspan="2" style="width: 50%;text-align: center;"> <p>CONTROL DOCUMENTARIO </p> <p>Transmittal </p></th>
        <th style="width: 30%;">  </th>
    </tr>   
    <tr> 
        <th style="width: 10%;text-align: center;color: #fff;background-color:rgba(0, 105, 173, 1)"> SIG AND </th>         
        <th style="width: 30%;text-align: center;color: #fff;background-color:rgba(0, 105, 173, 1)">  </th>
    </tr>    
</table>

<table style="width: 100%;" class="table table-bordered" font-size="9px" style="font-family: 'Abel', serif;">
    <tr>
        <th style="width: 15%"> Para</th>       
        <th style="width: 40%;"> <?php 
            $cliente = new Admin_Model_DbTable_Cliente();
            $where['clienteid']=$this->transmitta['clienteid'];
            $traercliente=$cliente-> _getOne($where);
            echo $traercliente['nombre_comercial'];            
            ?>

        </th> 
        <th style="width: 15%"> Transmittal N°</th> 
        <th style="width: 40%;" colspan="3"><?php echo $this->transmitta['transmittaid']  ?></th> 
    </tr>
    <tr>
        <th > Atención</th>       
        <th > <?php echo $this->transmitta['para'] ?></th> 
        <th > Proyecto</th> 
        <th colspan="3"  > <?php

            $propuesta = new Admin_Model_DbTable_Propuesta();            
            $where['codigo_prop_proy']=$this->transmitta['codigo_prop_proy'];
            $where['propuestaid']=$this->transmitta['propuestaid'];
            $where['revision']=$this->transmitta['revision'];
            $traerpropuesta=$propuesta->_getOne($where);
            echo $traerpropuesta['nombre_propuesta']; 
            ?>
       </th> 
    </tr>
    <tr>
        <th > C.c</th>       
        <th ><?php         
            // $where['clienteid']=$this->transmitta['clienteid']; 
            // $where['contactoid']=$this->transmitta['cc']; 
            // $contacto = new Admin_Model_DbTable_Contacto();  
            // $vercontact=$contacto->_getFilter($where);
            // echo $vercontact['nombre'],
            echo $this->transmitta['cc']
           
            ?> </th> 
        <th > Referencia</th> 
        <th colspan="3"><?php echo $this->transmitta['referencia'] ?></th> 
    </tr>
    <tr>
        <th style="width: 10%"> Envío</th>       
        <th style="width: 40%"> <input type="checkbox"><?php echo $this->transmitta['envio'] ?><br></th>       
        <th style="width: 10%"> Código</th> 
        <th style="width: 10%"> <?php echo $this->transmitta['propuestaid'] ?></th> 
        <th style="width: 10%"> Fecha</th> 
        <th style="width: 20%"> <?php echo $this->transmitta['fecha_envio'] ?> </th> 
    </tr>
</table>


<div  class="table table-bordered" style="width: 100%;height:550px"  ;>
    <table class="table table-striped table-advance table-hover" font-size="9px" style="font-family: 'Abel', serif;">
    <tr >
        <th style="width: 10%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> N°</th>       
        <th style="width: 10%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> Código</th> 
        <th style="width: 10%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> Rev.</th> 
        <th style="width: 40%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> Título o Descripción</th> 
        <th style="width: 20%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> Tipo</th> 
        <th style="width: 20%;text-align: center;background-color:rgba(0, 105, 173, 1);color: #fff;"> Cantidad</th> 

    </tr>
    <tr>
        <th style="width: 10%;text-align: center"> 1 </th>       
        <th style="width: 10%;text-align: center"> <?php echo $this->transmitta['propuestaid'] ?></th> 
        <th style="width: 10%;text-align: center"> <?php echo $this->transmitta['revision'] ?></th> 
        <th style="width: 40%;text-align: center"> <?php echo $this->transmitta['descripcion'] ?> </th> 
        <th style="width: 20%;text-align: center"> <?php echo $this->transmitta['tipo_envio'] ?></th> 
        <th style="width: 20%;text-align: center"> 1 </th> 
    </tr>

    </table>    
    
</div>



<table class="table table-bordered" font-size="9px" style="font-family: 'Abel', serif;">      
    <tr> 
        <th colspan="6" style="width: 100%"> Observación:</th> 
    </tr>
      
    <tr> 
        <th style="width: 50%"> 
            <p>Tipo de Envío:</p>
            <p><span >A : </span><i ></i>Documento para Revisión y Aprobación</p>
            <p><span >B : </span><i ></i>Documento para Información</p>
            <p><span >C : </span><i ></i>Documento Final</p>
        </th> 
        <th style="width: 50%">
            <p>Tipo de Envío:</p>
            <p><span >AP : </span><i ></i>Aprobado</p>
            <p><span >AC : </span><i ></i>Aprobado con Comentarios</p>
            <p><span >NA : </span><i ></i>No Aprobado, Corregir y Emitir Nuevamente</p>
        </th> 
    </tr>
    <tr> 
        <th style="width: 50%"> 
            <p>Recibido por:</p>
            <p>Fecha</p>
            <p>Firma:</p>
        </th> 
        <th style="width: 50%"> 
            <p>De:</p>
            <p>Firma:</p>
        </th> 
    </tr>
</table>

 
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- <link href="css/bootstrap-reset.css" rel="stylesheet"> -->
 
   
   <!--  <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" /> -->



<?php 
    $html = ob_get_contents();
    $mpdf=new mPDF('win-1252','A4','','',15,15,30,12,5,7);
    $mpdf->SetHTMLHeader($header);
    /*$mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema Anddes');*/
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('ASIGNATURAS -'.$this->perid.'.pdf','D');
?>    