<?php
    $dir = APPLICATION_LIBRARY."/pdf/MPDF57/mpdf.php";
    include_once($dir);
    ob_start();
    $sesion1  = Zend_Auth::getInstance();
    $sesion = $sesion1->getStorage()->read();
?>

<!-- <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />  --> 


<table  style="width:100%," data-max="15" class="table table-bordered">
    <tr>
        <th ><img style="width: 30%;" src="/img/logo.jpg"></th>
        <th rowspan="2" style="width: 50%;text-align: center;"> CONTROL DOCUMENTARIO Transmittal</th>
        <th style="width: 30%;">  </th>
    </tr>   
    <tr> 
        <th style="width: 10%;text-align: center;"> SIG AND </th>         
        <th style="width: 30%;">  </th>
    </tr>    
</table>

<table style="width: 100%;" class="table table-bordered">
    <tr>
        <th style="font-size: 12px;width: 15%"> Para</th>       
        <th style="font-size: 12px;width: 40%"> <?php 
            $cliente = new Admin_Model_DbTable_Cliente();
            $where['clienteid']=$this->transmitta['clienteid'];
            $traercliente=$cliente-> _getOne($where);
            echo $traercliente['nombre_comercial'];            
            ?>

        </th> 
        <th style="font-size: 12px;width: 15%"> Transmittal N°</th> 
        <th style="font-size: 12px;width: 40%" colspan="3"><?php echo $this->transmitta['transmittaid']  ?></th> 
    </tr>
    <tr>
        <th style="font-size: 12px;"> Atención</th>       
        <th style="font-size: 12px;"> <?php echo $this->transmitta['para'] ?></th> 
        <th style="font-size: 12px;"> Proyecto</th> 
        <th style="font-size: 12px;" colspan="3"> <?php

            $propuesta = new Admin_Model_DbTable_Propuesta();            
            $where['codigo_prop_proy']=$this->transmitta['codigo_prop_proy'];
            $where['propuestaid']=$this->transmitta['propuestaid'];
            $where['revision']=$this->transmitta['revision'];
            $traerpropuesta=$propuesta->_getOne($where);
            echo $traerpropuesta['nombre_propuesta']; 
            ?>
       </th> 
    </tr>
    <tr>
        <th style="font-size: 12px;"> C.c</th>       
        <th style="font-size: 12px;" ><?php         
            // $where['clienteid']=$this->transmitta['clienteid']; 
            // $where['contactoid']=$this->transmitta['cc']; 
            // $contacto = new Admin_Model_DbTable_Contacto();  
            // $vercontact=$contacto->_getFilter($where);
            // echo $vercontact['nombre'],
            echo $this->transmitta['cc']
           
            ?> </th> 
        <th style="font-size: 12px;" > Referencia</th> 
        <th style="font-size: 12px;" colspan="3"><?php echo $this->transmitta['referencia'] ?></th> 
    </tr>
    <tr>
        <th style="font-size: 12px;width: 10%"> Envío</th>       
        <th style="font-size: 12px;width: 40%"> <input type="checkbox"><?php echo $this->transmitta['envio'] ?><br></th>       
        <th style="font-size: 12px;width: 10%"> Código</th> 
        <th style="font-size: 12px;width: 10%"> <?php echo $this->transmitta['propuestaid'] ?></th> 
        <th style="font-size: 12px;width: 10%"> Fecha</th> 
        <th style="font-size: 12px;width: 20%"> <?php echo $this->transmitta['fecha_envio'] ?> </th> 
    </tr>
</table>

<table class="table table-bordered">
    <tr style="background-color:#1C38B4;">
        <th style="font-size: 12px;width: 10%;text-align: center"> N°</th>       
        <th style="font-size: 12px;width: 10%;text-align: center"> Código</th> 
        <th style="font-size: 12px;width: 10%;text-align: center"> Rev.</th> 
        <th style="font-size: 12px;width: 40%;text-align: center"> Título o Descripción</th> 
        <th style="font-size: 12px;width: 20%;text-align: center"> Tipo</th> 
        <th style="font-size: 12px;width: 20%;text-align: center"> Cantidad</th> 
    </tr>
    <tr>
        <th style="font-size: 12px;width: 10%;text-align: center"> 1 </th>       
        <th style="font-size: 12px;width: 10%;text-align: center"> <?php echo $this->transmitta['propuestaid'] ?></th> 
        <th style="font-size: 12px;width: 10%;text-align: center"> <?php echo $this->transmitta['revision'] ?></th> 
        <th style="font-size: 12px;width: 40%;text-align: center"> <?php echo $this->transmitta['descripcion'] ?> </th> 
        <th style="font-size: 12px;width: 20%;text-align: center"> <?php echo $this->transmitta['tipo_envio'] ?></th> 
        <th style="font-size: 12px;width: 20%;text-align: center"> 1 </th> 
        <!-- <th style="border: 1px solid #000;font-size: 12px;width: 20%"> LISTA DE ASIGNATURAS - '.'</th>  -->
    </tr> 
    <tr> 
        <th colspan="6" style="width: 100%"> Observación:</th> 
    </tr>

    
</table>

<table class="table table-bordered" style="font-size: 12px">
    <tr> 
        <th style="width: 50%"> 
            <p>Tipo de Envío:</p>
            <p><span class="text-muted">A : </span><i class="fa fa-time"></i>Documento para Revisión y Aprobación</p>
            <p><span class="text-muted">B : </span><i class="fa fa-time"></i>Documento para Información</p>
            <p><span class="text-muted">C : </span><i class="fa fa-time"></i>Documento Final</p>
        </th> 
        <th style="width: 50%">
            <p>Tipo de Envío:</p>
            <p><span class="text-muted">AP : </span><i class="fa fa-time"></i>Aprobado</p>
            <p><span class="text-muted">AC : </span><i class="fa fa-time"></i>Aprobado con Comentarios</p>
            <p><span class="text-muted">NA : </span><i class="fa fa-time"></i>No Aprobado, Corregir y Emitir Nuevamente</p>
        </th> 
    </tr>
    <tr> 
        <th style="width: 50%"> 
            <p>Recibido por:</p>
            <p>Fecha</p>
            <p>Firma:</p>
        </th> 
        <th style="width: 50%"> 
            <p>De:</p>
            <p>Firma:</p>
        </th> 
    </tr>
</table>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
      <!--right slidebar-->
      <link href="css/slidebars.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />

   <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="js/respond.min.js" ></script>

  <!--right slidebar-->
  <script src="js/slidebars.min.js"></script>
    <!--common script for all pages-->
<script src="js/common-scripts.js"></script>

<?php 
    $html = ob_get_contents();
    $mpdf=new mPDF('win-1252','A4','','',15,15,30,12,5,7);
    $mpdf->SetHTMLHeader($header);
    $mpdf->SetFooter(' {DATE j/m/Y}|Página {PAGENO}|Sistema de Gestión e-UNDAC');
    ob_end_clean();
    $mpdf -> WriteHTML($html);
    $mpdf->Output('ASIGNATURAS -'.$this->perid.'.pdf','D');
?>    