
  <?php 
  if ($this->categoria=='ALL')
  {
    ?>
    <div style="   height: 25px;" class="row" >  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
  <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listarproyectos/fecha/<?php echo date("Y-m-d"); ?>" class="button block green noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/onebit.png"> <br>Proyectos</h1>
      <p style="margin-bottom: 0px;">Ingresar las actividades generales del proyecto con sus horas totales, fecha de inicio y fin.</p>
    </a>
  </div>
<div class="one ninths bounceInRight animated" style=" width: 60px;  height: 30px;"></div>
  <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listaractividadesproyecto/fecha/<?php echo date("Y-m-d"); ?>" class="button block blue noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/calendar.ico"> <br>Planificación</h1>
      <p style="margin-bottom: 0px;">Resumen de los proyectos programados de la semana actual con los responsables y su equipo.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated"></div>
</div>
<div style="   height: 25px;" class="row" >  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/resumen/fecha/<?php echo date("Y-m-d"); ?>"  class="button block red noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/traffic.png"> <br>Semáforo</h1>
      <p style="margin-bottom: 0px;">Muestra que personas del área ingresan sus horas reales.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated" style="
    width: 60px;
    height: 30px;"></div>

    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listareportes/fecha/<?php echo date("Y-m-d"); ?>"  class="button block asphalt noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/Chart_bar.png"> <br>Reportes</h1>
      <p style="margin-bottom: 0px;">Reporte de cargabilidad y rendimiento del personal del area.</p>   
      
      
    </a>
  </div>

<div class="one ninths bounceInRight animated"></div>
</div>
<?php
  } 



  if ($this->nivel == '1') 
  { ?>
<div style="   height: 25px;" class="row" >  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
  <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listarproyectosarea/fecha/<?php echo date("Y-m-d"); ?>" class="button block green noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/onebit.png"> <br>Proyectos</h1>
      <p style="margin-bottom: 0px;">Ingresar las actividades generales del proyecto con sus horas totales, fecha de inicio y fin.</p>
    </a>
  </div>
<div class="one ninths bounceInRight animated" style=" width: 60px;  height: 30px;"></div>
  <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listaractividadesproyecto/fecha/<?php echo date("Y-m-d"); ?>" class="button block blue noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/calendar.ico"> <br>Planificación</h1>
      <p style="margin-bottom: 0px;">Resumen de los proyectos programados de la semana actual con los responsables y su equipo.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated"></div>
</div>
<div style="   height: 25px;" class="row" >  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/resumen/fecha/<?php echo date("Y-m-d"); ?>"  class="button block red noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/traffic.png"> <br>Semáforo</h1>
      <p style="margin-bottom: 0px;">Muestra que personas del área ingresan sus horas reales.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated" style="
    width: 60px;
    height: 30px;"></div>

    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listareportes/fecha/<?php echo date("Y-m-d"); ?>"  class="button block asphalt noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/Chart_bar.png"> <br>Reportes</h1>
      <p style="margin-bottom: 0px;">Reporte de cargabilidad y rendimiento del personal del area.</p>   
      
      
    </a>
  </div>

<div class="one ninths bounceInRight animated"></div>
</div>

  <!--
    <div class="one sixth three-up-small-tablet two-up-mobile padded bounceInLeft animated">
      <div class="info callout">
        <h4 data-compression="7" data-max="20" class="responsive align-center zero">Planificacion</h4>
        <center>
          <a href="/proyectos/proyectos/listarproyectosarea/fecha/<?php echo date("Y-m-d"); ?>" title="proyectos">
          <img src="/images/reportes.png"></a>
        </center>
      </div>
    </div>
    <div class="one sixth three-up-small-tablet two-up-mobile padded bounceInLeft animated">
      <div class="info callout">
        <h4 data-compression="7" data-max="20" class="responsive align-center zero">Resumen</h4>
        <center>
          <a href="/proyectos/proyectos/listaractividadesproyecto/fecha/<?php echo date("Y-m-d"); ?>" title="actividad"><img src="/images/2.png"></a>
        </center>
      </div>
    </div>
    <div class="one sixth three-up-small-tablet two-up-mobile padded bounceInLeft animated">
      <div class="info callout">
        <h4 data-compression="7" data-max="20" class="responsive align-center zero">Semaforo</h4>
        <center>
          <a href="/proyectos/proyectos/resumen/fecha/<?php echo date("Y-m-d"); ?>" title="bien"><img src="/images/stock.png"></a>
        </center>
      </div>
    </div>
    <div class="one sixth three-up-small-tablet two-up-mobile padded bounceInLeft animated">
      <div class="info callout">
        <h4 data-compression="7" data-max="20" class="responsive align-center zero">Reportes</h4>
        <center>
          <a href="/proyectos/proyectos/listareportes/fecha/<?php echo date("Y-m-d"); ?>" title="bien"><img src="/images/stock.png"></a>
        </center>
      </div>
    </div>-->
  <?php } 
  
    if ($this->nivel == '2') 
    {
    ?>
    
<div style="   height: 25px;" class="row" >
  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
  <div class="three ninths bounceInRight animated">
    

  

    <a href="/proyectos/proyectos/listaractividadesproyecto/fecha/<?php echo date("Y-m-d"); ?>" class="button block blue noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/calendar.ico"> <br>Planificación</h1>
      <p style="margin-bottom: 0px;">Resumen de los proyectos programados de la semana actual con los responsables y su equipo.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated" style=" width: 60px;  height: 30px;"></div>
  <div class="three ninths bounceInRight animated">
     <a href="/proyectos/proyectos/llenarhorassemana/fecha/<?php echo date("Y-m-d"); ?>/responsable/<?php echo $this->dni?>"class="button block green noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/onebit.png"> <br>Ingreso de Horas</h1>
      
      <p style="margin-bottom: 0px;">Ingresar las horas reales a las actividades programadas en la semana.</p>
    </a>


  </div>

<div class="one ninths bounceInRight animated"></div>

</div>


<div style="   height: 25px;" class="row" >
  </div>

<div class="row" >

<div class="one ninths bounceInRight animated"></div>
    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/resumen/fecha/<?php echo date("Y-m-d"); ?>"  class="button block red noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/traffic.png"> <br>Semáforo</h1>
      <p style="margin-bottom: 0px;">Muestra que personas del área ingresan sus horas reales.</p>   
      
    </a>
  </div>
<div class="one ninths bounceInRight animated" style="
    width: 60px;
    height: 30px;"></div>

    <div class="three ninths bounceInRight animated">
    <a href="/proyectos/proyectos/listareportes/fecha/<?php echo date("Y-m-d"); ?>"  class="button block asphalt noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/Chart_bar.png"> <br>Reportes</h1>
      <p style="margin-bottom: 0px;">Reporte de cargabilidad y rendimiento del personal del area.</p>   
    </a>
  </div>
<div class="one ninths bounceInRight animated"></div>
</div>
    <?php  
    }
    
      if ($this->nivel == '3') 
    {
    ?>

   
<div style="   height: 25px;" class="row" >
  </div>
<div class="row" >
<div class="one ninths bounceInRight animated"></div>
  <div class="three ninths bounceInRight animated">
    

  

    <a href="/proyectos/proyectos/llenarhorassemana/fecha/<?php echo date("Y-m-d"); ?>/responsable/<?php echo $this->dni?>"class="button block green noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/onebit.png"> <br>Ingreso de Horas</h1>
      
      <p style="margin-bottom: 0px;">Ingresar las horas reales a las actividades programadas en la semana.</p>
    </a>
  </div>
<div class="one ninths bounceInRight animated" style=" width: 60px;  height: 30px;"></div>
  <div class="three ninths bounceInRight animated">
       <a href="/proyectos/proyectos/listareportepersona/fecha/<?php echo date("Y-m-d"); ?>/dni/<?php echo $this->dni; ?>"  class="button block asphalt noicon" style="height: 200px;">
      <br><h1 class="zero"><img src="/images/Chart_bar.png"> <br>Reportes</h1>
      <p style="margin-bottom: 0px;">Reporte de cargabilidad y rendimiento del personal del area.</p>   
      
      
    </a>
  </div>

<div class="one ninths bounceInRight animated"></div>

</div>




      
    <?php } 
   ?>


<div class="row">
  <div class="one half">

  </div>
<div class="one half">
  <div id="chart_div3"></div>
</div>
</div>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});
  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);
  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {
    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Antamina', 2],
      ['Corporacion Centro', 2],
      ['Panamerican', 4],
      ['Las Bambas', 1],
      ['La Arena', 6],
      ['Cerro Verde', 2],
      ['Activos Mineros', 1],
      ['Aporta', 1],
      ['Pluspetrol', 2],
      ['Anglo American', 1],
      ['Alaska', 1]
    ]);
    var options = {'title':'Proyectos por Clientes ',
      'width':500,
      'height':400};
    var options1 = {'title':'Proyectos por Encargado ',
      'width':500,
     'height':400};
    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
    // var chart = new google.visualization.PieChart(document.getElementById('chart_div1'));
    //chart.draw(data1, options);
}
</script>

<script type="text/javascript">
// Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});
// Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart1);
// Callback that creates and populates a data table,
// instantiates the pie chart, passes in the data and
// draws it.
  function drawChart1() {
  // Create the data table.
  var data3 = new google.visualization.DataTable();
   data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([

          ['Antamina', 2],
          ['Corporacion Centro', 2],
          ['Panamerican', 4],
          ['Las Bambas', 1],
          ['La Arena', 6],
          ['Cerro Verde', 2],
          ['Activos Mineros', 1],
          ['Aporta', 1],
          ['Pluspetrol', 2],
          ['Anglo American', 1],
          ['Alaska', 1]


        ]);

       /* var data1 = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([

          ['Renzo Ayala', 5],
          ['Jesus Negron', 4],
          ['Miguel Jimenez', 3],
          ['Gonzalo Nureña', 1],
          ['Luis Rivas', 6],
          ['Waldo Huallanca', 4]
          
        ]);*/


        // Set chart options
        var options = {'title':'Proyectos por Clientes ',
                       'width':500,
                       'height':400};

     var options1 = {'title':'Proyectos por Encargado ',
                       'width':500,
                       'height':400};
        // Instantiate and draw our chart, passing in some options.
        var chart1 = new google.visualization.PieChart(document.getElementById('chart_div3'));
        chart1.draw(data3, options1);
       // var chart = new google.visualization.PieChart(document.getElementById('chart_div1'));
        //chart.draw(data1, options);

      }
    </script>