<section class="panel">
    <header class="panel-heading">
      Lista de Propuestas
      <span class="pull-right">
            
            <a id="mostrar_enelaboracion" class=" btn btn-success btn-xs"> En Elaboración</a>
            <a id="mostrar_enviada" class=" btn btn-warning  btn-xs"> Enviada</a>
            <a id="mostrar_ganada" class=" btn btn-primary  btn-xs" style="background-color: #59ace2;color: #fff;"> Ganada</a>
            <a id="mostrar_perdida" class=" btn btn-danger  btn-xs"> Perdida</a>
            <a id="mostrar_declinada" class=" btn btn-default  btn-xs"> Declinada</a>
            <a id="mostrar_anulada" class=" btn   btn-xs" style="background-color: #8175c7;color: #fff;"> Anulada</a>
            

      </span>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
              <div class="input-group"><input id="buscar_propuesta" type="text" placeholder="Buscar Propuesta" class="input-sm form-control"> <span class="input-group-btn">
              <button id="btn_buscar_propuesta" type="button" class="btn btn-sm btn-success"> Buscar!</button> 
<a href="/propuesta/index/nuevo" class=" btn btn-primary btn-sm" style="background-color: #59ace2;color: #fff;"> Crear Propuesta</a>
<!--<a href="/propuesta/index/generartransmittal" class=" btn btn-primary btn-sm" > Crear Transmittal</a>-->

<a href="#" class=" btn btn-danger btn-sm " > Exportar</a>


              </span></div>
          </div>
      </div>
  </div>
  
  <div id="propuesta_enelaboracion" >
  <table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 3%;">Código</th>
          <th style="width: 3%;">Revisión</th>
          <th style="width: 20%;">Cliente</th>
          <th style="width: 30%;">Nombre</th>
          <th style="width: 20%;"><center>Parte Propuesta</center></th>
          <th style="width: 19%;">Status</th>
          <th style="width: 5%;">Acciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_enelaboracion as $lista) {
          //print_r($lista);
        ?>  

        <tr>
            <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>

            <td class="p-name">
                <?php 
                    $buscarparte = new Admin_Model_DbTable_Partepropuesta();
                    $listparte=$buscarparte->_getPartePropuestaxIndices($lista['propuestaid'],$lista['revision'],$lista['clienteid'],$lista['unidad_mineraid']);
                    foreach ($listparte as $listas) {
                      print_r($listas['nro_propuesta']);
                      echo"<br>";
                    }
                

                ?>  
            </td>

          
            <td>
                <?php
                if ($lista['estado_propuesta']=='EE') 
                    {
                        ?>
                        <span class="label label-success label-mini">En Elaboración</span><?php
                    }
                ?>
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>

               <a title="Generar Transmittal" href="/propuesta/index/generartransmittal/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/clienteid/<?php echo $lista['clienteid']?>/unidadid/<?php echo $lista['unidad_mineraid']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-asterisk"></i></a>
               

              
               <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>

  <div id="propuesta_ganada" style="display: none;">
  <table class="table table-hover p-table">
      <thead>
      <tr>  
           <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 35%;">Nombre</th>
          <th style="width: 20%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_ganada as $lista) {
          //print_r($lista);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
          
            <td>
                <?php
                if ($lista['estado_propuesta']=='G') 
                    {
                        ?>
                        <span class="label label-primary label-mini">Ganada</span><?php
                    }
                ?>
            
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/EE">En Elaboración</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
             
             <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>

   <div id="propuesta_perdida" style="display: none;">
  <table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 35%;">Nombre</th>
          <th style="width: 20%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_perdida as $lista) {
          //print_r($lista);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
            


              <td>
                <?php
                if ($lista['estado_propuesta']=='P') 
                    {
                        ?>
                        <span class="label label-danger label-mini">Perdida</span><?php
                    }
                ?>
            
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/EE">En Elaboración</a></li>
                  <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>


          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
               <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>


  <div id="propuesta_enviada" style="display: none;">
  <table class="table table-hover p-table">
      <thead>
      <tr>  
          <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 35%;">Nombre</th>
          <th style="width: 20%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_enviada as $lista) {
          //print_r($lista);
        ?>  

        <tr>
            <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
          
            <td>
                <?php
                if ($lista['estado_propuesta']=='E') 
                    {
                        ?>
                        <span class="label label-warning label-mini">Enviada</span><?php
                    }
                ?>
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                   <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/EE">En Elaboración</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>       
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
          
            <a title="Generar Revision" href="/propuesta/index/generarrevision/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/clienteid/<?php echo $lista['clienteid']?>/unidadid/<?php echo $lista['unidad_mineraid']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-asterisk"></i></a>
               


              <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>


   
   <div id="propuesta_declinada" style="display: none;">
  <table class="table table-hover p-table">
      <thead>
      <tr>  
         <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 35%;">Nombre</th>
          <th style="width: 20%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_declinada as $lista) {
          //print_r($lista);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
          
            <td>
                <?php
                if ($lista['estado_propuesta']=='D') 
                    {
                        ?>
                        <span class="label label-default label-mini">Declinada</span><?php
                    }
                ?>
            
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/EE">En Elaboración</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>                   
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/A">Anulada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
             <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>

<div id="propuesta_anulada" style="display: none;">
  <table class="table table-hover p-table">
      <thead>
      <tr>  
         <th style="width: 10%;">Codigo</th>
          <th style="width: 5%;">Revisión</th>
          <th style="width: 30%;">Cliente</th>
          <th style="width: 35%;">Nombre</th>
          <th style="width: 20%;">Status</th>
          <th style="width: 10%;">Operaciones</th>
      </tr>
      </thead>
      <tbody>

  <?php
        $c=1;
       foreach ($this->lista_anulada as $lista) {
          //print_r($lista);
        ?>  

      <tr>
           <td class="p-name">
            <a class="control-label">
                <?php echo $lista['propuestaid'];?>
                </a>
            </td>

            <td class="p-name">
                <center><?php echo $lista['revision'];?>  </center>
            </td>

            <td class="p-name">
                <?php
                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
            </td>
            <td class="p-name">
                <?php echo $lista['nombre_propuesta']; ?>  
            </td>
          
            <td>
                <?php
                if ($lista['estado_propuesta']=='A') 
                    {
                        ?>
                        <span class="label label-info label-mini">Anulada</span><?php
                    }
                ?>           
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/EE">En Elaboración</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G">Ganada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/P">Perdida</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/E">Enviada</a></li>
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/D">Declinada</a></li>             
                    <li><a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/S">Superada</a></li>
                </ul>
            </div>
            </td>
          <td>
              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
               <a title="Eliminar" onclick="return confirm('Esta Seguro que desea eliminar el registro?');" href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/ELI" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
          </td>
       

      </tr>

      <?php  }?>
     
      </tbody>
  </table>
  </div>
  <div id="resultado_busqueda">     
  </div>
</section>
<!-- page end-->


<script>
$(document).ready(function(){
    $("#mostrar_ganada").click(function(){
             
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").show();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();

    });
    $("#mostrar_enelaboracion").click(function(){
        $("#propuesta_enelaboracion").show();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });
    $("#mostrar_perdida").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").show();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_enviada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").show();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_declinada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").show();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").hide();
    });

    $("#mostrar_anulada").click(function(){
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").show();
        $("#resultado_busqueda").hide();
    });    


    $("#btn_buscar_propuesta").click(function(){
        var buscar_propuesta = $("#buscar_propuesta").val();
        
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").show();
        if (buscar_propuesta=='')  
        {
            alert("ingrese propuesta a buscar");
        }
        else
        { 
            var url="/propuesta/index/buscar/propuesta/"+buscar_propuesta;    
        }
        $("#resultado_busqueda").load(url);
    });    

});
</script>