
              <section class="panel">
                  <header class="panel-heading">
                      Lista de Propuestas
                      <span class="pull-right">
                        	<a href="/propuesta/index/nuevo" class=" btn btn-success btn-xs"> Crear Propuesta</a>
                      </span>
                  </header>
                  <div class="panel-body">
                      <div class="row">

                          <div class="col-md-12">
                              <div class="input-group"><input type="text" placeholder="Buscar Propuesta" class="input-sm form-control"> <span class="input-group-btn">
                              <button type="button" class="btn btn-sm btn-success"> Buscar!</button> </span></div>
                          </div>
                      </div>
                  </div>
                  <table class="table table-hover p-table">
                      <thead>
                      <tr>
                          <th>Nombre Propuesta</th>
                          <th>Status de la Propuesta</th>
                          <th>Operaciones</th>
                      </tr>
                      </thead>
                      <tbody>

                  <?php
                        $c=1;
                       foreach ($this->listapropuesta as $lista) {
                         // print_r($this->listapropuesta);
                        ?>  

                      <tr>
                          <td class="p-name">
                              <a href="project_details.html">
                              <?php
                                echo $lista['propuestaid'];

                                echo " Revisión: ";
                                echo $lista['revision'];

                          ?>  
                        </a>
                              <br>
                              <small><?php
                                echo $lista['nombre_propuesta'];
                          ?> </small>
                          </td>
                          
                          <td>
                              <span class="label label-primary">Activo</span>
                          </td>
                          <td>
                              <a href="/propuesta/index/ver/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>"
                               class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Ver </a>
                              <a href="/propuesta/index/ver" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Editar </a>
                              <a href="/propuesta/index/ver" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Eliminar </a>
                          </td>
                      </tr>

                      <?php  }?>
                     
                      </tbody>
                  </table>
              </section>
              <!-- page end-->
        
