<!-- page start-->

<div class="row">

    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Nueva Propuesta - Cliente
            </header>
           
            <div class="panel-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="cliente" class="col-lg-2 col-sm-2 control-label">Cliente</label>
                        <div class="col-lg-10">
                        <select id="clienteid" class="form-control input-sm m-bot15 col-lg-10">
                        
                            <option value="">Seleccione Cliente</option>
                                <?php 
                                    $bdcliente = new Admin_Model_DbTable_Cliente();
                                    $listcliente=$bdcliente->_getClienteAllOrdenado();
                                    foreach ($listcliente as $cli) {?>
                                    <option value="<?php echo $cli['clienteid']?>"><?php echo strtoupper($cli['nombre_comercial'])?></option>
                                <?php }?>
                        </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="unidad" class="col-lg-2 col-sm-2 control-label">Unidad Minera</label>
                        <div class="col-lg-10">
                        <select  id="uminera" name="unidadminera" class="form-control">
                        </select>



                        </div>
                    </div>

                    <div class="form-group">
                        <label for="propuestaid" class="col-lg-2 col-sm-2 control-label">Codigo</label>
                        <div class="col-lg-3">
                            <input class="form-control" id="propuestaid">
                         
                        </div>
                        <label for="revision" class="col-lg-2 col-sm-2 control-label">Revision</label>
                        <div class="col-lg-3">
                            <input class="form-control" id="revision">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nombre_propuesta" class="col-lg-2 col-sm-2 control-label">Nombre</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="nombrepropuesta" >
                        </div>
                    </div>

                </form>
            </div>
        </section>
    </div>
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Nueva Propuesta - Datos del Equipo
            </header>
           
            <div class="panel-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="responsable" class="col-lg-4 col-sm-4 control-label">Responsable</label>
                        <div class="col-lg-6">
                        <select id="responsable" class="form-control input-sm m-bot15 col-lg-10">


                            <option value="">Seleccione Responsble</option>
                                


                            <?php 
                                $bdpersona = new Admin_Model_DbTable_Persona();
                                $listresp_propuesta=$bdpersona->_getPropuestaxResponsablePropuesta('RESP-PROP');
                                foreach ($listresp_propuesta as $responsable) {?>
                                <option value="<?php echo $responsable['dni']?>"><?php echo strtoupper($responsable['alias'])?></option>
                                <?php }?>
                        </select>

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="revisor" class="col-lg-4 col-sm-4 control-label">Revisor Principal</label>
                        <div class="col-lg-6">
                        <select id='revisor' class="form-control input-sm m-bot15 col-lg-10">
                            

                            <option value="">Revisor Principal Propuesta</option>
                                


                            <?php 
                                $bdpersona = new Admin_Model_DbTable_Persona();
                                $listresp_propuesta=$bdpersona->_getPropuestaxResponsablePropuesta('RP-PROP');
                                foreach ($listresp_propuesta as $responsable) {?>
                                <option value="<?php echo $responsable['dni']?>"><?php echo strtoupper($responsable['alias'])?></option>
                                <?php }?>
                        </select>

                        </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="gerente" class="col-lg-4 col-sm-4 control-label">Gerente Proyecto</label>
                        <div class="col-lg-6">
                        <select id="gerente" class="form-control input-sm m-bot15 col-lg-10">
                           

                            <option value="">Gerente Proyecto</option>
                                


                            <?php 
                                $bdpersona = new Admin_Model_DbTable_Persona();
                                $listresp_propuesta=$bdpersona->_getPropuestaxResponsablePropuesta('GP-PROP');
                                foreach ($listresp_propuesta as $responsable) {?>
                                <option value="<?php echo $responsable['dni']?>"><?php echo strtoupper($responsable['alias'])?></option>
                                <?php }?>
                        </select>

                        </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="control_documnetario" class="col-lg-4 col-sm-4 control-label">Control Documentario</label>
                        <div class="col-lg-6">
                        <select id='control_documentario' class="form-control input-sm m-bot15 col-lg-10">
                           

                            <option value="">Seleccione Control Documentario</option>
                                


                            <?php 
                                $bdpersona = new Admin_Model_DbTable_Persona();
                                $listresp_propuesta=$bdpersona->_getPropuestaxResponsablePropuesta('CD-PROP');
                                foreach ($listresp_propuesta as $responsable) {?>
                                <option value="<?php echo $responsable['dni']?>"><?php echo strtoupper($responsable['alias'])?></option>
                                <?php }?>
                        </select>

                        </select>
                        </div>
                    </div>

                </form>
            </div>
        </section>
    </div>
</div>
<div class="row">
  <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Datos Propuesta 
            </header>
           
            <div class="panel-body">
                <form class="form-horizontal" role="form">

                    <div class="form-group">
                        <label for="estado_propuesta" class="col-lg-4 col-sm-4 control-label">Estado Propuesta</label>
                        <div class="col-lg-6">
                        <select id='estado_propuesta' class="form-control input-sm m-bot15 col-lg-10">
                            <option value="G">Ganada</option>
                            <option value="E">Enviada</option>
                            <option value="EE">En elaboración</option>
                            <option value="P">Perdida</option>
                            <option value="D">Declinada</option>
                            <option value="S">Standby</option>
                            <option value="A">Anulada</option>
                        </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tipo_propuesta" class="col-lg-4 col-sm-4 control-label">Tipo Propuesta</label>
                        <div class="col-lg-6">
                        <select id="tipo propuesta" class="form-control input-sm m-bot15 col-lg-10">
                            <option value="SA">Suma Alzada</option>
                            <option value="CU">Costos Unitarios</option>
                        </select>
                        </div>
                    </div>

                   

                    <div class="form-group">
                        <label for="tipo_servicio" class="col-lg-4 col-sm-4 control-label">Tipo de Servicio</label>
                        <div class="col-lg-6">
                        <select id="tipo_servicio" class="form-control input-sm m-bot15 col-lg-10">
                            <option value="AMB">Ambiental</option>
                            <option value="TDM">TDM</option>
                            <option value="ING">Ingeniería</option>
                            <option value="GEO">Geotecnia</option>
                            <option value="CON">Construcción</option>
                        </select>
                        </div>
                    </div>

          
                    
                    <div class="panel-body">
                                                    <button type="submit" class="btn btn-success" id="guardar_equipo">Guardar</button>
                        
                    </div>
                </form>
            </div>
        </section>
    </div>
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Fechas Propuesta
            </header>
            <div class="panel-body">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                           <label class="control-label col-md-3">Default Datepicker</label>
                                  <div class="col-md-3 col-xs-11">
                                      <input class="form-control form-control-inline input-medium default-date-picker"  size="16" type="text" value="" />
                                      <span class="help-block">Select date</span>
                                  </div>
                    </div>
                    <div class="form-group">
                        <label  class="col-lg-3 col-sm-3 control-label">Right Icon</label>
                        <div class="col-lg-9">
                            <div class="iconic-input right">
                                <i class="fa fa-book"></i>
                                <input type="text" class="form-control" placeholder="right icon">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label  class="col-lg-3 col-sm-3 control-label">Input with Loading</label>
                        <div class="col-lg-9">
                            <div class="iconic-input right">
                                <input type="text" class="form-control spinner" placeholder="Something Processing">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label col-lg-3">Button addons</label>
                        <div class="col-lg-9">
                            <div class="input-group m-bot15">
                                <span class="input-group-btn">
                                  <button type="button" class="btn btn-white"><i class="fa fa-search"></i></button>
                                </span>
                                <input type="text" class="form-control">
                            </div>

                        </div>
                    </div>

                </form>
            </div>
        </section>
    </div>
</div>

<!-- page end-->

<script type='text/javascript'>
  $("#clienteid").change(function(){
    var clienteid = $(this).val(); 
    url2="/propuesta/index/uminera/clienteid/"+clienteid;
    $("#uminera").load(url2);
    }); 
</script>
