 
              <!-- page start-->
              <section class="panel">
                  <header class="panel-heading">
                      Detalles Propuesta
                      
                  </header>

              </section>
              <div class="row">
                  <div class="col-md-8">
                      <section class="panel">
                          <div class="bio-graph-heading project-heading">
                              <strong> 

                              <?php 
                              echo "Propuesta:";
                              print_r($this->buscapropuesta[0]['propuestaid']);
                              echo" -" ; print_r($this->buscapropuesta[0]['revision']); 
                              echo "<br>";
                              ?> </strong>
                              <small><?php
                              $buscacliente = new Admin_Model_DbTable_Cliente();
                              $buscarunidadminera = new Admin_Model_DbTable_Unidadminera();

                              $ruc=$this->buscapropuesta[0]['clienteid'];
                              $buscanombre_cliente=$buscacliente->_getClientexIndice($ruc);
                              print_r($buscanombre_cliente[0]['nombre_comercial']);
                              

                              ?> </small>
                               <small><?php
                                echo "<br>";
                                print_r($this->buscapropuesta[0]['nombre_propuesta']);
                          ?> </small>

                          </div>
                          <div class="panel-body bio-graph-info">
                              <!--<h1>New Dashboard BS3 </h1>-->
                              <div class="row p-details">
                                  <div class="bio-row">
                                      <p><span class="bold">Responsable </span>: <?php print_r($this->buscapropuesta[0]['responsable_propuesta'])?> </p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Estado </span>: <span class="label label-primary">Activo</span></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Cliente</span>: <?php print_r($this->buscapropuesta[0]['clienteid'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Unidad Minera</span>:  <?php print_r($this->buscapropuesta[0]['unidad_mineraid'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Gerente</span>: <?php print_r($this->buscapropuesta[0]['gerente_proyecto'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Revision </span>:  <?php print_r($this->buscapropuesta[0]['revision'])?></p>
                                  </div>
         
                              </div>

                          </div>

                      </section>
                  </div>
                  <div class="col-md-4">
                      <section class="panel">
                          <header class="panel-heading">
                              Descripcion Propuesta
                          </header>

                          <div class="panel-body">
                              <a href="#"><img src="/img/cliente/<?php print_r($this->buscapropuesta[0]['clienteid'])?>.jpg" alt="20px"/></a>
                              <br>
                              <p>
                                  <?php print_r($this->buscapropuesta[0]['descripcion'])?>
                              </p>
                              <br/>
                             
                              <br/>
                              <h5 class="bold">Archivos Necesarios</h5>
                              <ul class="list-unstyled p-files">
                                  <li><a href=""><i class="fa fa-file-text"></i> Project-document.docx</a></li>
                                  <li><a href=""><i class="fa fa-picture-o"></i> Logo-company.jpg</a></li>
                                  <li><a href=""><i class="fa fa-mail-forward"></i> Email-from-flatbal.mln</a></li>
                                  <li><a href=""><i class="fa fa-file"></i> Contract-10_12_2014.docx</a></li>
                              </ul>
                              <br/>

                              <h5 class="bold">Tags</h5>
                              <ul class="p-tag-list">
                                  <li><a href=""><i class="fa fa-tag"></i> Lagunas Norte</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Pozo</a></li>
                                  
                              </ul>

                     
                          </div>

                      </section>
                  </div>
              </div>
              <!-- page end-->
 