<?php
//$this->pendiente;
//print_r($this->pendiente);
// $this->pendiente as $lista;
    ?>

<body ng-controller="GastosCtrl">

  <div class="panel">
    <section class="panel">
      <header class="panel-heading">
        Lista de Gastos
        <span class="pull-right">
          <button type="button" class="btn btn-success btn-xs" ng-click="vg.cargarGastos('B')">Pendientes</button>
          <button type="button" class="btn btn-primary btn-xs" ng-click="vg.cargarGastos('E')">Enviados</button>
          <button type="button" class="btn btn-warning btn-xs" ng-click="vg.cargarGastos('A')">Aprobados</button>
          <button type="button" class="btn btn-danger btn-xs" ng-click="vg.cargarGastos('R')">Rechazados</button>
          |
          <button type="button" class="btn btn-default btn-xs" ng-click="vg.AgregarGastoRendicion()">Rendir Gastos</button>
        </span>



      </header>
    </section>
<form method="POST" action="#" editable-form name="tableform" onaftersave="va.ModificarArea()" oncancel="cancel()" >

    <div class="panel-body">
      <table datatable="ng" class="table table-condensed table-hover p-table">
        <thead>
          <th style="width: 10%;">Numero</th>
          <th style="width: 30%;">Nombre</th>
          <th style="width: 15%;">Fecha</th>
          <th style="width: 15%;">Monto Total</th>
          <th style="width: 15%;">Estado</th>
          <th style="width: 15%;">Acciones</th>
        </thead>
        <tbody>
          <tr ng-repeat="gasto in vg.gastos track by $index">{{gasto.numero}}
            <td> {{gasto.numero_completo}} </td>
            <td> {{gasto.nombre}} </td>
            <td> {{gasto.fecha | date: 'dd-MM-yyyy'}} </td>
            <td> {{gasto.monto_total}} </td>
            <td> <span class="label label-default label-min">{{gasto.estado}}</span>
             <!-- <select ng-model="gasto.estado"
             ng-options="gasto.value as gasto.text for gasto in vg.estadogasto" ng-change="vg.cambiarEstadoGasto($index,gasto.estado)" >
             {{ vg.showEstadoGasto(gasto) }}
           </select> -->
         </td>
         <td>
          <ul>
            <li>
            <!--   <button type="button" class="btn btn-success btn-xs" ng-click="vg.verModulos()">
                Rendir Gastos
              </button> -->
              <button type="button" class="btn btn-info btn-xs" ng-click="gasto.verInformacion()">
                Rendir
              </button>
              <button type="button" class="btn btn-default btn-xs" ng-click="gasto.Imprimir()">
                Imprimir
              </button>
                <!-- <a href="#/detalles" class="btn btn-warning btn-xs showdetails" title="Detalles" ><i class="fa fa-folder"></i></a> -->
                <a data-toggle="modal" href="#myModalDetail" class="btn btn-warning btn-xs editdetails" title="Detalles" numero="gasto.numero"><i class="fa fa-folder"></i></a>
                <!-- <a data-toggle="modal" href="#myModalDetail" class="btn btn-info btn-xs editdetails" title="Editar"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-edit"></i></a> -->
                <a href="/rendiciongastos/index/imprimirrendicion/uid/<?php echo $lista['uid']?>/dni/<?php echo $lista['dni']?>/numero/<?php echo $lista['numero']?>" class="btn btn-default btn-xs" title="Imprimir"><i class="fa fa-print"></i></a>
                <a class="btn btn-danger btn-xs" title="Eliminar"><i class="fa fa-archive"></i></a> 
              <center>
                <!-- <a href="#/rendirgastos" class="btn btn-info btn-xs editdetails" title="Rendir Gastos"><i class="fa fa-edit" ng-click="gasto.verInformacion()"></i></a>
                <!-- $uid = $this->sesion->uid; -->
                <!-- $dni = $this->sesion->dni; -->


              </center>
            </li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</div>

</form>
        <!--
        <div class="panel">
            <button type="button" class="btn btn-default">Editar</button>
            <button type="button" class="btn btn-default">Exportar</button>
            <button type="button" class="btn btn-default">Imprimir</button>
        </div>
      -->
    </div>
  </body>


    <div class="modal fade" id="myModalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content" style="width: 1350px; top: 100%; margin-left: -230px;">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Detalles</h4>
                </div>
                <div class="modal-body">
                    <div id="load_detalless"></div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(".showdetails").click(function(){
            var numero = $(this).attr('numero');
            var uid = $(this).attr('uid');
            var dni = $(this).attr('dni');
            var url = "/expense/index/detalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
            $("#load_detalless").load(url);
        });

        $(".editdetails").click(function(){
            var numero = $(this).attr('numero');
            var uid = $(this).attr('uid');
            var dni = $(this).attr('dni');
            var url = "/rendiciongastos/editardetalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
            $("#load_detalless").load(url);
        });

    </script>

