<div ng-app="moduloRg">
	<div ng-view>

	</div>
</div>

<!-- JavaScript a utilizar -->
    <script type="text/javascript" src="/js/angular-route.js"></script>
    <script type="text/javascript" src="/js/Chart.js"></script>
    <script type="text/javascript" src="/js/angular-chart.js"></script>
    <script type="text/javascript" src="/js/checklist-model.js"></script>
    <script type="text/javascript" src="/js/xeditable.js"></script>
    <script type="text/javascript" src="/js/angular-mock.js"></script>
    <script type="text/javascript" src="/js/angular-file-upload.min.js"></script>

    <script src="http://m-e-conroy.github.io/angular-dialog-service/javascripts/dialogs.min.js" type="text/javascript"></script>

<!-- Estilos a utilizar -->
    <!-- <link rel="stylesheet" type="text/css" href="/css/style-controlproyecto.css"> -->
    <link rel="stylesheet" type="text/css" href="/css/xeditable.css">

<!-- Rutas de JavaScript Controllers de rutas-->
	<script type="text/javascript" src="/js/RendicionGastos/rendiciongastos.js"></script>

<!-- Rutas de JavaScript Controllers -->
	<script type="text/javascript" src="/js/RendicionGastos/controllers/GastosCtrl.js"></script>
    <script type="text/javascript" src="/js/RendicionGastos/controllers/ModalRendicionCtrl.js"></script>

<!-- Rutas de JavaScript Services -->
	<script type="text/javascript" src="/js/RendicionGastos/services/httpFactory.js"></script>

	<script type="text/javascript" src="/js/RendicionGastos/services/gastosFactory.js"></script>

