 <!-- INICIO DE LA TABLA DE PRUEBA CLIENTE EN ANGULAR-->
 <div class="panel">
 <!-- <div class="panel"> -->
   <section class="panel">

     <header class="bio-graph-heading project-heading">
      <strong>
        <p>Nombre de Rendicion : {{vrg.rendir.nombre}}</p>
      </strong>
    </header>
    <div class="panel-body bio-graph-info">
      <div class="bio-row">
        <span class="bold">N° de Rendicion :</span>
        {{vrg.rendir.numero_completo}}
      </div>
      <div class="bio-row">
        <span class="bold">Monto Total :</span>
        {{vrg.rendir.monto_total}}
      </div>
      <div class="bio-row">
        <span class="bold">Fecha de Rendicion :</span>
        {{vrg.rendir.fecha}}
      </div>
      <div class="bio-row">
        <span class="bold"> Estado :</span>
        {{vrg.rendir.estado}}
      </div>
    </div>


  <div class="pane-heading">
    <div class=" panel btn-edit">
      <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show(); vrg.CancelarRendir()">
        Editar Gastos
      </button>
      <button class="btn btn-primary" ng-click="vrg.ShowFormRendir()" ng-hide="vrg.ShowFormRendir; vrg.formVisibilityRendir" ng-show="!tableform.$visible">Agregar Gasto</button>
    </div>
  </div>
    <!-- inicio del formulario para ingresar datos -->
    <div class="form-group ">
      <div ng-show="vrg.formVisibilityRendir"  >
        <form name='validinput'>
          <div class="input-group">
            <div class="panel">
              <div class="panel-heading">
              <!-- <div class="col-xs-3" >
                  <span class="input-group-addon">Cliente</span>
                  <input type="text" class="form-control input-sm" placeholder='clienteid' name='clienteid' data-ng-model="vrg.clienteid"  required data-ng-class='{error: validinput.clienteid.$invalid && !validinput.$pristine}'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Proyecto</span>
                  <input type="text" class="form-control input-sm" placeholder='proyectoid' name='proyectoid' data-ng-model="vrg.proyectoid"  required data-ng-class='{error: validinput.proyectoid.$invalid && !validinput.$pristine}'>
                </div> -->
                <div class="col-xs-3" >
                  <span class="input-group-addon">Descripcion</span>
                  <input type="text" class="form-control input-sm" placeholder='descripcion' name='descripcion' data-ng-model="vrg.descripcion" >
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Gastos</span>
                  <input type="text" class="form-control input-sm" placeholder='gastoid' name='gastoid' data-ng-model="vrg.gastoid" >
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Cliente</span>
                  <input type="text" class="form-control input-sm" placeholder='bill_cliente' name='bill_cliente' data-ng-model="vrg.bill_cliente" >
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Reembolso</span>
                  <input type="text" class="form-control input-sm" placeholder='reembolsable' name='reembolsable' data-ng-model="vrg.reembolsable"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Fecha de Factura</span>
                  <input type="text" class="form-control input-sm" placeholder='yyyy-mm-dd' name='fecha_factura' data-ng-model="vrg.fecha_factura"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Moneda</span>
                  <input type="text" class="form-control input-sm" placeholder='moneda' name='moneda' data-ng-model="vrg.moneda"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">N° Documento</span>
                  <input type="text" class="form-control input-sm" placeholder='num_factura' name='num_factura' data-ng-model="vrg.num_factura"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Proveedor</span>
                  <input type="text" class="form-control input-sm" placeholder='proveedor' name='proveedor' data-ng-model="vrg.proveedor"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Neto</span>
                  <input type="text" class="form-control input-sm" placeholder='monto_igv' name='monto_igv' data-ng-model="vrg.monto_igv"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Otros Impuestos</span>
                  <input type="text" class="form-control input-sm" placeholder='otro_impuesto' name='otro_impuesto' data-ng-model="vrg.otro_impuesto"/>
                </div>
              </div>
            </div>
          </div>


          <div class="panel-heading col-md-6">
            <div class="btn-group">
              <button class="btn btn-warning" ng-click="vrg.GuardarGastos()" data-ng-disabled='!validinput.$valid'>Guardar</button>
              <button class="btn btn-danger" ng-click="vrg.CancelarRendir()">Cancelar</button>
            </div>
          </div>

        </form>
      </div>
    </div>
    <!-- fin del formulario para ingresar datos -->


  </section>


  <!-- inicio del formulario para modificar datos -->
  <div class="panel-heading">
    <form method="POST" action="#" editable-form name="tableform" onaftersave="vrg.ModificarGastoPersona()" oncancel="cancel()" >

      <section class="panel-heading">
        <div class="btn-form" ng-show="tableform.$visible">
          <div class="btn-group">
            <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
            <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
          </div>
        </div>



      </section>

      <font size=1>
        <table datatable="ng" class="table table-condensed table-hover p-table dataTables_wrappe table-striped">
          <div>
            <thead>
              <!-- <th style="width: 10%;">Cliente</th>
              <th style="width: 10%;">Proyecto</th> -->
              <th style="width: 10%;">Descripcion</th>
              <th style="width: 5%;">Gastos</th>
              <th style="width: 5%;">Cliente</th>
              <th style="width: 5%;">Reembolso</th>
              <th style="width: 5%;">Fecha Factura</th>
              <th style="width: 5%;">N° Factura</th>
              <th style="width: 5%;">Moneda</th>
              <th style="width: 5%;">Proveedor</th>
              <th style="width: 5%;">Neto</th>
              <th style="width: 5%;">Otros Impuestos</th>
              <th style="width: 5%;">IGV</th>
              <th style="width: 5%;">Monto Total</th>
            </thead>

            <tr ng-repeat="rendiciones in vrg.rendir track by $index">
              <!-- <td>
                <span editable-text="rendiciones.clienteid" e-from="tableform" e-required>
                 {{rendiciones.clienteid}}
               </span>
             </td>
             <td>
              <span editable-text="rendiciones.proyectoid" e-from="tableform" e-required >
                {{rendiciones.proyectoid}}
              </span>
            </td> -->
            <td>
              <span editable-text="rendiciones.descripcion" e-from="tableform">
                {{rendiciones.descripcion}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.gastoid" e-from="tableform" >
                {{rendiciones.gastoid}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.bill_cliente" e-from="tableform">
                {{rendiciones.bill_cliente}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.reembolsable" e-from="tableform">
                {{rendiciones.reembolsable}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.fecha_factura" e-from="tableform">
                {{rendiciones.fecha_factura}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.num_factura" e-from="tableform">
                {{rendiciones.num_factura}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.moneda" e-from="tableform">
                {{rendiciones.moneda}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.proveedor" e-from="tableform">
                {{rendiciones.proveedor}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.monto_igv" e-from="tableform">
                {{rendiciones.monto_igv}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.otro_impuesto" e-from="tableform">
                {{rendiciones.otro_impuesto}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.igv" e-from="tableform">
                {{rendiciones.igv}}
              </span>
            </td>
            <td>
              <span text="rendiciones.monto_total" e-from="tableform">
                {{rendiciones.monto_total}}
              </span>
            </td>
          </tr>

        </table>
      </font>

      <section class="panel-heading">
<!-- <div class="btn-form" ng-show="tableform.$visible">
    <button type="button" ng-disabled="tableform.$waiting" ng-click="vrg.agregarArea()" class="btn btn-primary ">Agregar Area</button>
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
  </div> -->
</section>

</form>
</div>

<section class="panel-heading">
  <div class="btn-edit">
    <!-- <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
      </button> -->
    </div>
  </section>
  <!-- fin del formulario para modificar datos -->
</div>