 <!-- INICIO DE LA TABLA DE PRUEBA CLIENTE EN ANGULAR-->
 <div class="panel">
 <!-- <div class="panel"> -->
   <section class="panel">

     <header class="bio-graph-heading project-heading">
      <strong>
        <p>Nombre de Rendicion: {{vr.gastos.nombre}}</p>
      </strong>
    </header>
    <div class="panel-body bio-graph-info">
      <div class="bio-row">
        <span class="bold">N° de Rendicion:</span>
        {{vr.gastos.numero_completo}}
      </div>
      <div class="bio-row">
        <span class="bold">Monto Total:</span>
        {{vr.gastos.monto_total}}
      </div>
      <div class="bio-row">
        <span class="bold">Fecha de Rendicion:</span>
        {{vr.gastos.fecha}}
      </div>
      <div class="bio-row">
        <span class="bold"> Estado:</span>
        {{vr.gastos.estado}}
      </div>
    </div>


  <div class="pane-heading">
    <div class=" panel btn-edit">
      <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show(); vc.CancelarCliente()">
        Editar Gastos
      </button>
      <button class="btn btn-primary" ng-click="vc.ShowFormCliente()" ng-hide="vc.formVisibilityCliente; vc.tableVisibilityCliente" ng-show="!tableform.$visible">Agregar Gasto</button>
    </div>
  </div>
    <!-- inicio del formulario para ingresar datos -->
    <div class="form-group ">
      <div ng-show="vc.formVisibilityCliente"  >
        <form name='validinput'>
          <div class="input-group">
            <div class="panel">
              <div class="panel-heading">
              <div class="col-xs-3" >
                  <span class="input-group-addon">Cliente</span>
                  <input type="text" class="form-control input-sm" placeholder='clienteid' name='clienteid' data-ng-model="vc.clienteid"  required data-ng-class='{error: validinput.clienteid.$invalid && !validinput.$pristine}'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Proyecto</span>
                  <input type="text" class="form-control input-sm" placeholder='clienteid' name='clienteid' data-ng-model="vc.clienteid"  required data-ng-class='{error: validinput.clienteid.$invalid && !validinput.$pristine}'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Descripcion</span>
                  <input type="text" class="form-control input-sm" placeholder='clienteid' name='clienteid' data-ng-model="vc.clienteid"  required data-ng-class='{error: validinput.clienteid.$invalid && !validinput.$pristine}'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Gastos</span>
                  <input type="text" class="form-control input-sm" placeholder='nombre_comercial' name='nombre_comercial' data-ng-model="vc.nombre_comercial"  required data-ng-class='{ error: validinput.nombre_comercial.$invalid && !validinput.$pristine }'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Cliente</span>
                  <input type="text" class="form-control input-sm" placeholder='nombre' name='nombre' data-ng-model="vc.nombre"  required data-ng-class='{ error: validinput.nombre.$invalid && !validinput.$pristine }'>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Reembolso</span>
                  <input type="text" class="form-control input-sm" placeholder='codigoid' name='codigoid' data-ng-model="vc.codigoid"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Fecha de Factura</span>
                  <input type="text" class="form-control input-sm" placeholder='yyyy-mm-dd' name='fecha_registro' data-ng-model="vc.fecha_registro"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Moneda</span>
                  <input type="text" class="form-control input-sm" placeholder='web' name='web' data-ng-model="vc.web"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">N° Documento</span>
                  <input type="text" class="form-control input-sm" placeholder='direccion' name='direccion' data-ng-model="vc.direccion"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Proveedor</span>
                  <input type="text" class="form-control input-sm" placeholder='paisid' name='paisid' data-ng-model="vc.paisid"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Neto</span>
                  <input type="text" class="form-control input-sm" placeholder='departamentoid' name='departamentoid' data-ng-model="vc.departamentoid"/>
                </div>
                <div class="col-xs-3" >
                  <span class="input-group-addon">Otros Impuestos</span>
                  <input type="text" class="form-control input-sm" placeholder='provinciaid' name='provinciaid' data-ng-model="vc.provinciaid"/>
                </div>
              </div>
            </div>
          </div>


          <div class="panel-heading col-md-6">
            <div class="btn-group">
              <button class="btn btn-warning" ng-click="vc.GuardarCliente()" data-ng-disabled='!validinput.$valid'>Guardar</button>
              <button class="btn btn-danger" ng-click="vc.CancelarCliente()">Cancelar</button>
            </div>
          </div>

        </form>
      </div>
    </div>
    <!-- fin del formulario para ingresar datos -->


  </section>


  <!-- inicio del formulario para modificar datos -->
  <div class="panel-heading">
    <form method="POST" action="#" editable-form name="tableform" onaftersave="vc.ModificarCliente()" oncancel="cancel()" >

      <section class="panel-heading">
        <div class="btn-form" ng-show="tableform.$visible">
          <div class="btn-group">
            <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
            <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
          </div>
        </div>



      </section>

      <font size=1>
        <table datatable="ng" class="table table-condensed table-hover p-table dataTables_wrappe table-striped">
          <div>
            <thead>
              <th style="width: 10%;">Cliente</th>
              <th style="width: 10%;">Proyecto</th>
              <th style="width: 10%;">Descripcion</th>
              <th style="width: 5%;">Gastos</th>
              <th style="width: 5%;">Cliente</th>
              <th style="width: 5%;">Reembolso</th>
              <th style="width: 5%;">Fecha Factura</th>
              <th style="width: 5%;">Moneda</th>
              <th style="width: 5%;">N° Documento</th>
              <th style="width: 5%;">Proveedor</th>
              <th style="width: 5%;">Neto</th>
              <th style="width: 5%;">Otros Impuestos</th>
            </thead>


            <tr ng-repeat="clientes in vc.cliente">
              <td>
                <span editable-text="clientes.clienteid" e-from="tableform" e-required>
                 {{clientes.clienteid}}
               </span>
             </td>
             <td>
              <span editable-text="clientes.nombre_comercial" e-from="tableform" e-required >
                {{clientes.nombre_comercial}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.nombre" e-from="tableform">
                {{clientes.nombre}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.codigoid" e-from="tableform" >
                {{clientes.codigoid}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.fecha_registro" e-from="tableform">
                {{clientes.fecha_registro}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.web" e-from="tableform">
                {{clientes.web}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.direccion" e-from="tableform">
                {{clientes.direccion}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.paisid" e-from="tableform">
                {{clientes.paisid}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.departamentoid" e-from="tableform">
                {{clientes.departamentoid}}
              </span>
            </td>
            <td>
              <span editable-text="clientes.provinciaid" e-from="tableform">
                {{clientes.provinciaid}}
              </span>
            </td>
          </tr>

        </table>
      </font>

      <section class="panel-heading">
<!-- <div class="btn-form" ng-show="tableform.$visible">
    <button type="button" ng-disabled="tableform.$waiting" ng-click="vc.agregarArea()" class="btn btn-primary ">Agregar Area</button>
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
  </div> -->
</section>

</form>
</div>

<section class="panel-heading">
  <div class="btn-edit">
    <!-- <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
      </button> -->
    </div>
  </section>
  <!-- fin del formulario para modificar datos -->
</div>