<head>
  <script>
    $("#datepicker1").datepicker
    ({
      showWeek: true,
        //firstDay: 1,
        maxDate:0, dateFormat:'dd/mm/yy', yearRange: '-100:+0',firstDay: 1,
        //minDate: new Date(2015, 4, noSunday()),
        minDate: new Date(2015,5,1),
      });
</script>

</head>

<!-- INICIO DE LA TABLA DE PRUEBA CLIENTE EN ANGULAR-->
<div class="panel">
 <!-- <div class="panel"> -->
 <section class="panel">

   <header class="bio-graph-heading project-heading">
    <strong>
      <p>Nombre de Rendicion : {{vrg.rendir.nombre}}</p>
    </strong>
  </header>
  <div class="panel-body bio-graph-info">
    <div class="bio-row">
      <span class="bold">N° de Rendicion :</span>
      {{vrg.rendir.numero_completo}}
    </div>
    <div class="bio-row">
      <span class="bold">Monto Total :</span>
      {{vrg.rendir.monto_total}}
    </div>
    <div class="bio-row">
      <span class="bold">Fecha de Rendicion :</span>
      {{vrg.rendir.fecha | date: 'dd-MM-yyyy'}}
    </div>
    <div class="bio-row">
      <span class="bold"> Estado :</span>
      {{vrg.rendir.estado}}
    </div>
  </div>

  <div class="pane-heading">
    <div class=" panel btn-edit">
      <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show(); vrg.CancelarRendir()"><i class="glyphicon glyphicon-pencil"> Editar</i></button>
      <button class="btn btn-primary" ng-click="vrg.GuardarGastos()" > <i class="glyphicon glyphicon-check"> Agregar</i></button>
    </div>
  </div>
  <span class="pull-right">
    <!-- <a href="/rendiciongastos#/" class=" btn btn-primary btn-sm" > Volver </a> -->
  </span>
  <!-- inicio del formulario para ingresar datos -->
  
  <!-- fin del formulario para ingresar datos -->


</section>


<!-- inicio del formulario para modificar datos -->
<div class="panel-heading">
  <form method="POST" action="#" editable-form name="tableform" onaftersave="vrg.ModificarGastoPersona()" oncancel="cancel()" >

    <section class="panel-heading">
      <div class="btn-form" ng-show="tableform.$visible">
        <div class="btn-group">
          <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success" onbeforesave="vrg.Actualizar($data)" ><i class="glyphicon glyphicon-floppy-saved"> Guardar</i></button>
          <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger"><i class="glyphicon glyphicon-floppy-remove"> Cancelar</i></button>
        </div>
      </div>



    </section>

    <font size=1>
      <table class="table table-responsive table-condensed table-hover p-table dataTables_wrappe table-striped ">
        <div>
          <tr style="font-weight: bold">
            <td style="width: 1%">Id</td>
            <!-- <th style="width: 10%;">Cliente</th> -->
            <td >Proyecto</td>
            <td >Descripcion</td>
            <td >Gastos</td>
            <td >Cliente</td>
            <td >Reembolso</td>
            <td >Fecha Factura</td>
            <td >N° Factura</td>
            <td >Moneda</td>
            <td >Proveedor</td>
            <td >Neto</td>
            <td >Otros Impuestos</td>
            <td >IGV</td>
            <td >Monto Total</td>
            <td style="width: 1%"><span ng-show="tableform.$visible">Accion</span></td>
          </tr>

          <tr ng-repeat="rendiciones in vrg.rendir track by $index">
            <td>
              <span text="rendiciones.clienteid" e-from="tableform" e-required style="font-weight: bold">
               {{$index + 1}}
             </span>
           </td>
           <!--   <td>
                <span editable-select="rendiciones.clienteid" e-from="tableform" >
                 {{rendiciones.clienteid}}
               </span>
             </td> -->
             <td>
              <!-- <span editable-select="rendiciones.proyectoid" e-from="tableform" e-ng-options="tipo.listaproyectos as tipo.nombre_proyecto for tipo in vrg.listaproyectos"> -->
              <span editable-text="rendiciones.proyectoid" e-from="tableform" >
                {{rendiciones.proyectoid}}
              </span>
            </td>
            <td>
              <span editable-textarea="rendiciones.descripcion" e-from="tableform">
                {{rendiciones.descripcion}}
              </span>
            </td>
            <td>
              <span editable-select="rendiciones.gastoid" e-from="tableform" e-ng-options="tipo.listagastos as tipo.nombre_gasto for tipo in vrg.listagastos" >
                <option>{{rendiciones.gastoid}}</option>
              </span>
            </td>
            <td>
              <span ng-if="rendiciones.bill_cliente" = 'true' ng-else="No" = 'false' editable-checkbox="rendiciones.bill_cliente" e-from="tableform" ng-value="true">
                Si
              </span>
            </td>
            <td>
              <span ng-true-value="'YES'" ng-false-value="'NO'" editable-checkbox="rendiciones.reembolsable" e-from="tableform" ng-value="true">
                Si
              </span>
            </td>
            <td>
           <!--    <span editable-text="rendiciones.fecha_factura" e-from="tableform" e-datepicker-popup="yyyy-MM-dd">
                {{rendiciones.fecha_factura | date: 'dd-MM-yyyy'}}
              </span> -->

              <input class="form-control" id="datepicker1" ng-show="tableform.$visible"  type="datepicker" e-form="tableform" ui-date="{ dateFormat: 'dd-mm-yy' }" ename="fecha_factura" ng-model='rendiciones.fecha_factura'/>
              <span ng-show="!tableform.$visible" ename="fecha_factura" >
                {{ rendiciones.fecha_factura | date:"dd-MM-yyyy" }}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.num_factura" e-from="tableform">
                {{rendiciones.num_factura}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.moneda" e-from="tableform">
                {{rendiciones.moneda}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.proveedor" e-from="tableform">
                {{rendiciones.proveedor}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.monto_igv" e-from="tableform">
                {{rendiciones.monto_igv}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.otro_impuesto" e-from="tableform">
                {{rendiciones.otro_impuesto}}
              </span>
            </td>
            <td>
              <span editable-text="rendiciones.igv" e-from="tableform">
                {{rendiciones.igv}}
              </span>
            </td>
            <td>
              <span text="rendiciones.monto_total" e-from="tableform">
                {{rendiciones.monto_total}}
                <!-- {{rendiciones.monto_igv+rendiciones.otro_impuesto}} -->
              </span>
            </td>
            <td><button type="button" ng-show="tableform.$visible" ng-click="vrg.deleteGasto($index,lista)" class="btn btn-danger pull-right" title="Eliminar"><i class="glyphicon glyphicon-trash"></button></td>
          </tr>

        </table>
      </font>
</form>
</div>
  <!-- fin del formulario para modificar datos -->
</div>