 ¿Cuánto? <p type="text" ng-model="CP.cuanto" size="4" ></p>
 	<input type="button" value="7" ng-click="alu.sumar()"/>
    <input type="button" value="15" ng-click="alu.restar()"/>


<table class=" table table-striped table-hover table-bordered " >
  <tr>
  	<td><b>Fecha Inicio</b></td><td><p type="text" ng-model="CP.cuanto" size="4" ></p></td>
  	<td><b>Fecha Final</b></td><td><p type="text" ng-model="CP.cuanto" size="4" ></p></td>
  </tr>
  <tr >
    <td ng-repeat="tiempo in CP.labels">{{tiempo}}</td>  
  </tr>
  <tr >
    <td ng-repeat="tiempo in CP.data" ng-init="paso = $index">
    	<input type="text" ng-model="CP.planificado" size="4" />{{ tiempo }}
    </td>  
  </tr>
  <tr >
    <td ng-repeat="tiempo in CP.labels">
    	<input type="text" ng-model="CP.ejecutado" size="4" />
    </td>  
  </tr>
</table>


<div  ng-init="pensamientos = [];">
        <p>
            ¿Qué hay de nuevo?
            <br />
            <input type="text" ng-model="nuevoPensamiento" /> 
            <input type="button" value="Agregar" ng-click="pensamientos.push(nuevoPensamiento); nuevoPensamiento = '';" />
        </p>
        <h5>Curva de acuerdo  a un proyecto</h5>
      <table>
		  <tr>
		  <td
	         ng-repeat="pensamiento in pensamientos" ng-init="paso = $index">
		        <span>
	                Dia: {{pensamiento}} (í {{paso}})
		        </span>
	        
		  </td>
		  </tr>
	  </table>
</div>

<canvas id="line" class="chart chart-line" data="CP.data"
  labels="CP.labels" legend="true" series="CP.series"
  click="CP.onClick">
</canvas> 

<canvas id="bar" class="chart chart-bar" data="CP.data"
  labels="CP.labels"></canvas> 



	<head>
	
		<style>
			canvas{
			}
		</style>
	</head>
	<body>
		<canvas id="canvas" height="450" width="450"></canvas>


	<script>

	// 	var pieData = [
	// 			{
	// 				value: 30,
	// 				color:"#F38630"
	// 			},
	// 			{
	// 				value : 50,
	// 				color : "#E0E4CC"
	// 			},
	// 			{
	// 				value : 100,
	// 				color : "#69D2E7"
	// 			}
			
	// 		];

	// var myPie = new Chart(document.getElementById("canvas").getContext("2d")).Pie(pieData);
	
	</script>
	</body>

