
	<div class="col-md-6">
		<div class="panel">
			<h1 class="panel-heading">Carga Laboral Control Proyecto (En Proceso)</h1>
			<div class="panel-body">
				<canvas id="bar" class="chart chart-bar"  labels="CP.labels"
					series="CP.series" options="CP.options"></canvas>
			</div>
		</div>
	</div>

<div ng-repeat="label in CP.labels ">
    <div class="nombre">{{label}}</div>                
</div>