    <div ng-app="moduloCp">
        <div ng-view>

        </div>
    </div>

            <script type="text/javascript" src="/js/angular-route.js"></script>
            <script type="text/javascript" src="/js/Chart.js"></script>
            <script type="text/javascript" src="/js/angular-chart.js"></script>
            <script type="text/javascript" src="/js/modulo-controlproyecto.js"></script>
     
            <script type="text/javascript" src="/js/checklist-model.js"></script>
            <script type="text/javascript" src="/js/xeditable.js"></script>
            <link rel="stylesheet" type="text/css" href="/css/style-controlproyecto.css">
            <link rel="stylesheet" type="text/css" href="/css/xeditable.css">
        
            <script src="http://m-e-conroy.github.io/angular-dialog-service/javascripts/dialogs.min.js" type="text/javascript"></script>