<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Editable Table</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="assets/data-tables/DT_bootstrap.css" />

      <!--right slidebar-->
    <link href="css/slidebars.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />


  </head>

              <section class="panel">
                  <header class="panel-heading">
                      Lista de Entregables
                  </header>
                  <div class="panel-body" style="overflow: scroll" width="1000px">
                      <div class="adv-table editable-table ">
                          <div class="clearfix">
                              <div class="btn-group">
                                  <button id="editable-sample_new" class="btn green">
                                      Agregar <i class="fa fa-plus"></i>
                                  </button>
                              </div>
                              <div class="btn-group pull-right">  
                                  <?php 
                                  $theVariable = array('A' => 'A','B' => 'B','C' => 'C','D' => 'D','E' => 'E','F' => 'F','G' => 'G','H' => 'H',
                                                       'I' => 'I','J' => 'J','K' => 'K','L' => 'L','M' => 'M','N' => 'N','O' => 'O','P' => 'P',
                                                       'Q' => 'Q','R' => 'R','S' => 'S','U' => 'U','V' => 'V','W' => 'W','X' => 'X','Y' => 'Y',
                                                       'Z' => 'Z','todos' => 'todos');
                                  ?>
                                  Revision:
                                  <select  id="revision_entregable" class="col-sm-2 form-control">
                           
                                      <?php $j=0;
                                      foreach ($theVariable as $key) { ?>
                                      <option value="<?php echo $key ?>"><?php echo $key; ?></option>
                         
                                      <?php  $j++;  } ?>
                                  </select>   

                                  <!-- <button class="btn dropdown-toggle" data-toggle="dropdown">Herramientas <i class="fa fa-angle-down"></i>
                                  </button>
                                  <ul class="dropdown-menu pull-right">
                                      <li><a href="#">Print</a></li>
                                      <li><a href="#">Save as PDF</a></li>
                                      <li><a href="#">Export to Excel</a></li>
                                  </ul> -->
                              </div>
                          </div>

                              
                        <div id="area_tabla">
                          <table class=" table table-striped table-hover table-bordered " id="editable-sample">
                            <thead>
                              <tr class="menu">    
                                <th>Item</th>
                                <th>EDT</th>
                                <th>Tipo de Documento</th>
                                <th>Disciplina</th>
                                <th>Codigo Anddes</th>
                                <th>Codigo Cliente</th>                          
                                <th >Descripcion de Entregables</th>
                                <th>Fecha A</th>
                                <th >Fecha B</th>
                                <th >Fecha 0</th>
                                <th >Editar</th>
                                <th >Eliminar</th>
                              </tr>
                            </thead>

                            <div >
                              <tbody class="filtros">

                              <?php $lista=$this->lista_det; 
                               //print_r($lista);
                              $i=0;
                              if($lista){
                              foreach ($lista as $entregable) { ?>
                                                           
                                <tr data-uid="123" class="<?php echo $entregable['revision_entregable'] ?>">
                                      <td><?php echo $i?></td>
                                      <td><?php echo $entregable['edt']?></td>                              
                                                    
                                      <td class="center"><?php echo $entregable['tipo_documento']?></td>
                                      <td class="center"><?php echo $entregable['disciplina']?></td>
                                      <td class="center"><?php echo $entregable['codigo_anddes']?></td>
                                      <td class="center"><?php echo $entregable['codigo_cliente']?></td>
                                      <td class="center"><?php echo $entregable['descripcion_entregable']?></td>
                                      <td class="center"><?php echo $entregable['fecha_a']?></td>
                                      <td class="center"><?php echo $entregable['fecha_b']?></td>
                                      <td class="center"><?php echo $entregable['fecha_0']?></td>
                                 
                                      <td><a class="edit" href="javascript:;">Editar</a></td>
                                      <td><a class="delete" href="javascript:;">Eliminar</a></td>
                                </tr>                              
                                  
                              <?php $i++; } } ?>

                              </tbody>
                            </div>
                          </table>
                        </div>

                       

                      </div>
                  </div>
              </section>
       <!--main content end-->
      <!-- Right Slidebar start -->
    
      <!-- Right Slidebar end -->
      <!--footer start-->

      <!--footer end-->

    <script type="text/javascript">
    $(document).ready(function(){
        $('#revision_entregable').click(function() {
        //var textoFiltro = $(this).text().replace(/\s/g,"-");
        //var textoFiltro = $(this).text().toLowerCase().replace(/\s/g,"-");
        var textoFiltro=$(this).val();
        //alert(textoFiltro);

        if(textoFiltro == 'todos')
        {
            $('tbody.filtros tr.hidden').fadeIn('slow').removeClass('hidden');
        }
        else
        {
            $('.filtros tr').each(function()
            {
                if(!$(this).hasClass(textoFiltro))
                {
                    //alert(textoFiltro); 
                    $(".menu").show();

                    //console.log($(".menu").removeClass('hidden'));
                    $(this).fadeOut('normal').addClass('hidden');
                }
                else
                {
                    //alert("llego");
                    $(this).fadeIn('slow').removeClass('hidden');
                }
            });
        }
        return false;
        });
    });
    </script>

    <link href="/css/bootstrap-reset.css" rel="stylesheet">
    
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="/assets/data-tables/DT_bootstrap.css" />
    <link href="/css/slidebars.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/style-responsive.css" rel="stylesheet" />
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!--external css-->


    <script src="/js/jquery.js"></script>
    <script src="/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script class="include" type="text/javascript" src="/js/jquery.dcjqaccordion.2.7.js"></script>

    <script src="/js/jquery.scrollTo.min.js"></script>

    <script src="/js/jquery.nicescroll.js" type="text/javascript"></script>

  <!--right slidebar-->
    <script src="/js/slidebars.min.js"></script>
      <!--right slidebar-->
    <!-- Custom styles for this template -->

   <script type="text/javascript" src="/assets/data-tables/jquery.dataTables.js"></script>
   <script type="text/javascript" src="/assets/data-tables/DT_bootstrap.js"></script>

    <script src="/js/editable-table.js"></script>
    <script src="/js/respond.min.js" ></script>
    <script src="/js/common-scripts.js"></script>
      <script>
          jQuery(document).ready(function() {
              EditableTable.init();
          });
      </script>




<script type="text/javascript">
  var EditableTable = function () {

    return {
        //main function to initiate the module
        init: function () {
            function restoreRow(oTable, nRow) {
                var aData = oTable.fnGetData(nRow);
                var jqTds = $('>td', nRow);

                for (var i = 0, iLen = jqTds.length; i < iLen; i++) {
                    oTable.fnUpdate(aData[i], nRow, i, false);
                }
                oTable.fnDraw();
            }

            function editRow(oTable, nRow) {
                var aData = oTable.fnGetData(nRow);
                var jqTds = $('>td', nRow);
                jqTds[0].innerHTML = '<input type="text" disabled class="col-lg-1 col-md-1 col-sm-1" value="' + aData[0] + '">';
                jqTds[1].innerHTML = '<input type="text" class="form-control" value="' + aData[1] + '">';
                  
                aDataD='Documento';
                aDataP='Plano';
                jqTds[2].innerHTML='<select class="form-control" ><option value="' + aDataD + '">Documemto</option><option value="' + aDataP + '">Plano</option></select>';      

                //alert(aData[2]);
                //jqTds[2].innerHTML = '<input type="text" class="form-control small" value="' + aData[2] + '">';
                //alert(jqTds[1].innerHTML );
                jqTds[3].innerHTML = '<input type="text" class="form-control" value="' + aData[3] + '">';
                jqTds[4].innerHTML = '<input type="text" class="form-control" value="' + aData[4] + '">';
                jqTds[5].innerHTML = '<input type="text" class="form-control" value="' + aData[5] + '">';
                jqTds[6].innerHTML = '<input type="text" class="form-control" value="' + aData[6] + '">';
                jqTds[7].innerHTML = '<input type="text" class="form-control" value="' + aData[7] + '">';
                jqTds[8].innerHTML = '<input type="text" class="form-control" value="' + aData[8] + '">';
                jqTds[9].innerHTML = '<input type="text" class="form-control" value="' + aData[9] + '">';

                jqTds[10].innerHTML = '<a class="edit" href="">Guardar</a>';
                jqTds[11].innerHTML = '<a class="cancel" href="">Cancel</a>';
            }

            function saveRow(oTable, nRow) {
                var jqInputs = $('input', nRow);
                var jqSelect = $('select', nRow);
                //console.log(jqInputs);
                //console.log($(nRow[2]).text);

                var edt=jqInputs[1].value;
                var tipo_doc=jqSelect[0].value;
                console.log(tipo_doc);
                var disc=jqInputs[2].value;
                var cod_anddes=jqInputs[3].value;
                var cod_cliente=jqInputs[4].value;
                var descripcion=jqInputs[5].value;
                var fechaA=jqInputs[6].value;
                var fechaB=jqInputs[7].value;
                var fecha0=jqInputs[8].value;
                var revision=$("#revision_entregable").val();

                url="/control/control/guardarlista/codigo_prop_proy/<?php echo $this->codigo_prop_proy;?>/proyectoid/<?php echo $this->proyectoid; ?>/revision/"+revision+"/edt/"+edt+"/tipo_doc/"+tipo_doc+"/disc/"+disc+"/cod_anddes/"+cod_anddes+"/cod_cliente/"+cod_cliente+"/descripcion/"+descripcion+"/fechaA/"+fechaA+"/fechaB/"+fechaB+"/fecha0/"+fecha0;
               // alert(url);

                $.ajax({
                type: "POST",
                url: url,
                data: $(this).serialize(),
                dataType: "html",                                                 
                  error: function()
                  {
                    alert("error petición ajax load");
                  },
                    success: function(data)
                  {                                
                  }
                });

                oTable.fnUpdate(jqInputs[0].value, nRow, 0, false);
                oTable.fnUpdate(jqInputs[1].value, nRow, 1, false);
                oTable.fnUpdate(jqSelect[0].value, nRow, 2, false);
                oTable.fnUpdate(jqInputs[2].value, nRow, 3, false);
                oTable.fnUpdate(jqInputs[3].value, nRow, 4, false);
                oTable.fnUpdate(jqInputs[4].value, nRow, 5, false);
                oTable.fnUpdate(jqInputs[5].value, nRow, 6, false);
                oTable.fnUpdate(jqInputs[6].value, nRow, 7, false);
                oTable.fnUpdate(jqInputs[7].value, nRow, 8, false);
                oTable.fnUpdate(jqInputs[8].value, nRow, 9, false);
          
                oTable.fnUpdate('<a class="edit" href="">Editar</a>', nRow, 10, false);
                oTable.fnUpdate('<a class="delete" href="">Eliminar</a>', nRow, 11, false);
                oTable.fnDraw();
            }

            function cancelEditRow(oTable, nRow) {
                var jqInputs = $('input', nRow);
                oTable.fnUpdate(jqInputs[0].value, nRow, 0, false);
                oTable.fnUpdate(jqInputs[1].value, nRow, 1, false);
                oTable.fnUpdate(jqInputs[2].value, nRow, 2, false);
                oTable.fnUpdate(jqInputs[3].value, nRow, 3, false);
                oTable.fnUpdate(jqInputs[4].value, nRow, 4, false);
                oTable.fnUpdate(jqInputs[5].value, nRow, 5, false);
                oTable.fnUpdate(jqInputs[6].value, nRow, 6, false);
                oTable.fnUpdate(jqInputs[7].value, nRow, 7, false);
                oTable.fnUpdate(jqInputs[8].value, nRow, 8, false);
                oTable.fnUpdate(jqInputs[9].value, nRow, 9, false);
                oTable.fnUpdate('<a class="edit" href="">Edit</a>', nRow, 10, false);
                oTable.fnDraw();
            }

            var oTable = $('#editable-sample').dataTable({
                "aLengthMenu": [
                    [5, 15, 20, -1],
                    [5, 15, 20, "All"] // change per page values here
                ],
                // set the initial value
                "iDisplayLength": 15,
                "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
                "sPaginationType": "bootstrap",
                "oLanguage": {
                    "sLengthMenu": "_MENU_ filas por pagina",
                    "oPaginate": {
                        "sPrevious": "Siguiente",
                        "sNext": "Anterior"
                    }
                },
                "aoColumnDefs": [{
                        'bSortable': false,
                        'aTargets': [0]
                    }
                ]
            });

            jQuery('#editable-sample_wrapper .dataTables_filter input').addClass("form-control medium"); // modify table search input
            jQuery('#editable-sample_wrapper .dataTables_length select').addClass("form-control xsmall"); // modify table per page dropdown

            var nEditing = null;

            $('#editable-sample_new').click(function (e) {
                e.preventDefault();
                var aiNew = oTable.fnAddData(['', '', '', '','','','','','','',
                        '<a class="edit" href="">Editar</a>', '<a class="cancel" data-mode="new" href="">Cancelar</a>'
                ]);
                var nRow = oTable.fnGetNodes(aiNew[0]);

                //alert(nRow);

                editRow(oTable, nRow);
                nEditing = nRow;
            });

            $('#editable-sample a.delete').live('click', function (e) {
                e.preventDefault();

                if (confirm("Desea eliminar ese registro ?") == false) {
                    return;
                }

                var nRow = $(this).parents('tr')[0];
                var nRowa = $(this).parents('td')[5];

                //var children = document.getElementById('area_tabla').getElementsByTagName('td')[0].innerHTML;
                oTable.fnDeleteRow(nRow);
                
                // var tabla2 = document.getElementById("area_tabla");
                // var tdsTabla2 = tabla2.getElementsByTagName("td");
                // var i =0;
                // for (i=0; i<tdsTabla2.length; i++){
                //   alert('tdsTabla2[i]');
                // }
       

            });

            $('#editable-sample a.cancel').live('click', function (e) {
                e.preventDefault();
                if ($(this).attr("data-mode") == "new") {
                    var nRow = $(this).parents('tr')[0];
                    oTable.fnDeleteRow(nRow);
                } else {
                    restoreRow(oTable, nEditing);
                    nEditing = null;
                }
            });

            $('#editable-sample a.edit').live('click', function (e) {
                e.preventDefault();

                /* Get the row as a parent of the link that was clicked on */
                var nRow = $(this).parents('tr')[0];

                if (nEditing !== null && nEditing != nRow) {
                    /* Currently editing - but not this row - restore the old before continuing to edit mode */
                    restoreRow(oTable, nEditing);
                    editRow(oTable, nRow);
                    nEditing = nRow;
                } else if (nEditing == nRow && this.innerHTML == "Guardar") {
                    /* Editing this row and want to save it */
           

                    //console.log(nRow);
                    //console.log($(nRow[5]).text);
                    //console.log(nEditing);

                    saveRow(oTable, nEditing);
                    nEditing = null;
                    //alert("Updated! Do not forget to do some ajax to sync with backend :)");
                } else {
                    /* No edit in progress - let's start one */
                    editRow(oTable, nRow);
                    nEditing = nRow;
                }
            });
        }

    };

}();


</script>
























