  			 <?php if($this->lista_personas) {?>
<!--   			  <ul class="directory-list">
                  <li><a href="#">a</a></li>
                  <li><a href="#">b</a></li>
                  <li><a href="#">c</a></li>
                  <li><a href="#">d</a></li>
                  <li><a href="#">e</a></li>
                  <li><a href="#">f</a></li>
                  <li><a href="#">g</a></li>
                  <li><a href="#">h</a></li>
                  <li><a href="#">i</a></li>
                  <li><a href="#">j</a></li>
                  <li><a href="#">k</a></li>
                  <li><a href="#">l</a></li>
                  <li><a href="#">m</a></li>
                  <li><a href="#">n</a></li>
                  <li><a href="#">o</a></li>
                  <li><a href="#">p</a></li>
                  <li><a href="#">q</a></li>
                  <li><a href="#">r</a></li>
                  <li><a href="#">s</a></li>
                  <li><a href="#">t</a></li>
                  <li><a href="#">u</a></li>
                  <li><a href="#">v</a></li>
                  <li><a href="#">w</a></li>
                  <li><a href="#">x</a></li>
                  <li><a href="#">y</a></li>
                  <li><a href="#">z</a></li>
              </ul> -->
              <div class="directory-info-row">
              <div class="row">

              <?php foreach ($this->lista_personas as $personas) { ?>
                
              <div class="col-md-6 col-sm-6">
                  <div class="panel">
                      <div class="panel-body">
                          <div class="media">
                              <a class="pull-left" href="#">
                                  <img class="thumb media-object" src="/img/fotos-anddes/<?php echo $personas['dni'];?>.jpg" style="width : 50px ; height : 50px">
                              </a>
                              <div class="media-body">
                              <h4><?php echo $personas['nombres']; echo " "; echo $personas['ape_paterno'];echo " ";echo $personas['ape_materno']   ?><span class="text-muted small"> - UI Engineer</span></h4>
                   

                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <?php }?>
              

              </div>
              </div>
              
              </div>
              <?php
          	  }
              else
              {
              ?>
              	<div>
              		<p>No se encontraron resultados</p>
              	</div>
              <?php
              }
              ?>
