  			 <?php if($this->lista_personas) {?>

              <div class="directory-info-row">
              <div class="row">

              <?php foreach ($this->lista_personas as $personas) { ?>
                
              <div class="col-md-6 col-sm-6">
                  <div class="panel">
                      <div class="panel-body">
                          <div class="media">
                              <a class="pull-left" href="/rrhh/perfil/ver/dni/<?php echo $personas['dni'];?>">
                                  <img class="thumb media-object" src="/img/fotos-anddes/<?php echo $personas['dni'];?>.jpg" style="width : 50px ; height : 50px">
                              </a>
                              <div class="media-body">
                              <h4><?php echo $personas['nombres']; echo " "; echo $personas['ape_paterno'];echo " ";echo $personas['ape_materno']   ?><span class="text-muted small"> - UI Engineer</span></h4>
                   

                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <?php }?>
              

              </div>
              </div>
              
              </div>
              <?php
          	  }
              else
              {
              ?>
              	<div>
              		<p>No se encontraron resultados</p>
              	</div>
              <?php
              }
              ?>
