<?php 
if ($this->gasto) { 
$data_rendicion = $this->data_rendicion;
    ?>
<div class="row">
<form action="" id="form_rendicion" class="form-horizontal">
    <div class="col-lg-4">
        <section class="panel">
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-lg-4 col-sm-4 control-label" style="font-size : 12px">N° Rendición</label>
                    <div class="col-lg-8">
                        <?php echo $data_rendicion['numero_completo'];?>
                        <input name="numero" type="hidden" value="<?php echo $data_rendicion['numero'];?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-4 col-sm-4 control-label" style="font-size : 12px">Título Rendición</label>
                    <div class="col-lg-8">
                        <input name="nombre" type="text" class="form-control" value="<?php echo ($data_rendicion['nombre'])? $data_rendicion['nombre']: '';?>"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-4 col-sm-4 control-label" style="font-size : 12px">Fecha</label>
                    <div class="col-lg-8">
                        <input name="fecha_rendicion" type="text" class="form-control" value="<?php echo ($data_rendicion['fecha'])? $data_rendicion['fecha']: '';?>" readonly/>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="col-lg-4">
        <section class="panel">
            <div class="panel-body" style="padding : 10x 10px">
                <div id="load_data_consolidated"></div>
                <div class="form-group">
                    <label class="col-lg-6 col-sm-6 control-label" style="font-size : 12px">Total Monto</label>
                    <div class="col-lg-6">

                        <input name="monto_total" type="text" class="form-control" value="<?php echo ($data_rendicion['monto_total'])? $data_rendicion['monto_total']: '';?>" readonly/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-6 col-sm-6 control-label" style="font-size : 12px">Total Reembolso</label>
                    <div class="col-lg-6">
                        <input name="monto_reembolso" type="text" class="form-control" value="<?php echo ($data_rendicion['monto_reembolso'])? $data_rendicion['monto_reembolso']: '';?>" readonly/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-6 col-sm-6 control-label" style="font-size : 12px">Total Cliente</label>
                    <div class="col-lg-6">
                        <input name="monto_cliente" type="text" class="form-control" value="<?php echo ($data_rendicion['monto_cliente'])? $data_rendicion['monto_cliente']: '';?>" readonly/>
                    </div>
                </div>
            </div>
        </section>
    </div>
</form>
    <div class="col-lg-4">
        <section class="panel">
            <div class="panel-body" style="padding : 28px 15px 28px 15px">
                <a id="guardar_gastos" class="btn btn-success pull-right btn-sm" href="##">
                    <i class="fa fa-save"></i> Guardar
                </a>
                <a id="enviar_gasto" class="btn btn-warning pull-right btn-sm" href="##" style="margin-right : 10px">
                    <i class="fa fa-chevron-circle-right"></i> Enviar
                </a>
            </div>
        </section>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
    <form action="" id="form_gastos">
    <?php 
    $gasto = $this->gasto;
    if ($gasto) {
        $j = 0;
        foreach ($gasto as $data_gasto) { ?>
            <section class="panel">
                <header class="panel-heading modal-header" style="padding : 7px">
                      <?php echo $data_gasto['proyectoid']. ' - ' .$data_gasto['nombre_proyecto'] ?>
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped table-condensed" style="font-size:11px">
                            <thead>
                                <tr>
                                    <?php if ($data_rendicion['estado'] != "E") { ?>
                                        <th style="width : 30px"></th>
                                        <?php
                                    } ?>
                                    <th>Descripción</th>
                                    <th colspan="2"><center>Gasto</center></th>
                                    <th>Cant.</th>
                                    <th>PU</th>
                                    <th>Clien.</th>
                                    <th>Reemb.</th>
                                    <th>Fecha</th>
                                    <th>Moneda</th>
                                    <th>N° Documento</th>
                                    <th>Proveedor</th>
                                    <th>Neto</th>
                                    <th>Otro Imp.</th>
                                    <th>IGV (18%)</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                            foreach ($data_gasto['actividades'] as $data_actividades) { ?>
                                <tr class="gradeX">
                                    <td>
                                        <a href="##" class="btn btn-warning btn-xs duplicar_actividad" title="Duplicar" gasto-persona-id="<?php echo $data_actividades['gasto_persona_id'] ?>" proyectoid="<?php echo $data_actividades['proyectoid']?>" codigo-prop-proy="<?php echo $data_actividades['codigo_prop_proy']?>" categoriaid="<?php echo $data_actividades['categoriaid']?>" areaid="<?php echo $data_actividades['areaid']?>" cargo="<?php echo $data_actividades['cargo']?>" revision="<?php echo $data_actividades['revision']?>" actividadid="<?php echo $data_actividades['actividadid']?>">
                                                <strong>+</strong>
                                        </a>
                                            
                                        <a href="##" class="btn btn-danger btn-xs delete_actividad" title="Eliminar" gasto-persona-id = "<?php echo $data_actividades['gasto_persona_id'] ?>" style="margin-top: 2px">
                                            <strong>-</strong>
                                        </a>
                                    </td>
                                    <td>
                                        <input name="description[]" type="text" class="form-control" value="<?php echo ($data_actividades['descripcion'])? $data_actividades['descripcion'] : ''; ?>" />
                                    </td>
                                    <td>
                                        <select name="gasto_padre[]" id="gasto_padre<?php echo $data_actividades['gasto_persona_id'] ?>" class="list_gasto form-control">
                                            <?php if ($this->list_gastos): ?>
                                                <option value="">Seleccione</option>
                                            <?php foreach ($this->list_gastos as $list_gastos) {
                                                    if ($data_actividades['tipo_proyecto'] == 'Construcción'){ 
                                                        if ($list_gastos['tipo_gasto'] == "construccion" || $list_gastos['tipo_gasto'] == "laboratorio") { ?>
                                                            <option value="<?php echo $list_gastos['gastoid']. '-' .$list_gastos['tipo_gasto'] ?>" <?php print ($data_actividades['gasto_padre']==$list_gastos['gastoid'].'-'.$list_gastos['tipo_gasto'])? 'selected' : ''; ?>><?php echo $list_gastos['gastoid'].' - '.$list_gastos['nombre_gasto'] ?></option>
                                            <?php       }
                                                    } else { 
                                                        if ($list_gastos['tipo_gasto'] != "construccion" || $list_gastos['tipo_gasto'] == "laboratorio") { ?>
                                                        <option value="<?php echo $list_gastos['gastoid']. '-' .$list_gastos['tipo_gasto'] ?>" <?php print ($data_actividades['gasto_padre']==$list_gastos['gastoid'].'-'.$list_gastos['tipo_gasto'])? 'selected' : ''; ?>><?php echo $list_gastos['gastoid'].' - '.$list_gastos['nombre_gasto'] ?></option>
                                                    <?php
                                                        }
                                                    } 
                                                } ?>
                                            <?php else: ?>
                                                <option value="">No Existen Gastos</option>
                                            <?php endif ?>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="gasto_hijo[]" id="gasto_hijo<?php echo $data_actividades['gasto_persona_id'] ?>" class="list_gasto form-control">
                                            <option value="">Seleccione</option>
                                        </select>
                                    </td>
                                    <td>
                                        <center><input name="lab_cantidad[]" id="lab_cantidad<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 50px" value="<?php echo ($data_actividades['laboratorio_cantidad'])? $data_actividades['laboratorio_cantidad'] : ''; ?>" readonly/></center>
                                    </td>
                                    <td>
                                        <center><input name="lab_pu[]" id="lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 50px" value="<?php echo ($data_actividades['laboratorio_PU'])? $data_actividades['laboratorio_PU'] : ''; ?>" readonly/></center>
                                    </td>
                                    <td>
                                        <center>
                                            <input name="cliente[<?php echo $j?>]" type="checkbox" class="form-control" style="width : 15px" value="TRUE" <?php print ($data_actividades['bill_cliente']=='TRUE')? 'checked' : ''; ?>/>
                                        </center>
                                    </td>
                                    <td>
                                        <center><input name="reembolsable[<?php echo $j?>]" type="checkbox" class="form-control"   style="width : 15px" value="TRUE" <?php print ($data_actividades['reembolsable']=='TRUE')? 'checked' : ''; ?>/></center>
                                    </td>
                                    <td>
                                        <center><input name="fecha[]" type="text" class="form-control datefactura" style="width : 70px" value="<?php echo ($data_actividades['fecha_factura'])? $data_actividades['fecha_factura'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <select name="moneda[]" class="form-control">
                                            <option value="">Seleccione</option>
                                            <option value="Soles" <?php echo ($data_actividades['moneda']=='Soles')? 'selected':'';?>>Soles</option>
                                            <option value="Dolar" <?php echo ($data_actividades['moneda']=='Dolar')? 'selected':'';?>>Dolar</option>
                                            <option value="Real" <?php echo ($data_actividades['moneda']=='Real')? 'selected':'';?>>Real</option>
                                            <option value="Peso" <?php echo ($data_actividades['moneda']=='Peso')? 'selected':'';?>>Peso</option>
                                        </select>
                                    </td>
                                    <td>
                                        <center><input name="documento[]" type="text" class="form-control" style="width : 70px" value="<?php echo ($data_actividades['num_factura'])? $data_actividades['num_factura'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <center><input name="proveedor[]" type="text" class="form-control" style="width : 70px" value="<?php echo ($data_actividades['proveedor'])? $data_actividades['proveedor'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <center><input name="monto[]" id="neto<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 70px" value="<?php echo ($data_actividades['monto_igv'])? $data_actividades['monto_igv'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <center><input name="otro_impuesto[]" id="otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 50px" value="<?php echo ($data_actividades['otro_impuesto'])? $data_actividades['otro_impuesto'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <center><input name="igv[]" id="igv<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 50px" value="<?php echo ($data_actividades['igv'])? $data_actividades['igv'] : ''; ?>"></center>
                                    </td>
                                    <td>
                                        <center><input name="monto_total[]" id="total<?php echo $data_actividades['gasto_persona_id'] ?>" type="text" class="form-control" style="width : 70px" value="<?php echo ($data_actividades['monto_total'])? $data_actividades['monto_total'] : ''; ?>"></center>
                                    </td>
                                    <input type="hidden" name="gasto_persona_id[]" value="<?php echo $data_actividades['gasto_persona_id'] ?>"/>
                                    <input type="hidden" name="codigo_prop_proy[]" value="<?php echo $data_actividades['codigo_prop_proy'] ?>"/>
                                    <input type="hidden" name="proyectoid[]" value="<?php echo $data_actividades['proyectoid'] ?>"/>
                                </tr>
                                <script type="text/javascript">
                                    $("#gasto_padre<?php echo $data_actividades['gasto_persona_id'] ?>").change(function(){
                                        var gasto = $(this).val();
                                        var res = gasto.split("-");
                                        if (res[1]=='laboratorio') {
                                            $("#lab_cantidad<?php echo $data_actividades['gasto_persona_id'] ?>").attr('readonly', false);
                                            $("#lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>").attr('readonly', false);
                                        } else {
                                            $("#lab_cantidad<?php echo $data_actividades['gasto_persona_id'] ?>").attr('readonly', true);
                                            $("#lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>").attr('readonly', true);
                                        };
                                    });

                                    $("#gasto_hijo<?php echo $data_actividades['gasto_persona_id'] ?>").change(function(){
                                        var gasto = $(this).val();
                                        var res = gasto.split("-");
                                        if (res[1] == 'laboratorio') {
                                            $("#lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>").val(res[2]);
                                        };
                                    });

                                    $("#lab_cantidad<?php echo $data_actividades['gasto_persona_id'] ?>").keyup(function(){
                                        var cant = $(this).val();
                                        var pu = $("#lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        var new_neto1 = parseFloat(cant)*parseFloat(pu);
                                        if (isNaN(new_neto1)) {
                                            new_neto1 = '';
                                        };
                                        $("#neto<?php echo $data_actividades['gasto_persona_id'] ?>").val(new_neto1);
                                        var otro = $("#otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        if (otro == '' || otro =='0') {
                                            otro = 0;
                                        };
                                        var igv = (new_neto1 * 0.18);
                                        var total_neto = parseFloat(new_neto1)+parseFloat(igv);
                                        var total = parseFloat(total_neto)+parseFloat(otro);
                                        if (isNaN(total)) {
                                            total = 0;
                                        };
                                        if (isNaN(igv)) {
                                            igv = 0;
                                        };
                                        $("#igv<?php echo $data_actividades['gasto_persona_id'] ?>").val(igv);
                                        $("#total<?php echo $data_actividades['gasto_persona_id'] ?>").val(total);
                                    });

                                    $("#lab_pu<?php echo $data_actividades['gasto_persona_id'] ?>").keyup(function(){
                                        var pu = $(this).val();
                                        var cant = $("#lab_cantidad<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        var new_neto1 = parseFloat(cant)*parseFloat(pu);
                                        if (isNaN(new_neto1)) {
                                            new_neto1 = '';
                                        };
                                        $("#neto<?php echo $data_actividades['gasto_persona_id'] ?>").val(new_neto1);
                                        var otro = $("#otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        if (otro == '' || otro =='0') {
                                            otro = 0;
                                        };
                                        var igv = (new_neto1 * 0.18);
                                        var total_neto = parseFloat(new_neto1)+parseFloat(igv);
                                        var total = parseFloat(total_neto)+parseFloat(otro);
                                        if (isNaN(total)) {
                                            total = 0;
                                        };
                                        if (isNaN(igv)) {
                                            igv = 0;
                                        };
                                        $("#igv<?php echo $data_actividades['gasto_persona_id'] ?>").val(igv);
                                        $("#total<?php echo $data_actividades['gasto_persona_id'] ?>").val(total);
                                    });

                                    $("#neto<?php echo $data_actividades['gasto_persona_id'] ?>").keyup(function(){
                                        var neto = $(this).val();
                                        var otro = $("#otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        if (otro == '' || otro =='0') {
                                            otro = 0;
                                        };
                                        var igv = (neto * 0.18);
                                        var total_neto = parseFloat(neto)+parseFloat(igv);
                                        var total = parseFloat(total_neto)+parseFloat(otro);
                                        if (isNaN(total)) {
                                            total = 0;
                                        };
                                        if (isNaN(igv)) {
                                            igv = 0;
                                        };
                                        $("#igv<?php echo $data_actividades['gasto_persona_id'] ?>").val(igv);
                                        $("#total<?php echo $data_actividades['gasto_persona_id'] ?>").val(total);
                                    });

                                    $("#otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>").keyup(function(){
                                        var neto = $("#neto<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        var otro = $(this).val();
                                        if (otro == '' || otro =='0') {
                                            otro = 0;
                                        };
                                        var igv = (neto * 0.18);
                                        var total_neto = parseFloat(neto)+parseFloat(igv);
                                        var total = parseFloat(total_neto)+parseFloat(otro);
                                        if (isNaN(total)) {
                                            total = 0;
                                        };
                                        if (isNaN(igv)) {
                                            igv = 0;
                                        };
                                        $("#igv<?php echo $data_actividades['gasto_persona_id'] ?>").val(igv);
                                        $("#total<?php echo $data_actividades['gasto_persona_id'] ?>").val(total);
                                    });

                                    $("#igv<?php echo $data_actividades['gasto_persona_id'] ?>").keyup(function(){
                                        var neto = $("#neto<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        var otro = $("#otro_imp<?php echo $data_actividades['gasto_persona_id'] ?>").val();
                                        var igv_tmp = $(this).val();
                                        if (otro == '' || otro =='0') {
                                            otro = 0;
                                        };
                                        if (igv_tmp == '' || igv_tmp =='0') {
                                            new_igv = 0;
                                        } else {
                                            new_igv = igv_tmp;
                                        };
                                        var total_neto = parseFloat(neto)+parseFloat(new_igv);
                                        var total = parseFloat(total_neto)+parseFloat(otro);
                                        $("#total<?php echo $data_actividades['gasto_persona_id'] ?>").val(total);
                                    });

                                    $("#gasto_padre<?php echo $data_actividades['gasto_persona_id'] ?>").change(function(){
                                        var gasto_padre = $(this).val();
                                        $("#gasto_hijo<?php echo $data_actividades['gasto_persona_id'] ?>").load("/expense/index/gastohijo/gastoid/"+gasto_padre);
                                    });

                                    $("#gasto_padre<?php echo $data_actividades['gasto_persona_id'] ?> option:selected").each(function() {
                                        var gasto_padre = $(this).val();
                                        var gasto_persona_id = "<?php echo $data_actividades['gasto_persona_id'] ?>";
                                        if (gasto_padre) {
                                            $("#gasto_hijo<?php echo $data_actividades['gasto_persona_id'] ?>").load("/expense/index/gastohijo/gastoid/"+gasto_padre+"/gasto_persona_id/"+gasto_persona_id);
                                        };
                                    });
                                </script>
                            <?php
                            $j++;
                            }
                             ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            
            <?php
        }
    }
     ?>
    </form>
    </div>
</div>
<div id="load_duplicidad"></div>

<script type="text/javascript">
    $(".datefactura").datepicker();

    $(".duplicar_actividad").click(function(){
        var gasto_persona_id = $(this).attr('gasto-persona-id');
        var proyectoid = $(this).attr('proyectoid');
        var codigo_prop_proy = $(this).attr('codigo-prop-proy');
        var categoriaid = $(this).attr('categoriaid');
        var areaid = $(this).attr('areaid');
        var cargo = $(this).attr('cargo');
        var revision = $(this).attr('revision');
        var actividadid = $(this).attr('actividadid');

        var numero = "<?php echo $this->numero?>";
        var uid = "<?php echo $this->uid?>";
        var dni = "<?php echo $this->dni?>";

        $.ajax({
            type   : 'post',
            url    : '/expense/index/updategastorendicion/',
            data   : $('#form_rendicion').serialize(),
            success: function(data){
                $.ajax({
                    type   : 'post',
                    url    : '/expense/index/updategastopersona/',
                    data   : $('#form_gastos').serialize(),
                    success: function(data){
                        var url2 = "/expense/index/guardargastopersona/proyectoid/"+proyectoid+"/codigo-prop-proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid+"/areaid/"+areaid+"/cargo/"+cargo+"/revision/"+revision+"/actividadid/"+actividadid;
                        $("#load_duplicidad").load(url2);
                        var url3 = "/expense/index/editardetalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
                        $("#load_detalless").load(url3);
                    }
                });
            }
        });
    });

    $(".delete_actividad").click(function(){
        var gasto_persona_id = $(this).attr('gasto-persona-id');
        var numero = "<?php echo $this->numero?>";
        var uid = "<?php echo $this->uid?>";
        var dni = "<?php echo $this->dni?>";

        url = "/expense/index/eliminargastopersona/gasto_persona_id/"+gasto_persona_id;
        $("#load_duplicidad").load(url);
        var url3 = "/expense/index/editardetalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
        $("#load_detalless").load(url3);
    });

    $('#guardar_gastos').click(function(){
        $.ajax({
            type   : 'post',
            url    : '/expense/index/updategastorendicion/',
            data   : $('#form_rendicion').serialize(),
            success: function(data){
                $.ajax({
                    type   : 'post',
                    url    : '/expense/index/updategastopersona/',
                    data   : $('#form_gastos').serialize(),
                    success: function(data){
                        alert("El gasto fue registrado.");
                    }
                });
            }
        });
    });

    $('#enviar_gasto').click(function(){
        $.ajax({
            type   : 'post',
            url    : '/expense/index/updateenviargastorendicion/',
            data   : $('#form_rendicion').serialize(),
            success: function(data){
                $.ajax({
                    type   : 'post',
                    url    : '/expense/index/updateenviargastopersona/',
                    data   : $('#form_gastos').serialize(),
                    success: function(data){
                        alert("El gasto fue enviado.");
                        window.location.reload();
                    }
                });
            }
        });
    });
</script>

<?php 
} ?>