<section class="panel">
        <header class="panel-heading">
          Rendiciones
          <span class="pull-right">
                <a id="mostrar_pendiente" class=" btn btn-success  btn-xs"> Pendiente</a>
                <a id="mostrar_enviado" class=" btn btn-primary  btn-xs"> Enviado</a>
                <a id="mostrar_aprobada" class=" btn btn-warning  btn-xs"> Aprobada</a>
                <a id="mostrar_rechazada" class=" btn btn-danger  btn-xs"> Rechazada</a>
          </span>
        </header>
        <div id="rendicion_pendientes">
        <table class="table table-hover p-table">
            <thead>
                <tr>
                    <th style="width: 2%;">Num</th>
                    <th style="width: 20%;">Nombre</th>
                    <th style="width: 20%;">Fecha</th>
                    <th style="width: 10%;"><center>Total</center></th>
                    <th style="width: 20%;">Estado</th>
                    <th style="width: 3%;">&nbsp;&nbsp;&nbsp;&nbsp;Acciones&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            <?php
            if ($this->pendiente) {
            foreach ($this->pendiente as $lista) { ?>
                <tr>
                    <td class="p-name">
                        <center><?php echo $lista['numero'];?></center>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['nombre'];?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['fecha']; ?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['monto_total']; ?>
                    </td>
                    <td>
                        <?php
                        if ($lista['estado']=='B') { ?>
                            <span class="label label-success label-mini">Pendiente</span>
                            <?php
                        } ?>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="##" class="enviar" uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>" estate="E">Enviar</a></li>
                            </ul>
                        </div>
                    </td>
                    <td>
                        <center>
                            <a data-toggle="modal" href="#myModalDetail" class="btn btn-warning btn-xs showdetails" title="Detalles"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-folder"></i></a>
                            <a data-toggle="modal" href="#myModalDetail" class="btn btn-info btn-xs editdetails" title="Editar"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-edit"></i></a>
                        </center>
                    </td>
                </tr>
                <script type="text/javascript">
                    $(".enviar").click(function(){
                        var numero = $(this).attr('numero');
                        var uid = $(this).attr('uid');
                        var dni = $(this).attr('dni');
                        var estate = $(this).attr('estate');
                        $("#load_change_state").load("/expense/aprobacion/estado/numero/"+numero+"/uid/"+uid+"/dni/"+dni+"/estate/"+estate);
                        window.location.reload();
                    });
                </script>
          <?php  }
            }?>
            </tbody>
        </table>
        </div>

        <div id="rendicion_enviados" style="display: none;">
        <table class="table table-hover p-table">
            <thead>
                <tr>  
                    <th style="width: 2%;">Num</th>
                    <th style="width: 20%;">Nombre</th>
                    <th style="width: 20%;">Fecha</th>
                    <th style="width: 10%;"><center>Total</center></th>
                    <th style="width: 20%;">Estado</th>
                    <th style="width: 3%;">&nbsp;&nbsp;&nbsp;&nbsp;Acciones&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            <?php
            if ($this->enviado) {
            foreach ($this->enviado as $lista) { ?>
                <tr>
                    <td class="p-name">
                        <center><?php echo $lista['numero'];?></center>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['nombre'];?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['fecha']; ?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['monto_total']; ?>
                    </td>
                    <td>
                        <?php
                        if ($lista['estado']=='E') { ?>
                            <span class="label label-primary label-mini">Enviado</span>
                            <?php
                        } ?>
                    </td>
                    <td>
                        <center>
                            <a data-toggle="modal" href="#myModalDetail" class="btn btn-warning btn-xs showdetails" title="Detalles"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-folder"></i></a>
                        </center>
                    </td>
                </tr>
          <?php  }
            }?>
            </tbody>
        </table>
        </div>

        <div id="rendicion_rechazados" style="display: none;">
        <table class="table table-hover p-table">
            <thead>
                <tr>  
                    <th style="width: 2%;">Num</th>
                    <th style="width: 20%;">Nombre</th>
                    <th style="width: 20%;">Fecha</th>
                    <th style="width: 10%;"><center>Total</center></th>
                    <th style="width: 20%;">Estado</th>
                    <th style="width: 3%;">&nbsp;&nbsp;&nbsp;&nbsp;Acciones&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            <?php
            if ($this->rechazado) {
            foreach ($this->rechazado as $lista) { ?>
                <tr>
                    <td class="p-name">
                        <center><?php echo $lista['numero'];?></center>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['nombre'];?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['fecha']; ?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['monto_total']; ?>
                    </td>
                    <td>
                        <?php
                        if ($lista['estado']=='R') { ?>
                            <span class="label label-danger label-mini">Rechazado</span>
                            <?php
                        } ?>
                    </td>
                    <td>
                        <center>
                            <a data-toggle="modal" href="#myModalDetail" class="btn btn-warning btn-xs showdetails" title="Detalles"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-folder"></i></a>
                        </center>
                    </td>
                </tr>
          <?php  }
            }?>
            </tbody>
        </table>
        </div>

        <div id="rendicion_aprobados" style="display: none;">
        <table class="table table-hover p-table">
            <thead>
                <tr>  
                    <th style="width: 2%;">Num</th>
                    <th style="width: 20%;">Nombre</th>
                    <th style="width: 20%;">Fecha</th>
                    <th style="width: 10%;"><center>Total</center></th>
                    <th style="width: 20%;">Estado</th>
                    <th style="width: 3%;">&nbsp;&nbsp;&nbsp;&nbsp;Acciones&nbsp;&nbsp;&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            <?php
            if ($this->aprobado) {
            foreach ($this->aprobado as $lista) { ?>
                <tr>
                    <td class="p-name">
                        <center><?php echo $lista['numero'];?></center>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['nombre'];?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['fecha']; ?>
                    </td>
                    <td class="p-name">
                        <?php echo $lista['monto_total']; ?>
                    </td>
                    <td>
                        <?php
                        if ($lista['estado']=='A') { ?>
                            <span class="label label-warning label-mini">Aprobados</span>
                            <?php
                        } ?>
                    </td>
                    <td>
                        <center>
                            <a data-toggle="modal" href="#myModalDetail" class="btn btn-warning btn-xs showdetails" title="Detalles"  uid="<?php echo $lista['uid']; ?>" dni="<?php echo $lista['dni']; ?>" numero="<?php echo $lista['numero']; ?>"><i class="fa fa-folder"></i></a>
                        </center>
                    </td>
                </tr>
          <?php  }
            }?>
            </tbody>
        </table>
        </div>
    </section>

    <div class="modal fade" id="myModalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content" style="width: 1250px; top: 100%; margin-left: -180px;">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Detalles</h4>
                </div>
                <div class="modal-body">
                    <div id="load_detalless"></div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <div id="load_change_state"></div>

    <script type="text/javascript">
        $(".showdetails").click(function(){
            var numero = $(this).attr('numero');
            var uid = $(this).attr('uid');
            var dni = $(this).attr('dni');
            var url = "/expense/index/detalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
            $("#load_detalless").load(url);
        });

        $(".editdetails").click(function(){
            var numero = $(this).attr('numero');
            var uid = $(this).attr('uid');
            var dni = $(this).attr('dni');
            var url = "/expense/index/editardetalles/numero/"+numero+"/uid/"+uid+"/dni/"+dni;
            $("#load_detalless").load(url);
        });

        $("#mostrar_pendiente").click(function(){
            $("#rendicion_pendientes").show();
            $("#rendicion_enviados").hide();
            $("#rendicion_rechazados").hide();
            $("#rendicion_aprobados").hide();
        });

        $("#mostrar_enviado").click(function(){
            $("#rendicion_pendientes").hide();
            $("#rendicion_enviados").show();
            $("#rendicion_rechazados").hide();
            $("#rendicion_aprobados").hide();
        });

        $("#mostrar_aprobada").click(function(){
            $("#rendicion_pendientes").hide();
            $("#rendicion_enviados").hide();
            $("#rendicion_rechazados").hide();
            $("#rendicion_aprobados").show();
        });

        $("#mostrar_rechazada").click(function(){
            $("#rendicion_pendientes").hide();
            $("#rendicion_enviados").hide();
            $("#rendicion_rechazados").show();
            $("#rendicion_aprobados").hide();
        });
    </script>