  
<section class="panel">
  <header class="panel-heading">
    Expense Sheet para usuario
    </header>
      <div class="panel-body">
        <table class="table table-hover p-table">
          <thead>
            <tr>  
              <th style="width: 10%;">codigo_prop_proy</th>
              <th style="width: 10%;">proyectoid</th>          
            </tr>
          </thead>
          <?php
            $c=0;
          foreach ($this->listaproyecto as $lista) {
               
            ?>                   
            <tr>
               <td class="p-name">
                <span class="tools pull-right">
                <a href="javascript:;" class="fa fa-chevron-down"><?php echo $lista['codigo_prop_proy']; ?></a>           
                <a href="javascript:;" class="fa fa-times"></a>
                </span>
              </td>
              <td>
                <a href="#"><?php echo $lista['proyectoid']; ?></a>                                
              </td>
              <tr>      


                    <div class="adv-table editable-table ">
                      <div class="clearfix">
                        <div class="btn-group">
                          <button id="editable-sample_new" class="btn green">
                          Add New <i class="fa fa-plus"></i>
                          </button>
                        </div>
                        <div class="btn-group pull-right">
                          <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                          </button>
                          <ul class="dropdown-menu pull-right">
                            <li><a href="#">Print</a></li>
                            <li><a href="#">Save as PDF</a></li>
                            <li><a href="#">Export to Excel</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="space15"></div>
                        <table class="table table-striped table-hover table-bordered" id="editable-sample">
                        <thead>
                          <tr>
                            <th>Proyecto</th>
                            <th>Actividad</th>
                            <th>Fecha de Gasto</th>
                            <th>Descripcion</th>
                            <th>Tipo Gasto</th>
                            <th>Bill Cliente</th>
                            <th>Reembolso</th>
                            <th>#Factura</th>
                            <th>Proveedor</th> 
                            <th>Edit</th>
                            <th>Delete</th>
                          </tr>
                        </thead>
                                              
                        <tbody>
                          <tr class="">
                            <td>Jondi Rose</td>
                            <td>Alfred Jondi Rose</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td class="center">super user</td>
                            <td><a class="edit" href="javascript:;">Edit</a></td>
                            <td><a class="delete" href="javascript:;">Delete</a></td>
                          </tr>
                          <tr class="">
                            <td>Dulal</td>
                            <td>Jonathan Smith</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td class="center">new user</td>
                            <td><a class="edit" href="javascript:;">Edit</a></td>
                            <td><a class="delete" href="javascript:;">Delete</a></td>
                          </tr>
                          <tr class="">
                            <td>Sumon</td>
                            <td> Sumon Ahmed</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td>1234</td>
                            <td class="center">super user</td>
                            <td><a class="edit" href="javascript:;">Edit</a></td>
                            <td><a class="delete" href="javascript:;">Delete</a></td>
                          </tr>

                        </tbody>
                      </table>
                    </div>

              </tr>                            
            </tr>                            
              <?php $c++;}?>
        </table>       
      </div>
</section>
    


        
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Dynamic Table</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!--dynamic table-->
    <link href="assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />
    <link href="assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />
    <link rel="stylesheet" href="assets/data-tables/DT_bootstrap.css" />
      <!--right slidebar-->
      <link href="css/slidebars.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  
    
   
              <div class="row">
                <div class="col-sm-12">
                  <section class="panel">
                  <header class="panel-heading">
                      DataTables hidden row details example
                  </header>
                  <table class="table table-hover p-table">
                    <thead>
                    </thead>
                      <tr>  
                         <?php
                         $c=0;
                         foreach ($this->listaproyecto as $lista) {
                          ?>        
                          <tr>
                            <td><?php echo $lista['codigo_prop_proy']; ?>                       
                             <span class="tools pull-right">
                              <a id="de_<?php echo $c?>" href="#" >kkk</a>
                              <a id="de_<?php echo $c?>" href="javascript:;" >kkk</a>
                              <a href="javascript:;" class="fa fa-times"></a>
                            </span>
                            </td>
                          </tr>
                           
                            <script type="text/javascript">
                                   $("#de_<?php echo $c?>").click(function(){
                                      alert('fff');
                                      console.log('nnnnnn');
                                   }
                            </script>

                      </tr>

  
                          </div>
                   <?php $c++;}?>
                  </table>
                  </section>
              </div>
              </div>
              <!-- page end-->


 












                        <div class="panel-body">
                          <div class="adv-table">
                              <table class="display table table-bordered" id="hidden-table-info">
                                <thead>
                                <tr>
                                    <th>Rendering engine</th>
                                    <th>Browser</th>
                                    <th class="hidden-phone">Platform(s)</th>
                                    <th class="hidden-phone">Engine version</th>
                                    <th class="hidden-phone">CSS grade</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr class="gradeX">
                                    <td>Trident</td>
                                    <td>Internet
                                        Explorer 4.0</td>
                                    <td class="hidden-phone">Win 95+</td>
                                    <td class="center hidden-phone">4</td>
                                    <td class="center hidden-phone">X</td>
                                </tr>

                                <tr class="gradeA">
                                    <td>Trident</td>
                                    <td>AOL browser (AOL desktop)</td>
                                    <td class="hidden-phone">Win XP</td>
                                    <td class="center hidden-phone">6</td>
                                    <td class="center hidden-phone">A</td>
                                </tr>     

                                <tr class="gradeX">
                                    <td>Misc</td>
                                    <td>Lynx</td>
                                    <td class="hidden-phone">Text only</td>
                                    <td class="center hidden-phone">-</td>
                                    <td class="center hidden-phone">X</td>
                                </tr>
                                <tr class="gradeC">
                                    <td>Misc</td>
                                    <td>IE Mobile</td>
                                    <td class="hidden-phone">Windows Mobile 6</td>
                                    <td class="center hidden-phone">-</td>
                                    <td class="center hidden-phone">C</td>
                                </tr>

                                </tbody>
                              </table>
                          </div>







      <div class="sb-slidebar sb-right sb-style-overlay">
          <h5 class="side-title">Online Customers</h5>
          <ul class="quick-chat-list">
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/chat-avatar2.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>John Doe</strong>
                          <small>Dream Land, AU</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/pro-ac-1.png" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-success">5</span>
                          </div>
                          <strong>Jane Doe</strong>
                          <small>ABC, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/avatar1.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>Anjelina Joli</strong>
                          <small>Fockland, UK</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/mail-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-warning">7</span>
                          </div>
                          <strong>Mr Tasi</strong>
                          <small>Dream Land, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
          </ul>
          <h5 class="side-title"> pending Task</h5>
          <ul class="p-task tasks-bar">
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">40%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">40% Complete (success)</span>
                          </div>
                      </div>
                  </a>
              </li>

              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">45%</div>
                      </div>
                      <div class="progress progress-striped active">
                          <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                              <span class="sr-only">45% Complete</span>
                          </div>
                      </div>

                  </a>
              </li>
              <li class="external">
                  <a href="#">See All Tasks</a>
              </li>
          </ul>
      </div>
 

    <!-- js placed at the end of the document so the pages load faster -->

    <script src="js/jquery.js"></script>
    <script src="js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="js/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="assets/advanced-datatable/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="assets/data-tables/DT_bootstrap.js"></script>
    <script src="js/respond.min.js" ></script>

    <!--right slidebar-->
    <script src="js/slidebars.min.js"></script>

    <!--dynamic table initialization -->
    <script src="js/dynamic_table_init.js"></script>


    <!--common script for all pages-->
    <script src="js/common-scripts.js"></script>

  </body>
</html>
















                 





<input class="form-control form-control-inline input-medium default-date-picker hasDatepicker" size="16" type="text" id="f_charla_informativa" value="">


  <script src="js/jquery-migrate-1.2.1.min.js"></script>
  <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
  <script src="js/jquery.scrollTo.min.js"></script>
  <script type="text/javascript" src="assets/data-tables/jquery.dataTables.js"></script>
  <script type="text/javascript" src="assets/data-tables/DT_bootstrap.js"></script>
  <script src="js/respond.min.js" ></script>
  <script src="js/common-scripts.js"></script>
  <script src="js/editable-table.js"></script>

  <script>
    jQuery(document).ready(function() {
      EditableTable.init();
    });
  </script>
  
  <script type='text/javascript'>      
    $("#save").click(function(){
  </script>




<!--  <form class="form-inline" role="form">    

          <div class="form-group">
            <label class="col-md-2 col-sm-2 control-label">Proyecto</label>
           label>
              <div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </div>

          <div class="form-group">
            <label class="col-md-3 col-sm-3 control-label">Titulo Rendicion</label>
              <div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-3">Fecha Rendicion</label>
              <div class="col-md-3 col-xs-11">
                  <div data-date-viewmode="years" data-date-format="dd-mm-yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                    <input type="text" readonly="" value="12-02-2012" size="16" class="form-control">
                    <span class="input-group-btn add-on">
                    <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                    </span>
                  </div>
              </div>
          </div>
 
          <button type="submit" class="btn btn-success">Añadir</button>
        </form> -->