  
<section class="panel">
  <header class="panel-heading">
    Expense Sheet para usuario
    </header>
      <div class="panel-body">
        <form class="form-inline" role="form">    

          <div class="form-group">
            <label class="col-md-2 col-sm-2 control-label">Proyecto</label>
              <div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </div>

          <div class="form-group">
            <label class="col-md-3 col-sm-3 control-label">Titulo Rendicion</label>
              <div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-3">Fecha Rendicion</label>
              <div class="col-md-3 col-xs-11">
                  <div data-date-viewmode="years" data-date-format="dd-mm-yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                    <input type="text" readonly="" value="12-02-2012" size="16" class="form-control">
                    <span class="input-group-btn add-on">
                    <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                    </span>
                  </div>
              </div>
          </div>
 
          <button type="submit" class="btn btn-success">Añadir</button>
        </form>
      </div>
</section>



    
<section class="panel">
  <header class="panel-heading">
  Editable Table
  </header>
  <div class="panel-body">
    <div class="adv-table editable-table ">
      <div class="clearfix">
        <div class="btn-group">
          <button id="editable-sample_new" class="btn green">
          Add New <i class="fa fa-plus"></i>
          </button>
        </div>
        <div class="btn-group pull-right">
          <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
          </button>
          <ul class="dropdown-menu pull-right">
            <li><a href="#">Print</a></li>
            <li><a href="#">Save as PDF</a></li>
            <li><a href="#">Export to Excel</a></li>
          </ul>
        </div>
      </div>
      <div class="space15"></div>
        <table class="table table-striped table-hover table-bordered" id="editable-sample">
        <thead>
          <tr>
            <th>Proyecto</th>
            <th>Actividad</th>
            <th>Fecha de Gasto</th>
            <th>Descripcion</th>
            <th>Tipo Gasto</th>
            <th>Bill Cliente</th>
            <th>Reembolso</th>
            <th>#Factura</th>
            <th>Proveedor</th> 
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
                              
        <tbody>
          <tr class="">
            <td>Jondi Rose</td>
            <td>Alfred Jondi Rose</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td class="center">super user</td>
            <td><a class="edit" href="javascript:;">Edit</a></td>
            <td><a class="delete" href="javascript:;">Delete</a></td>
          </tr>
          <tr class="">
            <td>Dulal</td>
            <td>Jonathan Smith</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td class="center">new user</td>
            <td><a class="edit" href="javascript:;">Edit</a></td>
            <td><a class="delete" href="javascript:;">Delete</a></td>
          </tr>
          <tr class="">
            <td>Sumon</td>
            <td> Sumon Ahmed</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td>1234</td>
            <td class="center">super user</td>
            <td><a class="edit" href="javascript:;">Edit</a></td>
            <td><a class="delete" href="javascript:;">Delete</a></td>
          </tr>

        </tbody>
      </table>
    </div>
  </div>
</section>

  <script src="js/jquery-migrate-1.2.1.min.js"></script>
  <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
  <script src="js/jquery.scrollTo.min.js"></script>
  <script type="text/javascript" src="assets/data-tables/jquery.dataTables.js"></script>
  <script type="text/javascript" src="assets/data-tables/DT_bootstrap.js"></script>
  <script src="js/respond.min.js" ></script>
  <script src="js/common-scripts.js"></script>
  <script src="js/editable-table.js"></script>

  <script>
    jQuery(document).ready(function() {
      EditableTable.init();
    });
  </script>

