<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                  Actividades
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class="adv-table">
                    <table  class="display table table-bordered table-striped">
                        <thead>
                            <tr >
                                <th>Proyecto / Actividades</th>
                                <th>Fecha</th>
                                <th>Descripción</th>
                                <th>Tipo de Gasto</th>
                                <th>Monto Neto</th>
                                <th>IGV</th>
                                <th>Monto Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="gradeX">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>