<section class="panel">
    <header class="panel-heading" style="padding-bottom : 17px">
        Rendición Gastos
        <span class="pull-right">
            <a id = "agregar_gasto" class="btn btn-primary pull-right btn-sm" data-toggle="modal" href="#add_gasto">
                <i class="fa fa-check-square-o"></i> Agregar
            </a>

            <a class="btn btn-success pull-right btn-sm" href="/expense/index/historico" style="margin-right : 10px">
                <i class="fa fa-list"></i> Pendientes
            </a>
        </span>
    </header>
    <div class="modal fade" id="add_gasto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="padding: 10px; ">
                    <button type="button" class="close refresh" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar Actividades</h4>
                </div>
                <div class="modal-body">
                    <div class="chat-room">
                        <aside class="left-side">
                            <div class="user-head">
                                <h5>Clientes</h5>
                            </div>
                            <ul class="chat-list">
                                <?php 
                                $equipo = $this->clientes;
                                foreach ($equipo as $data_equipo) { ?>
                                    <li>
                                        <a style="padding:5px 5px;" class="cliente" clienteid="<?php echo $data_equipo['clienteid'] ?>" unidadid="<?php echo $data_equipo['unidad_mineraid'] ?>" href="##">
                                            <i class="fa fa-rocket"></i>
                                            <span><?php echo $data_equipo['nombre_comercial'] ?></span>
                                        </a>
                                    </li>
                                    <?php
                                }
                                 ?>
                            </ul>
                        </aside>

                        <aside class="right-side">
                            <div id="proyectos"></div>
                        </aside>
                        <!-- <aside style="width:20%; " class="right-side">
                            <div id="disciplina"></div>
                        </aside> -->
                        <!-- <aside style="width:20%; " class="right-side">
                            <div id="actividades_padres"></div>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="tareas"></div>
                        </aside> -->
                    </div>
                </div>
                <div class="modal-footer " style="padding: 7px">
                    <button data-dismiss="modal" class="btn btn-default refresh" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="ingreso"></div>

<script type="text/javascript">
    $("#agregar_gasto").click();

    $("#agregar_gasto").click(function(){
        $("#proyectos").html('');
        $("#disciplina").html('');
        $("#actividades_padres").html('');
        $("#tareas").html('');
    });

    $(".refresh").click(function(){
        var numero = "<?php echo $this->numero?>";
        $("#ingreso").load("/expense/index/ingreso/numero/"+numero);
    });

    $(".cliente").click(function(){
        $("#proyectos").html('');
        $("#disciplina").html('');
        $("#actividades_padres").html('');
        $("#tareas").html('');
        var unidad_mineraid = $(this).attr('unidadid');
        var clienteid = $(this).attr('clienteid');
        var numero = "<?php echo $this->numero?>";
        $("#proyectos").load("/expense/index/proyectos/unidad_mineraid/"+unidad_mineraid+"/clienteid/"+clienteid+"/numero/"+numero);
    });
</script>