<div class="user-head">
    <h5>Tareas</h5>
</div>
  <ul class="nav nav-pills nav-stacked">
<?php
    $tareas = $this->tareas;
    foreach ($tareas as $data_tareas) { ?>
        <li>
            <a style="padding:10px 10px;" href="##">
                <span><?php echo $data_tareas['nombre'] ?></span>
                <input class="pull-right tarea_check" type = "checkbox" codigo-prop-proy="<?php echo $data_tareas['codigo_prop_proy'] ?>" proyectoid="<?php echo $data_tareas['proyectoid'] ?>" categoriaid="<?php echo $data_tareas['categoriaid'] ?>" areaid = "<?php echo $data_tareas['areaid'] ?>" revision = "<?php echo $data_tareas['revision'] ?>" actividadid = "<?php echo $data_tareas['actividadid'] ?>" cargo = "<?php echo $this->cargo ?>">
            </a>
        </li>
        <?php
    } ?>
    <script type="text/javascript">
            $('.tarea_check').click(function(event) {
                if ($(this).is(":checked")) {
                    var proyectoid = $(this).attr('proyectoid');
                    var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                    var categoriaid = $(this).attr('categoriaid');
                    var areaid = $(this).attr('areaid');
                    var cargo = $(this).attr('cargo');
                    var revision = $(this).attr('revision');
                    var actividadid = $(this).attr('actividadid');
                    url="/expense/index/guardargastopersona/codigo-prop-proy/"+codigo_prop_proy+"/proyectoid/"+proyectoid+"/categoriaid/"+categoriaid+"/areaid/"+areaid+"/cargo/"+cargo+"/revision/"+revision+"/actividadid/"+actividadid;
                    $("#loadguardar2").load(url);
                    $("#ingreso").load("/expense/index/ingreso/");
                }
            });
        </script>
</ul>
<div id="loadguardar2"></div>