
<section class="panel">
    <header class="panel-heading" style="padding-bottom : 17px">
        Hoja de Tiempo
            <span class="pull-right">
                <a id="mostrar_htpersona" class=" btn btn-success  btn-xs"> Persona</a>
                <a id="mostrar_htaprobacion" class=" btn btn-primary  btn-xs"> Aprobacion</a>
                <a id="mostrar_hthistorico" class=" btn btn-warning  btn-xs"> Historico Aprobaciones</a>
          </span> 
    </header>
</section>

<div id='htpersona'> </div>
<div id="htaprobacion" style="display: none;">
<div id="hthistorico" style="display: none;">


<script type="text/javascript">
  
        $("#mostrar_htpersona").click(function(){
        	var url = "/timesheet/aprobacion/hojatiempopersona";
            $("#htpersona").load(url);
            /*$("#htpersona").show();
            $("#htaprobacion").hide();
            $("#hthistorico").hide();*/
        });

        $("#mostrar_htaprobacion").click(function(){
            $("#htpersona").hide();
            $("#htaprobacion").show();
            $("#hthistorico").hide();
        });

        $("#mostrar_hthistorico").click(function(){
            $("#htpersona").hide();
            $("#htaprobacion").hide();
            $("#hthistorico").show();
        });

      
    </script>