<section class="panel">
  <header class="panel-heading" style="padding-bottom : 10px">
    <div><center>Lista de Hojas de Tiempo</center></div>
  </header>
</section>
<div class="inbox-body">
  <div id="uno">
    <table class="table table-hover p-table datatable-order-search">
      <thead>
        <tr>  
          <th ><center># </center></th>
          <th >Hoja Tiempo</th>
          <th >Semana</th>
          <th >Estado</th>
          <th >Facturable</th>
          <th >No Facturable</th>
          <th >Administrativa</th>
          <th >Total</th>
        </tr>
      </thead>
      <tbody>
        <?php
          $c=1;     
            foreach ($this->resultadomerge as $equipo_area){ 
              foreach ($equipo_area  as $valorsuma){ 
                
                ?>
                <tr >
                    <td ><center><?php echo $c ?></center></td>                  
                    <td>

                      <?php if ($valorsuma['estado_hojatiempo']=='A') { 
                          $color='success';
                        }

                        if ($valorsuma['estado_hojatiempo']=='O') { 
                          $color='danger';
                        }

                        if ($valorsuma['estado_hojatiempo']=='E') { 
                          $color='warning';
                        }


                        ?>

                      
                      <button id="detalletime_<?php echo $c?>" href="#modalsemana" class="btn btn-<?php echo $color?>" data-toggle="modal"  uid=<?php echo $valorsuma['uid']?> dni=<?php echo $valorsuma['dni']?> semanaid=<?php echo $valorsuma['semanaid']?>  >
                      ver detalle
                      </button>                                      

                    </td>
                    <td class="view-message "><?php echo $valorsuma['semanaid']?></td>                               
                    <td class="view-message "><?php echo $valorsuma['estado_detalle']?></td>                               
                    <td class="view-message "><?php echo $valorsuma['billable']?></td>
                    <td class="view-message "><?php echo $valorsuma['nonbillable']?></td>
                    <td class="view-message "><?php echo $valorsuma['adm']?></td>
                    <td class="view-message "><?php echo $valorsuma['h_total']?></td>
                  </tr>
                  <script type="text/javascript">
                    $(document).ready(function(){
                      $("#detalletime_<?php echo $c?>").click(function(){
                        var uid=$(this).attr('uid');
                        var dni=$(this).attr('dni');
                        var semanaid=$(this).attr('semanaid');
                        var url = "/timesheet/aprobacion/mostrarhojatiempopersona/uid/"+ uid+"/dni/"+dni+"/semanaid/"+semanaid; 
                        $("#modaltimes").load(url);                                         
                        });
                    });
                  </script>  
                   <?php $c++;
     
              }
           
         }
         ?>
      </tbody>
    </table>
  </div>
  <div id="ver"></div>
  <div class="modal fade" id="modalsemana" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content" style="width: 1250px; top: 100%; margin-left: -150px; ">
        
        <div class="modal-body">
          <div id="modaltimes"></div>
        </div>
        <div class="modal-footer">
          <button  data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modali"></div>

<script type="text/javascript">
  $(document).ready(function() {
    $(function(){
    $('select').customSelect();
    });
  });
</script>

<script>
  $(document).ready(function() {
    $('.datatable-order-search').dataTable( {
        "paging":   false,
        "ordering": true,
        "info":     true
    } );
  } );
</script>