<div class="inbox-body">
<section class="panel">
    <header class="panel-heading" style="padding-bottom : 10px">
        <div><center>Lista de pendiente de aprobación de Hojas de Tiempo para Gerente Proyecto</center></div>
    </header>
</section>
<div class="inbox-body">
    <div id="uno">
    <table class="table table-hover p-table datatable-order-search">
        <thead>
            <tr>  
                <th >#</th>    
                <th >Hoja Tiempo</th>
                <th >Nombre</th>
                <th >Semana</th>
                <th >Facturable</th>
                <th >No Facturable</th>
                <th >Administrativa</th>
                <th >Total</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $c=1;
        foreach ($this->lista_empleados_aprobar as $lista_empleados_proyecto){ 
            if ($lista_empleados_proyecto['uid']!=$this->uid_gerente){
            ?>
            <tr>
                <td><center><?php echo $c ?></center></td>   
                <td>   
                    <button id="detalleaprobaciongerente_<?php echo $c?>" href="#modalsemana_aprobaciongerente" class="btn btn-success" data-toggle="modal"  uid=<?php echo $lista_empleados_proyecto['uid']?> dni=<?php echo $lista_empleados_proyecto['dni']?> semanaid=<?php echo $lista_empleados_proyecto['semanaid']?>  >ver detalle </button>
                </td>
                <td class="view-message "><?php //echo $valorsuma['dni']
                    $equipo = explode(".", $lista_empleados_proyecto['uid']);
                    echo (ucwords($equipo[0])); echo " ";
                    echo (ucwords($equipo[1])); 
                ?></td>
                <td class="view-message "><?php echo $lista_empleados_proyecto['semanaid']?></td>
                <td class="view-message "><?php echo $lista_empleados_proyecto['facturable']?></td>
                <td class="view-message "><?php echo $lista_empleados_proyecto['nofacturable']?></td>
                <td class="view-message "><?php echo $lista_empleados_proyecto['administrativa']?></td>
                <td class="view-message "><?php echo $lista_empleados_proyecto['total']?></td>

                    </tr>
                    <script type="text/javascript">
                        $(document).ready(function(){
                          $("#detalleaprobaciongerente_<?php echo $c?>").click(function(){
                            var uid=$(this).attr('uid');
                            var dni=$(this).attr('dni');
                            var semanaid=$(this).attr('semanaid');
                            var url = "/timesheet/aprobacion/mostrardetallegerente/uid/"+ uid+"/dni/"+dni+"/semanaid/"+semanaid; 
                            $("#modalaprobaciongerente").load(url);
                            });
                        });
                    </script>  
                <?php $c++;
        }}?>
        </tbody>
    </table>
  </div>
<div id="ver"></div>
<div class="modal fade" id="modalsemana_aprobaciongerente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" style="width: 1250px; top: 100%; margin-left: -150px; ">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Aprobar Hoja de Tiempo</h4>
            </div>
            <div class="modal-body">
                <div id="modalaprobaciongerente"></div>
            </div>
            <div class="modal-footer">
                <button  type="submit" data-dismiss="modal" class="btn btn-default" >Cerrar</button>
            </div>
        </div>
    </div>
</div>
</div>
<div id="modali"></div>

<script>
  $(document).ready(function() {
    if ( $.fn.dataTable.isDataTable( '.datatable-order-search' ) ) {
      table = $('.datatable-order-search').DataTable();
    }
    else {
      table = $('.datatable-order-search').DataTable( {
        paging: false,
        ordering: true,
      } );
    }
  } );
</script>