<div class="inbox-body">
<section class="panel">
  <header class="panel-heading" style="padding-bottom : 10px">
    <div><center>Lista historica de Hojas de Tiempo del Gerente Proyecto</center></div>
  </header>
</section>
<div class="inbox-body">
  <div id="uno">
    <table class="table table-hover p-table datatable-order-search">
      <thead>
        <tr>  
          <th ><center># </center></th>
          <th >Hoja Tiempo</th>
          <th >Nombre</th>
          <th >Semana</th>
          <th >Estado</th>
          <th >Facturable</th>
          
          <!--<th >No Facturable</th>
          <th >Administrativa</th>-->
          <th >Total</th>
        </tr>
      </thead>
      <tbody>
        <?php
          $c=1;     
          
              foreach ($this->lista_empleados_aprobar  as $valorsuma){ 
                ?>
                <tr >
                    <td ><center><?php echo $c ?></center></td>                  
                    <td>
                    <?php   
                        if ($valorsuma['estado_historial']=='RGP')
                        {?>
                           <button id="detallehistorico_<?php echo $c?>" href="#modalsemana_historico" class="btn btn-danger" data-toggle="modal"  uid=<?php echo $valorsuma['uid']?> dni=<?php echo $valorsuma['dni']?> semanaid=<?php echo $valorsuma['semanaid']?>  >
                                ver detalles
                            </button> 
                        <?php }   
                        if ($valorsuma['estado_historial']=='R')
                        {?>
                               <button id="detallehistorico_<?php echo $c?>" href="#modalsemana_historico" class="btn btn-danger" data-toggle="modal"  uid=<?php echo $valorsuma['uid']?> dni=<?php echo $valorsuma['dni']?> semanaid=<?php echo $valorsuma['semanaid']?>  >
                                ver detalles
                            </button> 
                        
                        <?php
                        }   
                        if ($valorsuma['estado_historial']=='A')
                        {?>
                             <button id="detallehistorico_<?php echo $c?>" href="#modalsemana_historico" class="btn btn-success" data-toggle="modal"  uid=<?php echo $valorsuma['uid']?> dni=<?php echo $valorsuma['dni']?> semanaid=<?php echo $valorsuma['semanaid']?>  >
                                ver detalles
                            </button> <?php
                        }   
                    ?>
                                                         
                    </td>
                    <td class="view-message "><?php 
                      $equipo = explode(".", $valorsuma['uid']);
                      echo (ucwords($equipo[0])); echo " ";
                      echo (ucwords($equipo[1])); 
                      ?>
                    </td>
                    <td class="view-message "><?php echo $valorsuma['semanaid']?></td>                               
                    <td class="view-message "><?php 
                        if ($valorsuma['estado_historial']=='RGP')
                        {
                            echo "Rechazado";
                        }   
                        if ($valorsuma['estado_historial']=='R')
                        {
                            echo "Rechazado";
                        }   
                        if ($valorsuma['estado_historial']=='A')
                        {
                            echo "Aprobado";
                        }   


                    ?></td>                               
                    <td class="view-message "><?php echo $valorsuma['billable']?></td>

                    <!--<td class="view-message "><?php echo $valorsuma['nonbillable']?></td>
                    <td class="view-message "><?php echo $valorsuma['adm']?></td>-->
                    <td class="view-message "><?php echo $valorsuma['h_total']?></td>
                  </tr>
                  <script type="text/javascript">
                    $(document).ready(function(){
                      $("#detallehistorico_<?php echo $c?>").click(function(){
                        var uid=$(this).attr('uid');
                        var dni=$(this).attr('dni');
                        var semanaid=$(this).attr('semanaid');
                        var url = "/timesheet/aprobacion/mostrardetallegerente/uid/"+ uid+"/dni/"+dni+"/semanaid/"+semanaid; 
                        $("#modaltimes_historico").load(url);                                         
                        });
                    });
                  </script>  
                   <?php $c++;
     
              }
         
         ?>
      </tbody>
    </table>
  </div>
  <div id="ver"></div>
  <div class="modal fade" id="modalsemana_historico" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content" style="width: 1250px; top: 100%; margin-left: -150px; ">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Hoja de Tiempo</h4>
        </div>
        <div class="modal-body">
          <div id="modaltimes_historico"></div>
        </div>
        <div class="modal-footer">
          <button  data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modali"></div>

<script>
  $(document).ready(function() {
    if ( $.fn.dataTable.isDataTable( '.datatable-order-search' ) ) {
      table = $('.datatable-order-search').DataTable();
    }
    else {
      table = $('.datatable-order-search').DataTable( {
        paging: false,
        ordering: true,
      } );
    }
  } );
</script>