<div class="container">
        <form id="<?php  print $this->form->getname()?>"  name="<?php print $this->form->getname()?>" action="<?php print $this->form->getaction()?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-signin">
            <h2 class="form-signin-heading" style="background-color : white"><img width="200" src="/img/logo.jpg"></h2>
            <div style="text-align : center">BIENVENIDO</div>
            <div class="login-wrap">
                 <?php print $this->form->usuario ?>
                <?php print $this->form->clave ?>
                <?php print $this->form->enviar?>
            </div>
            <div style="clear:both"></div>
        </form>
        <?php if ($this->msgerror){?>
            <div style="color: red; border: 1px solid #zzz;padding-bottom: 30px;padding-top: 5px"><?php echo $this->msgerror?></div>
        <?php } ?>   
</div>