 <!-- INICIO DE LA TABLA DE AREA EN ANGULAR-->
 <div class="panel">
 <section class="panel">
 <header class="panel-heading">
 <h2>Lista de Areas</h2>



 <div class="btn-edit">
  <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show(); va.CancelarArea()">
    editar
  </button>
  <button class="btn btn-primary" ng-click="va.ShowFormArea()" ng-hide="va.formVisibilityArea; va.tableVisibilityArea" ng-show="!tableform.$visible">Agregar Area</button>
</div>
<!-- inicio del formulario para ingresar datos -->
  <div class="form-group ">
    <div ng-show="va.formVisibilityArea"  >
      <form name='validinput'>
        <div class="input-group">
          <div class="panel">
          <div class="panel-heading">
            <div class="col-xs-1" >
              <span class="input-group-addon">ID</span>
              <input type="text" class="form-control input-sm" placeholder='areaid' name='areaid' data-ng-model="va.areaid"  required data-ng-class='{error: validinput.areaid.$invalid && !validinput.$pristine}'>
            </div>
            <div class="col-xs-3" >
              <span class="input-group-addon">Nombre</span>
              <input type="text" class="form-control input-sm" placeholder='nombre' name='nombre' data-ng-model="va.nombre"  required data-ng-class='{ error: validinput.nombre.$invalid && !validinput.$pristine }'>
            </div>
            <div class="col-xs-3" >
              <span class="input-group-addon">Area Padre</span>
              <input type="text" class="form-control input-sm" placeholder='area_padre' name='area_padre' data-ng-model="va.area_padre"/>

              <!-- <select id="va.area_padre" class="form-control input-sm" placeholder='area_padre' name='area_padre' data-ng-model="va.area.areaid" data-ng-options="c.nombre for c in va.area">
              <option value="va.area_padre">Seleccione...</option>
              </select> -->
              <!-- <select class="form-control" ng-model="areapadre.nombre"
            ng-options="areapadre.areaid as areapadre.nombre for areapadre in va.area">
            </select> -->

            </div>
            <div class="col-xs-1" >
              <span class="input-group-addon">Proyecto</span>
              <!-- <input type="text" class="form-control input-sm" placeholder='isproyecto' name='isproyecto' data-ng-model="va.isproyecto"/> -->
              <select id="va.isproyecto" class="form-control input-sm" placeholder='isproyecto' name='isproyecto' data-ng-model="va.isproyecto">
                <option value="">Seleccione...</option>
                <option value="S">Si</option>
                <option value="N">No</option>
              </select>
            </div>
            <div class="col-xs-1" >
              <span class="input-group-addon">Propuesta</span>
              <!-- <input type="select" class="form-control input-sm" placeholder='ispropuesta' name='ispropuesta' data-ng-model="va.ispropuesta"/> -->
              <select id="va.ispropuesta" class="form-control input-sm" placeholder='ispropuesta' name='ispropuesta' data-ng-model="va.ispropuesta">
              <option value="">Seleccione...</option>
                <option value="S">Si</option>
                <option value="N">No</option>
              </select>
            </div>
            <div class="col-xs-1" >
              <span class="input-group-addon">Contacto</span>
              <!-- <input type="text" class="form-control input-sm" placeholder='iscontacto' name='iscontacto' data-ng-model="va.iscontacto"/> -->
              <select id="va.iscontacto" class="form-control input-sm" placeholder='iscontacto' name='iscontacto' data-ng-model="va.iscontacto">
              <option value="">Seleccione...</option>
                <option value="S">Si</option>
                <option value="N">No</option>
              </select>
            </div>
            <div class="col-xs-1" >
              <span class="input-group-addon">Comercial</span>
              <!-- <input type="text" class="form-control input-sm" placeholder='iscomercial' name='iscomercial' data-ng-model="va.iscomercial"/> -->
              <select id="va.iscomercial" class="form-control input-sm" placeholder='iscomercial' name='iscomercial' data-ng-model="va.iscomercial">
              <option value="">Seleccione...</option>
                <option value="S">Si</option>
                <option value="N">No</option>
              </select>
            </div>
            <div class="col-xs-1" >
              <span class="input-group-addon">Orden</span>
              <!-- <input type="text" class="form-control input-sm" placeholder='orden' name='orden' data-ng-model="va.orden"/> -->
              <select id="va.orden" class="form-control input-sm" placeholder='orden' name='orden' data-ng-model="va.orden">
              <option value="">Seleccione...</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
                <option value="M">M</option>
                <option value="N">N</option>
                <option value="O">O</option>
                <option value="P">P</option>
                <option value="Q">Q</option>
                <option value="R">R</option>
                <option value="S">S</option>
                <option value="T">T</option>
                <option value="U">U</option>
                <option value="V">V</option>
                <option value="W">W</option>
                <option value="X">X</option>
                <option value="Y">Y</option>
                <option value="Z">Z</option>
              </select>
            </div>
          </div>
          </div>
        </div>


      <div class="panel-heading col-md-6">
        <div class="btn-group">
          <button class="btn btn-warning" ng-click="va.GuardarArea()" data-ng-disabled='!validinput.$valid'>Guardar</button>
          <button class="btn btn-danger" ng-click="va.CancelarArea()">Cancelar</button>
        </div>
      </div>

    </form>
    </div>
  </div>
<!-- fin del formulario para ingresar datos -->


</section>
<div class="panel-heading">
<form method="POST" action="#" editable-form name="tableform" onaftersave="va.ModificarArea()" oncancel="cancel()" >

<section class="panel-heading">
<div class="btn-form" ng-show="tableform.$visible">
  <div class="btn-group">
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
    </div>
</div>



</section>


<font size=1>
<table datatable="ng" class="table table-condensed table-hover p-table dataTables_wrappe table-striped">
<div>
  <thead>
    <th style="width: 5%;">ID</th>
    <th style="width: 20%;">NOMBRE DE AREA</th>
    <th style="width: 20%;">AREA PADRE</th>
    <th style="width: 10%;">PROYECTO</th>
    <th style="width: 10%;">PROPUESTA</th>
    <th style="width: 10%;">CONTACTO</th>
    <th style="width: 10%;">COMERCIAL</th>
    <th style="width: 10%;">ORDEN</th>
  </thead>


  <tr ng-repeat="areas in va.area track by $index">
    <td>
      <span editable-text="areas.areaid" e-from="tableform" e-required>
         {{areas.areaid}}
      </span>
    </td>
    <td>
      <span editable-text="areas.nombre" e-from="tableform" e-required >
        {{areas.nombre}}
      </span>
    </td>
    <td>
      <span editable-text="areas.area_padre" e-from="tableform">
        {{areas.area_padre}}
      </span>
    </td>
    <td>
      <span editable-text="areas.isproyecto" e-from="tableform" >
        {{areas.isproyecto}}
      </span>
    </td>
    <td>
      <span editable-text="areas.ispropuesta" e-from="tableform">
        {{areas.ispropuesta}}
      </span>
    </td>
    <td>
      <span editable-text="areas.iscontacto" e-from="tableform">
        {{areas.iscontacto}}
      </span>
    </td>
    <td>
      <span editable-text="areas.iscomercial" e-from="tableform">
        {{areas.iscomercial}}
      </span>
    </td>
    <td>
      <span editable-text="areas.orden" e-from="tableform">
        {{areas.orden}}
      </span>
    </td>
  </tr>

</table>
<font>



<section class="panel-heading">
<!-- <div class="btn-form" ng-show="tableform.$visible">
    <button type="button" ng-disabled="tableform.$waiting" ng-click="va.agregarArea()" class="btn btn-primary ">Agregar Area</button>
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
</div> -->
</section>

</form>
</div>

<section class="panel-heading">
<div class="btn-edit">
    <!-- <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button> -->
</div>
</section>

</div>