 <!-- INICIO DE LA TABLA DE PRUEBA AREA EN ANGULAR-->
 <div class="panel">
 <section class="panel">
 <header class="panel-heading">
 <h2>Lista de Areas</h2>

<div class="btn-edit">
    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button>
</div>
</section>
<div class="panel-heading">
 <form method="POST" action="#" editable-form name="tableform" onaftersave="va.guardararea()" oncancel="cancel()" >


<section class="panel-heading">
<div class="btn-form" ng-show="tableform.$visible">
    <button type="button" ng-disabled="tableform.$waiting" ng-click="va.agregarArea()" class="btn btn-primary">Agregar Area</button>
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
</div>
</section>


<table datatable="ng" class="table table-condensed table-hover p-table">


<thead>
  <th style="width: 5%;">ID</th>
  <th style="width: 20%;">NOMBRE DE AREA</th>
  <th style="width: 20%;">AREA PADRE</th>
  <th style="width: 10%;">PROYECTO</th>
  <th style="width: 10%;">PROPUESTA</th>
  <th style="width: 10%;">CONTACTO</th>
  <th style="width: 10%;">COMERCIAL</th>
  <th style="width: 10%;">ORDEN</th>
</thead>

<tr ng-repeat="areas in va.area">
  <td>
    <span editable-text="areas.areaid" e-from="tableform" e-required>
       {{areas.areaid}}
    </span>
  </td>
  <td>
    <span editable-text="areas.nombre" e-from="tableform" e-required>
      {{areas.nombre}}
    </span>
  </td>
  <td>
    <span editable-text="areas.area_padre" e-from="tableform">
      {{areas.area_padre}}
    </span>
  </td>
  <td>
    <span editable-text="areas.isproyecto" e-from="tableform" >
      {{areas.isproyecto}}
    </span>
  </td>
  <td>
    <span editable-text="areas.ispropuesta" e-from="tableform">
      {{areas.ispropuesta}}
    </span>
  </td>
  <td>
    <span editable-text="areas.iscontacto" e-from="tableform">
      {{areas.iscontacto}}
    </span>
  </td>
  <td>
    <span editable-text="areas.iscomercial" e-from="tableform">
      {{areas.iscomercial}}
    </span>
  </td>
  <td>
    <span editable-text="areas.orden" e-from="tableform">
      {{areas.orden}}
    </span>
  </td>
</tr>

</table>

<section class="panel-heading">
<div class="btn-form" ng-show="tableform.$visible">
    <button type="button" ng-disabled="tableform.$waiting" ng-click="va.agregarArea()" class="btn btn-primary ">Agregar Area</button>
    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-success">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-danger">cancelar</button>
</div>
</section>

</form>
</div>

<section class="panel-heading">
<div class="btn-edit">
    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button>
</div>
</section>


</div>

<style type="text/css">
/*.dataTables_wrapper .dataTables_paginate .paginate_button {*/
    /*box-sizing: border-box;*/
    /*border-bottom: border;*/
    /*display: inline-block;*/
    /*min-width: 1.5em;*/
    /*padding: 0.5em 1em;*/
    /*margin-left: 2px;*/
    /*text-align: center;*/
    /*text-decoration: none !important;*/
    /*cursor: pointer;*/
    /*color: #333 !important;*/
    /*border: 1px solid transparent;*/
    /*border-radius: 2px;*/
}
</style>