 <!-- INICIO DE LA TABLA DE PRUEBA AREA EN ANGULAR-->
 <div class="panel">
 <header class="panel-heading">
 <h2>Lista de Areas</h2>
 <div class="btn-edit">
    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button>
</div>
<div class="btn-form" ng-show="tableform.$visible">

    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-primary">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-default">cancelar</button>
</div>

<div class="panel-body">

 <form method="POST" action="#" editable-form name="tableform" onaftersave="va.guardararea()" oncancel="cancel()" >
<table class=" table table-hover p.table">

<tr ng-repeat="areas in va.area">
  <td>
    <span editable-text="areas.areaid" e-from="tableform">
       {{areas.areaid}}
    </span>
  </td>
  <td>
    <span editable-text="areas.nombre" e-from="tableform">
      {{areas.nombre}}
    </span>
  </td>
</tr>

</table>
 <div class="btn-edit">
    <button type="button" class="btn btn-default" ng-show="!tableform.$visible" ng-click="tableform.$show()">
        editar
    </button>
</div>
<div class="btn-form" ng-show="tableform.$visible">

    <button type="submit" ng-disabled="tableform.$waiting" class="btn btn-primary">guardar</button>
    <button type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-default">cancelar</button>
</div>
</form>
</div>
</header>
</div>