    <aside class="profile-nav col-lg-3">
        <section class="panel">
            <div class="user-heading round">
                <a href="#">                            
                <img src="/img/fotos-anddes/<?php echo $this->lista_persona['dni'];?>.jpg" alt="">
                </a>
                <h1><?php echo $this->lista_persona['ape_paterno'];echo " ";echo $this->lista_persona['ape_materno'];echo " ";echo $this->lista_persona['nombres']?></h1>
                <p><?php echo $this->lista_persona['email_anddes'];?></p>
            </div>

            <ul class="nav nav-pills nav-stacked">
	            <li><a href="/rrhh/perfil/ver/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-user"></i> Perfil</a></li>
	            <li><a href="#"> <i class="fa fa-calendar"></i> Actividades Recientes <span class="label label-danger pull-right r-activity">9</span></a></li>
	            <li  class="active"><a href="/rrhh/perfil/editar/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Editar perfil</a></li>
	            <li  class="active"><a href="/rrhh/perfil/cambiarpass/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Cambio Contrasena</a></li>
            </ul>

        </section>
                   
    </aside>
    <aside class="profile-info col-lg-9">   
    <section>
        <div class="panel panel-primary">
            <div class="panel-heading"> Cambiar Nueva Contraseña </div>
                <div class="panel-body">
                    <form action="/rrhh/perfil/cambiarpass/dni/<?php echo $this->lista_persona['dni'];?>" method="post" id="formu" role="form">
                             
                        <div class="form-group">
                            <label  class="col-lg-4 control-label">Nueva Contraseña</label>
	                            <div class="col-lg-6">
	                                <input type="password" class="form-control" id="newpassword" name="newpassword" placeholder=" ">
	                            </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label  class="col-lg-4 control-label">Repetir Nueva Contraseña</label>
                                <div class="col-lg-6">
                                     <input type="password" class="form-control" id="renewpassword" name="renewpassword" placeholder=" ">
                                </div>
                            </div>
                    
                            <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                            <button id="pass" type="submit" class="btn btn-info">Guardar</button>
                            <a type="button" href="/rrhh/perfil/ver/dni/<?php echo $this->lista_persona['dni'];?>" class="btn btn-default">Cancelar</a>
                        	</div>
                    	</div>
            	</form>
			</div>
        </div>
    </section>
    </aside>


<div id="passw"></div>


<script type="text/javascript">
/*    $("#formu").submit(function(){
      var dni="<?php echo $this->lista_persona;?>";
      var newpassword=$("#newpassword").val();
      var renewpassword=$("#renewpassword").val();
           //params = { 'dni': dni,'newpassword': newpassword,'renewpassword': renewpassword }
           $.ajax({
               type: 'POST',
               url: '/rrhh/perfil/cambiarpass/dni'+dni+'/newpassword/'+newpassword+'/renewpassword/'+renewpassword,
                  alert(url);       
               data: $(this).serialize(),
               success: function(data) {  
                  alert(dni);
                  alert(newpassword);
                  alert(renewpassword);
               $("#passw").html(data);
                 
              }
          }); 
    });*/

</script>
