    <aside class="profile-nav col-lg-3">
        <section class="panel">
            <div class="user-heading round">
                <a href="#">                            
                <img src="/img/fotos-anddes/<?php echo $this->lista_persona['dni'];?>.jpg" alt="">
                </a>
                <h1><?php echo $this->lista_persona['ape_paterno'];echo " ";echo $this->lista_persona['ape_materno'];echo " ";echo $this->lista_persona['nombres']?></h1>
                <p><?php echo $this->lista_persona['email_anddes'];?></p>
            </div>

            <ul class="nav nav-pills nav-stacked">
	            <li><a href="/rrhh/perfil/ver/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-user"></i> Perfil</a></li>
	            <li><a href="#"> <i class="fa fa-calendar"></i> Actividades Recientes <span class="label label-danger pull-right r-activity">9</span></a></li>
	            <li  class="active"><a href="/rrhh/perfil/editar/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Editar perfil</a></li>
	            <li  class="active"><a href="/rrhh/perfil/cambiarpass/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Cambio Contrasena</a></li>
            </ul>

        </section>
                   
    </aside>
    <aside class="profile-info col-lg-9">
        <section class="panel">
        <div class="bio-graph-heading">
            Curriculum Vitae
        </div>
        <div class="room-box">
            <h5 class="text-primary"><a href="chat_room.html">Resumen</a></h5>
                <p>Welcome to our world of marketing. Lorem ipsum dolor sit amet</p>
                <p>Welcome to our world of marketing. Lorem ipsum dolor sit amet</p>
                <p>Welcome to our world of marketing. Lorem ipsum dolor sit amet</p>         
                
        </div>
        </section>
        <section class="panel">
            <header class="panel-heading tab-bg-dark-navy-blue">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a data-toggle="tab" href="#experiencia">
                                Experiencia
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#estudios">
                               Estudios
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#perfeccionamiento">
                               Perfeccionamiento
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#conocimientos">
                               Conocimientos
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#certificaciones">
                               Certificaciones
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#idiomas">
                               Idiomas
                            </a>
                        </li>
                    </ul>
            </header>
            <div class="panel-body">
                <div class="tab-content tasi-tab">
                    <div id="experiencia" class="tab-pane active">
                        <h4 class="pro-d-head">Product Description</h4>
                                <p> Praesent ac condimentum felis. Nulla at nisl orci, at dignissim dolor, The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. </p>
                                <p> Praesent ac condimentum felis. Nulla at nisl orci, at dignissim dolor, The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. </p>
                        </div>
                        <div id="estudios" class="tab-pane">
                        <article class="media">
                                <a class="pull-left thumb p-thumb">
                                    <img src="img/avatar-mini.jpg">
                                </a>
                                <div class="media-body">
                                    <a href="#" class="cmt-head">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a>
                                    <p> <i class="fa fa-time"></i> 1 hours ago</p>
                                </div>
                                <p><span class="text-muted">Admin :</span> Kally Brash | <span class="text-muted">Member :</span> 13 | <span class="text-muted">Last Activity :</span> 15 min ago</p>
                        </article>
                        <article class="media">
                                <a class="pull-left thumb p-thumb">
                                    <img src="img/avatar-mini2.jpg">
                                </a>
                                <div class="media-body">
                                    <a href="#" class="cmt-head">Nulla vel metus scelerisquejjjjjjjjjjjjjjjjj
                                    jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjddddddddddddddddddd
                                    ddddddddddddddddddddddddddddddddddddd                                    
                                    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
                                    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
                                    dddddddddddddddddddddddddddddddddddd
                                     ante sollicitudin commodo</a>
                                    <p> <i class="fa fa-time"></i> 23 mins ago</p>
                                    </div>
                        </article>
                        <article class="media">
                                    <a class="pull-left thumb p-thumb">
                                        <img src="img/avatar-mini3.jpg">
                                    </a>
                                    <div class="media-body">
                                        <a href="#" class="cmt-head">Donec lacinia congue felis in faucibus. </a>
                                        <p> <i class="fa fa-time"></i> 15 mins ago</p>
                                    </div>
                        </article>
                    </div>

                </div>
            </div>
        </section>

        <!--Funciones Responsabilidades-->
        <section class="panel">
            <header class="panel-heading tab-bg-dark-navy-blue">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a data-toggle="tab" href="#experiencia">
                                Funciones Responsabilidades
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#estudios">
                               Competencias
                            </a>
                        </li>

                    </ul>
            </header>
            <div class="panel-body">
                <div class="tab-content tasi-tab">
                    <div id="experiencia" class="tab-pane active">
                        <h4 class="pro-d-head">Product Description</h4>
                                <p> Praesent ac condimentum felis. Nulla at nisl orci, at dignissim dolor, The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. </p>
                                <p> Praesent ac condimentum felis. Nulla at nisl orci, at dignissim dolor, The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. The best product descriptions address your ideal buyer directly and personally. </p>
                        </div>
                        <div id="estudios" class="tab-pane">
                        <article class="media">
                                <a class="pull-left thumb p-thumb">
                                    <img src="img/avatar-mini.jpg">
                                </a>
                                <div class="media-body">
                                    <a href="#" class="cmt-head">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a>
                                    <p> <i class="fa fa-time"></i> 1 hours ago</p>
                                </div>
                                <p><span class="text-muted">Admin :</span> Kally Brash | <span class="text-muted">Member :</span> 13 | <span class="text-muted">Last Activity :</span> 15 min ago</p>
                        </article>
                        <article class="media">
                                <a class="pull-left thumb p-thumb">
                                    <img src="img/avatar-mini2.jpg">
                                </a>
                                <div class="media-body">
                                    <a href="#" class="cmt-head">Nulla vel metus scelerisquejjjjjjjjjjjjjjjjj
                                    jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjddddddddddddddddddd
                                    ddddddddddddddddddddddddddddddddddddd                                    
                                    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
                                    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
                                    dddddddddddddddddddddddddddddddddddd
                                     ante sollicitudin commodo</a>
                                    <p> <i class="fa fa-time"></i> 23 mins ago</p>
                                    </div>
                        </article>
                        <article class="media">
                                    <a class="pull-left thumb p-thumb">
                                        <img src="img/avatar-mini3.jpg">
                                    </a>
                                    <div class="media-body">
                                        <a href="#" class="cmt-head">Donec lacinia congue felis in faucibus. </a>
                                        <p> <i class="fa fa-time"></i> 15 mins ago</p>
                                    </div>
                        </article>
                    </div>

                </div>
            </div>
        </section>


        <!--Evaluaciones-->
        <section class="panel">
            <div class="room-box">
            <h5 class="text-primary"><a href="chat_room.html">Evaluaciones</a></h5>
                <p>Welcome to our world of marketing. Lorem ipsum dolor sit amet
                Welcome to our world of marketing. Lorem ipsum dolor sit amet
                Welcome to our world of marketing. Lorem ipsum dolor sit amet</p>
            <article class="media">
                <a class="pull-left thumb p-thumb">
                    <img src="img/avatar-mini.jpg">
                </a>
                <div class="media-body">
                    <a href="#" class="cmt-head">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a>
                    <p> <i class="fa fa-time"></i> 1 hours ago</p>
                </div>
                <p><span class="text-muted">Admin :</span> Kally Brash | <span class="text-muted">Member :</span> 13 | <span class="text-muted">Last Activity :</span> 15 min ago</p>
            </article>
            </div>

        </section>

    </aside>