<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
      <!--right slidebar-->
      <link href="css/slidebars.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />

  </head>

  <body>

  <section id="container" class="">

      <div class="row">
                  <aside class="profile-nav col-lg-3">
                      <section class="panel">
                          <div class="user-heading round"> 
                              <a href="#">
                                  <img src="/img/fotos-anddes/<?php echo $this->lista_persona['dni'];?>.jpg" alt="">
                              </a>
                              <h1><?php echo $this->lista_persona['ape_paterno'];echo " ";echo $this->lista_persona['ape_materno'];echo " ";echo $this->lista_persona['nombres']?></h1>
                             
                              <p><?php echo $this->lista_persona['email_anddes'];?></p>
                          </div>

                          <ul class="nav nav-pills nav-stacked">
                              <li class="active"><a href="#"> <i class="fa fa-user"></i> Perfil</a></li>
                              <li><a href="#"> <i class="fa fa-calendar"></i> Actividades Recientes <span class="label label-danger pull-right r-activity">9</span></a></li>
                              <li><a href="/rrhh/perfil/editar/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Editar perfil</a></li>

                              <li  class="active"><a href="/rrhh/perfil/cambiarpass/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Cambio Contrasena</a></li>
                              <li  class="active"><a href="/rrhh/perfil/curriculum/dni/<?php echo $this->lista_persona['dni'];?>"> <i class="fa fa-edit"></i> Curriculum Vitae</a></li>
                              <li  class="active"><a href="#"> <i class="fa fa-edit"></i> Evaluaciones</a></li>
                              <li  class="active"><a href="#"> <i class="fa fa-edit"></i> Capacitaciones</a></li>
                              <li  class="active"><a href="#"> <i class="fa fa-edit"></i> Proyectos</a></li>

                          </ul>

                      </section>
                  </aside>
                  <aside class="profile-info col-lg-9">

               <!--        <section class="panel">

                          <form>
                              <textarea placeholder="¿Qué hay en tu mente hoy?" rows="2" class="form-control input-lg p-text-area"></textarea>
                          </form>
                          <footer class="panel-footer">
                              <button class="btn btn-danger pull-right">Post</button>
                              <ul class="nav nav-pills">
                                  <li>
                                      <a href="#"><i class="fa fa-map-marker"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class="fa fa-camera"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class=" fa fa-film"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class="fa fa-microphone"></i></a>
                                  </li>
                              </ul>
                          </footer>

                      </section> -->

                      <section class="panel">
                          <div class="bio-graph-heading">
                              Perfil : <?php echo $this->lista_persona['ape_paterno'];echo " ";echo $this->lista_persona['ape_materno'];echo " ";echo $this->lista_persona['nombres']?>
                          </div>
                          <div class="panel-body bio-graph-info">
                              <h1>Datos Personales</h1>
                              <div class="row">
                                  <div class="bio-row">
                                      <p><span>Nombres </span>: <?php echo $this->lista_persona['nombres']?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Apellidos </span>: <?php echo $this->lista_persona['ape_paterno'];echo " ";echo $this->lista_persona['ape_materno'] ?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Estado Civil </span>:
                                        <?php
                                          switch ($this->lista_persona['estado_civil']) {
                                              case "S":
                                                  echo "Soltero";
                                                  break;
                                              case "C":
                                                  echo "Casado";
                                                  break;
                                              case "V":
                                                  echo "Viudo";
                                                  break;
                                              case "D":
                                                  echo "Divorciado";
                                                  break;
                                          }
                                        ?>                                     
                                  </div>
                                  <div class="bio-row">

                                      <p><span>Cumpleaños</span>: <?php echo $this->lista_persona['fecha_nacimiento'];?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Ocupacion </span>: <?php echo $this->lista_persona['ocupacion'];?></p>

                                  </div>
                                  <div class="bio-row">
                                      <p><span>Email </span>: <?php echo $this->lista_persona['email_personal'];?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Celular  </span>: <?php echo $this->lista_persona['celular'];?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Telefono </span>: <?php echo $this->lista_persona['telefono'];?></p>
                                  </div>
                              </div>
                          </div>
                      </section>
                      <section>
                          <div class="row">
                              <div class="col-lg-6">
                                  <div class="panel">
                                      <div class="panel-body">

                                          <div class="bio-desk">
                                              <h4 class="red">Anexo/Direccion</h4>
                                              <p>Anexo : <?php echo $this->lista_persona['anexo'];?></p>
                                              <p>Direccion : <?php echo $this->lista_persona['direccion'];?></p>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-lg-6">
                                  <div class="panel">
                                      <div class="panel-body">

                                          <div class="bio-desk">
                                              <h4 class="terques">Condicion </h4>
                                              <p>Condicion : 
                                                    <?php
                                                      switch ($this->lista_persona['condicion']) {
                                                          case "C":
                                                              echo "Contratado";
                                                              break;
                                                          case "P":
                                                              echo "Permanente";
                                                              break;
                                                          case "I":
                                                              echo "Indefinido";
                                                              break;                                                        
                                                      }
                                                    ?> 
                                              <p>Estado: 
                                                    <?php
                                                      switch ($this->lista_persona['estado']) {
                                                          case "A":
                                                              echo "Activo";
                                                              break;
                                                          case "I":
                                                              echo "Inactivo";
                                                              break;
                                                          case "E":
                                                              echo "Eliminado";
                                                              break;                                                        
                                                      }
                                                    ?> 
                                              </p>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                    
                          </div>
                      </section>
                  </aside>
      </div>


      <!-- Right Slidebar end -->

  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="js/respond.min.js" ></script>

  <!--right slidebar-->
  <script src="js/slidebars.min.js"></script>

    <!--common script for all pages-->
    <script src="js/common-scripts.js"></script>

  <script>

      //knob
      $(".knob").knob();

  </script>


  </body>
</html>
