    <div id="Proyecto_Total">
    <table class="table table-hover p-table">
          <thead>
            <tr>  
               <th style="width: 10%;">Código</th>
              <th style="width: 20%;">Cliente</th>
              <th style="width: 35;">Nombre</th>
              <th style="width: 10%;">Gerente de Proyecto</th>
              <th style="width: 15%;">Estado</th>
              <th style="width: 10%;">Acciones</th>
            </tr>
          </thead>
          <?php
            $c=0;

          foreach ($this->lista_buscar as $lista) {
             
            ?>                   
            <tr>
          <td class="p-name">
                
                <a href="#"><?php echo $lista['proyectoid']; ?></a>  
              </td>
                <td>
                 <?php
                 //$propuestaid=$lista['propuestaid'];
                 //$revision=$lista['revision'];
                 //$codigo=$lista['codigo_prop_proy'];

                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    //$buscanombre_cliente=$buscacliente->_getClientexPropuestaxRevisionxCodigo($propuestaid,$revision,$codigo);
                    //print_r($buscanombre_cliente[0]['nombre_comercial']);
                    //print_r($lista);
                    $buscanombre_cliente=$buscacliente->_getClientexIndice($lista['clienteid']);
                    
                    if ($buscanombre_cliente)
                    {
                      print_r($buscanombre_cliente[0]['nombre_comercial']);
                    }
                    else
                    {
                      echo "< None >";
                    }

                ?>  
              </td>
              <td>
                <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
              </td>
              <td>
                <a href="#"><?php echo $lista['gerente_proyecto']; ?></a>
              </td>

              <td>
                                 
                  <div class="btn-group">
                      <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                      <ul role="menu" class="dropdown-menu">
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cerrado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>
                                      
                      </ul>
                  </div>
              </td>

                <td>
                 <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i></a>
                <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> </a>
                <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
              </td>

              </tr>                            
              <?php $c++;}?>
    </table>
  </div>