<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h5> Time Sheet Semana <?php echo $this->semanalabor; echo ": ";?></h5><?php
         print_r($this->diassemana[7]); echo "-"; print_r($this->diassemana[13]);?>
        <span class="pull-right">
          <a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G" id="mostrar_perdida" class=" btn btn-success  btn-xs"> Enviar</a>
          <input class=" btn btn-success  btn-xs" type="button" id="agregar" value="Agregar fila" />
        </span>
      </header>
        <table class="table table-striped table-advance table-hover" id="tabla">
          <thead>
            <tr>
                <th>  </th>
                <th style="width:30%;"><center>Proyecto / Tarea</center></th>
                <th style="width:10%;"><center>lunes</center></th>
                <th style="width:10%;"><center>martes</center></th>
                <th style="width:10%;"><center>miercoles</center></th>
                <th style="width:10%;"><center>jueves</center></th>
                <th style="width:10%;"><center>viernes</center></th>
                <th style="width:10%;"><center>sabado</center></th>
                <th style="width:10%;"><center>domingo</center></th>
                
            </tr>
          </thead>
          <tbody>
     
            <tr class="fila-base" >
                <td  class="eliminar"><button  class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button></td>
                <td  ><select class="form-control input-sm m-bot15">
                                              <option>Option 1</option>
                                              <option>Option 2</option>
                                              <option>Option 3</option>
                                          </select></td>
                <td ><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                 <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                
            </tr>

          </tbody>
        </table>
    </section>
  </div>
</div>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<title>Documento sin título</title> 
<script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script> 
<script type="text/javascript" src="/js/jquery.ztree.all-3.5.js"></script> 
<script type="text/javascript" src="/droptree.js"></script> 
<link href="droptree_style.css" rel="stylesheet" /> 
<link href="zTreeStyle/zTreeStyle.css" rel="stylesheet" /> 
</head> 
<script type="text/javascript"> 
$(document).ready(function(){ 
$("#simple-select").droptree({ 
transition:'mfs', 
items:[{code:'man',name:'Hombre'}, 
{code:'woman',name:'Mujer'}, 
{code:'yao',name:'El monstruo'} 
]} 
); 


$("#simple_input").droptree({items:[ 
{code:'root',name:'El nodo raíz',pid:-1}, 
{code:'man',name:'Hombres',pid:'root'}, 
{code:'woman',name:'Mujeres',pid:'root'}, 
{code:'man1',name:'Los hombres de 1',pid:'man'}, 
{code:'man2',name:'Hombre 2',pid:'man'}, 
{code:'woman1',name:'Mujer 1',pid:'woman'} 
], 
transition:"ztree" 
}); 
}); 

</script> 
</head> 
<body> 

<div class="wrap" style="width:600px; margin:0 auto; margin-top:200px"> 
<div style="width:60px;float:left"> 
<select id="simple-select" name="simple-select"> 
<option value="opt1">option 1</option> 
<option value="opt2">option 2</option> 
<option value="opt3" selected="selected">option 3</option> 
</select> 
</div> 

<div style="float:right"> 
<input type="text" name="simple_input" id="simple_input" value="man2"/> 
</div> 

</div> 
</body> 
</html> 


<script type="text/javascript">
 
$(function(){
  // Clona la fila oculta que tiene los campos base, y la agrega al final de la tabla
  $("#agregar").on('click', function(){
    $("#tabla tbody tr:eq(0)").clone().removeClass('fila-base').appendTo("#tabla tbody");
  });
 
  // Evento que selecciona la fila y la elimina 
  $(document).on("click",".eliminar",function(){
    var parent = $(this).parents().get(0);
    $(parent).remove();
  });
});


</script>

    