<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h5> Time Sheet Semana <?php echo $this->semanalabor; echo ": ";?></h5><?php
         print_r($this->diassemana[7]); echo "-"; print_r($this->diassemana[13]);?>
        <span class="pull-right">
          <a href="/propuesta/index/cambiar/propuestaid/<?php echo $lista['propuestaid']?>/revision/<?php echo $lista['revision']?>/codigo/<?php echo $lista['codigo_prop_proy']?>/estado/G" id="mostrar_perdida" class=" btn btn-success  btn-xs"> Enviar</a>
          <input class=" btn btn-success  btn-xs" type="button" id="agregar" value="Agregar fila" />
        </span>
      </header>
        <table class="table table-striped table-advance table-hover" id="tabla">
          <thead>
            <tr>
                <th>  </th>
                <th>  </th>
                <th style="width:30%;"><center>Proyecto / Tarea</center></th>
                <th style="width:10%;"><center>lunes</center></th>
                <th style="width:10%;"><center>martes</center></th>
                <th style="width:10%;"><center>miercoles</center></th>
                <th style="width:10%;"><center>jueves</center></th>
                <th style="width:10%;"><center>viernes</center></th>
                <th style="width:10%;"><center>sabado</center></th>
                <th style="width:10%;"><center>domingo</center></th>
                
            </tr>
          </thead>
          <tbody>
     
            <tr class="fila-base" >
                <td ><a class="btn btn-default btn-sm " data-toggle="modal" href="#myModal9">
                                  Añadir
                              </a></td>
                <td  class="eliminar"><button  class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button></td>
                <td>  </td>
                <td ><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                 <td><input id="buscar_propuesta" type="text" class="input-sm form-control"> </td>
                
            </tr>

          </tbody>
        </table>
    </section>
  </div>
</div>




<div class="modal fade modal-dialog-center top-modal-with-space" id="myModal9" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="">
          <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Añadir Contacto</h4>

   



              </div>
              <div class="modal-body">
               <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="cliente" class="col-lg-2 col-sm-2 control-label">Cliente</label>
                        <div class="col-lg-10">
                        <select id="clienteid" class="form-control m-bot4 col-lg-10">
          <option>Cliente</option>
          <?php 
            $bdcliente = new Admin_Model_DbTable_Cliente();
            $listcliente=$bdcliente->_getClienteAllOrdenado();
            foreach ($listcliente as $cli) {?>
            <option value="<?php echo $cli['clienteid']?>"><?php echo strtoupper($cli['nombre_comercial'])?></option>
          <?php }?>
        </select>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="unidad" class="col-lg-3 col-sm-3 control-label">Area</label>
                        <div class="col-lg-9">
                        <select id="areaid" class="form-control m-bot1 col-lg-5">
          <option>Area</option>
          <?php 
            $bdarea = new Admin_Model_DbTable_Area();
            $listarea=$bdarea->_getAreaxContactoComercial();
            foreach ($listarea as $area) {?>
            <option value="<?php echo $area['areaid']?>"><?php echo strtoupper($area['nombre'])?></option>
          <?php }?>
        </select>
                        </div>
                    </div>

                  <div class="form-group">
                        <label for="nombre_contacto" class="col-lg-4 col-sm-4 control-label">Nombre y Apellido</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="nombre_contacto" >
                        </div>
                    </div>
                

                    <div class="form-group">
                        <label for="celular" class="col-lg-4 col-sm-4 control-label">Celular</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="numero" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="celular" class="col-lg-4 col-sm-4 control-label">Telefono</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="telefono" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="celular" class="col-lg-4 col-sm-4 control-label">Anexo</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="anexo" >
                        </div>
                    </div>

                 

                    <div class="form-group">
                        <label for="relacion" class="col-lg-4 col-sm-4 control-label">Correo</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="correo" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="relacion" class="col-lg-4 col-sm-4 control-label">Direccion</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="direccion" >
                            <div id="direccion_valida"></div>

                        </div>
                    </div>

                    </form>
                  

              </div>
              <div class="modal-footer">
                  <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                  <button id="guardar_contacto" class="btn btn-warning" type="button"> Guardar</button>
              </div>
          </div>
      </div>
  </div>
</div>



<script type="text/javascript">
 
$(function(){
  // Clona la fila oculta que tiene los campos base, y la agrega al final de la tabla
  $("#agregar").on('click', function(){
    $("#tabla tbody tr:eq(0)").clone().removeClass('fila-base').appendTo("#tabla tbody");
  });
 
  // Evento que selecciona la fila y la elimina 
  $(document).on("click",".eliminar",function(){
    var parent = $(this).parents().get(0);
    $(parent).remove();
  });
});


</script>

    