        <?php  $historialresumen=$this->historialresumen; ?>

        <?php 
        foreach ($historialresumen as $proyect) {
           
            // echo $proyect['revision_propuesta'];
            // echo $proyect['proyectoid'];
            // echo $proyect['revision_hojaresumen'];
            // echo $proyect['codigo_prop_proy'];       
        
          ?>          
          <div id="accordian">

              <ul>
                <li>           

                  <a  class="col-sm-2" class="btn btn-success" href="/proyecto/index/imphojaresumen/codigo_prop_proy/<?php echo $proyect['codigo_prop_proy']?>/proyectoid/<?php echo $proyect['proyectoid'] ?>/revision_hojaresumen/<?php echo $proyect['revision_hojaresumen'] ?>/revision_propuesta/<?php echo $proyect['revision_propuesta'] ?>/propuestaid/<?php echo $proyect['propuestaid'] ?>" id="imprimir">Imprimir</a>
                    
                  <h3><span class="icon-dashboard"></span><?php echo $proyect['nombre_proyecto'];echo "---Revision de Hoja Resumen ";echo $proyect['revision_hojaresumen'];?></h3>
                 
  
                  <ul>
                <!-- <section id="container" class=""> -->
                  <table style="width:100%; margin-bottom:20px;" border=" 1px">
                 
                      <tr style='background:rgba(0, 105, 173, 1)'>
                        <th colspan='6' style='font-size:12px; '>Informacion</th>
                      
                      </tr>


                          <tr>                          
                              <td class="col-sm-2" rowspan="2" >Nombre del Proyecto</td>  
                              <td class="col-sm-6" colspan="3" rowspan="2" ><?php echo $proyect['nombre_proyecto'] ?></td>                            
                              <td  class="col-sm-2">     
                                <span>N de Proyecto</span> 
                              </td>
                          
                              <td class="col-sm-3">
                                <span><?php echo $proyect['proyectoid'] ?></span>                          
                              </td> 
                          </tr>

                          <tr>                          
                              <td  class="col-sm-2">                           
                                
                                      <span>N de Propuesta</span>            
                                 
                              </td>
                          
                              <td class="col-sm-3"> 
                                  <span><?php echo $proyect['propuestaid'] ?></span>                        
                              </td> 
                          </tr>

                          <tr>                               
                              <td class="col-sm-2 "  >Descripcion del Proyecto</td>  
                              <td colspan="5" class="col-sm-10 ">
                                  <span><?php echo $proyect['descripcion'] ?></span>            
                              </td>
                          </tr>

                          <tr>                       
                            
                            <td class="col-sm-2">                                                    
                                <span>Propietario</span> 
                            </td>
                                <td class="col-sm-4">                                             
                                    compania    
                                </td>                             
                             
                                <td  colspan="2" rowspan="3" class="col-sm-3">
                                    <center><p><span>Planificado</span> </p></center>                            
                                </td>                             
                            
                                <td colspan="2" rowspan="3" class="col-sm-3">
                                    <center><p><span>Real</span> </p></center>
                                </td>                           
                          </tr>    

                          <tr>                       
                            
                            <td class="col-sm-2">                                             
                              <span>Unidad Minera</span> 
                            </td>

                               <td class="col-sm-4">                                               
                                        <?php echo $proyect['nombre'] ?>
                              </td>                 
                          </tr>

                          <tr>  
                            <td class="col-sm-2">                   
                              <span>Tipo de Servicio</span>
                            </td>
                            <td class="col-sm-4">                                                               
                                    geotecnia 
                            </td>                             
                                            
                          </tr>  

                          <tr>
                                <td  class="col-sm-2">                                                                                    
                                  Gerente del Proyecto                                  
                               </td>                           
                         
                                <td class="col-sm-4">
                                  <select  class="form-control" class="gerente_proyecto" name="gerente_proyecto" >
                                    <option value="<?php echo $proyect['gerente_proyecto'] ?>"> <?php echo $proyect['gerente_proyecto'] ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $gerente_proyecto){
                                    ?>
                                        <option value="<?php echo $gerente_proyecto['uid']?>"><?php echo $gerente_proyecto['uid']?></option>
                                     <?php } ?>
                                  </select> 
                                </td>

                                <td rowspan="2" class="col-sm-1">
                                  Fecha de Inicio
                                </td>
                                                        
                                <td class="col-sm-2" rowspan="2" >
                                    <input class="form-control default-date-picker " id="fecha_inicio_planificado" value="<?php echo $proyect['fecha_inicio_planificado'] ?>" type="text" > 

                                </td>
                                                 
                                <td class="col-sm-1" rowspan="2" >
                                   Fecha de Cierre
                                </td>                            
                                <td class="col-sm-2" rowspan="2" >
                                  <input class="form-control default-date-picker " id="fecha_inicio_real" value="<?php echo $proyect['fecha_inicio_real'] ?>" type="text" > 
                                </td>
                         
                          </tr>

                          <tr>
                                <td  class="col-sm-2">                                                                                   
                                    Jefe del Proyecto 1 
                                </td>                          
                         
                                <td class="col-sm-4">
                                  <select  class="form-control" class="jefe_proyecto1" name="jefe_proyecto1" >
                                    <option  value="<?php echo $proyect['jefe_proyecto1'] ?>"> <?php echo $proyect['jefe_proyecto1'] ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $jefe_proyecto1){
                                    ?>
                                        <option value="<?php echo $jefe_proyecto1['uid']?>"><?php echo $jefe_proyecto1['uid']?></option>
                                     <?php } ?>
                                  </select> 
                                                      
                                </td>
                          </tr>      

                          <tr>                      
                                <td  class="col-sm-2"  >                                                           
                                      Jefe del Proyecto 2 
                                </td>
                             
                                <td class="col-sm-4"  > 
                                  <select  class="form-control" class="jefe_proyecto2" name="jefe_proyecto1">
                                    <option  value="<?php echo $proyect['jefe_proyecto1'] ?>"><?php echo $proyect['jefe_proyecto2'] ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $jefe_proyecto2){
                                    ?>
                                      <option value="<?php echo $jefe_proyecto2['uid']?>"><?php echo $jefe_proyecto2['uid']?></option>
                                    <?php } ?>
                                  </select> 
                                                                                                   
                                                      
                                  
                                </td> 

                                <td class="col-sm-1" rowspan="2" >                                                        
                                      Fecha de Inicio 
                                </td>                           
                      
                                <td class="col-sm-2" rowspan="2" >
                                  <input class="form-control default-date-picker " id="fecha_fin_planificado" value="<?php echo $proyect['fecha_fin_planificado'] ?>" type="text" >                                  
                                </td>                           
                            
                                <td class="col-sm-1" rowspan="2" >                                                                          
                                      Fecha de Cierre 
                                </td>                             
                            
                                <td class="col-sm-2" rowspan="2" >
                                  <input class="form-control default-date-picker " id="fecha_fin_real" value="<?php echo $proyect['fecha_fin_real'] ?>" type="text">

                                </td>        
                          </tr>

                          <tr>                      
                                <td  class="col-sm-2">                                                           
                                    Control Documentario
                                </td>
                             
                                <td class="col-sm-4">
                                  <select  class="form-control" class="control_documentario" name="control_documentario" >
                                    <option value="<?php echo $proyect['jefe_proyecto1'] ?>"> <?php echo $proyect['control_documentario'] ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $control_documentario){
                                    ?>
                                        <option value="<?php echo $control_documentario['uid']?>"><?php echo $control_documentario['uid']?></option>
                                     <?php } ?>
                                  </select> 
                                                                                      
                                    <?php echo $proyect['control_documentario'] ?> 
                                </td> 
                          </tr>

                  </table>
                 
                  <!-- ------------------------------------------ C O N T A C T O S ------------------------------------------------------- -->
                    
                  <aside >
                    <table style="width:100%; margin-bottom:20px;" border=" 1px">
                                 
     <!--                              <tr style='background:rgba(0, 105, 173, 1)'>
                                      <th colspan='6' style='font-size:12px; '>Informacion Comercial</th>
                                  </tr>

                                  <?php $contact=$this->contact;
                                    //print_r($contact);
                                  ?>
                                  <div id="cont_<?php echo $contact['contactoid']?>">                           
                                    <tr>
                                        <td class="col-sm-2"><p><span>Nombre del Contacto</span></p></td>  
                                        <td class="col-sm-6 " colspan="3"><?php echo $proyect['ape_paterno'];echo " ";echo $proyect['ape_materno'];echo " ";echo $proyect['nombre1'];echo " "; $proyect['nombre2']; ?></td>
                                        <td class="col-sm-4" colspan="4">                               
                                              <center><p><span >Presupuesto</span></p></center>                                                                
                                        </td>                       
                                    </tr>


                                    <tr>
                                        <td class="col-sm-2" rowspan="2">                               
                                              <p><span>Cargo</span></p>                                   
                                        </td>
                                        <td class="col-sm-6" rowspan="2" colspan="3">
                                          <input class="form-control" id="puesto_trabajo" type="text" value="<?php echo $proyect['puesto_trabajo'] ?>" > 
                                        </td>
                                        
                                        <td class="col-sm-2" >                                  
                                                  <span>Moneda</span>  
                                          
                                        </td>
                                        <td class="col-sm-2">                                  
                                                <span>Dolares(USD)</span> 
                                                        
                                        </td>                          
                                    </tr>

                                    <tr>
                                        <td class="col-sm-2">  
                                                  <span>Honorarios</span>
                                        </td>
                                        <td class="col-sm-2"> 
                                                <span><?php echo $proyect['propuestaid'] ?></span>                
                                        </td>                          
                                    </tr>
                                 
                              
                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">
                                          <p><span>Telefono</span></p> 
                                        </td>
                                        <td class="col-sm-2" rowspan="2">
                                          <input class="form-control" id="telefono" type="text" value="<?php echo $proyect['telefono'] ?>" > 
                                        </td>
                                        <td class="col-sm-2" rowspan="2">
                                          <p><span>Anexo</span></p>                                  
                                        </td>

                                        <td class="col-sm-2" rowspan="2">
                                          <input class="form-control"id="anexo" type="text" value="<?php echo $proyect['anexo'] ?>" >           
                                        </td>
                                        
                                        <td class="col-sm-2">                                 
                                              <span>Gastos</span>  
                                        </td>
                                        <td class="col-sm-2">                                    
                                              <span>ffff</span>                                          
                                        </td>                                           
                                    </tr> -->

    <!--                                 <tr>  
                                        <td class="col-sm-2">
                                              <span>Laboratorio</span>
                                        </td>

                                        <td class="col-sm-2">                                    
                                                        
                                              <span>ee</span>                                                    
                                        </td>                                           
                                    </tr>


                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">                           
                                          <p><span>Celular 1</span></p>                                   
                                        </td>
                                        <td class="col-sm-2" rowspan="2">                                
                                          <input class="form-control" id="numero1" type="text" value="<?php echo $proyect['numero1'] ?>" >
                                        </td>
                                        <td class="col-sm-2" rowspan="2">                                   
                                                <p><span>Celular 2</span></p>                                     
                                        </td>
                                        <td class="col-sm-2" rowspan="2"> 
                                          <input class="form-control" id="numero2" type="text" value="<?php echo $proyect['numero2'] ?>" >

                                        </td>                                                              
                                        <td class="col-sm-2"> 
                                            <span>Otros</span>                                                                                                       
                                        </td>
                                        <td class="col-sm-2">
                                                <span>ffff</span>
                                        </td>                                                      
                                    </tr>

                                    <tr>                         
                                        <td class="col-sm-2"> 
                                            <span>Descuentos</span>                                      
                                        </td>
                                        <td class="col-sm-2">
                                            <span>ee</span>       
                                        </td>                                                      
                                    </tr>

                                    <tr >
                                        <td class="col-sm-2" rowspan="2">
                                              <p><span>Email</span></p> 
                                        </td>
                                        <td class="col-sm-6" colspan="3" rowspan="2">
                                          <input class="form-control" id="correo" type="text" value="<?php echo $proyect['correo'] ?>" >

                                        </td>                             
                                        <td class="col-sm-2">  
                                                  <span>Total</span>  
                                                  
                                        </td>
                                        <td class="col-sm-2">
                                                <span><?php echo $this->proyectoid ?></span>                                      
                                        </td>                            
                                    </tr>

                                    <tr >             
                                        <td class="col-sm-2"> 
                                                  <span>SOC 01</span>
                                        </td>
                                        <td class="col-sm-2">                                    
                                                <span><?php echo $proyect['propuestaid'] ?></span>                                                    
                                        </td>                            
                                    </tr>


                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">                               
                                              <p><span>Razon social</span></p>                                                                
                                        </td>
                                        <td class="col-sm-6" colspan="3" rowspan="2">
                                          <input class="form-control" id="nombre_comercial" type="text" value="<?php echo $proyect['nombre_comercial'] ?>" >
                                          </input>   
                                          
                                        </td>                                
                                        <td class="col-sm-2">  
                                                  <span>SOC 02</span>
                                        </td>
                                        <td class="col-sm-2">                               
                                                <span><?php echo $this->proyectoid ?></span>       
                                        </td>                                                                                                                 
                                    </tr>

                                    <tr>                                                                                             
                                        <td class="col-sm-2"> 
                                            <span>SOC 03</span>   
                                        </td>
                                        <td class="col-sm-2">                 
                                          <span><?php echo $proyect['propuestaid'] ?></span>                                                       
                                        </td>                                                                                                         
                                    </tr>
                                    <tr>                                 
                                        <td class="col-sm-2">                              
                                              <p><span>RUC</span></p>                                                                            
                                        </td>
                                        <td class="col-sm-2">  
                                          <input class="form-control" id="ruc" type="text" value="<?php echo $proyect['ruc'] ?>" >
                                          </input>                     
                                        </td>

                                        <td class="col-sm-2">                               
                                            <p><span>Telefono</span></p>                                
                                        </td>

                                        <td class="col-sm-2"> 
                                          <p><span> No especifica contacto o cliente(no hay campo)</span></p> 
                                        </td>

                                        <td class="col-sm-2">
                                          <span>Total + SOC</span>   
                                        </td>
                                        <td class="col-sm-2">
                                          <span>Otros</span>
                                        </td>  
                                    </tr>

                                    <tr>                                
                                        <td class="col-sm-2"> 
                                          <p><span>Direccion Fiscal</span></p>  
                                        </td>
                                        <td class="col-sm-6" colspan="3">
                                          <input class="form-control" id="direccion" type="text" value="<?php echo $proyect['direccion'] ?>" >
                                          </input>                                    
                                        </div>
                                   
                                        <td class="col-sm-2">
                                          <span>Adelanto %</span>  
                                        </td>
                                        <td class="col-sm-2"> 
                                        <input class="form-control" id="adelanto" type="text" value="<?php echo $proyect['adelanto'] ?>" >
                                          </input>  
                                          <div id="adelanto"> <?php echo $proyect['adelanto'] ?></div>
                                         
                                        </td>                               
                                    </tr>

                                    <tr>
                                        <td class="col-sm-2">
                                              <p><span>Documento de Aprobacion</span></p> 
                                        </td>

                                        <td class="col-sm-2">                                  
                                            <p><span>No hay campo en la BD</span></p>
                                        </td>

                                        <td class="col-sm-2">
                                                <p><span>Numero de Documento</span></p>                                    
                                        </td>

                                        <td class="col-sm-2">
                                            <p><span>  No hay campo en la BD</span></p>
                                        </td>

                                        <td class="col-sm-2">
                                            <span>Tipo de Contrato</span>            
                                        </td>
                                        <td class="col-sm-2">  
                                            <input class="form-control" id="tipo_contrato" type="text" value="<?php echo $proyect['tipo_contrato'] ?>" >
                                            </input>
                                        </td> 
                                    </tr>

                                    <tr>                                 
                                        <td class="col-sm-2">                               
                                          <p><span>Comentarios</span></p>                                   
                                        </td>

                                        <td class="col-sm-6" colspan="3"> 
                                          <textarea name="textarea"  id="comentario"  rows="5" cols="100">
                                            <?php echo $proyect['comentarios'] ?>
                                          </textarea>                        
                                        </td>

                                        <td class="col-sm-2">                               
                                            <span>Plazo de Pagos de Facturas %</span>        
                                        </td> 
                                        <td class="col-sm-2"> 
                                            <span>ddddd</span>            
                                        </td>                               
                                    </tr>

                                    <tr>                                 
                                        <td class="col-sm-2">
                                          <span>Foto Proyecto (link ruta) </span>
                                        </td>
                                        <td class="col-sm-6" colspan="3">
                                          <span>No hay campo en la BD</span>                                    
                                        </td>
                                        <td class="col-sm-2">
                                      
                                            <span>Fecha de Corte</span>            
                                        </td>
                                        <td class="col-sm-2">
                                            <span>no hay campo</span>            
                                        </td>                                
                                    </tr> -->

                                    <tr >                                 
                                      <td class="col-sm-2">                               
                                          <span> Observaciones </span>            
                                      </td>
                                      <td colspan="6" class="col-sm-10"> 
                                        
                                        <textarea name="textarea"  id="observacionoo"  rows="5" cols="100">
                                          <?php echo $proyect['observacion'] ?>
                                        </textarea>
                                        
                                      </td>                              
                                    </tr>

                                  
                        
                    </table>  

                  </aside>


                  </ul>
                </li>
       

              </ul>
          </div>
        
           

        <?php } ?>


 <input class="" id="lol" type="text" >
     <td class="col-sm-6" colspan="3"> 
                                          <textarea name="textarea"  id="comentarioxx"  rows="5" cols="100">
                                          </textarea>                        
                                        </td>

                                           

  <button id="guardar">Guardar</button>

            <script type="text/javascript">
            $(document).ready(function(){
              $("#guardar").click(function(){
                  alert("edita");


              var lol=$("#lol").val();
              var observacion=$("#observacionoo").val();
              var comentarioxx=$("#comentarioxx").val();
              alert(lol);
             
              alert(observacion);
              alert(comentarioxx);
 

             console.log(lol);
          


              });
            });
            </script>


            <script type="text/javascript">              
            // $(document).ready(function(){
            //   $("#accordian h3").click(function(){
            //     //slide up all the link lists
            //     $("#accordian ul ul").slideUp();
            //     //slide down the link list below the h3 clicked - only if its closed
            //     if(!$(this).next().is(":visible"))
            //     {
            //       $(this).next().slideDown();
            //     }
            //   })
            // })
            </script>

         

    
    

