        <?php  $historialresumen=$this->historialresumen; ?>

        <?php 
        $i=0;
        foreach ($historialresumen as $proyect) {
          ?>          
          <div id="accordian">

              <ul>
                <li>                     
                  <h3><span class="icon-dashboard"></span><?php echo $proyect['nombre_proyecto'];echo "---Revision de Hoja Resumen ";echo $proyect['revision_hojaresumen'];?></h3> 

                  <ul>
                  <button  class="btn btn-info" id="guardar_<?php echo $i?>">Guardar</button>
                  
                  <a role="button" class="btn btn-info" href="/proyecto/index/imphojaresumen/codigo_prop_proy/<?php echo $proyect['codigo_prop_proy']?>/proyectoid/<?php echo $proyect['proyectoid'] ?>/revision_hojaresumen/<?php echo $proyect['revision_hojaresumen'] ?>/revision_propuesta/<?php echo $proyect['revision_propuesta'] ?>/propuestaid/<?php echo $proyect['propuestaid'] ?>" id="imprimir">Imprimir</a>
                <!-- <section id="container" class=""> -->
                  <table style="width:100%; margin-bottom:20px;" border=" 1px">
                 
                      <tr style='background:rgba(0, 105, 173, 1)'>
                        <h3><center>Informacion</center></h3>
                      
                      </tr>                
                          <tr>                          
                              <td class="col-sm-2" rowspan="2" >Nombre del Proyecto</td>  
                              <td class="col-sm-6" colspan="3" rowspan="2" ><?php echo $proyect['nombre_proyecto'] ?></td>                            
                              <td  class="col-sm-1">     
                                <span>N de Proyecto</span> 
                              </td>
                          
                              <td class="col-sm-3">
                                <span><?php echo $proyect['proyectoid'] ?></span>                          
                              </td> 
                          </tr>

                          <tr>                          
                              <td  class="col-sm-1"> 
                                      <span>N de Propuesta</span> 
                              </td>
                          
                              <td class="col-sm-3"> 
                                  <span><?php echo $proyect['propuestaid'] ?></span>                        
                              </td> 
                          </tr>

                          <tr>                               
                              <td class="col-sm-2 "  >Descripcion del Proyecto</td>  
                              <td colspan="5" class="col-sm-10 ">
                                  <span><?php echo $proyect['descripcion'] ?></span>            
                              </td>
                          </tr> 

                          <tr>                       
                            
                            <td class="col-sm-2">                                                    
                                <span>Propietario</span> 
                            </td>
                                <td class="col-sm-4">                                             
                                    compania    
                                </td>                             
                             
                                <td  colspan="2" rowspan="3" class="col-sm-3">
                                    <center><p><span>Planificado</span> </p></center>                            
                                </td>                             
                            
                                <td colspan="2" rowspan="3" class="col-sm-3">
                                    <center><p><span>Real</span> </p></center>
                                </td>                           
                          </tr>    

                          <tr>                       
                            
                            <td class="col-sm-2">                                             
                              <span>Unidad Minera</span> 
                            </td>

                               <td class="col-sm-4">                                               
                                        <?php echo $proyect['nombre'] ?>
                              </td>                 
                          </tr>

                          <tr>  
                            <td class="col-sm-2">                   
                              <span>Tipo de Servicio</span>
                            </td>
                            <td class="col-sm-4">                                                               
                                    geotecnia 
                            </td>                             
                                            
                          </tr>  

                          <tr>
                                <td  class="col-sm-2">                                                                                    
                                  Gerente del Proyecto                                  
                               </td>                           
                         
                                <td class="col-sm-4">
                                  <select  class="form-control" id="gerente_proyecto_i_<?php echo $i?>" name="gerente_proyecto" >
                                    <option value="<?php echo $proyect['gerente_proyecto'] ?>"> <?php  
                                      $porciones = explode(".", $proyect['gerente_proyecto']);
                                        foreach ($porciones as $value) {                          
                                          echo (ucwords($value));  echo " ";                                                
                                        }

                                    ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $gerente_proyecto){
                                    ?>
                                        <option value="<?php echo $gerente_proyecto['uid']?>"><?php // $gerente_proyecto['uid']
                                            $porciones = explode(".", $gerente_proyecto['uid']);
                                              foreach ($porciones as $value) {                          
                                                echo (ucwords($value));  echo " ";                                                
                                              }
                                             
                                        ?></option>
                                     <?php } ?>
                                  </select> 
                                </td>

                                <td rowspan="2" class="col-sm-1">
                                  Fecha de Inicio
                                </td>
                                                       
                                <td class="col-sm-2" rowspan="2" >
                                    <input class="form-control default-date-picker " id="fecha_inicio_planificado_i_<?php echo $i?>" value="<?php echo $proyect['fecha_inicio_planificado'] ?>" type="text" > 

                                </td>
                                                 
                                <td class="col-sm-1" rowspan="2" >
                                   Fecha de Cierre
                                </td>                            
                                <td class="col-sm-2" rowspan="2" >

                                  <input class="form-control default-date-picker " id="fecha_inicio_real_i_<?php echo $i?>" value="<?php echo $proyect['fecha_inicio_real'] ?>" type="text" > 
                                </td>
                         
                          </tr>

                          <tr>
                                <td  class="col-sm-2">                                                                                   
                                    Jefe del Proyecto 1 
                                </td>                          
                         
                                <td class="col-sm-4">
                                  <select  class="form-control" id="jefe_proyecto1_i_<?php echo $i?>" name="jefe_proyecto1" >
                                    <option  value="<?php echo $proyect['jefe_proyecto1'] ?>"> <?php //echo $proyect['jefe_proyecto1'] 
                                      $porciones = explode(".", $proyect['jefe_proyecto1']);
                                        foreach ($porciones as $value) {                          
                                          echo (ucwords($value));  echo " ";                                                
                                      }

                                    ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $jefe_proyecto1){
                                    ?>
                                        <option value="<?php echo $jefe_proyecto1['uid']?>"><?php 
                                          $porciones = explode(".", $jefe_proyecto1['uid']);
                                            foreach ($porciones as $value) {                          
                                              echo (ucwords($value));  echo " ";                                                
                                          }

                                        ?></option>
                                     <?php } ?>
                                  </select> 
                                                      
                                </td>
                          </tr>      

                          <tr>                      
                                <td  class="col-sm-2"  >                                                           
                                      Jefe del Proyecto 2 
                                </td>
                             
                                <td class="col-sm-4"  > 
                                  <select  class="form-control" id="jefe_proyecto2_i_<?php echo $i?>" name="jefe_proyecto2">
                                    <option  value="<?php echo $proyect['jefe_proyecto2'] ?>"><?php //echo $proyect['jefe_proyecto2'] 
                                      $porciones = explode(".", $proyect['jefe_proyecto2']);
                                        foreach ($porciones as $value) {                          
                                          echo (ucwords($value));  echo " ";                                                
                                      }
                                    ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $jefe_proyecto2){
                                    ?>
                                      <option value="<?php echo $jefe_proyecto2['uid']?>"><?php //echo $jefe_proyecto2['uid']
                                        $porciones = explode(".", $jefe_proyecto2['uid']);
                                              foreach ($porciones as $value) {                          
                                                echo (ucwords($value));  echo " ";                                                
                                        }

                                      ?></option>
                                    <?php } ?>
                                  </select> 
                                </td> 

                                <td class="col-sm-1" rowspan="2" >                                                        
                                      Fecha de Inicio 
                                </td>                           
                      
                                <td class="col-sm-2" rowspan="2" >
                                  <input class="form-control default-date-picker " id="fecha_fin_planificado_i_<?php echo $i?>" value="<?php echo $proyect['fecha_fin_planificado'] ?>" type="text" >                                  
                                </td>                           
                            
                                <td class="col-sm-1" rowspan="2" >                                                                          
                                      Fecha de Cierre 
                                </td>                             
                            
                                <td class="col-sm-2" rowspan="2" >
                                  <input class="form-control default-date-picker " id="fecha_fin_real_i_<?php echo $i?>" value="<?php echo $proyect['fecha_fin_real'] ?>" type="text">

                                </td>        
                          </tr> 

                          <tr>                      
                                <td  class="col-sm-2">                                                           
                                    Control Documentario
                                </td>
                             
                                <td class="col-sm-4">
                                  <select  class="form-control" id="control_documentario_i_<?php echo $i?>" name="control_documentario" >
                                    <option value="<?php echo $proyect['control_documentario'] ?>"> <?php //echo $proyect['control_documentario']
                                      $porciones = explode(".", $proyect['control_documentario']);
                                        foreach ($porciones as $value) {                          
                                          echo (ucwords($value));  echo " ";                                                
                                      }

                                     ?></option>
                                    <?php
                                      foreach ( $this->ucat  as $control_documentario){
                                    ?>
                                        <option value="<?php echo $control_documentario['uid']?>"><?php //echo $control_documentario['uid']
                                          $porciones = explode(".", $control_documentario['uid']);
                                            foreach ($porciones as $value) {                          
                                          echo (ucwords($value));  echo " ";                                                
                                        }


                                        ?></option>
                                     <?php } ?>
                                  </select> 
                                                                                      
                              
                                </td> 
                          </tr>

                     

                  </table>
                 
                  <!-- ------------------------------------------ C O N T A C T O S ------------------------------------------------------- -->
                  <h3><center>Informacion Comercial</center></h3>
                  
                  <aside >

                    <table style="width:100%; margin-bottom:20px;" border=" 1px">
                                 

                       
                                   <!-- <tr style='background:rgba(0, 105, 173, 1)'>
                                      <th colspan='6' style='font-size:12px; '>Informacion Comercial</th>
                                  </tr>

                                  <?php $contact=$this->contact;
                                    //print_r($contact);
                                  ?>
                                  <div id="cont_<?php echo $contact['contactoid']?>">     -->                      
                                    <tr>
                                        <td class="col-sm-2"><p><span>Nombre del Contacto</span></p></td>  
                                        <td class="col-sm-6 " colspan="3"><?php echo $proyect['ape_paterno'];echo " ";echo $proyect['ape_materno'];echo " ";echo $proyect['nombre1'];echo " "; $proyect['nombre2']; ?></td>
                                        <td class="col-sm-4" colspan="4">                               
                                              <center><p><span >Presupuesto</span></p></center>                                                                
                                        </td>                       
                                    </tr> 

                                    <input type="hidden"  id="contactoid_i_<?php echo $i?>" value="<?php echo $proyect['contactoid'] ?>" > 

                                    <tr>
                                        <td class="col-sm-2" rowspan="2">                               
                                              <p><span>Cargo</span></p>                                   
                                        </td>
                                        <td class="col-sm-6" rowspan="2" colspan="3">
                                          <input class="form-control" id="puesto_trabajo_i_<?php echo $i?>" type="text" value="<?php echo $proyect['puesto_trabajo'] ?>" > 
                                        </td>
                                        
                                        <td class="col-sm-2" >                                  
                                                  <span>Moneda</span>  
                                          
                                        </td>
                                        <td class="col-sm-2">                                  
                                                <span>Dolares(USD)</span> 
                                                        
                                        </td>                          
                                    </tr> 

                                    <tr>
                                        <td class="col-sm-2">  
                                                  <span>Honorarios</span>
                                        </td>
                                        <td class="col-sm-2"> 
                                                <span><?php echo $proyect['propuestaid'] ?></span>                
                                        </td>                          
                                    </tr>
                                 
                              
                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">
                                          <p><span>Telefono</span></p> 
                                        </td>
                                        <td class="col-sm-2" rowspan="2">
                                          <input class="form-control" id="telefono_i_<?php echo $i?>" type="text" value="<?php echo $proyect['telefono'] ?>" > 
                                        </td>
                                        <td class="col-sm-2" rowspan="2">
                                          <p><span>Anexo</span></p>                                  
                                        </td>

                                        <td class="col-sm-2" rowspan="2">
                                          <input class="form-control"id="anexo_i_<?php echo $i?>" type="text" value="<?php echo $proyect['anexo'] ?>" >           
                                        </td>
                                        
                                        <td class="col-sm-2">                                 
                                              <span>Gastos</span>  
                                        </td>
                                        <td class="col-sm-2">                                    
                                              <span>ffff</span>                                          
                                        </td>                                           
                                    </tr> 

                                   <tr>  
                                        <td class="col-sm-2">
                                              <span>Laboratorio</span>
                                        </td>

                                        <td class="col-sm-2">                                    
                                                        
                                              <span>ee</span>                                                    
                                        </td>                                           
                                    </tr> 


                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">                           
                                          <p><span>Celular 1</span></p>                                   
                                        </td>
                                        <td class="col-sm-2" rowspan="2">                                
                                          <input class="form-control" id="numero1_i_<?php echo $i?>" type="text" value="<?php echo $proyect['numero1'] ?>" >
                                        </td>
                                        <td class="col-sm-2" rowspan="2">                                   
                                                <p><span>Celular 2</span></p>                                     
                                        </td>
                                        <td class="col-sm-2" rowspan="2"> 
                                          <input class="form-control" id="numero2_i_<?php echo $i?>" type="text" value="<?php echo $proyect['numero2'] ?>" >

                                        </td>                                                              
                                        <td class="col-sm-2"> 
                                            <span>Otros</span>                                                                                                       
                                        </td>
                                        <td class="col-sm-2">
                                                <span>ffff</span>
                                        </td>                                                      
                                    </tr> 

                                    <tr>                         
                                        <td class="col-sm-2"> 
                                            <span>Descuentos</span>                                      
                                        </td>
                                        <td class="col-sm-2">
                                            <span>ee</span>       
                                        </td>                                                      
                                    </tr> 

                                    <tr >
                                        <td class="col-sm-2" rowspan="2">
                                              <p><span>Email</span></p> 
                                        </td>
                                        <td class="col-sm-6" colspan="3" rowspan="2">
                                          <input class="form-control" id="correo_i_<?php echo $i?>" type="text" value="<?php echo $proyect['correo'] ?>" >

                                        </td>                             
                                        <td class="col-sm-2">  
                                                  <span>Total</span>  
                                                  
                                        </td>
                                        <td class="col-sm-2">
                                                <span><?php echo $this->proyectoid ?></span>                                      
                                        </td>                            
                                    </tr> 

                                    <tr >             
                                        <td class="col-sm-2"> 
                                                  <span>SOC 01</span>
                                        </td>
                                        <td class="col-sm-2">                                    
                                                <span><?php echo $proyect['propuestaid'] ?></span>                                                    
                                        </td>                            
                                    </tr> 


                                    <tr>                                 
                                        <td class="col-sm-2" rowspan="2">                               
                                              <p><span>Razon social</span></p>                                                                
                                        </td>
                                        <td class="col-sm-6" colspan="3" rowspan="2">
                                          <input disabled class="form-control" id="nombre_comercial_i_<?php echo $i?>" type="text" value="<?php echo $proyect['nombre_comercial'] ?>" >
                                          </input>   
                                          
                                        </td>                                
                                        <td class="col-sm-2">  
                                                  <span>SOC 02</span>
                                        </td>
                                        <td class="col-sm-2">                               
                                                <span><?php echo $this->proyectoid ?></span>       
                                        </td>                                                                                                                 
                                    </tr> 

                                    <tr>                                                                                             
                                        <td class="col-sm-2"> 
                                            <span>SOC 03</span>   
                                        </td>
                                        <td class="col-sm-2">                 
                                          <span><?php echo $proyect['propuestaid'] ?></span>                                                       
                                        </td>                                                                                                         
                                    </tr>  
                                    <tr>                                 
                                        <td class="col-sm-2">                              
                                              <p><span>RUC</span></p>                                                                            
                                        </td>
                                        <td class="col-sm-2">  
                                          <input class="form-control" id="ruc_i_<?php echo $i?>" type="text" value="<?php echo $proyect['ruc'] ?>" >
                                          </input>                     
                                        </td>

                                        <td class="col-sm-2">                               
                                            <p><span>Telefono</span></p>                                
                                        </td>

                                        <td class="col-sm-2"> 
                                          <p><span> No especifica contacto o cliente(no hay campo)</span></p> 
                                        </td>

                                        <td class="col-sm-2">
                                          <span>Total + SOC</span>   
                                        </td>
                                        <td class="col-sm-2">
                                          <span>Otros</span>
                                        </td>  
                                    </tr> 

                                    <tr>                                
                                        <td class="col-sm-2"> 
                                          <p><span>Direccion Fiscal</span></p>  
                                        </td>
                                        <td class="col-sm-6" colspan="3">
                                          <input class="form-control" id="direccion_i_<?php echo $i?>" type="text" value="<?php echo $proyect['direcli'] ?>" >
                                          </input>                                    
                                        </div>
                                   
                                        <td class="col-sm-2">
                                          <span>Adelanto %</span>  
                                        </td>
                                        <td class="col-sm-2"> 
                                        <input class="form-control" id="adelanto_i_<?php echo $i?>" type="text" value="<?php echo $proyect['adelanto'] ?>" >
                                          </input>  
                                          <div id="adelanto"> <?php echo $proyect['adelanto'] ?></div>
                                         
                                        </td>                               
                                    </tr>

                                    <tr>
                                        <td class="col-sm-2">
                                              <p><span>Documento de Aprobacion</span></p> 
                                        </td>

                                        <td class="col-sm-2">                                  
                                            <p><span>No hay campo en la BD</span></p>
                                        </td>

                                        <td class="col-sm-2">
                                                <p><span>Numero de Documento</span></p>                                    
                                        </td>

                                        <td class="col-sm-2">
                                            <p><span>  No hay campo en la BD</span></p>
                                        </td>

                                        <td class="col-sm-2">
                                            <span>Tipo de Contrato</span>            
                                        </td>
                                        <td class="col-sm-2">  
                                            <input class="form-control" id="tipo_contrato_i_<?php echo $i?>" type="text" value="<?php echo $proyect['tipo_contrato'] ?>" >
                                            </input>
                                        </td> 
                                    </tr> 
                                    <tr>                                 
                                        <td class="col-sm-2">                               
                                          <p><span>Comentarios</span></p>                                   
                                        </td>

                                        <td class="col-sm-6" colspan="3"> 
                                          <textarea name="textarea"  id="comentario_i_<?php echo $i?>"  rows="5" cols="100">
                                            <?php echo $proyect['comentarios'] ?>
                                          </textarea>                        
                                        </td>

                                        <td class="col-sm-2">                               
                                            <span>Plazo de Pagos de Facturas %</span>        
                                        </td> 
                                        <td class="col-sm-2"> 
                                            <span>ddddd</span>            
                                        </td>                               
                                    </tr> 



                                    <tr>                                 
                                        <td class="col-sm-2">
                                          <span>Foto Proyecto (link ruta) </span>
                                        </td>
                                        <td class="col-sm-6" colspan="3">
                                          <span>No hay campo en la BD</span>                                    
                                        </td>
                                        <td class="col-sm-2">
                                      
                                            <span>Fecha de Corte</span>            
                                        </td>
                                        <td class="col-sm-2">
                                            <span>no hay campo</span>            
                                        </td>                                
                                    </tr>

                                    <tr >                                 
                                      <td class="col-sm-2">                               
                                          <span> Observaciones </span>            
                                      </td>
                                      <td colspan="6" class="col-sm-10"> 
                                        
                                        <textarea name="textarea"  id="observacion_i_<?php echo $i?>"  rows="5" cols="100">
                                          <?php echo $proyect['observacion'] ?>
                                        </textarea>
                                        
                                      </td>                              
                                    </tr>

                                  
                        
                    </table>  

                  </aside>


                  </ul>
                </li>
       

              </ul>
          </div>
        
<!--         <input class=" default-date-picker  hasDatepicker " id="fecha_inicio_real" type="text" >
           
 -->

                        


            <script type="text/javascript">
            $(document).ready(function(){
              $("#guardar_<?php echo $i?>").click(function(){
                  console.log("guardar_<?php echo $i?>");


          
              var observacion=$("#observacion_i_<?php echo $i?>").val();
              var observacion=observacion.trim();
              var comentario=$("#comentario_i_<?php echo $i?>").val();
              var comentario=comentario.trim();

              var direccion=$("#direccion_i_<?php echo $i?>").val();
              var adelanto=$("#adelanto_i_<?php echo $i?>").val();
              var tipo_contrato=$("#tipo_contrato_i_<?php echo $i?>").val();
              var nombre_comercial=$("#nombre_comercial_i_<?php echo $i?>").val();
              var ruc=$("#ruc_i_<?php echo $i?>").val();
              var correo=$("#correo_i_<?php echo $i?>").val();
              var numero1=$("#numero1_i_<?php echo $i?>").val();
              var numero2=$("#numero2_i_<?php echo $i?>").val();
              var anexo=$("#anexo_i_<?php echo $i?>").val();
              var telefono=$("#telefono_i_<?php echo $i?>").val();
              var puesto_trabajo=$("#puesto_trabajo_i_<?php echo $i?>").val();

              var control_documentario=$("#control_documentario_i_<?php echo $i?>").val();
              var jefe_proyecto2=$("#jefe_proyecto2_i_<?php echo $i?>").val();
              var jefe_proyecto1=$("#jefe_proyecto1_i_<?php echo $i?>").val();
              var gerente_proyecto=$("#gerente_proyecto_i_<?php echo $i?>").val();

              var fecha_inicio_planificado=$("#fecha_inicio_planificado_i_<?php echo $i?>").val();
              var fecha_inicio_real=$("#fecha_inicio_real_i_<?php echo $i?>").val();
              var fecha_fin_planificado=$("#fecha_fin_planificado_i_<?php echo $i?>").val();
              var fecha_fin_real=$("#fecha_fin_real_i_<?php echo $i?>").val();                            
              var contactoid=$("#contactoid_i_<?php echo $i?>").val();                            
          
              var codigo_prop_proy="<?php echo $proyect['codigo_prop_proy']?>";
              var proyectoid="<?php echo $proyect['proyectoid']?>";
              var revision_hojaresumen="<?php echo $proyect['revision_hojaresumen']?>";
              var revision_propuesta="<?php echo $proyect['revision_propuesta']?>";
              var propuestaid="<?php echo $proyect['propuestaid']?>";                           
             
              // alert(observacion);
              // alert(comentario);
              // alert(direccion);
              // alert(adelanto);
              // alert(tipo_contrato);
              // alert(nombre_comercial);
              // alert(ruc);
              // alert(correo);
              // alert(numero1);
              // alert(numero2);
              // alert(anexo);
              // alert(telefono);

              // alert(control_documentario);
              // alert(jefe_proyecto2);
              // alert(jefe_proyecto1);
              // alert(gerente_proyecto);

              // alert(fecha_inicio_planificado);
              // alert(fecha_inicio_real);
              // alert(fecha_fin_planificado);
              // alert(fecha_fin_real);

              // alert(codigo_prop_proy);
              // alert(proyectoid);
              // alert(revision_hojaresumen);
              // alert(revision_propuesta);
              // alert(propuestaid);
              // alert(contactoid);

              url="/proyecto/index/updatehojaresumen/codigo_prop_proy/"+codigo_prop_proy+"/proyectoid/"+proyectoid+"/revision_hojaresumen/"+revision_hojaresumen+"/revision_propuesta/"+
              revision_propuesta+"/propuestaid/"+propuestaid+"/fecha_inicio_planificado/"+fecha_inicio_planificado+"/fecha_fin_planificado/"+fecha_fin_planificado+
              "/fecha_inicio_real/"+fecha_inicio_real+"/fecha_fin_real/"+fecha_fin_real+             
              "/gerente_proyecto/"+gerente_proyecto+"/jefe_proyecto1/"+jefe_proyecto1+"/jefe_proyecto2/"+jefe_proyecto2+"/control_documentario/"+control_documentario+

              "/telefono/"+telefono+"/anexo/"+anexo+
              "/numero2/"+numero2+"/numero1/"+numero1+
              "/correo/"+correo+"/ruc/"+ruc+
              "/nombre_comercial/"+nombre_comercial+"/tipo_contrato/"+tipo_contrato+
              "/adelanto/"+adelanto+"/direccion/"+direccion+"/puesto_trabajo/"+puesto_trabajo+
           
              "/comentario/"+comentario+"/observacion/"+observacion+ "/contactoid/"+contactoid;
              //alert(url);      

              $.ajax({
                type: "POST",
                url: url,
                data: $(this).serialize(),
                dataType: "html",                                                 
                error: function()
                {
                  alert("error petición ajax load");
                },
                  success: function(data)
                {                                
                }
              });


          
              });
            });
            </script>



         

        <?php $i++; } ?>
    

            <script type="text/javascript">              
            $(document).ready(function(){
              $("#accordian h3").click(function(){
                //slide up all the link lists
                $("#accordian ul ul").slideUp();
                //slide down the link list below the h3 clicked - only if its closed
                if(!$(this).next().is(":visible"))
                {
                  $(this).next().slideDown();
                }
              })
            })
            </script>



<!-- <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script> -->

    <style type="text/css">
        /*custom font for text*/
@import url(http://fonts.googleapis.com/css?family=Nunito);
/*CSS file for fontawesome - an iconfont we will be using. This CSS file imported contains the font-face declaration. More info: http://fortawesome.github.io/Font-Awesome/ */
@import url(http://thecodeplayer.com/uploads/fonts/fontawesome/css/font-awesome.min.css);

/*Basic reset*/
* {margin: 0; padding: 0;}

body {
  background: #4EB889;
  font-family: Nunito, arial, verdana;
}
#accordian {
  /*background: #004050;*/
  width: 100%;
  /*margin: 100px auto 0 auto;*/
  /*color: white;*/
  /*Some cool shadow and glow effect*/
  box-shadow: 
    0 5px 15px 1px rgba(0, 0, 0, 0.6), 
    0 0 200px 1px rgba(255, 255, 255, 0.5);
}
/*heading styles*/
#accordian h3 {
  font-size: 16px;
  line-height: 34px;
  padding: 0 10px;
  cursor: pointer;
  /*fallback for browsers not supporting gradients*/
  background: #003040; 
  /*background: linear-gradient(#003040, #002535);*/
}
/*heading hover effect*/
#accordian h3:hover {
  color: #4EB889;
  /*text-shadow: 0 0 1px rgba(255, 255, 255, 0.7);*/
}
/*iconfont styles*/
#accordian h3 span {
  font-size: 16px;
  margin-right: 10px;
}
/*list items*/
#accordian li {
  list-style-type: none;
}
/*links*/
#accordian ul ul li a {
  /*color: white;*/
  text-decoration: none;
  font-size: 11px;
  line-height: 27px;
  display: block;
  padding: 0 15px;
  /*transition for smooth hover animation*/
  transition: all 0.15s;
}
/*hover effect on links*/
#accordian ul ul li a:hover {
  /*background: #003545;*/
  border-left: 5px solid lightgreen;
}
/*Lets hide the non active LIs by default*/
#accordian ul ul {
  display: none;
}
#accordian li.active ul {
  display: block;
}


</style>    

  
