
  <section id="container" class="">
    <?php $this->proyectdetail;

    foreach ($this->proyectdetail as $proyect) {
      # code...
  
    ?>
                  <aside class="mid-side">
                      <div class="chat-room-head">
                          <center><h3>Informacion</h3></center>
                     
                      </div>

                          <div class="group-rom panel-body room-box">
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                  <li class="active" >Nombre del Proyecto</li>
                                </ul>
                              </div>
                              <div class="col-sm-5"><?php echo $proyect['descripcion'] ?></div>
                              <div class="col-sm-2">
                                <ul class="chat-list">    
                                    <li class="active">
                                      <span>N de Proyecto</span>            
                                    </li>
                                    <li class="active">
                                      <span>N de Propuesta</span>            
                                    </li>                                   
                                </ul>
                              </div>
                              <div class="col-sm-3">
                                <ul>    
                                    <li>
                                      <span><?php echo $this->proyectoid ?></span>            
                                    </li>
                                    <li>
                                      <span><?php echo $proyect['propuestaid'] ?></span>            
                                    </li>                                   
                                </ul>                             
                              </div>                      
                          </div>

                          <div class="group-rom panel-body room-box">
                              <div class="col-sm-2 " >
                                <ul class="chat-list">
                                  <li class="active" >Descripcion del Proyecto</li>
                                </ul>
                              </div>
                              <div class="col-sm-8 " >
                                <ul>    
                                    <li>
                                      <span><?php echo $proyect['descripcion'] ?></span>            
                                    </li>                                                                  
                                </ul>
                              </div>                              
                          </div>

                          <div class="group-rom panel-body room-box">
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                    <li class="active">                                                                    
                                        <span>Propietario</span> 
                                    </li>
                                    <li class="active">                                                           
                                        <span>Unidad Minera</span>
                                    </li>
                                    <li class="active">                  
                                        <span>Tipo de Servicio</span>
                                    </li>
                                </ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul class="chat-list">
                                    <li class="">                                                             
                                                compania                                     
                                    </li>
                                    <li class="">                                                                            
                                                <?php echo $proyect['nombre'] ?>                                     
                                    </li>
                                    <li class="">                                                                                   
                                                geotecnia                                       
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-3">
                                <ul class="chat-list">
                                    <li class="active">                                                                    
                                        <center><p><span>Propietario</span> </p></center>
                                    </li>
                                </ul>
                              </div>
                              <div class="col-sm-3">
                                <ul class="chat-list">
                                    <li class="active">                                                                    
                                        <center><p><span>Real</span> </p></center>
                                    </li>
                                </ul>                            
                              </div>
                          </div>                          
                       
                          <div class="group-rom panel-body room-box">
                              <div class="col-sm-2">
                                  <ul class="chat-list">
                                    <li class="active">                                                                            
                                                Gerente del Proyecto                                      
                                    </li>
                                    <li class="active">                                                                             
                                                Jefe del Proyecto 1                                   
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul>
                                    <li class="">  
                                          <?php echo $proyect['gerente_proyecto'] ?>   
                                    </li>
                                    <li class="">                                                                                   
                                                D                                      
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                  <li class="active" > Fecha de Inicio</li>
                                </ul>
                              </div>
                              <div class="col-sm-1"><?php echo $proyect['fecha_inicio'] ?></div>
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                  <li class="active" >  Fecha de Cierre</li>
                                </ul>
                              </div>
                              <div class="col-sm-1"><?php echo $proyect['fecha_cierre'] ?></div>
                          </div>

                          <div class="group-rom panel-body room-box">
                              <div class="col-sm-2">
                                  <ul class="chat-list">
                                    <li class="active">                                                                           
                                      Jefe del Proyecto 2                                     
                                    </li>
                                    <li class="active">                                                                                 
                                      Control Documentario                                 
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul >
                                    <li class="">                                                                         
                                        Campo no hay BD                                  
                                    </li>
                                    <li class="">                                                                                  
                                        <?php echo $proyect['control_documentario'] ?> 
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                  <li class="active">                                                                           
                                    Fecha de Inicio                                     
                                  </li>
                                </ul>
                              </div>

                              <div class="col-sm-1">
                                no hay campo tabla proyecto
                              </div>
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                  <li class="active">                                                                           
                                    Fecha de Cierre                                    
                                  </li>
                                </ul>
                              </div>
                              <div class="col-sm-1">no hay campo tabla proyecto</div>
                          </div>

                  </aside>

                  <!-- ------------------------------------------ C O N T A C T O S ------------------------------------------------------- -->
                    
                      
                  <aside >

                          <div class="group-rom">
                            <div class="chat-room-head">
                              <center><h3>Informacion Comercial</h3></center>
                            </div>
                            <div >
                              <?php if($this->contact) { ?>
                              <h5><a name="multiple-select" class="anchor" href="#multiple-select">Escoja un contacto</a></h5>
                              <div class="side-by-side clearfix">
                                <div>                                  
                                  <select id="contact" data-placeholder="Choose a Country..." style="width:350px;" multiple tabindex="3">
                                  
                                    <?php
                                    foreach ($this->contact as $contacto) {?> 
                                    <option value="cont_<?php echo $contacto['contactoid']?>"><?php  echo $contacto['ape_paterno'];echo " ";echo $contacto['ape_materno'];echo " ";echo $contacto['nombre1'];echo " ";echo $contacto['nombre2']?></option>
                                   
                                    <?php }  ?>
                                  </select>
                                </div>
                              </div>
                              <?php }else{  ?>
                                  <button type="button" data-dismiss="modal" aria-hidden="true">Agregar Contacto</button> 
                                  <?php  } ?>
                            </div>
                          </div>
                          <script type="text/javascript">
                              $(document).ready(function(){
                                $("#contact").click(function(){
                                  var valor=$(this).val();
                                    //alert(valor);
                                    $("#"+valor).show();
                                });
                              });
                          </script>                                           
                         
                          <?php 
                          //print_r($this->contact);
                          if($this->contact) {
                          foreach ($this->contact as $contact) { ?>
                        
                          <div style="display:none"  id="cont_<?php echo $contact['contactoid']?>">
                      
                            <div class="group-rom panel-body room-box ">                       
                                <div class="col-sm-4  ">
                                  <ul class="chat-list">
                                    <li class="active"> 
                                      <p><span>Nombre del Contacto</span></p> 
                                    </li>
                                  </ul> 
                                </div>
                                <div class="col-sm-4 "><?php echo $contact['ape_paterno'];echo " ";echo $contact['ape_materno'];echo " ";echo $contact['nombre1'] ?></div>
                                <div class="col-sm-4 ">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <center><p><span >Presupuesto</span></p></center>
                                    </li>
                                  </ul>                                
                                </div>                       
                            </div>


                            <div class="group-rom panel-body room-box" >
                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">
                                    <li class="active"> 
                                      <p><span>Cargo</span></p> 
                                    </li>
                                  </ul> 
                                </div>
                                <div class="col-sm-4"><?php echo $contact['puesto_trabajo'] ?></div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Moneda</span>            
                                        </li>
                                        <li class="active">
                                          <span>Honorarios</span>            
                                        </li>                                   
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                    <ul>    
                                      <li>
                                        <span>Dolares(USD)</span>            
                                      </li>
                                      <li>
                                        <span><?php echo $proyect['propuestaid'] ?></span>            
                                      </li>                                   
                                    </ul>                                
                                  </div>                                                         
                                </div>                          
                            </div>
                         
                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-2">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>Telefono</span></p> 
                                    </li>
                                  </ul>   
                                </div>
                                <div class="col-sm-6">                                  

                                  <div class="col-sm-4">
                                    <?php echo $contact['telefono'] ?>
                                  </div>

                                  <div class="col-sm-4">
                                    <ul class="chat-list">    
                                      <li class="active">
                                        <p><span>Anexo</span></p>                                  
                                      </li>
                                    </ul>
                                  </div>

                                  <div class="col-sm-4">
                                    <?php echo $contact['anexo'] ?>
                                  </div>
                                </div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li  class="active">
                                          <span>Gastos</span>            
                                        </li>
                                        <li class="active">
                                          <span>Laboratorio</span>            
                                        </li>                                   
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                    <ul>    
                                      <li>
                                        <span>ffff</span>            
                                      </li>
                                      <li>
                                        <span>ee</span>            
                                      </li>                                   
                                    </ul>                                
                                  </div>                                                         
                                </div>                          
                            </div>


                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-2">
                                  <ul class="chat-list">    
                                    <li  class="active">
                                      <p><span>Celular 1</span></p> 
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-6">

                                  <div class="col-sm-4">
                                    <?php echo $contact['numero1'] ?>
                                  </div>

                                  <div class="col-sm-4">
                                    <ul class="chat-list">    
                                      <li class="active">
                                        <p><span>Celular 2</span></p> 
                                      </li>
                                    </ul>
                                  </div>

                                  <div class="col-sm-4"> 
                                    <?php echo $contact['numero2'] ?>
                                  </div>

                                </div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Otros</span>            
                                        </li>
                                        <li class="active">
                                          <span>Descuentos</span>            
                                        </li>                                   
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                    <ul>    
                                      <li>
                                        <span>ffff</span>            
                                      </li>
                                      <li>
                                        <span>ee</span>            
                                      </li>                                   
                                    </ul>                                
                                  </div>                                                         
                                </div>                          
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>Email</span></p> 
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-4"><?php echo $contact['correo'] ?></div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Total</span>            
                                        </li>
                                        <li  class="active">
                                          <span>SOC 01</span>            
                                        </li>                                   
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                    <ul>    
                                      <li>
                                        <span><?php echo $this->proyectoid ?></span>            
                                      </li>
                                      <li>
                                        <span><?php echo $proyect['propuestaid'] ?></span>            
                                      </li>                                   
                                    </ul>                                
                                  </div>                                                         
                                </div>
                            
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>Razon social</span></p>                                
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-4"><?php echo $proyect['nombre_comercial'] ?></div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>SOC 02</span>            
                                        </li>
                                        <li class="active">
                                          <span>SOC 03</span>            
                                        </li>                                   
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                    <ul>    
                                      <li>
                                        <span>  <?php echo $this->proyectoid ?></span>            
                                      </li>
                                      <li>
                                        <span><?php echo $proyect['propuestaid'] ?></span>            
                                      </li>                                   
                                    </ul>                                
                                  </div>                                                         
                                </div>                          
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-2">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>RUC</span></p>  
                                    </li>
                                  </ul>                                                                 
                                </div>
                                <div class="col-sm-6">
                                  <div class="col-sm-4">
                                    <?php echo $proyect['ruc'] ?>
                                  </div>

                                  <div class="col-sm-4">
                                    <ul class="chat-list">    
                                      <li class="active">
                                        <p><span>Telefono</span></p>
                                      </li>
                                    </ul>
                                  </div>

                                  <div class="col-sm-4"> 
                                    <p><span> No especifica contacto o cliente(no hay campo)</span></p> 
                                  </div>

                                </div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Otros</span>            
                                        </li>
                                                              
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">                                
                                    <ul>    
                                        <li>
                                          <span>Otros</span>            
                                        </li>
                                                              
                                    </ul>
                                  </div>                                             
                                </div>                          
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-4"> 
                                  <p><span>Direccion Fiscal</span></p>  
                                </div>
                                <div class="col-sm-4"><?php echo $contact['direccion'] ?></div>
                                <div class="col-sm-4">
                                  <div class="col-sm-6">
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Adelanto %</span>            
                                        </li>
                                                                      
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                     <ul>    
                                        
                                        <li>
                                          <span><?php echo $proyect['propuestaid'] ?></span>            
                                        </li>                                   
                                    </ul>                             
                                  </div>
                                </div>
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-2">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>Documento de Aprobacion</span></p>                                   
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-6">
                                  <div class="col-sm-4">
                                    <p><span>No hay campo en la BD</span></p>
                                  </div>

                                  <div class="col-sm-4">
                                    <ul class="chat-list">    
                                      <li class="active">
                                        <p><span>Numero de Documento</span></p>                                    
                                      </li>
                                    </ul>
                                  </div>

                                  <div class="col-sm-4">
                                    <p><span>  No hay campo en la BD</span></p>
                                  </div>
                                </div>
                                
                                <div class="col-sm-4">
                                  <div class="col-sm-6">                                
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Tipo de Contrato</span>            
                                        </li>                                                              
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">                                
                                    <ul>    
                                        <li>
                                          <span>Otros</span>            
                                        </li>
                                                              
                                    </ul>
                                  </div>                                             
                                </div>
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">    
                                    <li class="active">
                                      <p><span>Comentarios</span></p>                                   
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-4"> 
                                  <p><span>No hay campo en la BD</span></p>                                   
                                </div>
                                <div class="col-sm-4">
                                  <div class="col-sm-6">
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Plazo de Pagos de Facturas %</span>        
                                        </li>                                                                      
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                     <ul>    
                                        
                                        <li>
                                          <span>ddddd</span>            
                                        </li>                                   
                                    </ul>                             
                                  </div>
                                </div>
                            </div>

                            <div class="group-rom panel-body room-box">
                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">    
                                    <li class="active"> 
                                      <span>Foto Proyecto (link ruta) </span>
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-4">
                                  <span>No hay campo en la BD</span>                                    
                                </div>
                                <div class="col-sm-4">
                                  <div class="col-sm-6">
                                    <ul class="chat-list">    
                                        <li class="active">
                                          <span>Fecha de Corte</span>            
                                        </li>
                                                                      
                                    </ul>
                                  </div>
                                  <div class="col-sm-6">
                                     <ul>    
                                        
                                        <li>
                                          <span>ddddd</span>            
                                        </li>                                   
                                    </ul>                             
                                  </div>
                                </div>
                            </div>

                            <div class="group-rom panel-body room-box">                                 
                                <div class="col-sm-4">
                                  <ul class="chat-list">    
                                    <li class="active"> 
                                      <span> Observaciones </span>            
                                    </li>
                                  </ul>
                                </div>
                                <div class="col-sm-8"> 
                                  <span>No hay campo en la BD.</span></div>                              
                            </div>

                          </div> 
                          <?php } }?>
                  </aside>
     
              </div>
              <!-- page end-->
    <?php  } ?>

  </section>
