
  <section id="container" class="">
      <!--header start-->

      <!--header end-->
  
      <!--main content start-->
    
              <!-- page start-->
              <div class="chat-room">
<!--                   <aside class="left-side">
                      <div class="user-head">
                          <i class="fa fa-comments-o"></i>
                          <h3>FlatChat</h3>
                      </div>
                      <ul class="chat-list">
                          <li class="">
                              <a class="lobby" href="lobby.html">
                                  <h4>                                     
                                      Nombre del Proyecto
                                  </h4>
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                       
                                <span>Descripcion del Proyecto</span>                         
                              </a>
                          </li>
                          <li class="active">
                              <a href="chat_room.html">                                
                                  <span>Propietario</span>                                
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                          
                                  <span>Unnidad Minera</span>                           
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                            
                                  <span>Tipo de Servicio</span>                               
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                                  
                                  <span>Gerente de Proyecto</span>                                
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                             
                                  <span>Jefe de Proyecto 1</span>                             
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                           
                                  <span>Jefe de Proyecto 2</span>                                
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                                
                                  <span>Control Documentario</span>                                 
                              </a>
                          </li>
                          <li>
                              <a href="chat_room.html">                              
                                  <span>Control Proyecto</span>                               
                              </a>
                          </li>

                      </ul>
                      <ul class="chat-list chat-user">

                          <li>
                              <a href="#">
                                  <i class="fa fa-circle text-success"></i>
                                  <span>Jonathan Smith</span>
                                  <i class="fa fa-times pull-right"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#">
                                  <i class="fa fa-circle text-success"></i>
                                  <span>Jhon Doe</span>
                                  <i class="fa fa-times pull-right"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#">
                                  <i class="fa fa-circle text-muted"></i>
                                  <span>Franklin kally</span>
                                  <i class="fa fa-times pull-right"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#">
                                  <i class="fa fa-circle text-danger"></i>
                                  <span>Anjelina Joe</span>
                                  <i class="fa fa-times pull-right"></i>
                              </a>
                          </li>

                      </ul>
                      <footer>
                              <a class="chat-avatar" href="javascript:;">
                                  <img alt="" src="img/mail-avatar.jpg">
                              </a>
                              <div class="user-status">
                                  <i class="fa fa-circle text-success"></i>
                                  Available
                              </div>
                              <a class="chat-dropdown pull-right" href="javascript:;">
                                  <i class="fa fa-chevron-down"></i>
                              </a>
                      </footer>
                  </aside> -->
                  <aside class="mid-side">
                      <div class="chat-room-head">
                          <h3>Informacion</h3>
                     
                      </div>

                          <div class="group-rom">
                              <div class="col-sm-2">Jonathan Smith</div>
                              <div class="col-sm-5">Jonathan Smith</div>
                              <div class="col-sm-2">
                                <ul>    
                                    <li>
                                      <span>N de Proyecto</span>            
                                    </li>
                                    <li>
                                      <span>N de Propuesta</span>            
                                    </li>                                   
                                </ul>
                              </div>
                              <div class="col-sm-3">
                                 <ul>    
                                    <li>
                                      <span>1508-125</span>            
                                    </li>
                                    <li>
                                      <span>1508-125-DNA</span>            
                                    </li>                                   
                                </ul>                             
                              </div>

                      
                          </div>
                          <div class="group-rom">
                              <div class="col-sm-2 odd" >
                                <p>Descripcion del Proyecto</p>
                              </div>
                              <div class="col-sm-8 odd" >
                                <ul>    
                                    <li>
                                      <span>N de Proyecto</span>            
                                    </li>                                                                  
                                </ul>
                              </div>                              
                          </div>

                          <div class="group-rom">
                              <div class="col-sm-2">
                                <ul class="chat-list">
                                    <li class="active">
                                        <a href="chat_room.html">                                
                                            <span>Propietario</span>                                
                                        </a>
                                    </li>
                                    <li>
                                        <a href="chat_room.html">                          
                                            <span>Unnidad Minera</span>                           
                                        </a>
                                    </li>
                                    <li>
                                        <a href="chat_room.html">                            
                                            <span>Tipo de Servicio</span>                               
                                        </a>
                                    </li>
                                <ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul class="chat-list">
                                    <li class="">
                                        <a class="chat_room.html">                       
                                                compania
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="chat_room.html">                                      
                                                santa rosa
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="chat_room.html">                                              
                                                geotecnia
                                        </a>
                                    </li>
                                  <ul>
                              </div>
                              <div class="col-sm-2">Planificado</div>
                              <div class="col-sm-2">Real</div>
                          </div>

                          
                              
                          </div>
                          <div class="group-rom">
                              <div class="col-sm-2">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                mendoza
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                negron
                                        </a>
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                mendoza
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                negron
                                        </a>
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-2">Fecha de Inicio</div>
                              <div class="col-sm-1">ddww</div>
                              <div class="col-sm-2">Fecha de Cierre</div>
                              <div class="col-sm-1">12:32</div>
                          </div>
                          <div class="group-rom">
                              <div class="col-sm-2">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-4">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                  </ul>
                              </div>
                              <div class="col-sm-2">Fecha de Inicio</div>

                              <div class="col-sm-1">ddww</div>
                              <div class="col-sm-2">Fecha de Cierre</div>
                              <div class="col-sm-1">12:32</div>
                          </div>

                          <div class="group-rom">
                            <div class="chat-room-head">
                              <h3>Informacion Comercial</h3>                     
                            </div>
                          </div>

                          <div class="group-rom">
                              <div class="col-sm-4">
                                 <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>                                  
                                  </ul>
                              </div>
                              <div class="col-sm-4">
                                <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                    <li class="">
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>
                                    </li>
                                    <li class="">
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>   
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li> 
                                    <li class="">
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>  
                                    </li>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                    <li class="">
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>
                                      <div class="col-sm-4">dd</div>  
                                    </li>
                                    
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                                                    
                                </ul>
                              </div>
                              <div class="col-sm-4">
                                <div class="col-sm-6">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>                                  
                                  </ul>
                                </div>

                                <div class="col-sm-6">
                                  <ul>
                                    <li class="">
                                        <a class="lobby" href="lobby.html">                                      
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>
                                     <li class="">
                                        <a class="lobby" href="lobby.html">                                              
                                                Nombre del Proyecto
                                        </a>
                                    </li>                                  
                                  </ul>
                                </div>
                              </div>

                          </div>



<!--                           <div class="group-rom">
                              <div class="first-part odd">Jonathan Smith</div>
                              <div class="second-part"><a href="#">search_scb_dialog.jpg</a> <span class="text-muted">46.8KB</span> <p>
                                  <img src="img/chat-attach.jpg" alt=""></p></div>
                              <div class="third-part">12:32</div>
                          </div>
                          <div class="group-rom">
                              <div class="first-part">Anjelina Joe</div>
                              <div class="second-part">Fantastic job, love it :)</div>
                              <div class="third-part">12:32</div>
                          </div>
                          <div class="group-rom">
                              <div class="first-part odd">Jonathan Smith</div>
                              <div class="second-part">Thanks</div>
                              <div class="third-part">12:33</div>
                          </div>

                      <footer>
                          <div class="chat-txt">
                              <input type="text" class="form-control">
                          </div>
                          <div class="btn-group">
                              <button type="button" class="btn btn-white"><i class="fa fa-meh-o"></i></button>
                              <button type="button" class="btn btn-white"><i class=" fa fa-paperclip"></i></button>
                          </div>
                          <button class="btn btn-danger">Send</button>
                      </footer> -->
                  </aside>
     
              </div>
              <!-- page end-->
      

  </section>
