		<div class="panel">
			<h1 class="panel-heading">Acciones</h1>
			<div class="panel-body">
				<div class="col-md-6 m-bot15">
					<a href="#/curvas">
						<button type="button" class="btn btn-primary btn-sm">
							CurvaS
						</button>
					</a>
					<a href="#/panel">
						<button type="button" class="btn btn-primary btn-sm">
							Rates
						</button>
					</a>
				</div>
			</div>
		</div>

