
      <!--sidebar end-->

      <!--main content start-->

              <!-- page start-->
              <div class="row">
                 
                  <div class="col-md-9">
                      <section class="panel">
                          <div class="panel-body">
                              <div class="pro-sort">
                                  <label class="pro-lab">Sort By</label>
                                  <select class="styled" >
                                      <option>Default Sorting</option>
                                      <option>Popularity</option>
                                      <option>Average Rating</option>
                                      <option>Newness</option>
                                      <option>Price Low to High</option>
                                      <option>Price High to Low</option>
                                  </select>
                              </div>
                              <div class="pro-sort">
                                  <label class="pro-lab">Show</label>
                                  <select class="styled" >
                                      <option>Result Per Page</option>
                                      <option>2 Per Page</option>
                                      <option>4 Per Page</option>
                                      <option>6 Per Page</option>
                                      <option>8 Per Page</option>
                                      <option>10 Per Page</option>
                                  </select>
                              </div>

                              <div class="pull-right">
                                  <ul class="pagination pagination-sm pro-page-list">

                                      <li><a href="#">1</a></li>
                                      <li><a href="#">2</a></li>
                                      <li><a href="#">3</a></li>
                                      <li><a href="#">»</a></li>
                                  </ul>
                              </div>
                          </div>
                      </section>

                      <div class="row product-list">

                      <table class="table table-hover p-table">

                        <?php
                        $c=1;
                        foreach ($this->listaproyecto as $lista) {
                        ?>  
                     

                        <tr>
                              <td class="p-name">
                                  <a href="project_details.html"><?php echo $lista['codigo_prop_proy']; ?></a>
                                  <br>
                                  <small>Created 27.11.2014</small>
                              </td>                            
                   
                              <!--<td>
                                  <span class="label label-primary">Active</span>
                              </td> -->

                              <td>
                                <select id="estado" name="estado" required="required">
                                    <option value="A">Activo</option>
                                    <option value="C">Cerrado</option>
                                    <option value="CA">Cancelado</option>
                                    <option value="PA">Paralizado</option>
                                </select>                              
                              </td>

                              <td>
                                  <a href="project_details.html" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                  <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                  <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                              </td>
                          </tr>

                              <!--<div class="col-md-4">
                                <section class="panel">
                                        <div class="pro-img-box">
                                            <img src="img/gallery/4.jpg" alt=""/>
                                                                         
                                        </div>                             

                                        <div class="panel-body">
                                                <div class="bio-chart">                                              
                                                    <h4 class="red"><?php //echo $lista['codigo_prop_proy']; ?></h4>                         
                                                    <h4 class="red"><?php //echo $lista['proyectoid']; ?></h4>                         
                                                </div>
                                                <div class="bio-desk">
                                                    
                                                    <p><?php //echo $lista['nombre_proyecto']; ?></p>                                           
                                                    <p><?php //echo $lista['monto_total']; ?></p>
                                                    <p><?php //echo $lista['fecha_inicio']; ?></p>
                                                    <p><?php //echo $lista['fecha_cierre']; ?></p>
                                                  
                                                </div>
                                        </div>
                                        <ul class="nav nav-pills nav-stacked">
                                            <li><a href="profile-activity.html"> <i class="fa fa-calendar"></i> Equipo <span class="label label-danger pull-right r-activity">9</span></a></li>
                                            <li class="active"><a href="profile.html"> <i class="fa fa-user"></i> Cliente</a></li>
                                            <li><a href="profile-edit.html"> <i class="fa fa-edit"></i> Reporte</a></li>
                                        </ul>
                                </section>
                              </div> -->

                        <?php
                        $c++;
                        }
                        ?>

                        </table>
                        </div>       

                  </div>
              </div>

              <!-- page end-->

      <!--main content end-->

      <!-- Right Slidebar start -->
      <div class="sb-slidebar sb-right sb-style-overlay">
          <h5 class="side-title">Online Customers</h5>
          <ul class="quick-chat-list">
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/chat-avatar2.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>John Doe</strong>
                          <small>Dream Land, AU</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/chat-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-important">3</span>
                          </div>
                          <strong>Jonathan Smith</strong>
                          <small>United States</small>
                      </div>
                  </div><!-- media -->
              </li>

              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/pro-ac-1.png" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-success">5</span>
                          </div>
                          <strong>Jane Doe</strong>
                          <small>ABC, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/avatar1.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>Anjelina Joli</strong>
                          <small>Fockland, UK</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/mail-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-warning">7</span>
                          </div>
                          <strong>Mr Tasi</strong>
                          <small>Dream Land, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
          </ul>
          <h5 class="side-title"> pending Task</h5>
          <ul class="p-task tasks-bar">
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">40%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">40% Complete (success)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Database Update</div>
                          <div class="percent">60%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                              <span class="sr-only">60% Complete (warning)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Iphone Development</div>
                          <div class="percent">87%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
                              <span class="sr-only">87% Complete</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Mobile App</div>
                          <div class="percent">33%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
                              <span class="sr-only">33% Complete (danger)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">45%</div>
                      </div>
                      <div class="progress progress-striped active">
                          <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                              <span class="sr-only">45% Complete</span>
                          </div>
                      </div>

                  </a>
              </li>
              <li class="external">
                  <a href="#">See All Tasks</a>
              </li>
          </ul>
      </div>
      <!-- Right Slidebar end -->



    <!--common script for all pages-->
    <script src="js/common-scripts.js"></script>

      <script type="text/javascript">

          $(document).ready(function() {

              $(function(){
                  $('select').customSelect();
              });
          });


      </script>

      <script>
          $("#estado").change(function(){
            // var $td = $(this).parent();
            // var $tr = $td.parent();
            // if ( $(this).val() != '') {
            //   _save($(this).val(),$tr);
            // }
            //alert('kkkk');

          });


      // function _save($value,$parent){

      //   var $params = {};
      //   $params['codigo_prop_proy'] = $.trim($parent.attr('codigo_prop_proy'));  
      //   $params['proyectoid']  = $.trim($parent.attr('proyectoid'));   
      //   $params['propuestaid'] = $.trim($parent.attr('propuestaid'));  
      //   $params['revision'] = $.trim($parent.attr('revision'));  
      //   $params['oid'] = $.trim($parent.attr('oid'));  
      //   $params['nombre_proyecto']  = $.trim($parent.attr('nombre_proyecto')); 
      //   $params['gerente_proyecto'] = $.trim($parent.attr('gerente_proyecto'));
      //   $params['control_proyecto'] = $.trim($parent.attr('control_proyecto'));
      //   $params['control_documentario'] = $.trim($parent.attr('control_documentario'));
      //   $params['estado'] = $.trim($parent.attr('estado'));
      //   $params['tipo_proyecto'] = $.trim($parent.attr('tipo_proyecto'));
      //   $params['paisid'] = $.trim($parent.attr('paisid'));
      

      //   result =  '';
      //   for (var prop in $params ) {
      //           result += '' + prop + '/' + $params[prop]  + '/'; 
      //       }
      //   result = result.substring(0, result.length-1);
      //   var url = "/proyecto/index/cambiarestado/"+result;
      //   $.ajax({
      //     url : url,
      //     async:false,
      //     success: function($data){
      //       if ($data.status == true ) {


      //       };
      //     },
      //     error: function ($error){
      //       alert("!Vaya¡ Ocurrio un Error al Cambiar Tipo de Curso");
      //     }
      //   });
      //   $params = {};
      //   return true;

      // }

      </script>


