
      <!--sidebar end-->

      <!--main content start-->
              <!-- page start-->
              <div class="row">
                 
                  
                  <div class="col-md-9">
                      <section class="panel">
                      <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                  <div class="input-group"><input type="text" placeholder="Buscar Propuesta" class="input-sm form-control"> <span class="input-group-btn">
                                  <button type="button" class="btn btn-sm btn-success"> Buscar!</button> </span></div>
                              </div>
                          </div>
                      </div>
                          <div class="panel-body">
                              <div class="pro-sort">
                                  <label class="pro-lab">Sort By</label>
                                  <select class="styled" >
                                      <option>Default Sorting</option>
                                      <option>Popularity</option>
                                      <option>Average Rating</option>
                                      <option>Newness</option>
                                      <option>Price Low to High</option>
                                      <option>Price High to Low</option>
                                  </select>
                              </div>
                              <div class="pro-sort">
                                  <label class="pro-lab">Show</label>
                                  <select class="styled" >
                                      <option>Result Per Page</option>
                                      <option>2 Per Page</option>
                                      <option>4 Per Page</option>
                                      <option>6 Per Page</option>
                                      <option>8 Per Page</option>
                                      <option>10 Per Page</option>
                                  </select>
                              </div>

                              <div class="pull-right">
                                  <ul class="pagination pagination-sm pro-page-list">

                                      <li><a href="#">1</a></li>
                                      <li><a href="#">2</a></li>
                                      <li><a href="#">3</a></li>
                                      <li><a href="#">»</a></li>
                                  </ul>
                              </div>
                          </div>
                      </section>

                      <div class="row product-list">

                      <table class="table table-hover p-table">

                        <?php
                        $c=0;
                        foreach ($this->listaproyecto as $lista) {
                        ?>                   

                        <tr>
                              <td class="p-name">
                                  <a href="project_details.html"><?php echo $lista['codigo_prop_proy']; ?></a>
                                  <a href="project_details.html"><?php echo $lista['proyectoid']; ?></a>

                                  <br>
                                  <small>Created 27.11.2014</small>
                              </td>
                              <td>
                                <select id="estado_<?php echo $c?>" name="estado">
                                  <option value="">Seleccione</option>
                                  <option value="A" <?php echo ($lista['estado'] == 'A')?'selected': '' ?> >Activo</option>
                                  <option value="C" <?php echo ($lista['estado'] == 'C')?'selected': '' ?> >Cerrado</option>
                                  <option value="CA" <?php echo ($lista['estado'] == 'CA')?'selected': '' ?> >Cancelado</option>
                                  <option value="PA" <?php echo ($lista['estado'] == 'PA')?'selected': '' ?> >Paralizado</option>

                                </select>
                              </td>

                              <td>
                                  <a href="project_details.html" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                  <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                  <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                              </td>

                              <script>
                                    $("#estado_<?php echo $c?>").change(function(){

                                      var $estado=$(this).val();
                                      var $codigo_prop_proy="<?php echo $lista['codigo_prop_proy']?>"
                                      var $proyectoid="<?php echo $lista['proyectoid']?>" 
                                      var $propuestaid="<?php echo $lista['propuestaid']?>" 
                                      var $revision="<?php echo $lista['revision']?>"
                                      var $oid="<?php echo $lista['oid']?>"
                                      var $nombre_proyecto="<?php echo $lista['nombre_proyecto']?>" 
                                      var $gerente_proyecto="<?php echo $lista['gerente_proyecto']?>"
                                      var $control_proyecto="<?php echo $lista['control_proyecto']?>"
                                      var $control_documentario="<?php echo $lista['control_documentario']?>"                                     
                                      var $tipo_proyecto="<?php echo $lista['tipo_proyecto']?>"
                                      var $paisid="<?php echo $lista['paisid']?>"
                                      var $fecha_inicio="<?php echo $lista['fecha_inicio']?>"
                                     
                                      url="/proyecto/index/cambiarestado/proyectoid/"+$proyectoid+"/propuesta/"+$propuestaid+"/nombre_proyecto/"+$nombre_proyecto+"/codigo_prop_proy/"+$codigo_prop_proy+"/estado/"+$estado+"/revision/"+$revision+"/oid/"+$oid+"/gerente_proyecto/"+$gerente_proyecto+"/control_proyecto/"+$control_proyecto+"/control_documentario/"+$control_documentario+"/tipo_proyecto/"+$tipo_proyecto+"/paisid/"+$paisid+"/fecha_inicio/"+$fecha_inicio;
                                      $("#loadingcourses").load(url);

                                    });  
                              </script>

                              <script>
                                    $("#deletecourse_<?php echo $c?>").click(function(){                                      
                                      var $codigo_prop_proy="<?php echo $lista['codigo_prop_proy']?>"
                                      var $proyectoid="<?php echo $lista['proyectoid']?>" 
                                      var $propuestaid="<?php echo $lista['propuestaid']?>" 
                                      var $revision="<?php echo $lista['revision']?>"
                                                                           
                                      url="/proyecto/index/delete/proyectoid/"+$proyectoid+"/propuesta/"+$propuestaid+"/codigo_prop_proy/"+$codigo_prop_proy+"/revision/"+$revision;
                                      //alert(url);
                                      //$("#deleteproyecto").load(url);
                                      location.href="/proyecto/index/listar/"; 
                                        $.ajax({
                                              type: 'POST',
                                              url: url,
                                              data: $(this).serialize(),
                                              success: function(data) {                                                    
                                                      $("#deleteproyecto").html(data);
                                                 
                                              }
                                              
                                        });       

                                    });  
                              </script>



                          </tr>

                            
                        <?php
                        $c++;
                        }
                        ?>

                        </table>
                        </div>       

                  </div>
              </div>

              <!-- page end-->
      <div id="loadingcourses"></div> 
      <div id="deleteproyecto"></div> 

      <!--main content end-->

      <!-- Right Slidebar start -->
      <div class="sb-slidebar sb-right sb-style-overlay">
          <h5 class="side-title">Online Customers</h5>
          <ul class="quick-chat-list">
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/chat-avatar2.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>John Doe</strong>
                          <small>Dream Land, AU</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/chat-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-important">3</span>
                          </div>
                          <strong>Jonathan Smith</strong>
                          <small>United States</small>
                      </div>
                  </div><!-- media -->
              </li>

              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/pro-ac-1.png" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-success">5</span>
                          </div>
                          <strong>Jane Doe</strong>
                          <small>ABC, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/avatar1.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>Anjelina Joli</strong>
                          <small>Fockland, UK</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="/img/mail-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-warning">7</span>
                          </div>
                          <strong>Mr Tasi</strong>
                          <small>Dream Land, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
          </ul>
          <h5 class="side-title"> pending Task</h5>
          <ul class="p-task tasks-bar">
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">40%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">40% Complete (success)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Database Update</div>
                          <div class="percent">60%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                              <span class="sr-only">60% Complete (warning)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Iphone Development</div>
                          <div class="percent">87%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
                              <span class="sr-only">87% Complete</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Mobile App</div>
                          <div class="percent">33%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
                              <span class="sr-only">33% Complete (danger)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">45%</div>
                      </div>
                      <div class="progress progress-striped active">
                          <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                              <span class="sr-only">45% Complete</span>
                          </div>
                      </div>

                  </a>
              </li>
              <li class="external">
                  <a href="#">See All Tasks</a>
              </li>
          </ul>
      </div>
      <!-- Right Slidebar end -->



    <!--common script for all pages-->
    <script src="js/common-scripts.js"></script>

      <script type="text/javascript">

          $(document).ready(function() {

              $(function(){
                  $('select').customSelect();
              });
          });


      </script>



