<?php 
  $is_area=$this->is_area;
  $is_gerente=$this->is_gerente;
  $dni=$this->dni;
?>
<section class="panel">
    <header class="panel-heading">
        Lista de Proyectos
    <span class="pull-right">
        <a id="mostrar_activo" class=" btn btn-success btn-xs"> Activo</a>
        <a id="mostrar_cerrado" class=" btn btn-warning  btn-xs"> Cerrado</a>
        <a id="mostrar_cancelado" class=" btn btn-primary  btn-xs" style="background-color: #59ace2;color: #fff;"> Cancelado</a>
        <a id="mostrar_paralizado" class=" btn btn-danger  btn-xs"> Paralizado</a>
    </span>
    </header>
</section>
<section class="panel"  >
    <?php if($is_area=='26') { ?> 
    <div class="panel-body" style="padding-bottom: 2px; padding-top: 5px;">
        <div class="row">
            <div class="col-md-12">   
                <a href="/proyecto/index/nuevo" class=" btn btn-primary btn-sm" > Crear Proyecto</a>
            </div>
        </div>       
    </div>
    <?php } ?>
    <div id="Proyecto_Activa">
        <table class="table table-hover p-table datatable-order-search">
            <thead>
            <tr>  
                <th style="width: 10%;">Código</th>
                <th style="width: 20%;">Cliente</th>
                <th style="width: 35;">Nombre</th>
                <th style="width: 10%;">Gerente Proyecto</th>
                <th style="width: 10%;">Control Proyecto</th>
                <th style="width: 10%;">Control Documentario</th>
                <th style="width: 10%;">Estado</th>
                    <?php  
                    if($is_area=='26')
                    { ?>
                    <th style="width: 10%;">Acciones</th>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <th style="width: 5%;">Acciones</th>
                        <?php }
                       
                    } ?>
            </tr>
            </thead>
            <?php
            $c=0;
            foreach ($this->listaproyecto as $lista) {
                if ($lista['estado_proyecto']=='A'){?>                   
                <tr>
                    <td class="p-name">
                        <a href="#"><?php echo $lista['proyectoid']; 

                        ?></a>  
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_comercial']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php  
                            $porciones = explode(".", $lista['gerente_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_documentario']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
                    { ?>
                    <td>
                        <a class=" btn btn-success btn-xs" style="width: 72px;">Activo</a> <br>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false" style="width: 72px;">Modificar<span class="caret"></span></button>

                            <ul role="menu" class="dropdown-menu">
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>">Cerrado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>     
                            </ul>
                        </div>
                    </td>
                    <?php } 
                    else { ?>
                    <td>
                       <a class=" btn btn-success btn-xs">Activo</a>
                    </td>
                    <?php } 
                    if($is_area=='26')
                    { ?>
                    <td>
                        <a href="/proyecto/index/verproyecto/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                        <a href="/control#/detalle/proyecto/<?php echo $lista['proyectoid']?>" class="btn btn-primary btn-xs"><i class="fa fa-asterisk" title="Control"></i></a>
                        <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
   
                    </td>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <td><center>
                                <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a></center>
                            </td>
                        <?php }
                       
                    } $c++;}}?>
        </table>
    </div>

    <div id="Proyecto_Cancelado">

          <table class="table table-hover p-table datatable-order-search">
            <thead>
            <tr>  
                <th style="width: 10%;">Código</th>
                <th style="width: 20%;">Cliente</th>
                <th style="width: 35;">Nombre</th>
                <th style="width: 10%;">Gerente Proyecto</th>
                <th style="width: 10%;">Control Proyecto</th>
                <th style="width: 10%;">Control Documentario</th>
                <th style="width: 15%;">Estado</th>
                    <?php  
                    if($is_area=='26')
                    { ?>
                    <th style="width: 10%;">Acciones</th>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <th style="width: 5%;">Acciones</th>
                        <?php }
                       
                    } ?>
            </tr>
            </thead>
            <?php
            $c=0;
            foreach ($this->listaproyecto as $lista) {
                if ($lista['estado_proyecto']=='CA'){?>                   
                <tr>
                    <td class="p-name">
                        <a href="#"><?php echo $lista['proyectoid']; 

                        ?></a>  
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_comercial']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php  
                            $porciones = explode(".", $lista['gerente_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_documentario']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
                    { ?>
                    <td>
                        <a class=" btn btn-success btn-xs">Activo</a>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>

                            <ul role="menu" class="dropdown-menu">
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>">Cerrado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>     
                            </ul>
                        </div>
                    </td>
                    <?php } 
                    else { ?>
                    <td>
                       <a class=" btn btn-success btn-xs">Activo</a>
                    </td>
                    <?php } 
                    if($is_area=='26')
                    { ?>
                    <td>
                        <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                        <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
                        <!-- <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a> -->
                    </td>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <td><center>
                                <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a></center>
                            </td>
                        <?php }
                       
                    } $c++;}}?>
        </table>
    </div>


  <div id="Proyecto_Paralizado">

        <table class="table table-hover p-table datatable-order-search">
            <thead>
            <tr>  
                <th style="width: 10%;">Código</th>
                <th style="width: 20%;">Cliente</th>
                <th style="width: 35;">Nombre</th>
                <th style="width: 10%;">Gerente Proyecto</th>
                <th style="width: 10%;">Control Proyecto</th>
                <th style="width: 10%;">Control Documentario</th>
                <th style="width: 15%;">Estado</th>
                    <?php  
                    if($is_area=='26')
                    { ?>
                    <th style="width: 10%;">Acciones</th>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <th style="width: 5%;">Acciones</th>
                        <?php }
                       
                    } ?>
            </tr>
            </thead>
            <?php
            $c=0;
            foreach ($this->listaproyecto as $lista) {
                if ($lista['estado_proyecto']=='PA'){?>                   
                <tr>
                    <td class="p-name">
                        <a href="#"><?php echo $lista['proyectoid']; 

                        ?></a>  
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_comercial']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php  
                            $porciones = explode(".", $lista['gerente_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_documentario']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
                    { ?>
                    <td>
                        <a class=" btn btn-success btn-xs">Activo</a>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>

                            <ul role="menu" class="dropdown-menu">
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>">Cerrado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>     
                            </ul>
                        </div>
                    </td>
                    <?php } 
                    else { ?>
                    <td>
                       <a class=" btn btn-success btn-xs">Activo</a>
                    </td>
                    <?php } 
                    if($is_area=='26')
                    { ?>
                    <td>
                        <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                        <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
                        <!-- <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a> -->
                    </td>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <td><center>
                                <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a></center>
                            </td>
                        <?php }
                       
                    } $c++;}}?>
        </table>
    </div>


  <div id="Proyecto_Cerrado">

        <table class="table table-hover p-table datatable-order-search">
            <thead>
            <tr>  
                <th style="width: 10%;">Código</th>
                <th style="width: 20%;">Cliente</th>
                <th style="width: 35;">Nombre</th>
                <th style="width: 10%;">Gerente Proyecto</th>
                <th style="width: 10%;">Control Proyecto</th>
                <th style="width: 10%;">Control Documentario</th>
                <th style="width: 15%;">Estado</th>
                    <?php  
                    if($is_area=='26')
                    { ?>
                    <th style="width: 10%;">Acciones</th>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <th style="width: 5%;">Acciones</th>
                        <?php }
                       
                    } ?>
            </tr>
            </thead>
            <?php
            $c=0;
            foreach ($this->listaproyecto as $lista) {
                if ($lista['estado_proyecto']=='C'){?>                   
                <tr>
                    <td class="p-name">
                        <a href="#"><?php echo $lista['proyectoid']; 

                        ?></a>  
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_comercial']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
                    </td>
                    <td>
                        <a href="#"><?php  
                            $porciones = explode(".", $lista['gerente_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_proyecto']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <td>
                        <a href="#"><?php 
                            $porciones = explode(".", $lista['control_documentario']);
                            foreach ($porciones as $value) {
                                echo (ucwords($value));  echo " ";
                            }
                        ?></a>
                    </td>
                    <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
                    { ?>
                    <td>
                        <a class=" btn btn-success btn-xs">Activo</a>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>

                            <ul role="menu" class="dropdown-menu">
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>">Cerrado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                                <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>     
                            </ul>
                        </div>
                    </td>
                    <?php } 
                    else { ?>
                    <td>
                       <a class=" btn btn-success btn-xs">Activo</a>
                    </td>
                    <?php } 
                    if($is_area=='26')
                    { ?>
                    <td>
                        <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                        <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
                        <!-- <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a> -->
                    </td>
                    <?php } 
                    else
                    { 
                        if($is_gerente=='S' or $dni == '08051678')
                        { ?>
                            <td><center>
                                <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a></center>
                            </td>
                        <?php }
                       
                    } $c++;}}?>
        </table>
    </div>




  <div id="Proyecto_Eliminado">
    <table class="table table-hover p-table datatable-order-search">
          <thead>
            <tr>  
             <th style="width: 10%;">Código</th>
              <th style="width: 20%;">Cliente</th>
              <th style="width: 35;">Nombre</th>
              <th style="width: 10%;">Gerente</th>
              <th style="width: 15%;">Estado</th>
              <th style="width: 10%;">Acciones</th>
            </tr>
          </thead>
          <?php
            $c=0;
          foreach ($this->listaproyecto as $lista) {
               if ($lista['estado']=='E'){
            ?>                   
            <tr>
              <td class="p-name">
                
                <a href="#"><?php echo $lista['proyectoid']; ?></a>  
              </td>
              <td>
                 <?php
                 $propuestaid=$lista['propuestaid'];
                 $revision=$lista['revision'];
                 $codigo=$lista['codigo_prop_proy'];

                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexPropuestaxRevisionxCodigo($propuestaid,$revision,$codigo);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
              </td>
              <td>
                <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
              </td>
              <td>
                <a href="#"><?php echo $lista['gerente_proyecto']; ?></a>
              </td>
              <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
              { ?>  
              <td>               
                  <span class="label label-success label-mini">Eliminado</span>
                  <div class="btn-group">
                      <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                      <ul role="menu" class="dropdown-menu">
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cerrado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>
                                      
                      </ul>
                  </div>
              </td>
              <?php } ?> 

              <?php 
              if($is_area=='26')
                { ?>
                <td>
                  <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                  <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
                  <!-- <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a> -->
                </td>
                <?php } 
                else
                { 
                  if($is_gerente=='S' or $dni == '08051678')
                  { ?>
                    <td>
                      <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                    </td>
                  <?php }             
                }
              ?>

              </tr>                            
              <?php $c++;}}?>
    </table>
  </div>


    <div id="Proyecto_Total">
  <table class="table table-hover p-table datatable-order-search">
          <thead>
            <tr>  
          <th style="width: 10%;">Código</th>
              <th style="width: 20%;">Cliente</th>
              <th style="width: 35;">Nombre</th>
              <th style="width: 10%;">Gerente</th>
              <th style="width: 15%;">Estado</th>
              <th style="width: 10%;">Acciones</th>
            </tr>
          </thead>
          <?php
            $c=0;
          foreach ($this->listaproyecto as $lista) {
             
            ?>                   
            <tr>
              <td class="p-name">
                
                <a href="#"><?php echo $lista['proyectoid']; ?></a>  
              </td>
              <td>
                 <?php
                 $propuestaid=$lista['propuestaid'];
                 $revision=$lista['revision'];
                 $codigo=$lista['codigo_prop_proy'];

                    $buscacliente = new Admin_Model_DbTable_Cliente();
                    $buscanombre_cliente=$buscacliente->_getClientexPropuestaxRevisionxCodigo($propuestaid,$revision,$codigo);
                    print_r($buscanombre_cliente[0]['nombre_comercial']);
                ?>  
              </td>
              <td>
                <a href="#"><?php echo $lista['nombre_proyecto']; ?></a>
              </td>
              <td>
                <a href="#"><?php echo $lista['gerente_proyecto']; ?></a>
              </td>

              <?php if($is_area=='26' or  $is_gerente=='S' or $dni == '08051678')
              { ?>  
              <td> 
                  <div class="btn-group">
                      <button data-toggle="dropdown" class="btn btn-info dropdown-toggle btn-xs" type="button" aria-expanded="false">Modificar<span class="caret"></span></button>
                      <ul role="menu" class="dropdown-menu">
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/A/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Activo</a></li>
                          <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/C/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cerrado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/CA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Cancelado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/PA/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Paralizado</a></li>
                           <li><a href="/proyecto/index/cambiarestado/proyectoid/<?php echo $lista['proyectoid']?>/propuesta/<?php echo $lista['propuestaid']?>/nombre_proyecto/<?php echo $lista['nombre_proyecto']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/estado/E/revision/<?php echo $lista['revision']?>/oid/<?php echo $lista['oid']?>/gerente_proyecto/<?php echo $lista['gerente_proyecto']?>/control_proyecto/<?php echo $lista['control_proyecto']?>/control_documentario/<?php echo $lista['control_documentario']?>/tipo_proyecto/<?php echo $lista['tipo_proyecto']?>/paisid/<?php echo $lista['paisid']?>/fecha_inicio/<?php echo $lista['fecha_inicio']?>">Eliminado</a></li>
                                      
                      </ul>
                  </div>
              </td>
              <?php } ?> 

              <?php 
              if($is_area=='26')
                { ?>
                <td>
                  <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>/revision/<?php echo $lista['revision']?>/propuesta/<?php echo $lista['propuestaid']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                  <a href="/proyecto/index/editar/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Editar"></i> </a>
                  <!-- <a id="deletecourse_<?php echo $c?>" href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a> -->
                </td>
                <?php
                } 
                else
                { 
                  if($is_gerente=='S' or $dni == '08051678')
                  { ?>
                    <td>
                      <a href="/proyecto/index/ver/proyectoid/<?php echo $lista['proyectoid']?>/codigo_prop_proy/<?php echo $lista['codigo_prop_proy']?>" class="btn btn-primary btn-xs"><i class="fa fa-folder" title="Detalle"></i></a>
                    </td>
                  <?php 
                  }             
                }
              ?>

              </tr>                            
              <?php $c++;}?>
    </table>
  </div>
    <div id="resultado_busqueda"> </div>
</section> 


<script type="text/javascript">
$(document).ready(function(){
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").show();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").hide();        
        $("#resultado_busqueda").hide();

    $("#mostrar_activo").click(function(){             
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").show();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").hide();        
        $("#resultado_busqueda").hide();
    });

      $("#mostrar_cerrado").click(function(){             
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").hide();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").show();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").hide();            
        $("#resultado_busqueda").hide();

    });
       $("#mostrar_cancelado").click(function(){             
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").hide();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").show();
        $("#resultado_busqueda").hide();
    });
        $("#mostrar_paralizado").click(function(){             
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").hide();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").show();
        $("#Proyecto_Cancelado").hide();
        $("#resultado_busqueda").hide();
    });
        $("#mostrar_eliminado").click(function(){             
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").hide();
        $("#Proyecto_Eliminado").show();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").hide();
        $("#resultado_busqueda").hide();

    });

    $("#btn_buscar_proyecto").click(function(){
        var buscar_proyecto = $("#buscar_proyecto").val();
        
        $("#Proyecto_Total").hide();
        $("#Proyecto_Activa").hide();
        $("#Proyecto_Eliminado").hide();
        $("#Proyecto_Cerrado").hide();
        $("#Proyecto_Paralizado").hide();
        $("#Proyecto_Cancelado").hide();
        $("#resultado_busqueda").show();
        if (buscar_proyecto=='')  
        {
            alert("ingrese propuesta a buscar");
        }
        else
        { 
            var url="/proyecto/index/buscar/proyecto/"+buscar_proyecto;   
            
        }
        
        $("#resultado_busqueda").load(url);
    });    

});
  
</script>
<!--
// conflicto con la barra de navegacion lo deshabilite Davis
<script src="/js/common-scripts.js"></script>
-->
<script type="text/javascript">
  $(document).ready(function() {
    $(function(){
      $('select').customSelect();
      });
  });
</script>

<script>
  $(document).ready(function() {
    $('.datatable-order-search').dataTable( {
        "paging":   false,
        "ordering": true,
        "info":     true
    } );

  } );
</script>