

  
              <!-- page start-->
              <section class="panel">
                  <header class="panel-heading">
                      Projects Details
                      <span class="pull-right">
                          <button type="button" id="loading-btn" class="btn btn-warning btn-xs"><i class="fa fa-refresh"></i> Refresh</button>
                      </span>
                  </header>

              </section>
              <div class="row">
                  <div class="col-md-8">
                      <section class="panel">
                          <div class="bio-graph-heading project-heading">
                              <strong> [ Nuevo Proyecto ] </strong>

                          </div>
                          <div class="panel-body bio-graph-info">
                              <!--<h1>New Dashboard BS3 </h1>-->
                              <div class="row p-details">

                                  <form name="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded">

                                  <div class="row">                                 
                                  <!-- <div class="col-sm-1"><input type="button" id="save"/><p>save</p></div> -->
                                    <div class="col-sm-1" id="save" ><br><a class="btn btn-info" href="#">save</a></br></div>
                                    <div class="col-sm-1"><br><a class="btn btn-info" href="/admin/faculty"  >Cancelar</a></br></div>
                                  </div>



                                    <div class="bio-row">
                                        <p><span class="bold">Proyectoid </span>: <?php print $this->form->proyectoid;?></p>
                                    </div>

                                    <div class="bio-row">
                                      <p><span class="bold">Nombre </span>: <?php print $this->form->nombre_proyecto;?></p>
                                    </div>

                                
                                    <div class="bio-row"> 
                                    <span class="bold">Propuesta </span>                                   
                                    <select  id="propuestaid" name="propuestaid" class="form-control">
                                        <option  value="">Seleccione..</option>
                                        <?php
                                        foreach ($this->propuestas  as $propuesta){
                                            ?>
                                            <option value="<?php echo $propuesta['propuestaid']?>"><?php echo $propuesta['nombre_propuesta']?></option>
                                            <?php
                                        }?>
                                    </select>
                                    </div> 

                                    <div class="bio-row">
                                        <span class="bold">Codigo Proyecto </span>
                                        <select disabled id="cod_proy_prop" name="cod_proy_prop" class="form-control">
                                         
                                        </select>
                                    </div>

                                    <div class="bio-row">
                                        <span class="bold">Cliente </span>
                                        <select disabled id="cliente" name="cliente" class="form-control">
                                         
                                        </select>
                                    </div>


                                    <div class="bio-row">
                                        <span class="bold">Unidad Minera </span>
                                        <select disabled id="uminera" name="uminera" class="form-control">
                                          
                                        </select>
                                    </div> 
 

                                    <div class="bio-row">
                                        <span class="bold">Revision </span>
                                        <select disabled  id="revision" name="revision" class="form-control">
                                          
                                        </select>
                                    </div> 
 

                                    <div class="bio-row">
                                      <p><span class="bold">Gerente</span>: <?php print $this->form->gerente_proyecto;?></p>
                                    </div>


                            
                                    <div class="bio-row">
                                      <p><span class="bold">Control/Proyecto</span>: <?php print $this->form->control_proyecto;?></p>
                                    </div>                          


                                    <div class="bio-row">
                                      <p><span class="bold">Descripcion </span>: <?php print $this->form->descripcion;?></p>
                                    </div>

                                    <div class="bio-row">
                                      <p><span class="bold">Fecha Inicio </span>: <?php print $this->form->fecha_inicio;?></p>
                                    </div>


                                    <div class="bio-row">
                                      <p><span class="bold">Control/Documentario </span>: <?php print $this->form->control_documentario;?></p>
                                    </div>

                                    <div class="bio-row">
                                      <p><span class="bold">Estado </span>: <?php print $this->form->estado;?></p>
                                    </div>
                               
                      

                             
                              </div>

                          </div>

                      </section>


                  </div>
                  <div class="col-md-4">
                      <section class="panel">
                          <header class="panel-heading">
                              Projects Description
                          </header>

                          <div class="panel-body">
                              <br/>

                                    <div class="bio-row">
                                      <p><span class="bold">tag: </span>: <?php print $this->form->tag;?></p>
                                    </div>

                                    <div class="bio-row">
                                      <p><span class="bold">tipo_proyecto: </span>: <?php print $this->form->tipo_proyecto;?></p>
                                    </div>

                              </form>
                              <h5 class="bold">Priority</h5>
                              <ul class="nav nav-pills nav-stacked labels-info ">
                                  <li><i class=" fa fa-circle text-danger"></i> High Priority</p></li>
                              </ul>

                              <br/>
                              <h5 class="bold">Project files</h5>
                              <ul class="list-unstyled p-files">
                                  <li><a href=""><i class="fa fa-file-text"></i> Project-document.docx</a></li>
                                  <li><a href=""><i class="fa fa-picture-o"></i> Logo-company.jpg</a></li>
                                  <li><a href=""><i class="fa fa-mail-forward"></i> Email-from-flatbal.mln</a></li>
                                  <li><a href=""><i class="fa fa-file"></i> Contract-10_12_2014.docx</a></li>
                              </ul>
                              <br/>

                              <h5 class="bold">Project Tags</h5>
                              <ul class="p-tag-list">
                                  <li><a href=""><i class="fa fa-tag"></i> Dlor</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Lorem ipsum</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Google</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Excellent</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Dlor</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Lorem ipsum</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Google</a></li>
                                  <li><a href=""><i class="fa fa-tag"></i> Excellent</a></li>
                              </ul>

                              <div class="text-center mtop20">
                                  <a href="#" class="btn btn-sm btn-primary">Add files</a>
                                  <a href="#" class="btn btn-sm btn-warning">Report contact</a>
                              </div>
                          </div>

                      </section>
                  </div>
              </div>
              <!-- page end-->

      <!--main content end-->

      <!-- Right Slidebar start -->
      <div class="sb-slidebar sb-right sb-style-overlay">
          <h5 class="side-title">Online Customers</h5>
          <ul class="quick-chat-list">
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/chat-avatar2.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>John Doe</strong>
                          <small>Dream Land, AU</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/chat-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-important">3</span>
                          </div>
                          <strong>Jonathan Smith</strong>
                          <small>United States</small>
                      </div>
                  </div><!-- media -->
              </li>

              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/pro-ac-1.png" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-success">5</span>
                          </div>
                          <strong>Jane Doe</strong>
                          <small>ABC, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/avatar1.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <strong>Anjelina Joli</strong>
                          <small>Fockland, UK</small>
                      </div>
                  </div><!-- media -->
              </li>
              <li class="online">
                  <div class="media">
                      <a href="#" class="pull-left media-thumb">
                          <img alt="" src="img/mail-avatar.jpg" class="media-object">
                      </a>
                      <div class="media-body">
                          <div class="media-status">
                              <span class=" badge bg-warning">7</span>
                          </div>
                          <strong>Mr Tasi</strong>
                          <small>Dream Land, USA</small>
                      </div>
                  </div><!-- media -->
              </li>
          </ul>
          <h5 class="side-title"> pending Task</h5>
          <ul class="p-task tasks-bar">
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">40%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">40% Complete (success)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Database Update</div>
                          <div class="percent">60%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                              <span class="sr-only">60% Complete (warning)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Iphone Development</div>
                          <div class="percent">87%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
                              <span class="sr-only">87% Complete</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Mobile App</div>
                          <div class="percent">33%</div>
                      </div>
                      <div class="progress progress-striped">
                          <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
                              <span class="sr-only">33% Complete (danger)</span>
                          </div>
                      </div>
                  </a>
              </li>
              <li>
                  <a href="#">
                      <div class="task-info">
                          <div class="desc">Dashboard v1.3</div>
                          <div class="percent">45%</div>
                      </div>
                      <div class="progress progress-striped active">
                          <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                              <span class="sr-only">45% Complete</span>
                          </div>
                      </div>

                  </a>
              </li>
              <li class="external">
                  <a href="#">See All Tasks</a>
              </li>
          </ul>
      </div>
      <!-- Right Slidebar end -->

      <!--footer start-->
 <div id="loadingcourses"></div> 
      <!--footer end-->

<script type='text/javascript'>
     
  $("#propuestaid").change(function(){
    var propuestaid = $(this).val(); 
    //alert(propuestaid);

    url="/proyecto/index/codproyprop/propuesta/"+propuestaid;
    url1="/proyecto/index/cliente/propuesta/"+propuestaid;
    url2="/proyecto/index/uminera/propuesta/"+propuestaid;
    url3="/proyecto/index/revision/propuesta/"+propuestaid;

    $("#cod_proy_prop").html("Cargando....");
    //alert(url);
    $("#cod_proy_prop").load(url);
    $("#cliente").load(url1);
    $("#uminera").load(url2);
    $("#revision").load(url3);

    }); 
</script>

<script type='text/javascript'>      
  $("#save").click(function(){

        var proyectoid = $("#proyectoid").val();
        var nombre_proyecto = $("#nombre_proyecto").val();
        var propuestaid = $("#propuestaid").val();   
        var cod_proy_prop = $("#cod_proy_prop").val();   
        var propuestaid = $("#propuestaid").val();   
        var codeo = $("#codeo").val();   
         
        var cliente = $("#cliente").val();   
        var uminera = $("#uminera").val();   
        var control_proyecto = $("#control_proyecto").val();  
        var revision = $("#revision").val();  
        var gerente_proyecto = $("#gerente_proyecto").val();  
        var tag = $("#tag").val();  
        var tipo_proyecto = $("#tipo_proyecto").val();  

      
        var descripcion = $("#descripcion").val();  
        var fecha_inicio = $("#fecha_inicio").val();  
        var control_documentario = $("#control_documentario").val();  
        var estado = $("#estado").val();  


        url="/proyecto/index/nuevo/proyectoid/"+proyectoid+"/propuesta/"+propuestaid+"/nombre_proyecto/"+nombre_proyecto+"/cod_proy_prop/"+cod_proy_prop+"/proyectoid/"+proyectoid+"/cliente/"+cliente+"/uminera/"+uminera+"/control_proyecto/"+control_proyecto+"/revision/"+revision+"/descripcion/"+descripcion+"/fecha_inicio/"+fecha_inicio+"/control_documentario/"+control_documentario+"/estado/"+estado+"/gerente_proyecto/"+gerente_proyecto+"/tipo_proyecto/"+tipo_proyecto+"/tag/"+tag;
       
          $.ajax({
                type: 'POST',
                url: url,
                data: $(this).serialize(),
                success: function(data) { 
                    $('#loadingcourses').html(data);
                    $('#loadingcourses').hide();
                    location.href="/proyecto/index/listar/";

                }
            });        
    }); 


</script>


