<div class="panel">

	<header>
		<h2>Panel de Control</h2>
  </header>

	<div class="col-md-6">
		<div class="panel">
			<h3>Cantidad de Proyectos</h3>
		
			<h3>Carga Laboral Control Documentario</h3>
			<table class="table table-bordered table-striped table-condensed">
				<thead>
					<th>
						Integrantes
					</th>
					<th>
						En Proceso
					</th>
					<th>
						Stand By
					</th>
					<th>
						Cancelado
					</th>
					<th>
						Cerrado
					</th>
				</thead>
				<tbody>
					<tr ng-repeat="integrante in CD.integrantes track by $index">
						<td>
							{{integrante.uid}}
						</td>
					
					</tr>
				</tbody>
			
			</table>
		</div>
	</div>

	<div class="col-md-6">
		<div class="panel">
			<h1 class="panel-heading">Carga Laboral Control Documentario (En Proceso)</h1>
			<div class="panel-body">
				<canvas id="bar" class="chart chart-bar" data="CD.datos" labels="CD.labels"
					series="CD.series" options="CD.options"></canvas>
			</div>
		</div>
	</div>

	<nav class="col-md-8 panel">
		<div class="col-md-6 panel-body">
			<a href="#/proyectos">
				<button type="button" class="btn btn-default">Listar los Proyectos</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/asignarcd">
				<button type="button" class="btn btn-default">Asignar CD a Proyecto</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/carpetas">
				<button type="button" class="btn btn-default">Ubicación de Carpetas de Proyectos</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/reporte">
				<button type="button" class="btn btn-default">Generar Reporte de Planificación</button>
			</a>
		</div>
	</nav>
</div>




	<div ng-repeat-start="integrante in CD.integrantes track by $index" class="animate-repeat-category">
		<button class="btn btn-primary btn-block btn-sm" ng-click="CD.toggleArea(integrante)">
	    {{integrante.area}}-{{integrante.name}}
	    <!-- {{ category.items }} -->
	    <span class="expand-indicator" ng-show="integrante.expanded">&mdash;</span>
	    <span class="expand-indicator" ng-show="!integrante.expanded">+</span>
	    </button>
	    <button class="btn btn-default" ng-click="CD.open()">Open me!</button>
	</div>

<!--  Item group inside each category -->
    <div class="list-items animate-show-item" ng-show="integrante.expanded">
	    <ul>
          <li ng-repeat="item in integrante.items" class="animate-repeat-item">
            {{item.uid}}
            <span ng-class="{done:item.completed}" ltc-editable class-off="done" ng-model="item.uid"></span>
            <button ng-show="!item.completed" ng-click="CD.completeTask(item)" class="btn btn-success btn-xs">done</button>
            <button ng-show="item.completed" ng-click="CD.uncompleteTask(item)" class="btn btn-warning btn-xs">reset</button>
            <button ng-click="CD.deleteTask(integrante, item)" class="btn btn-danger btn-xs">del</button>
          </li>
        </ul>
          <div class="no-items"><small ng-show="integrante.expanded && integrante.items.length==0">NO ITEMS!</small></div>
    </div>

	<div ng-repeat-end>
	    <button ng-show="category.expanded" class="btn btn-primary btn-block btn-sm animate-show-item" disabled="disabled">/ {{integrante.name}} </button>
	    <hr>
	</div>


	<!-- anadir area -->

	<div class="form-group" ng-class="{'has-error': errorNewCategory}">
        <label for="areaName">Add nueva area:</label>
        <input id="areaName" class="form-control" type="text" placeholder="type area name" ng-model="CD.newAreaName" ng-enter="addArea()" />
    </div>
        <hr>
    <div class="form-group">
        <button ng-click="CD.addArea()" class="btn btn-primary btn-xs">agregar</button>
    </div>
        <hr>

    <!-- anadir personas -->    

    <div class="form-group" ng-class="{'has-error': errorNewTask}">
        <label for="taskName">Add new task to category:</label>
        <input id="taskName" class="form-control" type="text" placeholder="type task name" ng-model="CD.newTaskName" ng-enter="CD.addTask()" />
    </div>
    <div class="form-group">
    	<select class="form-control" ng-model="CD.selectedCategory"           
          ng-options="c.name for c in CD.integrantes"></select>
    </div>

    <div class="form-group">
        <button ng-click="CD.addTask()" class="btn btn-primary btn-xs">agregar personal</button>
    </div>



<div ng-controller="ModalDemoCtrl">
{{algo}}
	<!-- <div ng-repeat="item in items  ">
	   <div class="nombre">{{ item.nombre }}-</div>
	 </div> -->

 
  <!--  <input type="checkbox" ng-model="activo" ng-change="avisar()">
    <p>
        <input type="checkbox" ng-model="clarooscuro" ng-true-value="claro" ng-false-value="oscuro" />
        Este campo tiene el value modificado. Ahora vale {{ vm.clarooscuro }}
    </p>
    <p>
        <input type="button" ng-click="activo=true" value="pulsa para cambiar la propiedad del modelo del primer checkbox a true"> Observarás que aunque el estado pueda cambiar, no se invoca al ng-change de ese primer checkbox.
    </p>   
-->



		<div class="well"><label ng-repeat="role in roles">
		  <input type="checkbox" checklist-model="user.roles" checklist-value="role" ng-model="justAnotherCheckedVar"> {{role.text}}
		</label></div>

		<button class="btn btn-default" ng-click="checkAll()">todos</button>
		<button class="btn btn-default" ng-click="uncheckAll()">ninguno</button>
		<button class="btn btn-default" ng-click="checkFirst()">primero</button>


    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
            <h3 class="modal-title">Im a modal!</h3>
        </div>
        <div class="modal-body">
        		sssss        
	     
            <ul>
                <li ng-repeat="item in items">                 
                    <a ng-click="selected.item = item">{{ item.nombre }}</a>
                </li>
            </ul>
            Selected: <b>{{ selected.item }}</b>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" ng-click="ok()">OK</button>
            <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
        </div>
    </script>
 
    <button class="btn btn-default" ng-click="open()">Open me!</button>
    <button class="btn btn-default" ng-click="open('lg')">Large modal</button>
    <button class="btn btn-default" ng-click="open('sm')">Small modal</button>
    <button class="btn btn-default" ng-click="toggleAnimation()">Toggle Animation ({{ animationsEnabled }})</button>
    <div ng-show="selected">Selection from a modal: {{ selected }}</div>
</div>