<div class="panel">

	<header>
		<h2>Control de Proyecto</h2>
  </header>

<!-- 	<nav class="col-md-8 panel">
		<div class="col-md-6 panel-body">
			<a href="#/proyectos">
				<button type="button" class="btn btn-default">Listar los Proyectos</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/asignarcd">
				<button type="button" class="btn btn-default">Asignar CD a Proyecto</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/carpetas">
				<button type="button" class="btn btn-default">Ubicación de Carpetas de Proyectos</button>
			</a>
		</div>
		<div class="col-md-6 panel-body">
			<a href="#/reporte">
				<button type="button" class="btn btn-default">Generar Reporte de Planificación</button>
			</a>
		</div>
	</nav> -->
</div>




	<div ng-repeat-start="integrante in CD.integrantes track by $index" class="animate-repeat-category">
		<button class="btn btn-primary btn-block btn-sm" ng-click="CD.toggleArea(integrante)">
	    {{integrante.area}}-{{integrante.name}}
	    <!-- {{ category.items }} -->
		    <span class="expand-indicator" ng-show="integrante.expanded">&mdash;</span>
		    <span class="expand-indicator" ng-show="!integrante.expanded">+</span>		   
	    </button>

	 	<button class="btn btn-success" ng-click="CD.launch('confirm',integrante)">Confirm Dialog</button>        
        <button class="btn btn-warning" ng-click="CD.launch('create')">Custom Dialog</button>



	    	<!-- <div ng-controller="ModalDemoCtrl"> -->

			        


<!-- <input type="checkbox" ng-model="role.uid" ng-true-value="true" ng-false-value="false" ng-click="CD.avisar()">{{role.uid}} -->
						

			    <script type="text/ng-template" id="myModalContent.html">
			        <div class="modal-header">
			            <h3 class="modal-title">Im a modal!</h3>
			        </div>
			        <div class="modal-body">

			        	<div class="well">
			        	<label ng-repeat="role in roles">
					
				       	<input type="checkbox" checklist-model="user.rol" checklist-value="role" 
						ng-true-value="true" ng-false-value="false" ng-checked="isChecked(role.uid)" ng-change="sync(bool,role)" ng-model="bool"
						 > {{role.uid}} 

						</label></div>

			        	<button class="btn btn-default" ng-click="checkAll()">todos</button>
						<button class="btn btn-default" ng-click="uncheckAll()">ninguno</button>
						<button class="btn btn-default" ng-click="checkFirst()">primero</button>  
			 
			   			<button class="btn btn-default" ng-click="addcheck()">GUARDAR</button>

			        </div>
			        <div class="modal-footer">
			            <button class="btn btn-primary" ng-click="ok()">OK</button>
			            <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
			        </div>
			    </script>
			 
			    <button class="btn btn-default" ng-click="open()">+</button>
			    <button class="btn btn-default" ng-click="open('lg')">H</button>
			    <button class="btn btn-default" ng-click="open('sm')">+</button>
			    <button class="btn btn-default" ng-click="toggleAnimation()">H ({{ animationsEnabled }})</button>
			    <div ng-show="selected">Selection from a modal: {{ selected }}</div>
			<!-- </div>   -->
	

	</div>

<!--  Item group inside each category -->
    <div class="list-items animate-show-item" ng-show="integrante.expanded">
	    <ul>
          <li ng-repeat="item in integrante.items" class="animate-repeat-item">
            {{item.uid}}
            <span ng-class="{done:item.completed}" ltc-editable class-off="done" ng-model="item.uid"></span>
            <button ng-show="!item.completed" ng-click="CD.completeTask(item)" class="btn btn-success btn-xs">done</button>
            <button ng-show="item.completed" ng-click="CD.uncompleteTask(item)" class="btn btn-warning btn-xs">reset</button>
            <button ng-click="CD.deleteTask(integrante, item)" class="btn btn-danger btn-xs">del</button>
          </li>
        </ul>
          <div class="no-items"><small ng-show="integrante.expanded && integrante.items.length==0">NO ITEMS!</small></div>
    </div>

	<div ng-repeat-end>
	    <button ng-show="category.expanded" class="btn btn-primary btn-block btn-sm animate-show-item" disabled="disabled">/ {{integrante.name}} </button>
	    <hr>
	</div>


	<!-- anadir area -->

	<div class="form-group" ng-class="{'has-error': errorNewCategory}">
        <label for="areaName">Add nueva area:</label>
        <input id="areaName" class="form-control" type="text" placeholder="type area name" ng-model="CD.newAreaName" ng-enter="addArea()" />
    </div>
        <hr>
    <div class="form-group">
        <button ng-click="CD.addArea()" class="btn btn-primary btn-xs">agregar</button>
    </div>
        <hr>

    <!-- anadir personas -->    

    <div class="form-group" ng-class="{'has-error': errorNewTask}">
        <label for="taskName">Add new task to category:</label>
        <input id="taskName" class="form-control" type="text" placeholder="type task name" ng-model="CD.newTaskName" ng-enter="CD.addTask()" />
    </div>
    <div class="form-group">
    	<select class="form-control" ng-model="CD.selectedCategory"           
          ng-options="c.name for c in CD.integrantes"></select>
    </div>

    <div class="form-group">
        <button ng-click="CD.addTask()" class="btn btn-primary btn-xs">agregar personal</button>
    </div>

    <button class="btn btn-primary btn-block btn-sm" ng-click="CD.llevar()">llevar</button>



   		<div class="well">

	    <label ng-repeat="role in CD.roles">
						{{role.uid}}
		<input type="checkbox" ng-checked="CD.isChecked(role.uid)" ng-change="CD.sync(bool,role)" ng-model="bool" ng-true-value="true" ng-false-value="false" >						
		<!-- ng-click="CD.ver()"  -->
		</label></div>