
<?php if($this->bandera=='S') { ?>
<?php
$proyectoid=$this->proyectoid;
$dir = APPLICATION_LIBRARY . "/excel/excel/reader.php";
include ($dir);
$data = new Spreadsheet_Excel_Reader();
$data->setOutputEncoding('CP1251');
$data->read('./upload/proyecto/'.$proyectoid.'-HH.xls');
echo "filas";echo ($data->sheets[0]['numRows']);
echo "columnas";echo ($data->sheets[0]['numCols']);
$columnas=$data->sheets[0]['numCols'];
echo $columnas;

for ($j = 1; $j <= $data->sheets[0]['numCols']; $j++) {
  if (isset( $data->sheets[0]['cells'][1][$j] ))
    { 
      //revisor, revisor principal, gerente
      $categoria=$data->sheets[0]['cells'][1][$j];
      echo $categoria; echo "<br>";
    }
}

for ($i = 2; $i <= $data->sheets[0]['numRows']; $i++) {
  $colsuma=$columnas-1;
  $areaid=$data->sheets[0]['cells'][$i][1];
  $actividadid=$data->sheets[0]['cells'][$i][2];
  $nombre=$data->sheets[0]['cells'][$i][3];
  $suma=$data->sheets[0]['cells'][$i][$colsuma];

  $actividadint=$actividadid;
  if (ctype_digit(trim($actividadint))) {
    $datosactividadpadre["actividadid"]=$actividadid;
    $datosactividadpadre["codigo_actividad"]=$areaid."-".$actividadid;
    $datosactividadpadre["codigo_prop_proy"]=$this->codigo;
    $datosactividadpadre["revision"]=$this->revision;
    $datosactividadpadre["areaid"]=$areaid;
    $datosactividadpadre["proyectoid"]=$this->proyectoid;
    $datosactividadpadre["propuestaid"]=$this->propuestaid;
    $datosactividadpadre["actividad_padre"]='';

    $datosactividadpadre["nombre"]=utf8_encode($nombre);
    $datosactividadpadre["fecha_creacion"]=date("Y-m-d");
    $datosactividadpadre["estado"]='P';
    $datosactividadpadre["duracion_total"]='0';
    $datosactividadpadre["h_propuesta"]=$suma;
$datosactividadpadre["h_extra"]='0';
    $datosactividadpadre["h_planificada"]='0';
    
    $datosactividadpadre["orden"]=$i-1;
    $datosactividadpadre["isproyecto"]='S';
    //$bdactividad = new Admin_Model_DbTable_Actividad();
    //  echo $areaid;
     echo $actividadid;
    //echo $nombre;
    echo $suma;
 
  }
  else
  {
    $actividadeshijas = explode(".",$actividadint);
              if (count($actividadeshijas)=='2'){
                    //echo $areaid;
  //echo $actividadid;
//echo $nombre;

              }

              if (count($actividadeshijas)=='3'){
  //                  echo $areaid;
  //echo $actividadid;
//echo $nombre;
//print_r($actividadeshijas) ;

              }



  }


      }


?>

<?php } ?>


<?php if($this->cargar=='S') { ?>

<form enctype="multipart/form-data" action="/../cargar_horas.php" method="post">
<input type="hidden" name="MAX_FILE_SIZE" value="200000" />
<input type="file" name="Filedata" />

<input type="submit" value="Cargar Propuesta HH al Servidor" />
<input style="display: none;" type="text" id="proyectoid" name="proyectoid" value="<?php echo $this->proyectoid;?>"/>
<input style="display: none;" type="text" id="codigo" name="codigo" value="<?php echo $this->codigo;?>"/>
</form>

<?php } ?>


