
              <!-- page start-->
              <section class="panel">
                  <header class="panel-heading">
                      Detalles del Projecto
                      <span class="pull-right">
                          
                      </span>
                  </header>

              </section>
              <div class="row">
                  <div class="col-md-8">
                      <section class="panel">
                          <div class="bio-graph-heading project-heading">
                              <strong>  Projecto: <?php print_r($this->proyecto['proyectoid']); echo "<br>";
                              print_r($this->proyecto['nombre_proyecto'])?></strong>
                          </div>
                          <div class="panel-body bio-graph-info">
                              <!--<h1>New Dashboard BS3 </h1>-->
                              <div class="row p-details">
                                  <div class="bio-row">
                                      <p><span class="bold">Codigo Proyecto </span>: <?php print_r($this->proyecto['proyectoid'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Estado </span>: <span class="label label-primary"></span><?php print_r($this->proyecto['estado'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Fecha Inicio </span>: <?php print_r($this->proyecto['fecha_inicio'])?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span class="bold">Fecha Cierre</span>: <?php print_r($this->proyecto['fecha_cierre'])?></p>
                                  </div>
                                  
                    

                              </div>

                          </div>

                      </section><section class="panel">
    <?php 
                        $proyectoid=$this->proyecto['proyectoid'];
                        $nombre_fichero = './upload/proyecto/'.$proyectoid.'-HH.xls';
                        if (file_exists($nombre_fichero)) {?>

                      
                     <header class="panel-heading">
                          Lista Actividades <a href="/proyecto/index/subiractividades/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_actividades" class="btn btn-sm btn-warning">Cargar Actividades</a>
                          <a href="/proyecto/index/subirareacategoria/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_actividades" class="btn btn-sm btn-warning">Cargar Areas x Categoria</a>

                          <a href="/proyecto/index/subirtareo/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_actividades" class="btn btn-sm btn-warning">Cargar HH</a>


                        </header>
                        <div id="cargar_actividades" class="panel-body" >
                          <table class="table table-hover p-table">
                          <thead>
                          <tr>
                              <th>Actividad</th>
                              <th>Nombre</th>
                              <th>Horas Propuesta</th>
                              
                              <th>Operaciones</th>
                          </tr>
                          </thead>
                          <tbody>
                          <?php 
                           $bdactividad = new Admin_Model_DbTable_Actividad();
                           $actividades=$bdactividad->_getActividadesxIndice($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision']);

                          foreach ($actividades as $lista) { 

                            ?>
                          <tr>
                              <td>
                                  <?php print_r($lista['actividadid']); ?>
                              </td>
                              <td>
                                 <?php print_r($lista['nombre']); ?>
                              </td>
                              <td>
                                  <?php print_r($lista['h_propuesta']); ?>
                              </td>
                             
                              <td>
                                  <span class="label label-info">Completed</span>
                              </td>
                          </tr>
                          
                          <?php }?>
                          </tbody>
                          </table>

                        </div>


                        <?php
                        } else {?>

                          <form enctype="multipart/form-data" action="/../cargar_horas.php" method="post">
                            <input type="hidden" name="MAX_FILE_SIZE" value="200000" />
                            <input type="file" name="Filedata" />

                            <input type="submit" value="Cargar Propuesta HH al Servidor" />
                            <input style="display: none;" type="text" id="proyectoid" name="proyectoid" value="<?php print_r($this->proyecto['proyectoid']);?>"/>
                            <input style="display: none;" type="text" id="codigo" name="codigo" value="<?php  print_r($this->proyecto['codigo_prop_proy']);?>"/>
                          </form>
                        <?php
                         
                        }
                      ?>
                        
                      </section>

                      <section class="panel">
                     
                      </section>

                  </div>
                  <div class="col-md-4">
                      <section class="panel">
                          <header class="panel-heading">
                              Descripcion Proyecto
                          </header>

                          <div class="panel-body">
                              <a href="#"><img src="/img/email-img/vector-lab.jpg" alt=""/></a>

                              <p>
                                  <?php print_r($this->proyecto['descripcion']); ?>
                              </p>
                              <br/>
                              

                              <br/>
                              
                              <br/>

                              <h5 class="bold">Lista de Disciplinas</h5>
                               <table class="table table-hover p-table">
                          <thead>
                          <tr>
                              <th>Disciplina</th>
                              <th>Nombre</th>
                              <th>Operaciones</th>
                          </tr>
                          </thead>
                          <tbody>
                          <?php 
                           $bdequipoarea = new Admin_Model_DbTable_Equipoarea();
                           $area=$bdequipoarea->_buscarAreasxProyecto($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid']);

                          foreach ($area as $lista) { 

                            ?>
                          <tr>
                              <td>
                                  <?php print_r($lista['areaid']); ?>
                              </td>
                              <td>
                                 <?php print_r($lista['nombre']); ?>
                              </td>
                              
                             
                              <td>
                                  <span class="label label-info">Completed</span>
                              </td>
                          </tr>
                          
                          <?php }?>
                          </tbody>
                          </table>

                             
                          </div>

                      </section>
                  </div>
              </div>
              <!-- page end-->


<script>
$(document).ready(function(){
   
  $("#guardar_contacto").click(function(){
        var clienteid = $("#clienteid").val(); 
        var areaid = $("#areaid").val(); 
        var numero = $("#numero").val(); 
        var relacion = $("#relacion").val(); 
        var correo = $("#correo").val(); 
        var telefono = $("#telefono").val(); 
        var anexo = $("#anexo").val(); 

        var captura_direccion = $("#direccion").val(); 
        var direccion= captura_direccion.replace(/\s/g,"_");
        var captura_nombre_contacto = $("#nombre_contacto").val(); 
        var nombre_contacto= captura_nombre_contacto.replace(/\s/g,"_");
        if (clienteid=='')  
        { alert("cargue nuevamente la pagina");        }
        else
        { url="/comercial/index/guardarcontacto/clienteid/"+clienteid+"/areaid/"+areaid+"/numero/"+numero+"/relacion/"+relacion+"/nombre_contacto/"+nombre_contacto+"/correo/"+correo+"/direccion/"+direccion+"telefono/"+telefono+"/anexo/"+anexo;

        $("#cargar").load(url);
        }   
    });

    $("#clienteid").click(function(){
      var clienteid = $("#clienteid").val(); 
      url="/comercial/index/direccion/clienteid/"+clienteid;
      
      $("#direccion_valida").load(url);

        
    });

    $("#btn_buscar_propuesta").click(function(){
        var buscar_propuesta = $("#buscar_propuesta").val();
        
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_enelaboracion").hide();
        $("#propuesta_ganada").hide();
        $("#propuesta_perdida").hide();
        $("#propuesta_enviada").hide();
        $("#propuesta_declinada").hide();
        $("#propuesta_anulada").hide();
        $("#resultado_busqueda").show();
        if (buscar_propuesta=='')  
        {
            alert("ingrese propuesta a buscar");
        }
        else
        { 
            var url="/propuesta/index/buscar/propuesta/"+buscar_propuesta;    
        }
        $("#resultado_busqueda").load(url);
    });  



});
</script>