<section class="panel">
  <header class="panel-heading">
    Detalles del Projecto
    <span class="pull-right">
    </span>
  </header>
</section>

<div class="row">
  <div class="col-md-8">
    <section class="panel">
      <div class="bio-graph-heading project-heading">
        <strong>  Projecto: <?php print_r($this->proyecto['proyectoid']); echo "<br>";
        print_r($this->proyecto['nombre_proyecto'])?></strong>
      </div>
      <div class="panel-body bio-graph-info">
        <div class="row p-details">
          <div class="bio-row">
            <p><span class="bold">Codigo Proyecto </span>: <?php print_r($this->proyecto['proyectoid'])?></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Estado </span>: <span class="label label-primary"></span><?php print_r($this->proyecto['estado'])?></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Fecha Inicio </span>: <?php print_r($this->proyecto['fecha_inicio'])?></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Fecha Cierre</span>: <?php print_r($this->proyecto['fecha_cierre'])?></p>
          </div>
        </div>
      </div>
    </section>
    <section class="panel">
      <?php $proyectoid=$this->proyecto['proyectoid'];
      $nombre_fichero = './upload/proyecto/'.$proyectoid.'-HH.xls';
      if (file_exists($nombre_fichero)) {?>
        <header class="panel-heading">
          Lista Actividades <a href="/proyecto/index/subiractividades/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_actividades" class="btn btn-sm btn-warning">Cargar Actividades</a>
          <a href="/proyecto/index/subirareacategoria/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_area_categoria" class="btn btn-sm btn-warning">Cargar Areas x Categoria</a>
          <a href="/proyecto/index/subirtareo/codigo_prop_proy/<?php  print_r($this->proyecto['codigo_prop_proy'])?>/proyectoid/<?php print_r($this->proyecto['proyectoid']);?>"  id="btn_cargar_hh" class="btn btn-sm btn-warning">Cargar HH</a>
        </header>
        <header class="panel-heading tab-bg-dark-navy-blue ">
          <ul class="nav nav-tabs">
            <li class="active">
              <a data-toggle="tab" href="#resumen" aria-expanded="false">Resumen</a>
            </li>
            <?php $actividadpadre= new Admin_Model_DbTable_Actividad();
            $list=$actividadpadre->_getActividadesPadres($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision']);
            foreach ($list as $lista) { ?>
              <li class="">
                <a data-toggle="tab" href="#actividad_<?php echo $lista['actividadid']?>" aria-expanded="true"><?php 
                  $nombre_actividad = explode(":",$lista['nombre']);
                  echo $nombre_actividad ['0']?></a>
              </li>
            <?php } ?>
            <li class="">
              <a data-toggle="tab" href="#gastos" aria-expanded="false">Gastos</a>
            </li>
            <li class="">
              <a data-toggle="tab" href="#laboratorio" aria-expanded="false">Laboratorio</a>
            </li>
          </ul>
        </header>
        
        <div class="panel-body">
          <div class="tab-content">
            <div id="resumen" class="tab-pane active">
              <div class="panel-body">
                  resumen horas     
              </div>
            </div>
            <div id="gastos" class="tab-pane">
              <div class="panel-body">
               
              </div>
            </div>
            <div id="laboratorio" class="tab-pane">
              <div class="panel-body">
              laboratorio
              </div>
            </div>
            <?php $actividadpadre= new Admin_Model_DbTable_Actividad();
            $list=$actividadpadre->_getActividadesPadres($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision']); $j=1;
            foreach ($list as $lista) { ?>
              <div id="actividad_<?php echo $lista['actividadid'] ?>" class="tab-pane">
                <div class="panel-body">
                  <?php
                    $actividadpadre= new Admin_Model_DbTable_Actividad();
                    $listact=$actividadpadre->_getActividadesHijas($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision'],$lista['actividadid']); $i=1;
                    foreach ($listact as $listaact) { ?>
                      <div class="panel-group m-bot20" id="accordion_actividades">
                        <div class="panel panel-default">
                          <div class="panel-heading">
                            <h4 class="panel-title">
                              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_actividades" href="#detalle_actividad_<?php echo $j; echo "_";echo $i;?>"> 
                                  <?php 
                                   
                                    echo $listaact['nombre'];?>
                              </a>
                              <span class="pull-right">
                                <a data-id="<?php print_r($lista['areaid']); ?>" class="open-Modal btn btn-info btn-xs" data-toggle="modal" href="#detalle_actividad_<?php echo $i;?>">Ver</a>
                              </span>
                            </h4>
                          </div>
                          <div id="detalle_actividad_<?php echo $j; echo "_";echo $i;?>" class="panel-collapse collapse">
                            <div class="panel-body">
                               <table class="table table-hover p-table">
                                    <thead>
                                      <tr>
                                        <th>Actividad</th>
                                        <th>Nombre</th>
                                        <th>Horas Propuesta</th>
                                        <th>Operaciones</th>
                                      </tr>
                                    </thead>
                                    <tbody>

                              <?php $actividadpadre= new Admin_Model_DbTable_Actividad();
                                $listartareas=$actividadpadre->_getActividadesHijas($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision'],$listaact['actividadid']);
                                foreach ($listartareas as $listartareas) {     
                                 // print_r($listartareas['nombre']);
                                 // echo "<br>";

                                  ;?>
                                    <tr>
                                    <td>
                                    <?php print_r($listartareas['actividadid']); ?>
                                    </td>
                                    <td>
                                    <?php print_r($listartareas['nombre']); ?>
                                    </td>
                                    <td>
                                    <?php print_r($listartareas['h_propuesta']); ?>
                                    </td>

                                    <td>
                                    <button type="button" class="btn btn-info btn-xs">Ver</button>
                                    </td>
                                    </tr>
                                 


                              <?php }?>
                                </tbody>
                              </table>
                            </div>
                           </div>
                        </div>
                      </div>
                    <?php $i++;}?>
                </div>
              </div>
              <?php $j++;}?>
          </div>
        </div>

<!--
<div id="cargar_actividades" class="panel-body" >
<table class="table table-hover p-table">
<thead>
<tr>
<th>Actividad</th>
<th>Nombre</th>
<th>Horas Propuesta</th>

<th>Operaciones</th>
</tr>
</thead>
<tbody>
<?php 
$bdactividad = new Admin_Model_DbTable_Actividad();
$actividades=$bdactividad->_getActividadesxIndice($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision']);

foreach ($actividades as $lista) { 

?>
<tr>
<td>
<?php print_r($lista['actividadid']); ?>
</td>
<td>
<?php print_r($lista['nombre']); ?>
</td>
<td>
<?php print_r($lista['h_propuesta']); ?>
</td>

<td>
<button type="button" class="btn btn-info btn-xs">Ver</button>
</td>
</tr>

<?php }?>
</tbody>
</table>



</div>-->


<?php
} else {?>

<form enctype="multipart/form-data" action="/../cargar_horas.php" method="post">
<input type="hidden" name="MAX_FILE_SIZE" value="200000" />
<input type="file" name="Filedata" />

<input type="submit" value="Cargar Propuesta HH al Servidor" />
<input style="display: none;" type="text" id="proyectoid" name="proyectoid" value="<?php print_r($this->proyecto['proyectoid']);?>"/>
<input style="display: none;" type="text" id="codigo" name="codigo" value="<?php  print_r($this->proyecto['codigo_prop_proy']);?>"/>
</form>
<?php

}
?>

</section>

<section class="panel">
  <?php $proyectoid=$this->proyecto['proyectoid'];
  $nombre_fichero = './upload/proyecto/'.$proyectoid.'-HH.xls';
  if (file_exists($nombre_fichero)) {?>
  <script >
     $("#gastos_mostrar").show();
  </script>
  <?php }?>
</section>


<section class="panel">

</section>

</div>
<div class="col-md-4">
<section class="panel">
<header class="panel-heading">
Descripcion Proyecto
</header>

<div class="panel-body">
<a href="#"><img src="/img/email-img/vector-lab.jpg" alt=""/></a>

<p>
<?php print_r($this->proyecto['descripcion']); ?>
</p>
<br/>


<br/>

<br/>

<?php 
$bdequipoarea = new Admin_Model_DbTable_Equipoarea();

$area=$bdequipoarea->_buscarAreasxProyecto($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid']);
$i=1;

if ($area){
  ?>
<h5 class="bold">Lista de Disciplinas</h5>

<div class="panel-group m-bot20" id="accordion">
<?php
foreach ($area as $lista) { ?>
<div class="panel panel-default">
<div class="panel-heading">
<h4 class="panel-title">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $i;?>">
<?php print_r($lista['areaid']); 
echo "-";
print_r($lista['nombre']); ?>

</a>
<span class="pull-right">


<a data-id="<?php print_r($lista['areaid']); ?>" class="open-Modal btn btn-info btn-xs" data-toggle="modal" href="#myModal9">
Añadir 
</a>

</span>
</h4>
</div>
<div id="<?php echo $i;?>" class="panel-collapse collapse">
<div class="panel-body">
<?php 
$bdequipo = new Admin_Model_DbTable_Equipo();
$equipo=$bdequipo->_buscarEquipoxProyectoxArea($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid'],$lista['areaid']);

foreach ($equipo as $lista) { 
echo $lista['uid'];
echo $lista['dni'];
echo "<br>";

}?>

</div>
</div>
</div>
<?php $i++;} }?>

</div>




</div>

</section>
</div>
</div>
<!-- page end-->




<div class="modal fade modal-dialog-center top-modal-with-space" id="myModal9" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<h4 class="modal-title">Añadir Personas x Rate al Proyecto</h4>
</div>
<div class="modal-body">




<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="cliente" class="col-lg-2 col-sm-2 control-label">Area</label>
      <div class="col-lg-10">
        <select id="equipo_areaid" class="form-control m-bot4 col-lg-10">
          <option>Area</option>
          <?php 
            $bdequipoarea = new Admin_Model_DbTable_Equipoarea();
            $area=$bdequipoarea->_buscarAreasxProyecto($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid']);
            $i=1;
            foreach ($area as $lista) {?>
            <option value="<?php echo $lista['areaid']?>"><?php echo strtoupper($lista['nombre'])?></option>
          <?php }?>
        </select>
      </div>
  </div>

<div class="form-group ">
  <label for="unidad" class="col-lg-3 col-sm-3 control-label">Categoria</label>
    <div class="col-lg-9">

     <select  id="categoriaid" name="categoriaid" class="form-control">
                        </select>

      

</div>
</div>

<div class="form-group">
<label for="nombre_colaborador" class="col-lg-4 col-sm-4 control-label">Colaboradores</label>
<div class="col-lg-6">
 <div id="nombre_colaborador">
   

 </div>
</div>



</div>




</form>


</div>
<div class="modal-footer">
<button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
<button id="guardar_contacto" class="btn btn-warning" type="button"> Guardar</button>
</div>
</div>
</div>
</div>
</div>



<script>

 $("#equipo_areaid").change(function(){
    var areaid = $(this).val(); 
    //alert(areaid);
    url="/proyecto/index/buscarcategoria/areaid/"+areaid;
    //alert(url);
    $("#categoriaid").load(url);
    }); 

  $("#categoriaid").change(function(){
    var categoriaid = $(this).val(); 
    var areaid = $("#equipo_areaid").val(); 
    var proyectoid='<?php echo $this->proyecto['proyectoid']; ?>';
    var codigo='<?php echo $this->proyecto['codigo_prop_proy']; ?>';
    

   
    url="/proyecto/index/buscarpersonasxcategoria/categoria/"+categoriaid+"/areaid/"+areaid+"/proyectoid/"+proyectoid+"/codigo/"+codigo;
   
   $("#nombre_colaborador").load(url);
    }); 


$(document).ready(function(){

$("#guardar_contacto").click(function(){
var clienteid = $("#clienteid").val(); 
var areaid = $("#areaid").val(); 
var numero = $("#numero").val(); 
var relacion = $("#relacion").val(); 
var correo = $("#correo").val(); 
var telefono = $("#telefono").val(); 
var anexo = $("#anexo").val(); 

var captura_direccion = $("#direccion").val(); 
var direccion= captura_direccion.replace(/\s/g,"_");
var captura_nombre_contacto = $("#nombre_contacto").val(); 
var nombre_contacto= captura_nombre_contacto.replace(/\s/g,"_");
if (clienteid=='')  
{ alert("cargue nuevamente la pagina");        }
else
{ url="/comercial/index/guardarcontacto/clienteid/"+clienteid+"/areaid/"+areaid+"/numero/"+numero+"/relacion/"+relacion+"/nombre_contacto/"+nombre_contacto+"/correo/"+correo+"/direccion/"+direccion+"telefono/"+telefono+"/anexo/"+anexo;

$("#cargar").load(url);
}   
});

$("#clienteid").click(function(){
var clienteid = $("#clienteid").val(); 
url="/comercial/index/direccion/clienteid/"+clienteid;

$("#direccion_valida").load(url);


});

$("#btn_buscar_propuesta").click(function(){
var buscar_propuesta = $("#buscar_propuesta").val();

$("#propuesta_enelaboracion").hide();
$("#propuesta_enelaboracion").hide();
$("#propuesta_ganada").hide();
$("#propuesta_perdida").hide();
$("#propuesta_enviada").hide();
$("#propuesta_declinada").hide();
$("#propuesta_anulada").hide();
$("#resultado_busqueda").show();
if (buscar_propuesta=='')  
{
alert("ingrese propuesta a buscar");
}
else
{ 
var url="/propuesta/index/buscar/propuesta/"+buscar_propuesta;    
}
$("#resultado_busqueda").load(url);
});  



});

$(document).on("click", ".open-Modal", function () {
var myDNI = $(this).data('id');
$(".modal-body #DNI").val( myDNI );
});

</script>
