
<section class="panel">
  <header class="panel-heading">
    Detalles del Projecto
    <span class="pull-right">
    </span>
  </header>
</section>
<div class="row">
  <div class="col-md-8">
    <section class="panel">
      <div class="bio-graph-heading project-heading" style="background: rgba(0, 105, 173, 1); font-size: 14px;">
        <strong>  Projecto: <?php print_r($this->proyecto['proyectoid']); echo "<br>";
          print_r($this->proyecto['nombre_proyecto'])?>
        </strong>
      </div>
      <div class="panel-body bio-graph-info">
        <div class="row p-details">
          <div class="bio-row">
            <p><span class="bold">Cliente</span>: <?php 
              $buscacliente = new Admin_Model_DbTable_Cliente();
              $buscanombre_cliente=$buscacliente->_getClientexIndice($this->proyecto['clienteid']);
              if ($buscanombre_cliente)
                { print_r($buscanombre_cliente[0]['nombre_comercial']); }
              else
                { echo "< None >"; } ?>
            </p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Unidad Minera</span>: <?php 
              $buscaunidad = new Admin_Model_DbTable_Unidadminera();
              $buscanombre_unidad=$buscaunidad->_getUnidadmineraxid($this->proyecto['clienteid'],$this->proyecto['unidad_mineraid']);
              if ($buscanombre_unidad)
                { print_r($buscanombre_unidad[0]['nombre']); }
              else
                { echo "< None >"; } 
              ?>
            </p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Codigo</span>: <?php print_r($this->proyecto['proyectoid'])?></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Estado</span>: <span class="label label-primary"></span><?php 
              if ($this->proyecto['estado']=='A') { echo "Activo" ;}?>
            </p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Fecha Inicio </span>: <?php print_r($this->proyecto['fecha_inicio'])?></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">Fecha Cierre</span>: <?php print_r($this->proyecto['fecha_cierre'])?></p>
          </div>
        </div>
      </div>
    </section>

    <section class="panel">
      <?php 
      $proyectoid=$this->proyecto['proyectoid'];
      $nombre_fichero = './upload/proyecto/'.$proyectoid.'-HH.xls';
      ?>
      <header class="panel-heading">
        Lista Actividades y Gastos del Proyecto
      </header>
      <header class="panel-heading tab-bg-dark-navy-blue ">
        <ul class="nav nav-tabs">
          <li class="active">
            <a data-toggle="tab" href="#resumen" aria-expanded="false">Resumen</a>
          </li>
          <li class="">
            <a data-toggle="tab" href="#gastos" aria-expanded="false">Gastos</a>
          </li>
          <li class="">
            <a data-toggle="tab" href="#laboratorio" aria-expanded="false">Laboratorio</a>
          </li>
        </ul>
      </header>
      <div class="panel-body">
        <div class="tab-content">
          <div id="resumen" class="tab-pane active">
            <div class="panel-body">
              <?php 
                $actividadpadre= new Admin_Model_DbTable_Actividad();
                $list=$actividadpadre->_getActividadesPadresxReplicon($this->proyecto['proyectoid'],$this->proyecto['codigo_prop_proy'],$this->proyecto['propuestaid'],$this->proyecto['revision']);
              ?>
              <table class="table table-hover p-table">
                <thead>
                  <tr>  
                    <th style="width: 10%;">Id</th>
                    <th style="width: 70%;">Nombre Actividad</th>
                    <th style="width: 10;">Duracion</th>
                    <th style="width: 10%;">Acción</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($list as $lista) { ?>
                  <tr>
                    <td><?php print_r($lista['actividadid']); ?></td>
                    <td><?php print_r($lista['nombre']); ?></td>
                    <td><?php print_r($lista['h_propuesta']);?></td>
                    <td></td>
                  </tr>
                  <?php }?>
                </tbody>
              </table>
            </div>
          </div>
          <div id="gastos" class="tab-pane">
            <div class="panel-body">
            </div>
          </div>
          <div id="laboratorio" class="tab-pane">
            <div class="panel-body">
              laboratorio
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div class="col-md-4">
    <section class="panel">
      <header class="panel-heading">
        Descripcion Proyecto
      </header>
      <div class="panel-body">
        <div class="panel-body">
          <?php 
          $nombre_fichero = './img/cliente/'.$this->proyecto['clienteid'].'.jpg';
            if (file_exists($nombre_fichero))  { ?>
              <a href="" class="logo"><img width="150" src="/img/cliente/<?php print_r($this->proyecto['clienteid']);?>.jpg"></a>            
          <?php }
            else
            {?>
              <a href="" class="logo"><img width="150" src="/img/logo.jpg"></a>
            <?php
          }?>
        </div>
        <div class="panel-body">
          <h4 ><?php print_r($this->proyecto['nombre_proyecto'])?></h4>
          <p style="font-size: 12px;"> <?php print_r($this->proyecto['descripcion']); ?></p>
        </div>
        <h5 class="bold">Lista de Disciplinas</h5>
        <a id="anadirarea" href="##" class="btn btn-info btn-xs" >Anadir</a>
        <form action="">
              
          <select id="area_categoria" class="form-control input-sm m-bot15 col-lg-10">                        
            <option>Seleccione el Area</option>
            <?php  
              foreach ($this->area as $data_area) {?>                          
                <option value="<?php echo $data_area['areaid']?>"><?php  echo $data_area['nombre']?></option>
                  <?php }?>
                </select> 
                <select id="function" class="form-control input-sm m-bot15 col-lg-10">
                    <option value="SOPORTE">Soporte</option>
                    <option value="PROYECTO">Proyecto</option> 
          </select> 

                <input value="Publicar" type="submit" />
        </form>



          <?php 
          $bdequipoarea = new Admin_Model_DbTable_Equipoarea();
          $area=$bdequipoarea->_buscarAreasxProyecto($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid']);
          $i=1;          
          if ($area){
          ?>
              <script type="text/javascript">
              // $("#anadisr").click(function(){
              //   alert('ggg');

              //   alertify.prompt("This is a prompt dialog", function (e, str) {
              //     if (e) {
              //       alertify.success("You've clicked OK and typed: " + str);
              //       $('#anadirareaproyecto').prepend($(template).fadeIn());

              //     } else {
              //       alertify.error("You've clicked Cancel");
              //     }
              //   }, "Default Value");
              //   return false;

              // });  
              </script>

              <div class="panel-group m-bot20" id="accordion">
              <?php
              
              foreach ($area as $lista) { ?>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a style="font-size: 12px;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $i;?>">
                        <?php print_r($lista['areaid']); 
                        echo "-"; print_r($lista['nombre']); ?>
                      </a>
                      <span class="pull-right">
                        <a class="btn btn-info btn-xs" id="anadir_<?php echo $i?>" href="#" proyectoid="<?php echo $this->proyecto['proyectoid']?>"  codigo-prop-proy="<?php echo $this->proyecto['codigo_prop_proy'] ?>" areaid="<?php print_r($lista['areaid'])?>">+ </a>
                        <a class="btn btn-danger btn-xs" id="asigna_<?php echo $i?>" href="#" proyectoid="<?php echo $this->proyecto['proyectoid']?>"  codigo-prop-proy="<?php echo $this->proyecto['codigo_prop_proy'] ?>" areaid="<?php print_r($lista['areaid'])?>">H </a>
                      </span>
                    </h4>
                  </div>
                  <div id="<?php echo $i;?>" class="panel-collapse collapse">
                    <div class="panel-body">
                    <?php 
                      $bdequipo = new Admin_Model_DbTable_Equipo();
                      $equipo=$bdequipo->_buscarEquipoxProyectoxArea($this->proyecto['codigo_prop_proy'],$this->proyecto['proyectoid'],$lista['areaid']);?>

                      <section class="posts">
                      <table style="font-size: 12px;" class="table table-hover p-table">
                        <thead>
                          <tr>    
                            <th style="width: 50%;">Nombre</th>
                            <th style="width: 20%;">Categoria</th>
                            <th style="width: 10;">R.</th>
                            <th style="width: 10%;">R.Proy.</th>
                          </tr>
                        </thead>
                        <?php
                        foreach ($equipo as $lista) { 
                          //print_r($lista);
                        ?>

                          <tr>
                            <td class="p-name">
                              <a id="equipo_<?php echo $lista['dni']?>" href="#" proyectoid="<?php echo $this->proyecto['proyectoid']?>"  codigo-prop-proy="<?php echo $this->proyecto['codigo_prop_proy'] ?>" areaid="<?php print_r($lista['areaid'])?>" dni="<?php echo $lista['dni'];?>" uid="<?php echo $lista['uid'];?>"><?php $porciones = explode(".", $lista['uid']);
                                echo (ucwords($porciones[0])); echo " ";echo (ucwords($porciones[1])); ?>  
                              </a>
                            </td>
                            <td><?php
                              $dbcat= new Admin_Model_DbTable_Categoria();
                              $bucarcat=$dbcat->_getCategoriaxCategoriaid($lista['categoriaid']);
                              print_r($bucarcat[0]['categoriaid']);?>
                            </td>
                            <td>
                              <?php
                              $dbcat= new Admin_Model_DbTable_Categoria();
                              $bucarcat=$dbcat->_getCategoriaxCategoriaid($lista['categoriaid']); 
                              //print_r($bucarcat);
                              print_r($bucarcat[0]['rate_externo']); 
                              ?>
                            </td>
                            <td>                            
                              <?php echo trim($lista['rate_proyecto']); ?>
                            </td>
                            <td>
                              <span class="editar" onclick="transformarEnEditable(this)">Editar</span>
                            </td>
                          </tr>
                          <script type="text/javascript">
                            $(document).ready(function(){
                              $("#equipo_<?php echo  $lista['dni']?>").click(function(){
                                var proyectoid = $(this).attr('proyectoid');
                                var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                                var areaid = $(this).attr('areaid');
                                var dni = $(this).attr('dni');
                                var uid = $(this).attr('uid');
                                $("#myModalequipo").modal('show')
                                var url = "/proyecto/index/modificarequipo/proyectoid/"+ proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/areaid/"+areaid+"/dni/"+dni+"/uid/"+uid;
                                $("#modaltimes_equipo").load(url);   
                              });
                            });
                          </script>

                            <style type="text/css">
                              /* Curso JavaScript estilos aprenderaprogramar.com*/
                              /*body {font-family: Arial, Helvetica, sans-serif; background-color: #FFF8DC;}
                               
                              table { font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif; font-size: 12px; margin: 45px; width: 550px;
                                  text-align: center; border-collapse: collapse; }
                               
                              th { font-size: 13px; font-weight: normal; padding: 8px; background: #b9c9fe; border-top: 4px solid #aabcfe;
                                  border-bottom: 1px solid #fff; color: #039; }
                               
                              td { padding: 8px; background: #e8edff; border-bottom: 1px solid #fff; color: #669; border-top: 1px solid transparent; }
                               
                              tr:hover td { background: #d0dafd; color: #339; }
                              */
                               
                              .editar {color: blue; cursor:pointer;}
                               
                              #contenedorForm {margin-left: 45px; font-size:12px;}
                               
                              .boton {   color: black; padding: 5px; margin: 10px;
                                background-color: #b9c9fe;
                                font-weight: bold; }
                            </style>

                            <script>
                            /*Curso JavaScript aprenderaprogramar.com */
                            var editando=false;                           
                            function transformarEnEditable(nodo){
                            //El nodo recibido es SPAN
                            if (editando == false) {
                            var nodoTd = nodo.parentNode; //Nodo TD
                            var nodoTr = nodoTd.parentNode; //Nodo TR
                            var nodoContenedorForm = document.getElementById('contenedorForm'); //Nodo DIV
                            var nodosEnTr = nodoTr.getElementsByTagName('td');
                            var nombre = nodosEnTr[0].textContent;
                            var categoria = nodosEnTr[1].textContent;
                            var rate = nodosEnTr[2].textContent; 
                            var rate_proyecto = nodosEnTr[3].textContent;

                            alert(nombre);
                            alert(categoria);
                 
                            var nuevoCodigoHtml = 
                            '<td><input type="text" name="nombre" id="nombre" value="'+nombre+'" size="10"></td>'+
                            '<td><input type="text" name="categoria" id="categoria" value="'+categoria+'" size="5"</td>'+
                            '<td><input type="text" name="rate" id="rate" value="'+rate+'" size="5"</td>'+
                            '<td><input type="text" name="rate_proyecto" id="rate_proyecto" value="'+rate_proyecto+'" size="5"</td>'+'<td>En edición</td>';

                            // +'<td><input type="text" name="carbohidratos" id="carbohidratos" value="'+carbohidratos+'" size="5"</td> <td>En edición</td>';                           
                            nodoTr.innerHTML = nuevoCodigoHtml;                           
                            nodoContenedorForm.innerHTML = 'Pulse Aceptar para guardar los cambios o cancelar para anularlos'+
                            '<form name = "formulario" action="/proyecto/index/updateequipo/" method="post" onsubmit="capturarEnvio()" onreset="anular()">'+

                            '<input class="boton" type = "submit" value="Aceptar"> <input class="boton" type="reset" value="Cancelar">';
                            editando = "true";
                            }
                            else
                              {alert ('Solo se puede editar una línea. Recargue la página para poder editar otra');
                              }

                            }

                            function capturarEnvio(){
                              var nodoContenedorForm = document.getElementById('contenedorForm'); //Nodo DIV
                              nodoContenedorForm.innerHTML = 'Pulse Aceptar para guardar los cambios o cancelar para anularlos'+
                              '<form name = "formulario" action="/proyecto/index/updateequipo/" method="post" onsubmit="capturarEnvio()" onreset="anular()">'+
                              '<input type="hidden" name="nombre" value="'+document.querySelector('#nombre').value+'">'+
                              '<input type="hidden" name="areaid" value="2">'+
                              '<input type="hidden" name="rate" value="'+document.querySelector('#rate').value+'">'+
                              '<input type="hidden" name="rate_proyecto" value="'+document.querySelector('#rate_proyecto').value+'">'+
                          
                              '<input class="boton" type = "submit" value="Aceptarx"> <input class="boton" type="reset" value="Cancelar">';
                              alert(areaid);
                              document.formulario.submit();
                              }


                            </script> 
                           <?php
                          }?>
                      </table>
                      <!-- sirve para editar-->
                      <div id="contenedorForm">
                      </setion>
                    </div>
                  </div>
                </div>
                <script type="text/javascript">
                  $(document).ready(function(){
                    $("#anadir_<?php echo $i?>").click(function(){
                      var proyectoid = $(this).attr('proyectoid');
                      var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                      var areaid = $(this).attr('areaid');
                      $("#myModal9").modal('show')
                      var url = "/proyecto/index/buscarpersonasxcategoria/proyectoid/"+ proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/areaid/"+areaid;
                      $("#modaltimes_rate").load(url);   
                    });
                  });
                </script> 

                <script type="text/javascript">
                  $(document).ready(function(){
                    $("#asigna_<?php echo $i?>").click(function(){
                      var proyectoid = $(this).attr('proyectoid');
                      var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                      var areaid = $(this).attr('areaid');
                    
                      $("#modalperson").modal('show')
                                                          
                    var url = "/proyecto/index/asignaractividad/proyectoid/"+ proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/areaid/"+areaid;
                    //alert(url);
                    $("#modaltimes").load(url);   

                    });
                  });
                </script> 
              <?php $i++;} ?>
              <?php
              }?>

            </div>
          </div>
        </section>
      </div>
    </div>
<!-- page end-->
<div class="modal fade modal-dialog-center top-modal-with-space" id="myModalequipo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Cambiar Rate del Proyecto</h4>
        </div>
        <div class="modal-body">
          <div id="modaltimes_equipo"></div>
        </div>
        <div class="modal-footer">
          <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
         
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modalperson" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width: 1250px; top: 100%; margin-left: -200px; ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Asignar Personas a una Actividad</h4>
      </div>
      <div class="modal-body" style="padding-bottom: 1px;padding-top: 1px;padding-left: 1px;padding-right: 1px;">                           
        <div id="modaltimes"></div>
      </div>
      <div class="modal-footer">
        <button  data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
    
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

    $(document).ready(function(){
    $("#asigna").click(function(){
      var proyectoid = $(this).attr('proyectoid');
      var codigo_prop_proy = $(this).attr('codigo-prop-proy');

      $("#modalperson").modal('show')
                                          
    var url = "/proyecto/index/asignaractividad/proyectoid/"+ proyectoid+"/codigo_prop_proy/"+codigo_prop_proy;
    $("#modaltimes").load(url);   

     });
    });
</script> 


<div class="modal fade modal-dialog-center top-modal-with-space" id="myModal9" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Añadir Personas x Rate al Proyecto</h4>
        </div>
        <div class="modal-body">
          <div id="modaltimes_rate"></div>
        </div>
        <div class="modal-footer">
          <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
          <button id="guardar_contacto" class="btn btn-warning" type="button"> Guardar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
              $(function(){
                //$('form').hide();
                  $('form').slideUp(); 

                $('#anadirarea').on('click', mostrarFormulario);

                function mostrarFormulario() {
                  $('form').slideToggle();
                }

                $('form').on('submit', procesarFormulario);

                function procesarFormulario(ev)
                {
                  var areacat= $("#area_categoria").val();
                 
                  var funcion= $("#function").val();
                  var codigo="<?php echo $this->codigoproyecto ?>";
                  var proyecto="<?php echo $this->proyectoid ?>";
             
                  var url="/proyecto/index/guardarareaequipo/codigo_prop_proy/"+codigo+"/proyectoid/"+proyecto+"/funcion/"+funcion+"/area/"+areacat;
                 
                  alert(url);
                  //$("#anadirareaproyecto").load(url);
                  $('form').slideUp(); 
                     // var template='
                     //    <table style="font-size: 12px;" class="table table-hover p-table"> \
                     //    <thead> \
                     //      <tr> \
                     //        <th style="width: 50%;">Nombre</th> \
                     //        <th style="width: 20%;">Categoria</th> \
                     //        <th style="width: 10;">R.</th> \
                     //        <th style="width: 10%;">R.Proy.</th> \
                     //      </tr> \
                     //    </thead> \
                     //    </table> \
                     //    ';

                     // $('.posts').prepend($(template).fadeIn());

                  $.ajax({
                        type: "POST",
                        url: url,
                        data: $(this).serialize(),
                        dataType: "html",                                                 
                        error: function()
                        {
                          alert("error petición ajax load");
                        },
                        success: function(data)
                        {   

                          $("#anadirareaproyecto").empty();
                          $("#anadirareaproyecto").append(data);

                        }
                    });
                }

              });
</script>
<div id="anadirareaproyecto">gg</div>

<script>

 $("#equipo_areaid").change(function(){
    var areaid = $(this).val(); 
    //alert(areaid);
    url="/proyecto/index/buscarcategoria/areaid/"+areaid;
    //alert(url);
    $("#categoriaid").load(url);
    }); 

  $("#categoriaid").change(function(){
    var categoriaid = $(this).val(); 
    var areaid = $("#equipo_areaid").val(); 
    var proyectoid='<?php echo $this->proyecto['proyectoid']; ?>';
    var codigo='<?php echo $this->proyecto['codigo_prop_proy']; ?>';
    

   
    url="/proyecto/index/buscarpersonasxcategoria/categoria/"+categoriaid+"/areaid/"+areaid+"/proyectoid/"+proyectoid+"/codigo/"+codigo;
   
   $("#nombre_colaborador").load(url);
    }); 


$(document).ready(function(){

$("#guardar_contacto").click(function(){
var clienteid = $("#clienteid").val(); 
var areaid = $("#areaid").val(); 
var numero = $("#numero").val(); 
var relacion = $("#relacion").val(); 
var correo = $("#correo").val(); 
var telefono = $("#telefono").val(); 
var anexo = $("#anexo").val(); 

var captura_direccion = $("#direccion").val(); 
var direccion= captura_direccion.replace(/\s/g,"_");
var captura_nombre_contacto = $("#nombre_contacto").val(); 
var nombre_contacto= captura_nombre_contacto.replace(/\s/g,"_");
if (clienteid=='')  
{ alert("cargue nuevamente la pagina");        }
else
{ url="/comercial/index/guardarcontacto/clienteid/"+clienteid+"/areaid/"+areaid+"/numero/"+numero+"/relacion/"+relacion+"/nombre_contacto/"+nombre_contacto+"/correo/"+correo+"/direccion/"+direccion+"telefono/"+telefono+"/anexo/"+anexo;

$("#cargar").load(url);
}   
});

$("#clienteid").click(function(){
var clienteid = $("#clienteid").val(); 
url="/comercial/index/direccion/clienteid/"+clienteid;

$("#direccion_valida").load(url);


});

$("#btn_buscar_propuesta").click(function(){
var buscar_propuesta = $("#buscar_propuesta").val();

$("#propuesta_enelaboracion").hide();
$("#propuesta_enelaboracion").hide();
$("#propuesta_ganada").hide();
$("#propuesta_perdida").hide();
$("#propuesta_enviada").hide();
$("#propuesta_declinada").hide();
$("#propuesta_anulada").hide();
$("#resultado_busqueda").show();
if (buscar_propuesta=='')  
{
alert("ingrese propuesta a buscar");
}
else
{ 
var url="/propuesta/index/buscar/propuesta/"+buscar_propuesta;    
}
$("#resultado_busqueda").load(url);
});  



});

$(document).on("click", ".open-Modal", function () {
var myDNI = $(this).data('id');
$(".modal-body #DNI").val( myDNI );
});

</script>
