<div class = "content-filter-datatable">
  <div class = "content-elemnt-filter" id = "tb_planning_filter_date_range"></div>
  <div class = "content-elemnt-filter" id = "tb_planning_filter_date_state"></div>
</div>
<div class = "content-filter-datatable">
</div>
<table class = "table table-striped table-bordered" cellspacing="0" width="100%" id = 'datatable_personcharges' data-source = "/reporte/personcharges/jsondata">
  <thead>
    <tr>
      <th>Proyecto Id</th>
      <th>Gastos</th>
      <th>Usuario Id</th>
      <th>Usuario</th>
      <th>N° Rendición</th>
      <th>Descripción</th>
      <th>N° Documento</th>
      <th>Can.</th>
      <th>Proveedor</th>
      <th>Neto</th>
      <th>Otro imp.</th>
      <th>IGV (18%)</th>
      <th>Total</th>
      <th>Fecha Incurrida</th>
      <th>Titulo Incurrida</th>
      <th>Fecha Rendición</th>
      <th>Unidad Minera</th>
      <th>Proyecto</th>
    </tr>
  </thead>
  <tfoot>
    <th colspan="8" style="text-align:right">Total:</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tfoot>
</table>