<div class = "content-filter-datatable">
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_refund"></div>
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_contract"></div>
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_rendition"></div>
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_type_expence"></div>
  <a href="#" id="export_excel_person_charge" class = "btn btn-primary datatable-export-excel"><i class = "icon-export-export"></i>Excel</a>
</div>
<div class = "content-filter-datatable">
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_type_name"></div>
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_type_name_users"></div>
  <div class = "content-elemnt-filter" id = "tb_sheet_time_filter_type_users"></div>
</div>
<table class = "table table-striped table-bordered" cellspacing="0" width="100%" id = 'datatable_personcharges' data-source = "/reporte/personcharges/jsondata">
  <thead>
    <tr>
      <th>Proyecto Id</th>
      <th>Gastos</th>
      <th>Usuario Id</th>
      <th>Usuario</th>
      <th>N° Rendición</th>
      <th>Descripción</th>
      <th>N° Documento</th>
      <th>Can.</th>
      <th>Proveedor</th>
      <th>Neto</th>
      <th>Otro imp.</th>
      <th>IGV (18%)</th>
      <th>Total</th>
      <th>Fecha Incurrida</th>
      <th>Titulo Incurrida</th>
      <th>Fecha Rendición</th>
      <th>Unidad Minera</th>
      <th>Proyecto</th>
    </tr>
  <!-- </thead>
  <tfoot>
    <th colspan="8" style="text-align:right">Total:</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tfoot> -->
</table>