    <span style="font-weight:bold;">Tarea / Disciplina</span>

  <ul class="nav nav-pills nav-stacked">
<?php 
if ($this->actividadid != 1) {
    $actividades_hijos = $this->datos_disciplina;
    foreach ($actividades_hijos as $data_tareo_hijos) { ?>
        <li>
            <a style="padding:5px 5px;"  class = "actividad_hijas" codigo-prop-proy="<?php echo $this->codigo_prop_proy ?>" proyectoid="<?php echo $this->proyectoid ?>" categoriaid="<?php echo $this->categoriaid ?>" actividadid = "<?php echo $data_tareo_hijos['actividadid'] ?>" revision = "<?php echo $data_tareo_hijos['revision'] ?>" propuestaid = "<?php echo $data_tareo_hijos['propuestaid'] ?>" href="##">
                <i class="fa fa-rocket"></i>
                <span><?php  echo $data_tareo_hijos['nombre'] ?></span>
            </a>
        </li>
        <script type="text/javascript">
            $(".actividad_hijas").click(function(){
                var actividadid = $(this).attr('actividadid');
                var proyectoid = $(this).attr('proyectoid');
                var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                var categoriaid = $(this).attr('categoriaid');
                var revision = $(this).attr('revision');
                var propuestaid = $(this).attr('propuestaid');
                $("#actividades_tareas").load("/timesheet/index/actividadestarea/proyectoid/"+proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid+"/actividadid/"+actividadid+"/revision/"+revision+"/propuestaid/"+propuestaid);
            });
        </script>
        <?php
    } ?>

<?php  
} else { 
    $i=1;
    $actividades_hijos = $this->datos_tarea;

    foreach ($actividades_hijos as $data_tareo_hijos) { 
        $tareopersona = new Admin_Model_DbTable_Tareopersona();
        $buscar_tarea=$tareopersona->_getTareoxPersonaxSemanaxActividadid($this->uid,$this->dni,$this->semanaid,$data_tareo_hijos['actividad_padre'],$data_tareo_hijos['actividadid'],$data_tareo_hijos['codigo_actividad'],$this->codigo_prop_proy,$this->proyectoid,$data_tareo_hijos['revision']);
        if ($buscar_tarea){?>
            <li>
                <a style="padding:5px 5px;"   class = "actividad_hijas"  href="">
                    <span><?php echo $data_tareo_hijos['nombre'] ?></span>
                    <input  name="" id="" type = "checkbox" class = "pull-right" value="" checked="true">
                </a>
            </li>
        <?php
        } else {
        ?>
            <li>
                <a style="padding:5px 5px;"   class = "actividad_hijas"  href="">
                    <span><?php echo $data_tareo_hijos['nombre'] ?></span>
                    <input  name="tarea_h_<?php echo $i;?>" id="tarea_h_<?php echo $i;?>" type = "checkbox" class = "pull-right" value="" codigo-prop-proy="<?php echo $this->codigo_prop_proy ?>" proyectoid="<?php echo $this->proyectoid ?>" categoriaid="<?php echo $this->categoriaid ?>" actividadid = "<?php echo $data_tareo_hijos['actividadid'] ?>" revision = "<?php echo $data_tareo_hijos['revision'] ?>" propuestaid = "<?php echo $data_tareo_hijos['propuestaid'] ?>">
                </a>
            </li>
        <?php }?>
        <script type="text/javascript">
            $(document).ready(function(){
                $('[name^="tarea_h_<?php echo $i;?>"]').click(function(event) {
                    if ($(this).is(":checked")) {
                    
                        var codigo = '<?php echo $this->codigo_prop_proy; ?>';
                        var proyectoid='<?php echo $this->proyectoid; ?>';
                        var categoriaid='<?php echo $this->categoriaid; ?>';
                        var revision="<?php echo $data_tareo_hijos['revision']; ?>";
                        var propuestaid="<?php echo $data_tareo_hijos['propuestaid']; ?>";
                        var actividadid="<?php echo $data_tareo_hijos['actividadid']; ?>";
                        var codigo_actividad="<?php echo $data_tareo_hijos['codigo_actividad']; ?>";
                        var actividad_padre="<?php echo $data_tareo_hijos['actividad_padre']; ?>";
                        var h_propuesta="<?php echo $data_tareo_hijos['h_propuesta']; ?>";
                        url="/timesheet/index/guardartareopersona/codigo/"+codigo+"/proyectoid/"+proyectoid+"/revision/"+revision+"/categoriaid/"+categoriaid+"/propuestaid/"+propuestaid+"/actividadid/"+actividadid+"/codigo_actividad/"+codigo_actividad+"/actividad_padre/"+actividad_padre+"/h_propuesta/"+h_propuesta;
                        //alert(url);
                        $("#cargar").load(url);
                 
                
            }
            
        });    
    }); 


        </script>
        <?php
   $i++; } ?>
    
<?php } ?>
</ul>


<div id="cargar"> </div>