<!--     <span style="font-weight:bold;">Actividad</span>

  <ul class="nav nav-pills nav-stacked">
<?php 
    $actividades = $this->actividades;
    foreach ($actividades as $data_actividad) { ?>
        <li>
            <a style="padding:5px 5px;"  class = "actividad" codigo-prop-proy="<?php echo $this->codigo_prop_proy ?>" proyectoid="<?php echo $this->proyectoid ?>" categoriaid="<?php echo $this->categoriaid ?>" actividadid = "<?php echo $data_actividad['actividadid'] ?>" revision = "<?php echo $data_actividad['revision'] ?>" propuestaid = "<?php echo $data_actividad['propuestaid'] ?>" href="##">
                <i class="fa fa-rocket"></i>
                <span><?php echo $data_actividad['nombre'] ?></span>
            </a>
        </li>
        <script type="text/javascript">
            $(".actividad").click(function(){
                
                 $("#actividades_hijos").html('');
                 $("#actividades_tareas").html('');

                var actividadid = $(this).attr('actividadid');
                var proyectoid  = $(this).attr('proyectoid');
                var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                var categoriaid = $(this).attr('categoriaid');
                var revision = $(this).attr('revision');
                var propuestaid = $(this).attr('propuestaid');
                var fecha="<?php echo $this->fecha_consulta;?>";

                $("#actividades_hijos").load("/timesheet/index/actividadeshijos/proyectoid/"+proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid+"/actividadid/"+actividadid+"/revision/"+revision+"/propuestaid/"+propuestaid+"/fecha/"+fecha);
            });


            //$("#actividades").html('');
       
        //$("#actividades_tareas").html('');


        </script>
        <?php
    } ?>
</ul>-->
<span style="font-weight:bold;">Actividad</span>

  <ul class="nav nav-pills nav-stacked">
<?php
 
    $actividades_hijos = $this->actividades;
     $i=1;
    foreach ($actividades_hijos as $data_tareo_hijos) { 
        $tareopersona = new Admin_Model_DbTable_Tareopersona();
     
        $buscar_tarea=$tareopersona->_getTareoxPersonaxSemanaxActividadidxReplicon($this->uid,$this->dni,$this->semanaid,$data_tareo_hijos['actividad_padre'],$data_tareo_hijos['actividadid'],$data_tareo_hijos['codigo_actividad'],$this->codigo_prop_proy,$this->proyectoid,$data_tareo_hijos['revision']);

        if ($buscar_tarea){?>
            <li style="padding:5px 5px;color: #667fa0;"  >
                
                    <?php echo "- gfgfgf".$data_tareo_hijos['nombre'] ?>
                    <input disabled name="" id="" type = "checkbox" class = "pull-right" value="" checked="true">
                
            </li>
        <?php
        } else {

        ?>
              <li style="padding:5px 5px;color: #667fa0;"  >
                
                    <?php echo "- ".$data_tareo_hijos['nombre'] ?>
                    <input  name="tarea_h_<?php echo $data_tareo_hijos['actividadid'];?>" id="tarea_h_<?php echo $data_tareo_hijos['actividadid'];?>" type = "checkbox" class = "pull-right" value="" codigo-prop-proy="<?php echo $this->codigo_prop_proy ?>" proyectoid="<?php echo $this->proyectoid ?>" categoriaid="<?php echo $this->categoriaid ?>" actividadid = "<?php echo $data_tareo_hijos['actividadid'] ?>" revision = "<?php echo $data_tareo_hijos['revision'] ?>" propuestaid = "<?php echo $data_tareo_hijos['propuestaid'] ?>">
                
            </li>
        <?php $i++;  }?>
        <script type="text/javascript">
            $(document).ready(function(){
                $('[name^="tarea_h_<?php echo $data_tareo_hijos['actividadid'];?>"]').click(function(event) {
                    if ($(this).is(":checked")) {
                    
                        var codigo = '<?php echo $this->codigo_prop_proy; ?>';
                        var proyectoid='<?php echo $this->proyectoid; ?>';
                        var categoriaid='<?php echo $this->categoriaid; ?>';
                        var revision="<?php echo $data_tareo_hijos['revision']; ?>";
                        var propuestaid="<?php echo $data_tareo_hijos['propuestaid']; ?>";
                        var actividadid="<?php echo $data_tareo_hijos['actividadid']; ?>";
                        var codigo_actividad="<?php echo $data_tareo_hijos['codigo_actividad']; ?>";
                        var actividad_padre="<?php echo $data_tareo_hijos['actividad_padre']; ?>";
                        var h_propuesta="<?php echo $data_tareo_hijos['h_propuesta']; ?>";

                        var fecha = $("#fechasemana").text();

                        url="/timesheet/index/guardartareopersona/codigo/"+codigo+"/proyectoid/"+proyectoid+"/revision/"+revision+"/categoriaid/"+categoriaid+"/propuestaid/"+propuestaid+"/actividadid/"+actividadid+"/codigo_actividad/"+codigo_actividad+"/actividad_padre/"+actividad_padre+"/h_propuesta/"+h_propuesta+"/fecha/"+fecha;

                        //alert(url);
                        $("#cargar").load(url);
                 
                
            }
            
        });    
    }); 


        </script>
        <?php
    
    } ?>
</ul>
   <div id="cargar"> </div>