    <span style="font-weight:bold;">Tarea</span>

  <ul class="nav nav-pills nav-stacked">
<?php $i=1;
    $tareas = $this->tareas;
   
    foreach ($tareas as $data_tareas) { ?>
        <li>
            <?php 
               // if ()
            ?>
            <a style="padding:5px 5px;" class = "actividad_hijas"  href="">
                <span><?php echo $data_tareas['nombre'] ?></span>
            <input name="tarea_<?php echo $i;?>" id="tarea_<?php echo $i;?>" type = "checkbox" class = "pull-right" value="" codigo-prop-proy="<?php echo $this->codigo_prop_proy ?>" proyectoid="<?php echo $this->proyectoid ?>" categoriaid="<?php echo $this->categoriaid ?>" actividadid = "<?php echo $data_tareas['actividadid'] ?>" revision = "<?php echo $data_tareas['revision'] ?>" propuestaid = "<?php echo $data_tareas['propuestaid'] ?>">
            </a>
        </li>
        <script type="text/javascript">
            $(document).ready(function(){
                $('[name^="tarea_<?php echo $i;?>"]').click(function(event) {
                    if ($(this).is(":checked")) {
                        var codigo = '<?php echo $this->codigo_prop_proy; ?>';
                        var proyectoid='<?php echo $this->proyectoid; ?>';
                        var categoriaid='<?php echo $this->categoriaid; ?>';
                        var revision="<?php echo $data_tareas['revision']; ?>";
                        var propuestaid="<?php echo $data_tareas['propuestaid']; ?>";
                        var actividadid="<?php echo $data_tareas['actividadid']; ?>";
                        var codigo_actividad="<?php echo $data_tareas['codigo_actividad']; ?>";
                       
                        var actividad_padre="<?php echo $data_tareas['actividad_padre']; ?>";
                        var h_propuesta="<?php echo $data_tareas['h_propuesta']; ?>";
                        url="/timesheet/index/guardartareopersona/codigo/"+codigo+"/proyectoid/"+proyectoid+"/revision/"+revision+"/categoriaid/"+categoriaid+"/propuestaid/"+propuestaid+"/actividadid/"+actividadid+"/codigo_actividad/"+codigo_actividad+"/actividad_padre/"+actividad_padre+"/h_propuesta/"+h_propuesta;
                        $("#cargar").load(url);
                        
                 
                
            }
            
        });    
    }); 

            /*$(".actividad_hijas").click(function(){
                var actividadid = $(this).attr('actividadid');
                var proyectoid = $(this).attr('proyectoid');
                var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                var categoriaid = $(this).attr('categoriaid');
                var revision = $(this).attr('revision');
                var propuestaid = $(this).attr('propuestaid');
                $("#actividades_hijos").load("/timesheet/index/actividadestarea/proyectoid/"+proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid+"/actividadid/"+actividadid+"/revision/"+revision+"/propuestaid/"+propuestaid);
            });*/
        </script>
        <?php
    $i++;}?>
</ul>

<div id="cargar"> </div>