<section class="panel">
    <header class="panel-heading" style="padding-bottom : 22px">

        <h5> Time Sheet Semana <?php echo $this->semanalabor; echo ": ";?></h5><?php
         print_r($this->diassemana[7]); echo "-"; print_r($this->diassemana[13]);?>
        
          

        <span class="pull-right">

        <a class="btn btn-danger pull-right btn-xs" data-toggle="modal" href="#calendar">
            <i class="fa fa-calendar"></i> Calendario
        </a>
        <a id = "add_work" class="btn btn-success pull-right btn-xs" data-toggle="modal" href="#agregar" style="margin-right : 10px">
            <i class="fa fa-check-square-o"></i> Agregar
        </a>
        </span>
    </header>
    
    <div class="modal fade" id="agregar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="padding: 5px; ">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar Actividades</h4>
                </div>
                <div class="modal-body">
                    <div class="chat-room">
                        <aside class="left-side" style="width:15%">
                            <div class="user-head">
                                <h5>Proyecto</h5>
                            </div>
                            <ul class="chat-list">
                        <aside  style="width:20%; text-align: center;">
                         
                                <span style="font-weight:bold;">Proyecto</span>
                            
                            <ul class="nav nav-pills nav-stacked" >
                                <?php 
                                $equipo = $this->equipo;
                                foreach ($equipo as $data_equipo) { ?>
                                    <li >
                                        <a style="padding:5px 5px;" class="proyecto" codigo-prop-proy="<?php echo $data_equipo['codigo_prop_proy'] ?>" proyectoid="<?php echo $data_equipo['proyectoid'] ?>" categoriaid="<?php echo $data_equipo['categoriaid'] ?>" href="##">
                                            <i class="fa fa-rocket"></i>
                                            <span><?php echo $data_equipo['proyectoid']. ' - ' .$data_equipo['nombre_proyecto'] ?></span>
                                        </a>
                                    </li>
                                    <script type="text/javascript">
                                    $(".proyecto").click(function(){

                                        $("#actividades").html('');
                                        $("#actividades_hijos").html('');
                                        $("#actividades_tareas").html('');
                                        var proyectoid = $(this).attr('proyectoid');
                                        var codigo_prop_proy = $(this).attr('codigo-prop-proy');
                                        var categoriaid = $(this).attr('categoriaid');
                                        $("#actividades").load("/timesheet/index/actividades/proyectoid/"+proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid);

                                         
                                    });
                                    </script>
                                    <?php
                                }
                                 ?>
                            </ul>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="actividades"></div>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="actividades_hijos"></div>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="actividades_tareas"></div>
                        </aside>
                    </div>
                </div>
                <div class="modal-footer " style="padding: 5px; ">
                    <!--<button class="btn btn-warning" type="button">Agregar</button>-->
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade full-width-modal-right" id="calendar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content-wrap">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Calendario</h4>
                    </div>
                    <div class="modal-body">
                        <section class="panel">
                            <div class="panel-body">
                                <div id="datepicker"></div>
                            </div>
                        </section>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="registro"></div>

<script type="text/javascript">
    $("#add_work").click(function(){
        $("#actividades").html('');
        $("#actividades_hijos").html('');
        $("#actividades_tareas").html('');
    });



    $.datepicker.setDefaults($.datepicker.regional["es"]);
    $("#datepicker").datepicker({
        firstDay: 1,
        onSelect: function (date, inst) {
            var dateObj = $('#datepicker').datepicker('getDate');
            var dateFrom = $.datepicker.formatDate('mm/dd/yy', dateObj);
            var weekfrom = $.datepicker.iso8601Week(new Date(dateFrom));
            var diasSemana = new Array("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado");
            var day_select = diasSemana[dateObj.getDay()];
            for (i = 0; i < diasSemana.length; i++) { 
                if (diasSemana[i] == day_select) {
                    if (i == 0) {
                        var num_day = 6;
                        
                    } else {
                        var num_day = i - 1;
                    };
                };
            };
            fecha_inicio = mostrarFecha(dateObj,-num_day);
            $("#registro").load("/timesheet/index/registro/fecha/" + fecha_inicio);
        },
    });


    function mostrarFecha(fecha,days){
        milisegundos=parseInt(35*24*60*60*1000);
        //Obtenemos los milisegundos desde media noche del 1/1/1970
        tiempo=fecha.getTime();
        //Calculamos los milisegundos sobre la fecha que hay que sumar o restar...
        milisegundos=parseInt(days*24*60*60*1000);
        //Modificamos la fecha actual
        total=fecha.setTime(tiempo+milisegundos);
        day=fecha.getDate();
        month=fecha.getMonth()+1;
        year=fecha.getFullYear();
     
        return(day+"-"+month+"-"+year);
    }
</script>