<body onload="cargardatos()"> 
<section class="panel">

<header class="panel-heading" style="padding-bottom : 10px">
       
 Hoja de Tiempo 
       
  <a class="btn btn-danger pull-right btn-xs" data-toggle="modal" href="#calendar">
            <i class="fa fa-calendar"></i> Calendario
        </a>
        
           
         <a id = "" class="btn btn-primary pull-right btn-xs"  href="" style="margin-right : 10px">
            <i class="fa fa-print"></i> Imprimir
        </a>
         <a id = "" class="btn btn-default pull-right btn-xs" href="#" style="margin-right : 10px">
            <i class="fa fa-check-square"></i> Enviar
        </a>
        <a id = "" class="btn btn-info pull-right btn-xs"  href="#" style="margin-right : 10px">
            <i class="fa fa-save"></i> Guardar
        </a>

        <a id = "add_work" class="btn btn-success pull-right btn-xs" data-toggle="modal" href="#agregar" style="margin-right : 10px">
            <i class="fa fa-check-square-o"></i> Agregar
        </a>
        </span>
    </header>

  
   
    

    


        
    <div class="modal fade" id="agregar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content" style="width: 1250px; 
    top: 100%; margin-left: -180px;
   " >
                <div class="modal-header" style="padding: 5px; background: rgba(7, 35, 108, 0.92);">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar Actividades</h4>
                </div>
                <div class="modal-body" style="padding: 1px; ">
                    <div class="chat-room">
                       
                        <aside  style="width:10%; text-align: left;">
                         
                                <span style="font-weight:bold;">Cliente</span>
                            
                            <ul class="nav nav-pills nav-stacked">
                                <?php 
                                $equipo = $this->datoscliente;
                                //print_r($equipo);
                                foreach ($equipo as $data_equipo) { ?>
                                    <li >
                                        <a style="padding:5px 5px;" class="cliente" clienteid="<?php echo $data_equipo['clienteid'] ?>" unidadid="<?php echo $data_equipo['unidad_mineraid'] ?>" href="##">
                                            <?php echo $data_equipo['nombre_cliente'] ?>
                                        </a>
                                    </li>
                                    <script type="text/javascript">
                                    $(".cliente").click(function(){

                                        $("#proyectos").html('');
                                        $("#actividades").html('');
                                        $("#actividades_hijos").html('');
                                        $("#actividades_tareas").html('');
                                         var fecha = $("#fechasemana").text();
                                         
                                        var clienteid = $(this).attr('clienteid');
                                        var unidadid = $(this).attr('unidadid');

                                        $("#proyectos").load("/timesheet/index/proyectos/clienteid/"+clienteid+"/unidadid/"+unidadid+"/fecha/"+fecha);

                                         
                                    });
                                    </script>
                                    <?php
                                }
                                 ?>
                            </ul>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="proyectos"></div>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="actividades"></div>
                        </aside>
                        <aside style="width:20%; " class="right-side">
                            <div id="actividades_hijos"></div>
                        </aside>
                        <aside style="width:30%; " class="right-side">
                            <div id="actividades_tareas"></div>
                        </aside>
                    </div>
                </div>
                <div class="modal-footer " style="padding: 5px; ">
                    <!--<button class="btn btn-warning" type="button">Agregar</button>-->
                    <button id="guardar_act" data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade full-width-modal-right" id="calendar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content-wrap">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Calendario</h4>
                    </div>
                    <div class="modal-body">
                        <section class="panel">
                            <div class="panel-body">
                                <div id="datepicker"></div>
                            </div>
                        </section>
                    </div>
                    <div class="modal-footer">
                        <button  data-dismiss="modal" class="btn btn-default" type="button">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="registro"></div>
<div  id="fechasemana"></div>
</body> 
<script type="text/javascript">

$("#add_work").click(function(){
    $("#actividades").html('');
    $("#actividades_hijos").html('');
    $("#actividades_tareas").html('');
});

$("#guardar_act").click(function(){
   var dateObj = new Date();
//var dateObj = $('#datepicker').datepicker('getDate');
        var dateFrom = $.datepicker.formatDate('mm/dd/yy', dateObj);
        var weekfrom = $.datepicker.iso8601Week(new Date(dateFrom));
        var diasSemana = new Array("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado");
        var day_select = diasSemana[dateObj.getDay()];
        for (i = 0; i < diasSemana.length; i++) { 
            if (diasSemana[i] == day_select) {
                if (i == 0) {
                    var num_day = 6;
                    
                } else {
                    var num_day = i - 1;
                };
            };
        };
        fecha_inicio = mostrarFecha(dateObj,-num_day);
       var f = new Date(); 
    var fech=f.getFullYear()+"-"+(f.getMonth()+1) +"-"+f.getDate() ;
         $("#fechasemana").text( fech );
        $("#registro").load("/timesheet/index/registro/fecha/" + fecha_inicio); 
       

  
});



$.datepicker.setDefaults($.datepicker.regional["es"]);
$("#datepicker").datepicker({
    firstDay: 1,

    onSelect: function (date, inst) {
        var dateObj = $('#datepicker').datepicker('getDate');
        var dateFrom = $.datepicker.formatDate('mm/dd/yy', dateObj);
        var weekfrom = $.datepicker.iso8601Week(new Date(dateFrom));
        var diasSemana = new Array("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado");
        var day_select = diasSemana[dateObj.getDay()];
        for (i = 0; i < diasSemana.length; i++) { 
            if (diasSemana[i] == day_select) {
                if (i == 0) {
                    var num_day = 6;
                    
                } else {
                    var num_day = i - 1;
                };
            };
        };
       


        fecha_inicio = mostrarFecha(dateObj,-num_day);  
      // var f = new Date(); 
    //var fech=f.getFullYear()+"-"+(f.getMonth()+1) +"-"+f.getDate() ;
         $("#fechasemana").text( fecha_inicio );
        $("#registro").load("/timesheet/index/registro/fecha/" + fecha_inicio);
        

    },
});


function mostrarFecha(fecha,days){
    milisegundos=parseInt(35*24*60*60*1000);
    //Obtenemos los milisegundos desde media noche del 1/1/1970
    tiempo=fecha.getTime();
    //Calculamos los milisegundos sobre la fecha que hay que sumar o restar...
    milisegundos=parseInt(days*24*60*60*1000);
    //Modificamos la fecha actual
    total=fecha.setTime(tiempo+milisegundos);
    day=fecha.getDate();
    month=fecha.getMonth()+1;
    year=fecha.getFullYear();
 
    return(day+"-"+month+"-"+year);
}

function cargardatos(){ 
    var dateObj = new Date();
    //var dateObj = $('#datepicker').datepicker('getDate');
    var dateFrom = $.datepicker.formatDate('mm/dd/yy', dateObj);
    var weekfrom = $.datepicker.iso8601Week(new Date(dateFrom));
    var diasSemana = new Array("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado");
    var day_select = diasSemana[dateObj.getDay()];
    for (i = 0; i < diasSemana.length; i++) { 
        if (diasSemana[i] == day_select) {
            if (i == 0) {
                var num_day = 6;
                
            } else {
                var num_day = i - 1;
            };
        };
    };
    var f = new Date(); 
    var fech=f.getFullYear()+"-"+(f.getMonth()+1) +"-"+f.getDate() ;
         $("#fechasemana").text( fech );
      
    fecha_inicio = mostrarFecha(dateObj,-num_day);  


       
    $("#registro").load("/timesheet/index/registro/fecha/" + fecha_inicio); 
} 
</script>