<div id="report">
  <table class="table table-inbox table-hover" id="myTable" >
    <thead>
      <tr>  
        <th >#</th>
        <th >Menu</th>
        <th >Status</th>
        <th >Name</th>
        <th >Login</th>
        <th >Semana</th>
        <th >Periodo</th>
        <th >Billable</th>
        <th >Non-Billable</th>
        <th >Total</th>
        <th >Comentario</th>
      </tr>
    </thead>
    <tbody>
      <?php
      $c=1;
      foreach ($this->listasuma as $valorsuma){
      ?>    
      <tr name="oculus" id="xx" class="unread">
        <td class="view-message  text-right"><?php echo $c ?></td>
        <td class="inbox-small-cells">
        <input type="checkbox" class="mail-checkbox">
        </td>
        <td class="view-message "><?php echo $valorsuma['estado']?></td>
        <td class="view-message "><?php echo $valorsuma['dni']?></td>
        <td class="view-message "><?php echo $valorsuma['uid']?></td>                            
        <td class="view-message "><?php echo $valorsuma['semanaid']?></td>                            
        <td class="view-message "><?php echo $this->fecharecuperada?></td>                               
        <td class="view-message "><?php echo $valorsuma['billable']?></td>
        <td class="view-message "><?php echo $valorsuma['nonbillable']?></td>
        <td class="view-message "><?php echo $valorsuma['h_total']?></td>
        <td class="view-message "><?php echo $valorsuma['comentario']?></td>
      </tr>              
      <?php
      $c++; }  ?>              
    </tbody>
  </table>
</div>