<span style="font-weight:bold;">Proyecto</span>
    
    <ul class="nav nav-pills nav-stacked" >
        <?php 
        $equipo = $this->equipo;
        if ($this->unidadid!='10') {
        foreach ($equipo as $data_equipo) { ?>
            <li  >
                <a style="padding:1px 1px;" class="proyecto" codigo-prop-proy="<?php echo $data_equipo['codigo_prop_proy'] ?>" proyectoid="<?php echo $data_equipo['proyectoid'] ?>" categoriaid="<?php echo $data_equipo['categoriaid'] ?>" href="##">
                    
                    <?php echo $data_equipo['proyectoid']. ' - ' .$data_equipo['nombre_proyecto'] ?>
                </a>
            </li>

            <?php
        } }
        else
        {?>
        
            <li>
                <a style="padding:1px 1px;" class="proyecto" codigo-prop-proy="<?php echo '2015' ?>" proyectoid="<?php echo '1' ?>" categoriaid="<?php echo 'EQUIPO' ?>" href="##">
                    <?php echo "1. Administrativo" ?>
                </a>
            </li>    
            <li>
                <a style="padding:1px 1px;" class="proyecto" codigo-prop-proy="<?php echo '2015' ?>" proyectoid="<?php echo '2' ?>" categoriaid="<?php echo 'EQUIPO' ?>" href="##">
                    <?php echo "2. Propuesta" ?>
                </a>
            </li>    
            <li>
                <a style="padding:1px 1px;" class="proyecto" codigo-prop-proy="<?php echo '2015' ?>" proyectoid="<?php echo '3' ?>" categoriaid="<?php echo 'EQUIPO' ?>" href="##">
                    <?php echo "3. Proyectos Interno" ?>
                </a>
            </li>    
        <?php
        }
        ?>
        <script type="text/javascript">
            $(".proyecto").click(function(){
            $("#actividades").html('');
            $("#actividades_hijos").html('');
            $("#actividades_tareas").html('');
                var fecha="<?php echo $this->fecha_consulta;?>";
                var proyectoid = $(this).attr('proyectoid');
                var codigo_prop_proy = $(this).attr('codigo-prop-proy');
      
                var categoriaid = $(this).attr('categoriaid');
                url="/timesheet/index/actividades/proyectoid/"+proyectoid+"/codigo_prop_proy/"+codigo_prop_proy+"/categoriaid/"+categoriaid+"/fecha/"+fecha;
                //alert(url);
                $("#actividades").load(url);

               //alert(proyectoid);
               //alert(codigo_prop_proy);
               //alert(categoriaid);

            });
            </script>
    </ul>

                       
                       