<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                  Actividades
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class="adv-table">
                    <table  class="display table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Actividades</th>
                                <?php 
                                $fecha = $this->fecha;
                                $days_name = array("Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo");
                                for ($i=0; $i < 7; $i++) { ?>
                                    <th class = "center">
                                        <?php print $days_name[$i] ?> <br><?php print $fecha ?>
                                    </th>
                                    <?php
                                    $newDate = date("Y-m-d", strtotime($fecha));
                                    $nuevafecha = strtotime ( '+1 day' , strtotime ( $newDate ) ) ;
                                    $fecha = date ( 'd-m-Y' , $nuevafecha );
                                }
                                 ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                            $actividades = $this->actividades;
                            foreach ($actividades as $data_tareo) { ?>
                                <tr class="gradeX">
                                    <td><?php echo $data_tareo['nombre'] ?></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <?php
                            }
                             ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>