<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                  Actividades
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class="adv-table">
                    <table  class="display table table-bordered table-striped">
                        <thead>
                            <tr >
                              
                                <th>  
                                 
                                </th>

                                <th>Proyecto / Actividades</th>
                                <?php 
                                $fecha = $this->fecha;
                                $fecha_mostrar = $this->fecha_mostrar;
                                $days_name = array("lun","mar","mié","jue","vie","sáb","dom");
                                for ($i=0; $i < 7; $i++) { ?>
                                    <th style="width: 100px;"><center>
                                        <?php print $days_name[$i] ?> <br><?php 
                                        list($dia, $mes, $anio) = split('[/.-]', $fecha);

                                        print $dia ?></center>
                                    </th>
                                    <?php
                                    $newDate = date("Y-m-d", strtotime($fecha));
                                    $nuevafecha = strtotime ( '+1 day' , strtotime ( $newDate ) ) ;
                                    $fecha = date ( 'd-m-Y' , $nuevafecha );
                                }
                                 ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                             $fechaactual = $this->fecha;
                                $fechaactual = date("Y-m-d", strtotime($fechaactual));
                            $actividades = $this->actividades;

                            foreach ($actividades as $data_tareo) 

                                { ?>
                                <tr class="gradeX">
                                    <td> 

                                    <?php if ($data_tareo['tipo_actividad']=='G') {?>
                                      
                                      <a class="btn btn-danger btn-xs">
                                      NB
                                      </a>

                                      <?php }else{ ?>
                                     <a class="btn btn-success btn-xs ">
                                      B
                                      </a>

                                     
                                      <?php }?>
                                    </td>

                     

                                    <td>
                                                     
                                     <a onClick="window.open('/timesheet/index/actividadgeneral/codigo/<?php echo $data_tareo['codigo_prop_proy']?>/codigo_actividad/<?php echo $data_tareo['codigo_actividad']?>/actividadid/<?php echo $data_tareo['actividadid']?>/revision/<?php echo $data_tareo['revision']?>/actividad_padre/<?php echo $data_tareo['actividad_padre'] ?>/proyectoid/<?php echo $data_tareo['proyectoid']?>/semanaid/<?php echo $data_tareo['semanaid']?>/fecha_tarea/<?php echo $fechaactual ?>/asignado/<?php echo $data_tareo['asignado']?>/areaid/<?php echo $data_tareo['areaid']?>/categoriaid/<?php echo $data_tareo['categoriaid']?>/dni/<?php echo $data_tareo['dni']?>/cargo/<?php echo $data_tareo['cargo']?>/tipo_actividad/<?php echo $data_tareo['tipo_actividad']?>','mywindow','width=400,height=400,left=0,top=100,screenX=0,screenY=100')" class="btn btn-info btn-xs ">
                                      <i class="fa fa-asterisk"></i>
                                      </a>

                                    

                                    

                                    <?php echo $data_tareo['nombre_proyecto'];  echo " / "; echo $data_tareo['actividadid']; echo ": ";echo $data_tareo['nombre'] ?></td>
                                    
                                    <?php  $fecha = $this->fecha; 
                                     $fecha = date("Y-m-d", strtotime($fecha));
                                    for ($i=0; $i < 7; $i++) {
                                        $proyectoid=$data_tareo['proyectoid'];
                                        //  echo $proyectoid;echo "<br>";
                                        $codigo=$data_tareo['codigo_prop_proy'];
                                        // echo $codigo;echo "<br>";
                                        $revision=$data_tareo['revision'];
                                        //   echo $revision;echo "<br>";
                                        $actividadid=$data_tareo['actividadid'];
                                        //  echo $actividadid;echo "<br>";
                                        $actividad_padre=$data_tareo['actividad_padre'];
                                        //   echo $actividad_padre;echo "<br>";
                                        $semanaid=$data_tareo['semanaid'];
                                        $cadena=$data_tareo['etapa'];
                                        $resultado = str_replace("INICIO", "EJECUCION", $cadena);
                                        //  echo $semanaid;echo "<br>";
                                        $fecha_tarea=$fecha;
                                        // echo $fecha_tarea;echo "<br>";
                                        $fecha_planificacion=$fecha;
                                        // echo $fecha_planificacion;echo "<br>";
                                        $uid=$this->uid;
                                        // echo $uid;echo "<br>";
                                        $dni=$this->dni;
                                        //  echo $dni;echo "<br>";
                                        $cargo=$this->cargo;
                                         // echo $cargo; echo "<br>";
                                       $tareopersona = new Admin_Model_DbTable_Tareopersona();
                                       $buscar_tarea=$tareopersona->_getTareoxProyectoxTareaxDia($proyectoid,$codigo,$revision,$actividadid,$actividad_padre,$semanaid,$fecha_tarea,$fecha_planificacion,$uid,$dni,$cargo,$resultado);
                                       //print_r($buscar_tarea);
                                      ?>
                                    <td>
                                      <center>
                                        <input class="form-control" onBlur="fnc(event)" style="height: 26px; width: 60px;" maxlength="2" editable=true id="<?php echo $data_tareo['codigo_prop_proy']."!".$data_tareo['codigo_actividad']."!".$data_tareo['actividadid']."!".$data_tareo['revision']."!".$data_tareo['actividad_padre']."!".$data_tareo['proyectoid']."!".$data_tareo['semanaid']."!".$fecha."!".$data_tareo['asignado']."!".$data_tareo['areaid']."!".$data_tareo['categoriaid']."!".$data_tareo['dni']."!".$data_tareo['cargo']."!".$data_tareo['tipo_actividad']."!".$data_tareo['etapa'];?>"  type="text" name="horario"  value="<?php if ($buscar_tarea) {print_r($buscar_tarea[0]['h_real']);}

                                        ?>"  > 
                                        
                                      </center>
                                    </td>
                                    <?php 
                                        $newDate = date("Y-m-d", strtotime($fecha));
                                        $nuevafecha = strtotime ( '+1 day' , strtotime ( $newDate ) ) ;
                                        $fecha = date ( 'Y-m-d' , $nuevafecha );
                                        }?>
                                </tr>
                                <?php
                            }
                             ?>
                        </tbody>


                    </table>
                </div>
            </div>
        </section>
    </div>
</div>
<div id="horaregistrada"></div>
<div id="carga"></div>
<script type="text/javascript">
function fnc(evt) {
    var evt = evt.target ? evt : window.event;
    if (!evt.target) { evt.target = evt.srcElement; }
    var hora = $("#horaregistrada").text();
    values="-";

    $("#horaregistrada").text( values ); 
    var variables_input=evt.target.id;
    var hora_real = parseInt(hora);
    //alert(variables_input);
    var array_variables = variables_input.split("!");  
    var codigo_prop_proy=array_variables[0];
    var codigo_actividad=array_variables[1];
    var actividadid=array_variables[2];
    var revision=array_variables[3];
    var actividad_padre=array_variables[4];
    var proyectoid=array_variables[5];
    var semanaid=array_variables[6];
    var fecha_tarea =array_variables[7];
    var asignado=array_variables[8];
    var areaid=array_variables[9];
    var categoriaid =array_variables[10];
    var dni=array_variables[11];
    var cargo=array_variables[12];
    var tipo_actividad=array_variables[13];
    var etapa=array_variables[14];

    if (isNaN(hora_real)) {

    }
    else
    {
    var url="/timesheet/index/updatetareoreal/codigo_prop_proy/"+codigo_prop_proy+"/codigo_actividad/"+codigo_actividad+"/actividadid/"+actividadid+"/revision/"+revision+"/actividad_padre/"+actividad_padre+"/proyectoid/"+proyectoid+"/semanaid/"+semanaid+"/fecha_tarea/"+fecha_tarea+"/asignado/"+asignado+"/areaid/"+areaid+"/categoriaid/"+categoriaid+"/dni/"+dni+"/cargo/"+cargo+"/horareal/"+hora_real+"/tipo_actividad/"+tipo_actividad+"/etapa/"+etapa;
    //alert(url);
  $("#carga").load(url);  
    }
}

$( "input" )
  .keyup(function() {
  var value = $( this ).val();
  $("#horaregistrada").text( value );
})

</script>