<div class="form-group">
      <label class="control-label" for="message">Comentario</label>
      
      <?php                                 
      //echo  $this->comentario;            
      // $coment=trim($this->comentarios[0]['comentario']);
      // echo $coment;                  
      ?>

       <textarea class="form-control" id="message" rows="7" placeholder="Ingrese un comentario " value="<?php echo $coment ?>" ><?php echo $this->comentario ?></textarea> 
 </div> 