<section class="panel">
    <header class="panel-heading">
        Nueva Area
    </header>
</section>

<div class="row">
<div class="col-md-12">
<section class="panel">
    <div class="panel-body bio-graph-info">
        <div class="row p-details">
            
              <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Codigo del Area (*)</label>
                    <input id="areaid" type="text" class="input-sm form-control" maxlength="3"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Npmbre deL Area (*)</label>
                    <input id="nombre" type="text" class="input-sm form-control"/>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Area Padre</label>
                    <!-- <select id='area_padre' class="input-sm form-control"> -->
                    <select id='area_padre' data-placeholder="Choose a Country..." class="chosen-select" style="width:350px;" tabindex="2">
                        <option value="">Seleccione...</option>
                        <?php foreach ($this->lista_de_areas as $area_padre) {?>
                        <option value="<?php print_r($area_padre['areaid'])?>"><?php print_r($area_padre['nombre'])?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Proyecto</label>
                    <select id='isproyecto' class="input-sm form-control" >
                        <option value="">Seleccione...</option>
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Propuesta</label>
                    <select id='ispropuesta' class="input-sm form-control" >
                        <option value="">Seleccione...</option>
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Contacto</label>
                    <select id='iscontacto' class="input-sm form-control" >
                        <option value="">Seleccione...</option>
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Comercial</label>
                    <select id='iscomercial' class="input-sm form-control" >
                        <option value="">Seleccione...</option>
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="form-group">
                    <label >Orden</label>
                    <select id='orden' class="input-sm form-control">
                    <option value="">Seleccione...</option>
                    <?php for ($i=1; $i < 11; $i++) { ?>
                    <option value="<?php echo $i ?>"><?php echo $i ?></option>
                    <?php }?>
                    </select>
                </div>
            </div>
            <div class="bio-row form-group has-success">
                <div class="panel-body">
                    <a class="btn btn-success btn-sm" id="guardar_area">Guardar</a>                                      
                    <a class="btn btn-info btn-sm" href="/admin/tablamaestra/listararea">Cancelar</a> 
                </div>
            </div>
        </div>
    </div>
</section>
</div>
</div>

<div id="cargar_datos"></div>

<script type='text/javascript'>
 $("#guardar_area").click(function(){
   var areaid = $("#areaid").val();
   var nombre = $("#nombre").val();
   var area_padre = $("#area_padre").val();
   var isproyecto = $("#isproyecto").val();
   var ispropuesta = $("#ispropuesta").val();
   var iscontacto = $("#iscontacto").val();
   var iscomercial = $("#iscomercial").val();
   var orden = $("#orden").val();
   
   
   if (areaid=='' || nombre=='')
   {
    alert("ingrese los datos requeridos (*)");

   }
   else
   {
    url="/admin/tablamaestra/guardararea/areaid/"+areaid+"/nombre/"+nombre+"/area_padre/"+area_padre+"/isproyecto/"+isproyecto+"/ispropuesta/"+ispropuesta+"/iscontacto/"+iscontacto+"/iscomercial/"+iscomercial+"/orden/"+orden;
    $("#cargar_datos").load(url);
    document.location.href="/admin/tablamaestra/listararea";

   }
   });

</script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
  <script src="/../html/external_library/chosen/chosen.jquery.js" type="text/javascript"></script>

<script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>


