<?php
$html = '
  <table class = "table table-striped table-bordered" cellspacing="0" width="100%" id = "tb_sheet_time" >
  <thead>
      <tr>
        <th>Area</th>
        <th>Usuario</th>
        <th>Periodo de Hoja de Tiempo</th>
        <th>Estado</th>
      </tr>
    </thead>
    <tbody>'.
      $this->content_table
    .'</tbody>
  </table>
';
//==============================================================
//==============================================================
//==============================================================
$mpdf =  APPLICATION_LIBRARY . "/pdf/MPDF57/mpdf.php";
include($mpdf);

$mpdf=new mPDF('c','A4-L','','',0,0,0,0,0,0); 

$stylesheet = file_get_contents('/style.css');
$mpdf->WriteHTML($stylesheet,1);  // The parameter 1 tells that this is css/style only and no body/html/text

$mpdf->WriteHTML($html,2);

$mpdf->Output('mpdf.pdf','I');
exit();
//==============================================================
//==============================================================
//==============================================================


?>