<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
/** Include PHPExcel */
$PHPexcel = APPLICATION_LIBRARY . "/PHPExcel1.8/Classes/PHPExcel.php";
include ($PHPexcel);
$objPHPExcel = new PHPExcel();

$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()
            ->setCellValue('A1', 'Nombre Departamento')
            ->setCellValue('B1', 'Nombre Usuario')
            ->setCellValue('C1', 'Periodo de Tiempo')
            ->setCellValue('D1', 'Estado de Aprovación');

$sheet_times = new Reporte_DataTable_HojaTiempo();
$tb_area = new Admin_Model_DbTable_Area();
$tb_sheet_times = new Admin_Model_DbTable_Tareopersona();
$data = $sheet_times->sheet_times($this->params);
$objPHPExcel->getActiveSheet()->setTitle('Reporte HT');
$row = 1;
for ($i = 0; $i < count($data); $i++) {
  $row += 1;
  $name_area = $tb_area->_getName($data[$i]['areaid']);
  $objPHPExcel->getActiveSheet()
              ->setCellValue('A' . $row, $name_area["nombre"])
              ->setCellValue('B' . $row, $data[$i]['uid'])
              ->setCellValue('C' . $row, $data[$i]['semanaid'])
              ->setCellValue('D' . $row, $tb_sheet_times->_getNameStatus($data[$i]['estado']));
}

$objPHPExcel->setActiveSheetIndex(0);
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="Reporte HT Rev B.xls"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
exit;

