<div class = "content-filter-datatable">
  <div id = "tb_sheet_time_filter_surrender" class = "content-elemnt-filter"></div>
  <div id = "tb_sheet_time_filter_state" class = "content-elemnt-filter"></div>
  <div id = "tb_sheet_time_filter_area" class = "content-elemnt-filter"></div>
</div>
<div class = "content-filter-datatable">
  <div id = "tb_sheet_time_filter_user" class = "content-elemnt-filter"></div>
  <a href="#" id="export_excel" class = "btn btn-success datatable-export-excel glyphicon glyphicon-upload"><i class = "icon-export-export"></i>Excel</a>
  <a href="#" id="export_pdf" target="_blank" class = "btn btn-danger datatable-export-excel glyphicon glyphicon-upload"><i class = "icon-export-export"></i>Pdf</a>
</div>

<table class = "table table-striped table-bordered" cellspacing="0" width="100%" id = 'tb_sheet_time' data-source = "/reporte/hojatiempo/jsondata">
  <thead>
    <tr>
      <th>Area</th>
      <th>Usuario</th>
      <th>Periodo de Hoja de Tiempo</th>
      <th>Estado</th>
    </tr>
  </thead>
</table>