<div id = "tb_sheet_time_filter_surrender"></div>
<div id = "tb_sheet_time_filter_state"></div>
<div id = "tb_sheet_time_filter_area"></div>
<a href="#" id="export_excel">Exportar Excel</a>
<table class = "table table-striped table-bordered" id = 'tb_sheet_time' data-source = "/reporte/hojatiempo/jsondata">
  <thead>
    <tr>
      <th>Area</th>
      <th>Usuario</th>
      <th>Periodo de Hoja de Tiempo</th>
      <th>Estado</th>
    </tr>
  </thead>
</table>