<div class = "content-filter-datatable">
  <div class = "content-elemnt-filter" id = "tb_planning_filter_date_range"></div>
  <div class = "content-elemnt-filter" id = "tb_planning_filter_date_state"></div>
  <a href="#" id="export_excel_planning" class = "btn btn-primary datatable-export-excel"><i class = "icon-export-export"></i>Excel</a>
  <a href="#" id="planning_export_pdf" target="_blank" class = "btn btn-danger datatable-export-excel glyphicon glyphicon-upload"><i class = "icon-export-export"></i>Pdf</a>
</div>
<div class = "content-filter-datatable">
</div>
<table class = "table table-striped table-bordered" cellspacing="0" width="100%" id = 'datatable_planning' data-source = "/reporte/planning/jsondata">
  <thead>
    <tr>
      <th>Area</th>
      <th>Usuario</th>
      <th>Periodo de Hoja de Tiempo</th>
      <th>Supervisor</th>
      <th>Estado</th>
      <th>Horas viables</th>
      <th>Horas - N0 - viables</th>
    </tr>
  </thead>
</table>